import {T,M,mesh,beam} from './render.js';
import {BUILD} from './data.js';
import {clamp} from './math.js';
const EMPTY=new Set();
import {validEdit} from './rules.js';
export {validEdit} from './rules.js';
export class BuildingSystem{
 constructor(world,scene,audio){this.world=world;this.scene=scene;this.audio=audio;this.pieces=[];this.type='wall';this.material='wood';this.rotation=0;this.enabled=false;this.preview=null;this.candidate=null;this.anchor=null;this.cooldown=0;this.count=0;this.editing=null;this.validMat=new T.MeshBasicMaterial({color:0x57cfff,transparent:true,opacity:.3,depthWrite:false,wireframe:false});this.invalidMat=new T.MeshBasicMaterial({color:0xff5656,transparent:true,opacity:.25,depthWrite:false});}
 toggle(p){this.enabled=!this.enabled;this.anchor=p.y;if(!this.enabled)this.clearPreview();}
 clearPreview(){if(this.preview){this.scene.remove(this.preview);this.preview=null;}}
 nearest(p,range=8){let best=null,d=range;for(const b of this.pieces){if(b.dead)continue;const dist=Math.hypot(b.x-p.x,b.y+1.7-(p.y+1),b.z-p.z);if(dist<d){d=dist;best=b;}}return best;}
 target(p,yaw,pitch){const S=BUILD.tile,H=BUILD.height;const forward=4.6;let x=Math.round((p.x-Math.sin(yaw)*forward)/S)*S,z=Math.round((p.z-Math.cos(yaw)*forward)/S)*S;
 let near=null,d=12;for(const b of this.pieces){if(b.dead)continue;const dd=Math.hypot(b.x-x,b.z-z);if(dd<d){near=b;d=dd;}}
 const anchor=near?near.anchor:(this.anchor??p.y);let y=anchor+Math.round((p.y-anchor)/H)*H;if(pitch>.55)y-=H;if(pitch<-.5)y+=H;if(this.type==='floor'&&pitch<-.2)y+=H;const r=((Math.round(yaw/(Math.PI/2))+this.rotation)%4+4)%4;
 const t={x,y,z,rot:r*Math.PI/2,rotation:r,type:this.type,material:this.material,anchor,removed:new Set()};const duplicate=this.pieces.some(b=>!b.dead&&b.type===t.type&&Math.hypot(b.x-x,b.z-z)<.2&&Math.abs(b.y-y)<.2&&(b.type!=='wall'||b.rotation%2===r%2));t.supported=this.supported(t);t.valid=t.supported&&!duplicate&&y>this.world.height(x,z)-H;return t;}
 supported(t,all=this.pieces){const {x,y,z}=t,S=BUILD.tile;for(const dx of [-S/2,0,S/2])for(const dz of [-S/2,0,S/2]){const h=this.world.ground(x+dx,z+dz,y,0);if(y-h<.55&&y-h> -BUILD.height)return true;}return all.some(b=>!b.dead&&b!==t&&this.connected(t,b));}
 connected(a,b){const dx=Math.abs(a.x-b.x),dz=Math.abs(a.z-b.z),dy=Math.abs(a.y-b.y);return dx<=BUILD.tile+.12&&dz<=BUILD.tile+.12&&dx+dz<=BUILD.tile+.2&&dy<=BUILD.height+.12;}
 update(dt,p,yaw,pitch,resources){this.cooldown-=dt;for(const b of this.pieces){if(b.dead)continue;const duration=BUILD[b.material].time,old=Math.min(b.age,duration);b.age+=dt;const now=Math.min(b.age,duration),t=now/duration;b.hp=Math.min(b.maxHp,b.hp+(now-old)*(b.maxHp-30)/duration);b.mesh.scale.y=.88+.12*t;if(t===1)for(const m of b.mesh.children)m.visible=true;}

 if(!this.enabled||this.editing){this.clearPreview();return;}const t=this.target(p,yaw,pitch);if(resources[this.material]<10)t.valid=false;const key=[t.x,t.y,t.z,t.rotation,t.type,t.material,t.valid].join(',');if(key!==this.previewKey){this.clearPreview();this.preview=this.model(t,true);this.scene.add(this.preview);this.previewKey=key;}this.candidate=t;}
 place(resources,override=null){if(this.cooldown>0&&!override)return false;const t=override||this.candidate;if(!t||!t.valid||resources[t.material]<10)return false;resources[t.material]-=10;const b={...t,kind:'build',id:++this.count,hp:30,maxHp:BUILD[t.material].hp,age:0,resource:t.material,colliders:[],removed:new Set()};b.mesh=this.model(b);b.mesh.scale.y=.88;b.mesh.children.sort((a,b)=>a.position.y-b.position.y);this.scene.add(b.mesh);this.pieces.push(b);this.addCollision(b);this.cooldown=.055;this.audio?.play('build',t.material);return b;}
 model(b,ghost=false){const g=new T.Group(),S=BUILD.tile,H=BUILD.height;g.position.set(b.x,b.y,b.z);g.rotation.y=b.rot;const mat=ghost?(b.valid?this.validMat:this.invalidMat):b.material==='wood'?M.wood:b.material==='brick'?M.redbrick:M.metal;const frame=ghost?mat:b.material==='wood'?M.darktrim:M.steel;const put=(m,x,y,z,w,h,d,rot=0)=>{const o=mesh('box',m,g,[x,y,z],[w,h,d],rot);o.userData.sy=h;return o;};
 const skip=b.removed||EMPTY;
 if(b.type==='wall'){for(let row=0;row<3;row++)for(let col=0;col<3;col++){if(skip.has(row*3+col))continue;const x=-S/2+(col+.5)*S/3,y=H-(row+.5)*H/3;if(b.material==='wood'){for(let i=0;i<3;i++){const w=S/9-.035;put(mat,x-S/6+(i+.5)*S/9,y,0,w,H/3-.025,.12,[0,0,(i%2?1:-1)*.015]);}put(frame,x,y-H/6+.12,.07,S/3,.13,.14);}else if(b.material==='brick'){for(let i=0;i<4;i++)put(mat,x,y-H/6+(i+.5)*H/12,(i%2)*.015,S/3-.025,H/12-.026,.25);}else{put(mat,x,y,0,S/3-.03,H/3-.025,.07);put(frame,x-S/6+.04,y,.08,.075,H/3,.1);put(frame,x,y+H/6-.04,.06,S/3,.08,.08);}}if(!skip.size){put(frame,-S/2+.08,H/2,0,.14,H,.2);put(frame,S/2-.08,H/2,0,.14,H,.2);put(frame,0,.09,.1,S,.18,.18);if(b.material==='wood'){put(frame,0,H/2,.12,S*1.12,.13,.14,[0,0,.58]);}}
 }else if(b.type==='floor'){for(let iz=0;iz<2;iz++)for(let ix=0;ix<2;ix++){if(skip.has(iz*2+ix))continue;for(let j=0;j<5;j++)put(mat,-S/2+(ix+.5)*S/2,.04,-S/2+iz*S/2+(j+.5)*S/10,S/2-.03,.17,S/10-.025);put(frame,-S/2+(ix+.5)*S/2,-.09,-S/2+(iz+.5)*S/2,.13,.22,S/2);}}
 else if(b.type==='ramp'){const left=skip.has(0)||skip.has(2),right=skip.has(1)||skip.has(3);const w=skip.size?S/2:S,cx=skip.size?(left?S/4:-S/4):0;for(let i=0;i<16;i++)put(mat,cx,(i+.5)*H/16,S/2-(i+.5)*S/16,w-.04,.18,S/16+.01);for(let side of [-1,1]){const a=new T.Vector3(cx+side*w*.4,0,S/2),c=new T.Vector3(cx+side*w*.4,H,-S/2),beamMesh=beam(g,frame,a.toArray(),c.toArray(),.065);beamMesh.userData.sy=beamMesh.scale.y;}}
 else if(b.type==='roof'){for(let iz=0;iz<2;iz++)for(let ix=0;ix<2;ix++){if(skip.has(iz*2+ix))continue;const sx=ix?1:-1,sz=iz?1:-1;const pos=[0,H*.5,0,sx*S/2,0,0,sx*S/2,0,sz*S/2,0,0,sz*S/2];const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(pos,3));geom.setAttribute('uv',new T.Float32BufferAttribute([.5,.5,1,0,1,1,0,1],2));geom.setIndex([0,1,2,0,2,3,2,1,0,3,2,0]);geom.computeVertexNormals();const m=new T.Mesh(geom,mat);m.castShadow=m.receiveShadow=true;m.userData.sy=1;g.add(m);}}
 return g;}
 addCollision(b){const S=BUILD.tile,H=BUILD.height;const add=(x,y,z,w,h,d,kind='build',slope=null)=>{const c=Math.abs(Math.cos(b.rot)),s=Math.abs(Math.sin(b.rot)),px=b.x+x*Math.cos(b.rot)+z*Math.sin(b.rot),pz=b.z-x*Math.sin(b.rot)+z*Math.cos(b.rot),wx=w*c+d*s,dz=d*c+w*s;const box=this.world.collision.insert({min:{x:px-wx/2,y:b.y+y-h/2,z:pz-dz/2},max:{x:px+wx/2,y:b.y+y+h/2,z:pz+dz/2},kind,owner:b,slope});b.colliders.push(box);};
 if(b.type==='wall'){for(let row=0;row<3;row++)for(let col=0;col<3;col++)if(!b.removed.has(row*3+col))add(-S/2+(col+.5)*S/3,H-(row+.5)*H/3,0,S/3,H/3,.2);}
 else if(b.type==='floor'){for(let iz=0;iz<2;iz++)for(let ix=0;ix<2;ix++)if(!b.removed.has(iz*2+ix))add(-S/4+ix*S/2,0,-S/4+iz*S/2,S/2,.2,S/2,'floor');}
 else if(b.type==='ramp'){const left=b.removed.has(0)||b.removed.has(2),w=b.removed.size?S/2:S,cx=b.removed.size?(left?S/4:-S/4):0;for(let i=0;i<16;i++)add(cx,(i+.5)*H/16,S/2-(i+.5)*S/16,w,.18,S/16+.02,'stairs');}
 else for(let iz=0;iz<8;iz++)for(let ix=0;ix<8;ix++){if(b.removed.has(Math.floor(iz/4)*2+Math.floor(ix/4)))continue;const x=-S/2+(ix+.5)*S/8,z=-S/2+(iz+.5)*S/8,h=H*.5*(1-Math.max(Math.abs(x),Math.abs(z))/(S/2));add(x,h,z,S/8,.14,S/8,'stairs');}}
 damage(b,amount){if(b.dead)return;b.hp-=amount;if(b.hp<=0){this.destroy(b);this.checkSupport();}else b.mesh.traverse(m=>{if(m.isMesh)m.visible=Math.random()>.1;});}
 destroy(b){b.dead=true;this.scene.remove(b.mesh);for(const c of b.colliders)c.active=false;}
 checkSupport(){const alive=this.pieces.filter(p=>!p.dead),root=new Set();for(const p of alive){const S=BUILD.tile;let support=false;for(let a of [-S/2,0,S/2])for(let c of [-S/2,0,S/2])if(p.y-this.world.height(p.x+a,p.z+c)<.75)support=true;if(support)root.add(p);for(const c of this.world.collision.query(p.x,p.z,S/2))if(c.active&&c.owner.kind!=='build'&&c.kind!=='tree'&&c.max.x>p.x-S/2+.05&&c.min.x<p.x+S/2-.05&&c.max.z>p.z-S/2+.05&&c.min.z<p.z+S/2-.05&&c.max.y<=p.y+.4&&p.y-c.max.y<.6)root.add(p);}let changed=true;while(changed){changed=false;for(const p of alive)if(!root.has(p)&&[...root].some(b=>this.connected(p,b))){root.add(p);changed=true;}}for(const p of alive)if(!root.has(p))this.destroy(p);}
 beginEdit(p){const b=this.nearest(p,8);if(!b)return null;this.editing=b;this.clearPreview();return b;}
 applyEdit(removed){const b=this.editing;if(!b||!validEdit(b.type,removed))return false;this.scene.remove(b.mesh);for(const c of b.colliders)c.active=false;b.colliders=[];b.removed=new Set(removed);b.mesh=this.model(b);this.scene.add(b.mesh);this.addCollision(b);this.editing=null;this.audio?.play('edit');return true;}
 repair(p,resources){const b=this.nearest(p);if(!b||b.hp>=b.maxHp||resources[b.material]<2)return false;resources[b.material]-=2;b.hp=Math.min(b.maxHp,b.hp+60);this.audio?.play('build',b.material);return true;}
 reset(){for(const b of this.pieces)if(!b.dead)this.destroy(b);this.pieces=[];this.clearPreview();this.enabled=false;this.editing=null;}
}
