import {T,M,mesh,makeRenderer,loadWorldTextures} from './render.js';
import {World} from './world.js';
import {makeCharacter,makeBus,makeGlider,makeWeapon,makeDistantCharacter} from './character.js';
import {BUS_SECONDS,busPosition,makeDropPlan,advanceBotDrop} from './airdrop.js';
import {BuildingSystem} from './building.js';
import {UI,$,timeString} from './ui.js';
import {Sound} from './audio.js';
import {LOCATIONS,WEAPONS,BUILD,BOT_NAMES,SIZE} from './data.js';
import {rng,clamp,lerp,rayBox} from './math.js';

const defaults={quality:'high',sensitivity:1,volume:.5,pace:'quick',bots:99,turbo:true,autoMaterial:true,fps:false,skin:0};
function load(key,fallback){if(new URLSearchParams(location.search).has('qa'))return {...fallback};try{return {...fallback,...JSON.parse(localStorage.getItem(key)||'{}')};}catch{return {...fallback};}}
class Game{
 constructor(){this.settings=load('chapter-one-settings',defaults);this.profile=load('chapter-one-profile',{matches:0,wins:0,kills:0,chests:0,xp:0});this.sound=new Sound();this.render=makeRenderer($('game'));this.world=new World(this.render.scene);this.build=new BuildingSystem(this.world,this.render.scene,this.sound);this.state='loading';this.mode='solo';this.paused=false;this.input=new Set();this.yaw=0;this.pitch=.16;this.mouseDown=false;this.aim=false;this.marker=null;this.projectiles=[];this.effects=[];this.bots=[];this.warmupActors=[];this.busFlight=null;this.time=0;this.matchTime=0;this.fps=60;this.location=null;this.locTimer=0;this.cooldown=0;this.recoil=0;this.action=null;this.inStorm=false;this.storm={active:false,x:0,z:0,radius:1600,nextX:0,nextZ:0,nextRadius:1100,timer:100,phase:0,closing:false};this.random=rng(731018);this.player=this.newPlayer();this.avatar=makeCharacter(this.settings.skin);this.render.scene.add(this.avatar.root);this.bus=makeBus();this.bus.visible=false;this.render.scene.add(this.bus);this.glider=makeGlider();this.glider.visible=false;this.avatar.root.add(this.glider);this.ui=new UI(this);this.interaction=null;this.cameraTarget=new T.Vector3();this.cameraDesired=new T.Vector3();this.stormMesh=this.makeStorm();this.bindInput();this.applySettings();}
 newPlayer(){return{pos:new T.Vector3(LOCATIONS[0].x,LOCATIONS[0].y+.3,LOCATIONS[0].z+5),velY:0,health:100,shield:0,materials:{wood:0,brick:0,metal:0},ammo:{medium:0,light:0,shells:0,heavy:0,rockets:0},inventory:[null,null,null,null,null],slot:0,kills:0,chests:0,onGround:true,crouch:false,distance:0,shots:0,hits:0};}
 get p(){return this.player.pos;}
 async init(){await loadWorldTextures();this.setSkin(this.settings.skin);await this.world.create((t,text)=>{$('load-progress').style.width=(t*100)+'%';$('load-label').textContent=text;});this.world.initialLoot=this.world.loot.length;this.ui.prepareMap();await this.ui.makeIcons();this.ui.show('loading',false);this.returnLobby();this.last=performance.now();requestAnimationFrame(t=>this.frame(t));this.installDiagnostics();this.registerAgentControls();}
 isControllable(){return ['prematch','drop','glide','playing','bus'].includes(this.state)&&!this.ui.overlay;}
 bindInput(){addEventListener('resize',()=>{this.render.renderer.setSize(innerWidth,innerHeight);this.render.camera.aspect=innerWidth/innerHeight;this.render.camera.updateProjectionMatrix();});document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(['Space','Tab','F1','F2','F3','F4','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat){this.input.add(e.code);return;}if(e.code==='Escape'){if(this.ui.overlay)this.ui.close(false);else if(this.state!=='lobby'&&this.state!=='loading'&&!['eliminated','victory','spectating'].includes(this.state))this.ui.modal('pause');return;}if(e.code==='KeyM'){this.ui.openMap();return;}if(e.code==='Tab'||e.code==='KeyI'){if(this.ui.overlay==='inventory-overlay')this.ui.close();else if(this.state!=='lobby')this.ui.inventory();return;}if(this.ui.overlay){if(e.code==='KeyG'&&this.ui.overlay==='edit-overlay')this.ui.confirmEdit();return;}this.input.add(e.code);if(e.code==='Space'){if(this.state==='bus')this.jumpBus();else if(this.state==='drop'){this.state='glide';this.glider.visible=true;this.sound.play('glide');}else if(this.state==='glide'&&this.p.y-this.world.height(this.p.x,this.p.z)>45){this.state='drop';this.glider.visible=false;}else if(['playing','prematch'].includes(this.state)&&this.player.onGround){this.player.velY=7.3;this.player.onGround=false;this.sound.play('step');}}if(e.code==='KeyQ'&&['playing','prematch'].includes(this.state)){this.build.toggle(this.p);this.equip(this.player.slot);}
 if(e.code.startsWith('Digit')){const n=Number(e.code.slice(-1));if(n<=5){this.build.enabled=false;this.equip(n);}}if(e.code==='Backquote'){this.build.enabled=false;this.equip(0);}if(/^F[1-4]$/.test(e.code)){this.build.type=['wall','floor','ramp','roof'][Number(e.code[1])-1];if(!this.build.enabled)this.build.toggle(this.p);}
 if(e.code==='KeyR'){if(this.build.enabled)this.build.rotation=(this.build.rotation+1)%4;else this.reload();}if(e.code==='KeyG'){const b=this.build.beginEdit(this.p);if(b)this.ui.edit(b);else this.ui.notify('Look for one of your structures to edit.');}if(e.code==='KeyH'){if(!this.build.repair(this.p,this.player.materials))this.ui.notify('No damaged structure in reach.');}if(e.code==='KeyE')this.interact();});
 document.addEventListener('keyup',e=>this.input.delete(e.code));addEventListener('blur',()=>{this.input.clear();this.mouseDown=false;this.aim=false;});$('game').addEventListener('click',()=>{if(!this.ui.overlay&&this.state!=='lobby')this.capture();});document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===$('game');this.ui.pointerLocked=locked;this.ui.show('capture-mouse',!locked&&this.isControllable()&&this.state!=='bus');if(!locked){this.input.clear();this.mouseDown=false;this.aim=false;}});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===$('game')&&!this.ui.overlay){this.yaw-=e.movementX*.0022*this.settings.sensitivity*(this.aim?.55:1);this.pitch=clamp(this.pitch+e.movementY*.0018*this.settings.sensitivity*(this.aim?.5:1),-1.2,1.25);}});$('game').addEventListener('mousedown',e=>{if(!this.isControllable())return;if(e.button===0){this.mouseDown=true;if(document.pointerLockElement===$('game'))this.fire();}if(e.button===2){if(this.build.enabled)this.nextMaterial();else this.aim=true;}});document.addEventListener('mouseup',e=>{if(e.button===0)this.mouseDown=false;if(e.button===2)this.aim=false;});$('game').addEventListener('contextmenu',e=>e.preventDefault());$('game').addEventListener('wheel',e=>{e.preventDefault();if(!this.isControllable())return;this.build.enabled=false;this.equip((this.player.slot+(e.deltaY>0?1:5))%6);},{passive:false});}
 capture(){if(this.state==='lobby'||this.ui.overlay)return;this.sound.init();this.mouseActive=true;this.ui.show('capture-mouse',false);try{const p=$('game').requestPointerLock();p?.catch?.(()=>{this.fallbackMouse=true;this.ui.notify('Drag with right mouse to look. Arrow keys also rotate the camera.',4);});}catch{this.fallbackMouse=true;}$('game').focus();}
 applySettings(){const q=this.settings.quality;this.render.renderer.setPixelRatio(q==='low'?1:Math.min(devicePixelRatio,q==='medium'?1.3:1.8));this.render.renderer.shadowMap.enabled=q!=='low';this.render.scene.fog.density=q==='low'?.0019:q==='medium'?.00145:.0011;this.sound.setVolume(this.settings.volume);}
 saveSettings(){if(new URLSearchParams(location.search).has('qa')){this.applySettings();return;}try{localStorage.setItem('chapter-one-settings',JSON.stringify(this.settings));}catch{}this.applySettings();}
 saveProfile(){if(new URLSearchParams(location.search).has('qa')){this.ui.profile();return;}try{localStorage.setItem('chapter-one-profile',JSON.stringify(this.profile));}catch{}this.ui.profile();}
 setSkin(n){this.render.scene.remove(this.avatar.root);this.avatar=makeCharacter(n);this.render.scene.add(this.avatar.root);this.avatar.root.add(this.glider);this.settings.skin=n;this.saveSettings();this.equip(this.player.slot);}
 returnLobby(){this.busFlight=null;this.harvestImpact=null;this.swing=0;this.clearWarmup();this.ui.close(false);this.ui.show('results',false);this.ui.show('spectating',false);this.ui.show('hud',false);this.ui.show('lobby',true);this.ui.show('capture-mouse',false);document.exitPointerLock?.();this.state='lobby';this.paused=false;this.bus.visible=false;this.glider.visible=false;this.stormMesh.visible=false;this.build.reset();for(const b of this.bots){if(b.model)this.render.scene.remove(b.model.root);if(b.distant)this.render.scene.remove(b.distant);}this.bots=[];const l=LOCATIONS[0];this.p.set(l.x,l.y+.2,l.z+4);this.avatar.root.position.copy(this.p);this.avatar.root.rotation.y=Math.PI+.35;this.avatar.setWeapon('pickaxe');this.yaw=0;this.pitch=.1;this.ui.profile();this.action=null;this.mouseDown=false;}
 restoreWorld(){for(const extra of this.world.loot.splice(this.world.initialLoot))this.render.scene.remove(extra.mesh);for(const o of [...this.world.props,...this.world.buildings.flatMap(b=>b.parts)]){o.hp=o.maxHp;if(o.dead){o.dead=false;o.hp=o.maxHp;for(const r of o.refs||[]){r.b.mesh.setMatrixAt(r.index,r.matrix);r.b.mesh.instanceMatrix.needsUpdate=true;}if(o.mesh)o.mesh.visible=true;for(const c of this.world.collision.items)if(c.owner===o)c.active=true;}if(o.kind==='door'&&o.open)this.world.toggleDoor(o);}for(const c of this.world.chests){c.opened=false;c.dead=false;c.hp=100;c.mesh.visible=true;c.lid.rotation.y=0;c.collider.active=true;c.mesh.children[0].material=M.wood;}for(const l of this.world.loot){l.active=true;l.mesh.visible=true;}}
 startMatch(){this.busFlight=null;this.harvestImpact=null;this.swing=0;this.clearWarmup();this.sound.init();this.ui.close(false);this.ui.show('lobby',false);this.ui.show('results',false);this.ui.show('spectating',false);this.ui.show('hud',true);this.build.reset();this.restoreWorld();for(const b of this.bots){if(b.model)this.render.scene.remove(b.model.root);if(b.distant)this.render.scene.remove(b.distant);}for(const p of this.projectiles)this.render.scene.remove(p.mesh);this.projectiles=[];this.bots=[];this.player=this.newPlayer();this.matchTime=0;this.action=null;this.locTimer=0;this.location=null;this.cooldown=0;this.damageGrace=0;this.inStorm=false;this.storm.active=false;this.stormMesh.visible=false;this.bus.visible=false;this.yaw=0;this.pitch=.12;this.glider.visible=false;this.equip(0);this.recorded=false;this.placement=null;
 if(this.mode==='explore'){this.state='playing';this.travel(0);this.player.materials={wood:999,brick:999,metal:999};this.player.ammo={medium:300,light:180,shells:80,heavy:50,rockets:15};this.player.inventory=[this.item('ar'),this.item('pump'),this.item('sniper'),this.item('shield',3),this.item('rocket')];this.equip(1);this.ui.notify('Explore mode. Open the map to travel between locations.',6);}
 else{this.state='prematch';this.phaseTimer=10;const p=this.world.spawnIsland;this.p.set(p.x,p.y,p.z+3);this.makeBots();this.makeWarmup();this.ui.notify('Waiting for local players. The Battle Bus leaves soon.',5);}
 this.capture();}
 item(type,count=1){return {type,count,rounds:WEAPONS[type].mag||0};}
 weaponType(){return this.player.slot===0?'pickaxe':this.player.inventory[this.player.slot-1]?.type||'pickaxe';}
 equip(slot){this.harvestImpact=null;this.swing=0;this.player.slot=clamp(slot,0,5);this.action=null;this.avatar.setWeapon(this.weaponType());this.sound.play('click');this.ui.lastHotbar='';}
 travel(i){const l=LOCATIONS[i];this.location=l;this.p.set(l.x,l.y+.25,l.z+(l.type==='city'?5:l.type==='lake'?35:l.type==='woods'?58:9));if(l.type==='mine')this.p.set(l.x,26.9,l.z);this.p.y=this.world.ground(this.p.x,this.p.z,l.type==='mine'?this.p.y+1:Math.max(l.y+10,this.p.y),.5)+.04;for(let tries=0;tries<20&&this.world.blocked(this.p.x,this.p.z,this.p.y);tries++){this.p.z+=2;this.p.y=this.world.ground(this.p.x,this.p.z,l.y+10,.5)+.04;}this.player.velY=0;this.player.onGround=true;this.yaw=0;this.pitch=.12;this.glider.visible=false;this.state='playing';this.avatar.root.position.copy(this.p);this.locTimer=4;$('location-banner').innerHTML=`<small>ENTERED</small>${l.name.toUpperCase()}`;}
 clearWarmup(){for(const actor of this.warmupActors||[])this.render.scene.remove(actor.root);this.warmupActors=[];}
 launchBus(){this.clearWarmup();this.busFlight={elapsed:0,active:true};for(const b of this.bots){b.phase='bus';b.pos.copy(busPosition(0));}this.state='bus';this.phaseTimer=BUS_SECONDS;this.bus.visible=true;this.bus.position.set(-900,380,410);this.bus.rotation.y=-1.1;this.p.copy(this.bus.position);this.yaw=.8;this.pitch=.48;this.avatar.root.visible=false;this.ui.show('capture-mouse',false);this.ui.notify('Open the map to mark your landing spot.',5);}
 jumpBus(){if(this.state!=='bus')return;this.state='drop';this.avatar.root.visible=true;this.p.copy(this.bus.position).add(new T.Vector3(0,-5,0));this.player.velY=-15;this.yaw=-1.1;this.pitch=.36;this.sound.play('glide');this.storm={active:true,x:0,z:0,radius:1580,nextX:-160,nextZ:50,nextRadius:980,timer:this.settings.pace==='quick'?45:150,phase:0,closing:false};this.stormMesh.visible=true;this.capture();}
 nextMaterial(){const mats=['wood','brick','metal'];this.build.material=mats[(mats.indexOf(this.build.material)+1)%3];this.sound.play('click');}
 interact(){if(this.action)return;const i=this.interaction;if(!i)return;if(i.kind==='loot')this.pickup(i.item);else if(i.kind==='chest'){this.action={kind:'chest',target:i.item,remaining:.85,label:'SEARCHING'};this.sound.play('reload');}else if(i.kind==='door'){this.world.toggleDoor(i.item);this.sound.play('build','wood');}}
 pickup(l){if(!l.active)return;const w=WEAPONS[l.type],p=this.player;let idx=p.inventory.findIndex(it=>it?.type===l.type&&w.stack&&it.count<w.stack);if(idx>=0){const n=Math.min(l.count,w.stack-p.inventory[idx].count);p.inventory[idx].count+=n;l.count-=n;if(l.count<=0){l.active=false;l.mesh.visible=false;}}
 else{idx=p.inventory.findIndex(it=>!it);if(idx<0){idx=p.slot>0?p.slot-1:0;this.dropSlot(idx);}p.inventory[idx]=this.item(l.type,l.count);l.active=false;l.mesh.visible=false;if(l.rounds!==undefined)p.inventory[idx].rounds=l.rounds;if(w.mag&&!l.ammoGranted)p.ammo[w.ammo]+=w.ammo==='shells'?10:w.ammo==='heavy'?6:w.ammo==='rockets'?2:30;this.equip(idx+1);}this.sound.play('pickup');this.ui.notify(`${w.name} picked up`);}
 dropSlot(i){const it=this.player.inventory[i];if(!it)return;const dropped=this.world.addLoot(it.type,this.p.x-Math.sin(this.yaw)*1.8,this.p.y,this.p.z-Math.cos(this.yaw)*1.8,it.count);dropped.rounds=it.rounds;dropped.ammoGranted=true;this.player.inventory[i]=null;if(this.player.slot===i+1)this.equip(0);}
 reload(){const it=this.player.inventory[this.player.slot-1];if(!it||this.action)return;const w=WEAPONS[it.type];if(!w.mag||it.rounds>=w.mag||!this.player.ammo[w.ammo])return;this.action={kind:'reload',slot:this.player.slot-1,remaining:w.reload,label:'RELOADING'};this.sound.play('reload');}
 useItem(){const it=this.player.inventory[this.player.slot-1];if(!it||this.action)return;const w=WEAPONS[it.type];if(!w.heal)return;const value=w.health?this.player.health:this.player.shield;if(value>=w.limit&&!w.both){this.ui.notify(`${w.health?'Health':'Shield'} is already at ${w.limit}.`);return;}this.action={kind:'heal',slot:this.player.slot-1,remaining:w.use,label:it.type==='medkit'?'HEALING':'DRINKING'};this.sound.play('pickup');}
 updateAction(dt){if(!this.action)return;const a=this.action;a.remaining-=dt;if(a.kind==='chest'&&Math.hypot(this.p.x-a.target.x,this.p.z-a.target.z)>3.6){this.action=null;return;}if(a.remaining>0)return;if(a.kind==='reload'){const it=this.player.inventory[a.slot];if(it){const w=WEAPONS[it.type],n=Math.min(w.mag-it.rounds,this.player.ammo[w.ammo]);it.rounds+=n;this.player.ammo[w.ammo]-=n;this.sound.play('reload');}}
 if(a.kind==='heal'){const it=this.player.inventory[a.slot];if(it){const w=WEAPONS[it.type];if(w.both){this.player.shield=this.player.health=100;}else if(w.health)this.player.health=Math.min(w.limit,this.player.health+w.heal);else this.player.shield=Math.min(w.limit,this.player.shield+w.heal);it.count--;if(it.count<=0){this.player.inventory[a.slot]=null;this.equip(0);}this.sound.play('shield');}}
 if(a.kind==='chest'&&!a.target.opened){this.world.openChest(a.target);this.player.chests++;for(const k of ['medium','light'])this.player.ammo[k]+=18;this.player.ammo.shells+=8;this.player.materials.wood=Math.min(999,this.player.materials.wood+30);this.sound.play('chest');this.ui.notify('Chest searched · ammunition and materials collected');}this.action=null;}
 fire(){if(!['playing','prematch'].includes(this.state)||this.cooldown>0||this.ui.overlay||this.action)return;if(this.build.enabled){if(this.settings.autoMaterial&&this.player.materials[this.build.material]<10){for(const m of ['wood','brick','metal'])if(this.player.materials[m]>=10){this.build.material=m;break;}}const b=this.build.place(this.player.materials);if(!b)this.ui.notify('Find support and enough materials to build.',.7);return;}
 const type=this.weaponType(),w=WEAPONS[type];if(w.heal){this.useItem();return;}if(type==='pickaxe'){this.swing=w.rate;this.harvestImpact=w.rate*.46;this.sound.play('pickaxe');this.cooldown=w.rate;return;}const it=this.player.inventory[this.player.slot-1];if(!it?.rounds){this.reload();if(!this.player.ammo[w.ammo])this.ui.notify('Not enough ammo');return;}it.rounds--;this.cooldown=w.rate;this.player.shots++;this.recoil+=.018;this.sound.play('shoot',type);const dir=this.viewDirection();const eye=this.render.camera.position;const target=eye.clone().addScaledVector(dir,w.range);const muzzle=this.p.clone().add(new T.Vector3(.2,1.36,0)).addScaledVector(dir,.55);const aim=this.findHit(eye,dir,w.range,true);if(aim)target.copy(eye).addScaledVector(dir,aim.distance);const base=target.clone().sub(muzzle).normalize();
 if(w.projectile){this.spawnProjectile(muzzle,base,w.projectile,type,'player');}
 else{for(let i=0;i<(w.pellets||1);i++){const spread=w.spread*(this.aim?.28:1)*(this.player.crouch?.65:1)*(this.moveSpeed>1?1.7:1);const d=base.clone().add(new T.Vector3((this.random()-.5)*spread,(this.random()-.5)*spread,(this.random()-.5)*spread)).normalize();const hit=this.findHit(muzzle,d,w.range,true);let end=muzzle.clone().addScaledVector(d,hit?hit.distance:w.range);this.tracer(muzzle,end,w.pellets?0xffd991:0xfff1b8,.065);if(hit)this.applyShotHit(hit,w.damage*(w.pellets?clamp(1-hit.distance/w.range,.12,1):1),end,'player');}}
 this.flash(muzzle);if(it.rounds===0&&this.player.ammo[w.ammo]>0)setTimeout(()=>{if(this.weaponType()===type)this.reload();},300);}
 viewDirection(){return new T.Vector3(-Math.sin(this.yaw)*Math.cos(this.pitch),-Math.sin(this.pitch),-Math.cos(this.yaw)*Math.cos(this.pitch));}
 findHit(origin,direction,max,includeBots=true){let hit=this.world.collision.ray(origin,direction,max);if(hit)hit={kind:'environment',object:hit.object.owner,distance:hit.distance};let best=hit?.distance??max;const terrain=this.world.terrainHit(origin,direction,best);if(terrain!==null){best=terrain;hit={kind:'terrain',distance:terrain};}const ray=new T.Ray(origin,direction),tmp=new T.Vector3();if(includeBots)for(const b of this.bots){if(!b.alive)continue;const center=b.pos.clone().add(new T.Vector3(0,1,0)),head=b.pos.clone().add(new T.Vector3(0,1.73,0));let v=ray.intersectSphere(new T.Sphere(center,.47),tmp);if(v){const d=origin.distanceTo(v);if(d<best){best=d;hit={kind:'bot',bot:b,distance:d,head:false};}}v=ray.intersectSphere(new T.Sphere(head,.24),tmp);if(v){const d=origin.distanceTo(v);if(d<best+.25){best=d;hit={kind:'bot',bot:b,distance:d,head:true};}}}return hit;}
 applyShotHit(hit,damage,pos,by){if(hit.kind==='bot'){if(hit.head)damage*=2;const shield=hit.bot.shield>0;this.damageBot(hit.bot,damage,by);if(by==='player'){this.player.hits++;this.ui.damageNumber(damage,shield);this.sound.play(shield?'shield':'hit');$('hitmarker').style.opacity='1';setTimeout(()=>$('hitmarker').style.opacity='0',130);}}
 else if(hit.object){const o=hit.object;if(o.kind==='build')this.build.damage(o,damage);else{if(o.hp==null)return;o.hp-=damage;if(o.hp<=0){this.world.destroy(o);this.build.checkSupport();this.burst(pos,0xbdb48b,12);}else this.burst(pos,0xd2c2a1,4);}}}
 harvest(impactOnly=false){const dir=this.viewDirection(),origin=this.p.clone().add(new T.Vector3(0,1.3,0));let hit=this.findHit(this.render.camera.position,dir,12,true);if(hit){const point=this.render.camera.position.clone().addScaledVector(dir,hit.distance);if(point.distanceTo(origin)>4.4)hit=null;}if(!hit){const direct=this.world.collision.ray(origin,dir,4);if(direct)hit={kind:'environment',object:direct.object.owner,distance:direct.distance};}if(!impactOnly){this.swing=WEAPONS.pickaxe.rate;this.sound.play('pickaxe');}if(hit&&hit.kind!=='terrain'){const pos=origin.clone().addScaledVector(dir,Math.min(hit.distance,3));if(hit.kind==='bot'){this.damageBot(hit.bot,20,'player');this.ui.damageNumber(20,false);}else{const o=hit.object;if(o.kind==='build')this.build.damage(o,50);else{const mat=o.resource||'wood',n=o.kind==='tree'?12:o.kind==='rock'?10:7;this.player.materials[mat]=Math.min(999,this.player.materials[mat]+n);this.ui.notify(`+${n} ${mat.toUpperCase()}`,1);o.hp=(o.hp??150)-50;if(o.hp<=0){this.world.destroy(o);this.build.checkSupport();this.burst(pos,mat==='wood'?0xb79457:0xb9b5a5,18);}}this.sound.play('hit');this.burst(pos,0xdcc18e,7);}}}
 spawnProjectile(pos,dir,speed,type,owner){const meshP=new T.Mesh(type==='rocket'?new T.CylinderGeometry(.06,.06,.7,8):new T.SphereGeometry(.035,5,4),type==='rocket'?M.gold:M.light);meshP.position.copy(pos);meshP.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),dir);this.render.scene.add(meshP);this.projectiles.push({mesh:meshP,pos:pos.clone(),vel:dir.clone().multiplyScalar(speed),type,owner,age:0});}
 updateProjectiles(dt){for(let i=this.projectiles.length-1;i>=0;i--){const p=this.projectiles[i];p.age+=dt;if(p.type!=='rocket')p.vel.y-=9.8*dt;const step=p.vel.clone().multiplyScalar(dt),len=step.length(),dir=step.clone().normalize();const h=this.findHit(p.pos,dir,len,true);const next=p.pos.clone().add(step);if(h||next.y<this.world.height(next.x,next.z)||p.age>9){if(p.type==='rocket')this.explode(h?p.pos.clone().addScaledVector(dir,h.distance):next,p.owner);else if(h)this.applyShotHit(h,WEAPONS[p.type].damage,next,p.owner);this.render.scene.remove(p.mesh);this.projectiles.splice(i,1);continue;}p.pos.copy(next);p.mesh.position.copy(next);if(p.type==='rocket'&&Math.floor(p.age*20)%2===0)this.burst(next,0xd8c7b4,1,.25);}}
 explode(pos,owner){this.sound.play('explosion');this.burst(pos,0xfbc251,30,1.1);for(const b of this.bots)if(b.alive){const d=b.pos.distanceTo(pos);if(d<8)this.damageBot(b,110*(1-d/10),owner);}if(this.p.distanceTo(pos)<8)this.damagePlayer(110*(1-this.p.distanceTo(pos)/10));const seen=new Set();for(const c of this.world.collision.query(pos.x,pos.z,8)){const o=c.owner;if(seen.has(o))continue;seen.add(o);if(o.kind==='build')this.build.damage(o,180);else if(o.hp){o.hp-=160;if(o.hp<=0)this.world.destroy(o);this.build.checkSupport();}}}
 tracer(a,b,color=0xffcc79,time=.07){const geom=new T.BufferGeometry().setFromPoints([a,b]);const m=new T.Line(geom,new T.LineBasicMaterial({color,transparent:true,opacity:.8}));this.render.scene.add(m);this.effects.push({mesh:m,life:time,max:time});}
 flash(pos){const g=new T.Mesh(new T.IcosahedronGeometry(.1,0),new T.MeshBasicMaterial({color:0xffe883}));g.position.copy(pos);g.scale.set(1,1,3);this.render.scene.add(g);this.effects.push({mesh:g,life:.04,max:.04});}
 burst(pos,color,n=8,scale=.1){for(let i=0;i<n;i++){const m=new T.Mesh(new T.BoxGeometry(scale,scale,scale),new T.MeshStandardMaterial({color,roughness:1}));m.position.copy(pos);m.rotation.set(this.random()*6,this.random()*6,0);this.render.scene.add(m);this.effects.push({mesh:m,life:.5+this.random()*.35,max:.85,vel:new T.Vector3((this.random()-.5)*4,this.random()*4,(this.random()-.5)*4)});}}
 updateEffects(dt){for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;if(e.life<=0){this.render.scene.remove(e.mesh);e.mesh.geometry?.dispose();e.mesh.material?.dispose();this.effects.splice(i,1);}else if(e.vel){e.vel.y-=9*dt;e.mesh.position.addScaledVector(e.vel,dt);e.mesh.rotation.x+=dt*4;e.mesh.scale.setScalar(e.life/e.max);}}}
 damagePlayer(damage,source=null,ignoreShield=false){if(!['playing','drop','glide'].includes(this.state)||this.mode==='explore')return;if(this.damageGrace>0&&source)return;if(ignoreShield)this.player.health-=damage;else{const s=Math.min(this.player.shield,damage);this.player.shield-=s;this.player.health-=damage-s;}this.player.health=Math.max(0,this.player.health);if(source)this.damageGrace=.14;this.action=null;this.sound.play('hurt');$('damage-vignette').style.opacity='.85';setTimeout(()=>$('damage-vignette').style.opacity='0',220);if(this.player.health<=0){this.killer=source;this.state='eliminated';this.placement=this.aliveCount()+1;this.build.enabled=false;this.avatar.root.visible=false;this.burst(this.p.clone().add(new T.Vector3(0,1,0)),0x8cdcfa,20);this.recordResult(false);this.ui.results(false);}}
 damageBot(b,damage,by){if(!b.alive)return;const s=Math.min(b.shield,damage);b.shield-=s;b.health-=damage-s;b.alert=7;b.target=by==='player'?'player':by;b.buildCooldown=Math.min(b.buildCooldown,.3);if(b.health<=0){b.alive=false;if(b.model)b.model.root.visible=false;if(by==='player'){this.player.kills++;this.sound.play('eliminate');$('elimination').innerHTML=`ELIMINATED <b>${b.name}</b>`;setTimeout(()=>$('elimination').textContent='',2500);}this.ui.addFeed(`${by==='player'?'Player':typeof by==='object'?by.name:'The storm'} eliminated ${b.name}`);if(this.p.distanceTo(b.pos)<160){if(b.weapon)this.world.addLoot(b.weapon,b.pos.x,b.pos.y,b.pos.z);this.burst(b.pos.clone().add(new T.Vector3(0,1,0)),0x78cef1,14);}if(this.state==='playing'&&this.mode==='solo'&&this.aliveCount()===1)this.win();}}
 aliveCount(){return this.bots.filter(b=>b.alive).length+(this.player.health>0?1:0);}
 win(){if(this.state==='victory')return;this.state='victory';this.sound.play('victory');this.recordResult(true);this.ui.results(true);this.build.enabled=false;this.mouseDown=false;}
 recordResult(win){if(this.recorded)return;this.recorded=true;this.profile.matches++;this.profile.wins+=win?1:0;this.profile.kills+=this.player.kills;this.profile.chests+=this.player.chests;this.profile.xp+=Math.floor(this.matchTime*2+this.player.kills*100+(win?1000:200));this.saveProfile();}
 spectate(){this.ui.show('results',false);this.ui.show('spectating',true);this.state='spectating';this.paused=false;this.nextSpectator();}
 nextSpectator(){const alive=this.bots.filter(b=>b.alive);if(!alive.length){this.ui.show('spectating',false);this.ui.results(false);return;}const idx=alive.indexOf(this.spectatingBot);this.spectatingBot=alive[(idx+1)%alive.length];$('spectating-name').textContent=this.spectatingBot.name;}
 makeStorm(){const g=new T.CylinderGeometry(1,1,500,128,1,true);const m=new T.ShaderMaterial({side:T.DoubleSide,transparent:true,depthWrite:false,uniforms:{time:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform float time;void main(){float line=pow(abs(sin(vUv.x*1600.+time*.5)),18.);float wave=sin(vUv.y*100.-time*2.);gl_FragColor=vec4(.36+line*.3,.22+line*.42,.95,.16+line*.23+wave*.025);}' });const meshS=new T.Mesh(g,m);meshS.visible=false;this.render.scene.add(meshS);return meshS;}
 updateStorm(dt){const s=this.storm;if(!s.active||this.mode==='explore')return;s.timer-=dt;if(s.closing){const t=clamp(1-s.timer/s.duration,0,1);s.radius=lerp(s.fromRadius,s.nextRadius,t);s.x=lerp(s.fromX,s.nextX,t);s.z=lerp(s.fromZ,s.nextZ,t);}if(s.timer<=0){if(!s.closing){s.closing=true;s.fromRadius=s.radius;s.fromX=s.x;s.fromZ=s.z;s.duration=this.settings.pace==='quick'?38:72;s.timer=s.duration;this.sound.play('storm');this.ui.notify('STORM EYE SHRINKING',4);}else{s.closing=false;s.phase++;s.nextRadius=Math.max(0,s.radius*.52-8);const angle=this.random()*Math.PI*2,shift=(s.radius-s.nextRadius)*.42;s.nextX=s.x+Math.cos(angle)*shift;s.nextZ=s.z+Math.sin(angle)*shift;s.timer=this.settings.pace==='quick'?18:50;if(s.radius<4){s.radius=0;s.nextRadius=0;}this.ui.notify('A new storm circle has formed.',3);}}
 this.stormMesh.position.set(s.x,225,s.z);this.stormMesh.scale.set(s.radius,1,s.radius);this.stormMesh.material.uniforms.time.value=this.time;const viewed=this.state==='spectating'&&this.spectatingBot?this.spectatingBot.pos:this.p;this.inStorm=Math.hypot(viewed.x-s.x,viewed.z-s.z)>s.radius;this.stormTick=(this.stormTick||0)+dt;if(this.stormTick>=1){this.stormTick=0;const damage=Math.min(10,1+s.phase*1.5);if(this.inStorm)this.damagePlayer(damage,null,true);for(const b of this.bots)if(b.alive&&Math.hypot(b.pos.x-s.x,b.pos.z-s.z)>s.radius)this.damageBot(b,damage,'storm');}}
 makeBots(){const n=this.settings.bots,p=this.world.spawnIsland;for(let i=0;i<n;i++){this.bots.push({name:BOT_NAMES[i%BOT_NAMES.length]+(i>=BOT_NAMES.length?String(i):''),pos:new T.Vector3(p.x,p.y,p.z),phase:'waiting',dropPlan:makeDropPlan(i,n,this.random,this.world),hasDropped:false,airTime:0,health:100,shield:0,alive:true,weapon:null,ammo:0,model:null,distant:null,heading:this.random()*6.28,think:this.random()*1.5,shootCooldown:this.random()*2,buildCooldown:8+this.random()*10,materials:{wood:30,brick:0,metal:0},goal:null,path:[],pathTimer:0,target:null,alert:0,velY:0,age:0,lootCount:0});}}
 makeWarmup(){const p=this.world.spawnIsland;for(let i=0;i<Math.min(16,this.bots.length);i++){const actor=makeCharacter(i%3),angle=i*2.399,radius=6+(i%4)*4;actor.root.position.set(p.x+Math.cos(angle)*radius,p.y,p.z+Math.sin(angle)*radius*.5);actor.wander={heading:angle,turn:1+i*.09,jump:1+i*.23,vel:0,swing:0,steps:0};this.render.scene.add(actor.root);this.warmupActors.push(actor);}}
 updateWarmup(dt){const p=this.world.spawnIsland;for(let i=0;i<this.warmupActors.length;i++){const actor=this.warmupActors[i],w=actor.wander,pos=actor.root.position;w.turn-=dt;w.jump-=dt;w.swing=Math.max(0,w.swing-dt);if(w.turn<=0){const x=p.x+Math.sin(this.time*.45+i)*27,z=p.z+Math.cos(this.time*.53+i)*7;w.heading=Math.atan2(pos.x-x,pos.z-z);w.turn=1.2+i%3*.3;}const speed=2.2+(i%3)*.45,dx=-Math.sin(w.heading)*speed*dt,dz=-Math.cos(w.heading)*speed*dt;if(!this.world.blocked(pos.x+dx,pos.z+dz,pos.y)){pos.x+=dx;pos.z+=dz;w.steps+=Math.hypot(dx,dz);}else{w.heading+=1.5;w.turn=.3;}const h=this.world.ground(pos.x,pos.z,pos.y,.55);if(w.jump<=0&&pos.y<=h+.08){w.vel=i%3===0?6:0;w.swing=i%3===1?.48:0;w.jump=2.1+i*.15;}w.vel-=21.5*dt;pos.y=Math.max(h+.03,pos.y+w.vel*dt);if(pos.y<=h+.04)w.vel=0;actor.root.rotation.y=w.heading;actor.animate(this.time+i,speed,false,false,false,w.swing/.48,{airMode:w.vel?'jump':null});}}
 renderBot(b,i,distance){const airborne=b.phase==='drop'||b.phase==='glide',near=distance<180||b===this.spectatingBot;
  if(near&&!b.model){b.model=makeCharacter(i%3);b.model.setWeapon(b.weapon||'pickaxe');b.glider=makeGlider();b.model.root.add(b.glider);this.render.scene.add(b.model.root);}
  if(b.model){b.model.root.visible=near;b.model.root.position.copy(b.pos);b.model.root.rotation.y=b.heading;b.glider.visible=b.phase==='glide';if(near)b.model.animate(this.time+i,b.goal?3:0,!!b.target,false,airborne,Math.max(0,b.swing||0)/.48,{airMode:airborne?b.phase:null});}
  if(airborne&&!near&&distance<1200&&!b.distant){b.distant=makeDistantCharacter(i%3);b.farGlider=makeGlider();b.distant.add(b.farGlider);b.distant.traverse(m=>{if(m.isMesh)m.castShadow=false;});this.render.scene.add(b.distant);}
  if(b.distant){b.distant.visible=airborne&&!near&&distance<1200;b.distant.position.copy(b.pos);b.distant.rotation.y=b.heading;b.farGlider.visible=b.phase==='glide';}
 }

 botGoal(b){const s=this.storm;const dist=Math.hypot(b.pos.x-s.x,b.pos.z-s.z);if(s.active&&(dist>s.nextRadius*.9||s.phase>1)){const a=Math.atan2(b.pos.z-s.nextZ,b.pos.x-s.nextX);b.goal=new T.Vector3(s.nextX+Math.cos(a)*s.nextRadius*.3,this.world.height(s.nextX,s.nextZ),s.nextZ+Math.sin(a)*s.nextRadius*.3);b.lootTarget=null;return;}if(!b.weapon||b.lootCount<2){let nearest=null,best=250;for(const l of this.world.loot){if(!l.active||!WEAPONS[l.type].mag)continue;const d=b.pos.distanceTo(new T.Vector3(l.x,l.y,l.z));if(d<best){best=d;nearest=l;}}if(nearest){b.goal=new T.Vector3(nearest.x,nearest.y,nearest.z);b.lootTarget=nearest;return;}}const l=LOCATIONS[Math.floor(this.random()*LOCATIONS.length)];b.goal=new T.Vector3(l.x,l.y,l.z);b.lootTarget=null;}
 pathTo(b,goal){const step=2.56,origin={x:Math.round(b.pos.x/step),z:Math.round(b.pos.z/step)},tx=Math.round(goal.x/step),tz=Math.round(goal.z/step),key=(x,z)=>x+','+z;const start={...origin,g:0,f:0,parent:null},open=[start],seen=new Map([[key(start.x,start.z),start]]);let best=start;const heuristic=n=>Math.abs(n.x-tx)+Math.abs(n.z-tz);for(let k=0;k<180&&open.length;k++){open.sort((a,c)=>a.f-c.f);const n=open.shift();if(heuristic(n)<heuristic(best))best=n;if(heuristic(n)<1){best=n;break;}for(const[dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const x=n.x+dx,z=n.z+dz,id=key(x,z);if(seen.has(id))continue;const wx=x*step,wz=z*step,h=this.world.ground(wx,wz,b.pos.y,.55);let blocked=this.world.blocked(wx,wz,h);if(blocked){const doors=this.world.collision.query(wx,wz,1).filter(c=>c.kind==='door');if(doors.length)blocked=false;}if(blocked||Math.abs(h-this.world.ground(n.x*step,n.z*step,b.pos.y,.55))>1.2)continue;const a={x,z,g:n.g+(dx&&dz?1.41:1),parent:n};a.f=a.g+heuristic(a);seen.set(id,a);open.push(a);}}
 const path=[];while(best&&best.parent){path.unshift(new T.Vector3(best.x*step,b.pos.y,best.z*step));best=best.parent;}return path;}
 updateBots(dt){if(!['bus','playing','drop','glide','spectating'].includes(this.state))return;for(let i=0;i<this.bots.length;i++){const b=this.bots[i];if(!b.alive)continue;const viewer=this.state==='spectating'&&this.spectatingBot?.alive?this.spectatingBot.pos:this.p,distance=b.pos.distanceTo(viewer),near=distance<180;b.age+=dt;b.think-=dt;b.alert-=dt;b.shootCooldown-=dt;b.buildCooldown-=dt;b.pathTimer-=dt;b.swing=Math.max(0,(b.swing||0)-dt);if(b.phase==='waiting'||b.phase==='bus'){if(b.model)b.model.root.visible=false;if(b.distant)b.distant.visible=false;continue;}if(b.phase==='drop'||b.phase==='glide'){advanceBotDrop(b,dt,this.world);this.renderBot(b,i,distance);continue;}this.renderBot(b,i,distance);
 if(b.think<=0){b.think=.65+this.random()*.6;if(this.storm.active&&Math.hypot(b.pos.x-this.storm.nextX,b.pos.z-this.storm.nextZ)>this.storm.nextRadius*.9)this.botGoal(b);if(!b.goal||b.pos.distanceTo(b.goal)<3||b.lootTarget&&!b.lootTarget.active)this.botGoal(b);let target=null,best=near&&this.player.health>0&&this.state==='playing'?distance:180;if(best<100&&this.player.health>0)target='player';for(const o of this.bots){if(o===b||!o.alive||o.phase!=='grounded')continue;const d=b.pos.distanceTo(o.pos);if(d<best&&d<105){best=d;target=o;}}b.target=target;if(b.target&&b.weapon){const tp=target==='player'?this.p:target.pos,dir=tp.clone().add(new T.Vector3(0,1.1,0)).sub(b.pos.clone().add(new T.Vector3(0,1.4,0))).normalize(),h=this.world.collision.ray(b.pos.clone().add(new T.Vector3(0,1.4,0)),dir,best-1);if(h||this.world.terrainHit(b.pos.clone().add(new T.Vector3(0,1.4,0)),dir,best-1)!==null)b.target=null;}if(near&&b.goal&&b.pathTimer<=0){b.path=this.pathTo(b,b.goal);b.pathTimer=3;}}
 if(b.lootTarget?.active&&b.pos.distanceTo(new T.Vector3(b.lootTarget.x,b.lootTarget.y,b.lootTarget.z))<3){const l=b.lootTarget;b.weapon=l.type;b.ammo=WEAPONS[l.type].mag+60;b.lootCount++;l.active=false;l.mesh.visible=false;b.model?.setWeapon(b.weapon);b.lootTarget=null;b.goal=null;if(this.random()>.6)b.shield=25;}
 if(b.target&&b.weapon){const target=b.target==='player'?this.p:b.target.pos;if(!target||b.target!=='player'&&!b.target.alive){b.target=null;continue;}const d=b.pos.distanceTo(target);b.heading=Math.atan2(b.pos.x-target.x,b.pos.z-target.z);if(b.shootCooldown<=0&&d<130){const w=WEAPONS[b.weapon];b.shootCooldown=Math.max(w.rate,.48)+this.random()*.55;if(b.ammo<=0){b.shootCooldown=2.5;b.ammo=w.mag;}b.ammo--;const origin=b.pos.clone().add(new T.Vector3(0,1.38,0)),end=target.clone().add(new T.Vector3(0,1.1,0)),dir=end.clone().sub(origin).normalize();const hit=this.world.collision.ray(origin,dir,d-1);if(!hit&&this.world.terrainHit(origin,dir,d-1)===null){if(near){this.tracer(origin,end,0xffd183,.1);if(distance<60)this.sound.tone(140,.08,'triangle',.025,60);}const chance=clamp(.7-d*.004,.13,.7)*(b.target==='player'?.55:.9);if(this.random()<chance){const damage=w.damage*(w.pellets?w.pellets*.5:1)*.8;if(b.target==='player')this.damagePlayer(damage,b);else this.damageBot(b.target,damage,b);}}}
 if(b.buildCooldown<=0&&b.alert>0&&b.materials.wood>=10&&near){const yaw=b.heading,x=Math.round((b.pos.x-Math.sin(yaw)*3)/BUILD.tile)*BUILD.tile,z=Math.round((b.pos.z-Math.cos(yaw)*3)/BUILD.tile)*BUILD.tile,rot=Math.round(yaw/(Math.PI/2))*Math.PI/2,t={x,z,y:b.pos.y,anchor:b.pos.y,rot,rotation:Math.round(yaw/(Math.PI/2)),type:this.random()>.6?'ramp':'wall',material:'wood',valid:true};if(this.build.supported(t))this.build.place(b.materials,t);b.buildCooldown=9;}
 if(d>25){b.goal=target.clone();}else if(this.random()<dt*.4){b.goal=b.pos.clone().add(new T.Vector3((this.random()-.5)*10,0,(this.random()-.5)*10));}}
 if(b.goal){let target=near&&b.path.length?b.path[0]:b.goal;if(Math.hypot(target.x-b.pos.x,target.z-b.pos.z)<1){b.path.shift();target=b.path[0]||b.goal;}const dx=target.x-b.pos.x,dz=target.z-b.pos.z,len=Math.hypot(dx,dz);if(len>1){const speed=(b.target?3:4.5)*(this.world.wet(b.pos.x,b.pos.z)?.55:1),vx=dx/len*speed*dt,vz=dz/len*speed*dt;if(!b.target)b.heading=Math.atan2(-dx,-dz);if(!this.world.blocked(b.pos.x+vx,b.pos.z+vz,b.pos.y)){b.pos.x+=vx;b.pos.z+=vz;}else{const door=this.world.collision.query(b.pos.x+dx/len,b.pos.z+dz/len,1.5).find(c=>c.kind==='door'&&c.active);if(door)this.world.toggleDoor(door.owner);else if(!this.world.blocked(b.pos.x+vz,b.pos.z-vx,b.pos.y)){b.pos.x+=vz;b.pos.z-=vx;b.pathTimer=0;}else if(!this.world.blocked(b.pos.x-vz,b.pos.z+vx,b.pos.y)){b.pos.x-=vz;b.pos.z+=vx;b.pathTimer=0;}else{const hit=this.world.collision.ray(b.pos.clone().add(new T.Vector3(0,1.1,0)),new T.Vector3(dx/len,0,dz/len),2.5)?.object;if(hit?.owner?.hp&&b.shootCooldown<=0){b.swing=.48;hit.owner.hp-=25;if(hit.owner.hp<=0)this.world.destroy(hit.owner);b.shootCooldown=.6;}}}}}
 const ground=this.world.ground(b.pos.x,b.pos.z,b.pos.y,.55);if(b.pos.y>ground+.1){b.velY-=19*dt;b.pos.y=Math.max(ground,b.pos.y+b.velY*dt);}else{b.pos.y=ground+.02;b.velY=0;}if(b.pos.y<1&&!this.world.wet(b.pos.x,b.pos.z)){this.botGoal(b);} }
 }
 movePlayer(dt){const p=this.player;let dx=(this.input.has('KeyD')?1:0)-(this.input.has('KeyA')?1:0),dz=(this.input.has('KeyW')?1:0)-(this.input.has('KeyS')?1:0);if(this.input.has('ArrowLeft'))this.yaw+=dt*1.7;if(this.input.has('ArrowRight'))this.yaw-=dt*1.7;if(this.input.has('ArrowUp'))this.pitch-=dt;if(this.input.has('ArrowDown'))this.pitch+=dt;this.pitch=clamp(this.pitch,-1.2,1.25);p.crouch=this.input.has('ControlLeft')||this.input.has('KeyC');const len=Math.hypot(dx,dz);if(len){dx/=len;dz/=len;}
 const airborne=this.state==='drop'||this.state==='glide';let speed=airborne?(this.state==='drop'?17:13):p.crouch?2.1:this.aim?3.1:this.input.has('ShiftLeft')?5.5:4.15;const wet=this.world.wet(this.p.x,this.p.z);if(wet&&!airborne)speed*=.49;const mx=(Math.cos(this.yaw)*dx-Math.sin(this.yaw)*dz)*speed*dt,mz=(-Math.sin(this.yaw)*dx-Math.cos(this.yaw)*dz)*speed*dt;this.moveSpeed=len*speed;
 if(airborne){this.p.x+=mx;this.p.z+=mz;if(this.state==='drop'){p.velY=Math.max(-49,p.velY-16*dt);if(this.p.y-this.world.height(this.p.x,this.p.z)<40){this.state='glide';this.glider.visible=true;this.sound.play('glide');}}if(this.state==='glide')p.velY=lerp(p.velY,-5.5,Math.min(1,dt*4));this.p.y+=p.velY*dt;const h=this.world.ground(this.p.x,this.p.z,this.p.y+2,.5);if(this.p.y<=h+.06){this.p.y=h+.05;p.velY=0;p.onGround=true;this.state='playing';this.glider.visible=false;this.ui.notify('Land, loot, and survive.',4);this.damageGrace=3;}}
 else{const groundBefore=this.world.ground(this.p.x,this.p.z,this.p.y,.52);if(!this.world.blocked(this.p.x+mx,this.p.z,this.p.y,.3,p.crouch?1.28:1.7))this.p.x+=mx;if(!this.world.blocked(this.p.x,this.p.z+mz,this.p.y,.3,p.crouch?1.28:1.7))this.p.z+=mz;const ground=this.world.ground(this.p.x,this.p.z,this.p.y,.53);if(p.onGround&&ground>this.p.y&&ground-this.p.y<.55)this.p.y=ground;if(this.p.y>ground+.09)p.onGround=false;if(!p.onGround){p.velY-=21.5*dt;const ny=this.p.y+p.velY*dt;if(p.velY>0){const roof=this.world.collision.query(this.p.x,this.p.z,.3).find(c=>c.active&&!c.sensor&&c.min.y>this.p.y+1.3&&c.min.y<ny+1.8&&this.p.x>c.min.x-.2&&this.p.x<c.max.x+.2&&this.p.z>c.min.z-.2&&this.p.z<c.max.z+.2);if(roof)p.velY=-.1;}this.p.y+=p.velY*dt;if(this.p.y<=ground+.04){if(p.velY<-14)this.damagePlayer(Math.pow(-p.velY-13,1.8)*2,null,true);this.p.y=ground+.04;p.velY=0;p.onGround=true;this.sound.play('step');}}else this.p.y=ground+.03;if(len&&p.onGround){p.distance+=speed*dt;this.footstep=(this.footstep||0)+dt;if(this.footstep>.36){this.sound.play('step');this.footstep=0;}}}
 if(this.p.y<-7&&this.mode==='solo')this.damagePlayer(100,null,true);this.p.x=clamp(this.p.x,-1390,1390);this.p.z=clamp(this.p.z,-1390,1390);
 this.avatar.root.visible=true;this.avatar.root.position.copy(this.p);this.avatar.root.rotation.y=this.yaw;this.avatar.setWeapon(this.build.enabled?'blueprint':this.weaponType());this.avatar.animate(this.time,this.moveSpeed,this.aim,p.crouch,airborne,Math.max(0,this.swing||0)/WEAPONS.pickaxe.rate,{airMode:airborne?this.state:!p.onGround?'jump':null,action:this.action?.kind,progress:this.action?1-this.action.remaining/(WEAPONS[this.weaponType()].reload||WEAPONS[this.weaponType()].use||1):0});if(this.harvestImpact!==null&&this.harvestImpact!==undefined){this.harvestImpact-=dt;if(this.harvestImpact<=0){this.harvestImpact=null;if(this.weaponType()==='pickaxe')this.harvest(true);}}this.glider.visible=this.state==='glide';this.swing=Math.max(0,(this.swing||0)-dt);}
 updateInteraction(){if(!['playing','prematch'].includes(this.state)||this.build.enabled){$('interaction').style.display='none';this.interaction=null;return;}let near=null,best=3;for(const l of this.world.loot){if(!l.active)continue;const d=this.p.distanceTo(new T.Vector3(l.x,l.y,l.z));if(d<best){best=d;near={kind:'loot',item:l,text:WEAPONS[l.type].name};}}for(const c of this.world.chests){if(c.opened||c.dead)continue;const d=this.p.distanceTo(new T.Vector3(c.x,c.y,c.z));if(d<best){best=d;near={kind:'chest',item:c,text:'Search chest'};}}for(const c of this.world.collision.query(this.p.x,this.p.z,2.6)){if(c.owner?.kind==='door'){const o=c.owner,d=Math.hypot(this.p.x-o.x,this.p.z-o.z);if(d<best){best=d;near={kind:'door',item:o,text:o.open?'Close door':'Open door'};}}}if(!near){for(const b of this.world.buildings){if(Math.hypot(b.x-this.p.x,b.z-this.p.z)>25)continue;const door=b.parts.find(o=>o.kind==='door'&&o.open&&Math.hypot(o.x-this.p.x,o.z-this.p.z)<2.8);if(door){near={kind:'door',item:door,text:'Close door'};break;}}}this.interaction=near;$('interaction').style.display=near?'block':'none';if(near)$('interaction').innerHTML=`<kbd>E</kbd> ${near.text}`;}
 updateCamera(dt){const {camera,sun}=this.render;let follow=this.p;if(this.state==='lobby'){const t=this.time*.08;camera.fov=39;camera.position.set(this.p.x+.7,this.p.y+1.68,this.p.z+3.6);camera.lookAt(this.p.x-.05,this.p.y+1.03,this.p.z);this.avatar.root.visible=true;this.avatar.root.position.copy(this.p);this.avatar.root.rotation.y=Math.PI+.38;this.avatar.animate(this.time,0,false,false,false);this.glider.visible=false;}
 else if(this.state==='bus'){camera.fov=73;camera.position.copy(this.bus.position).add(new T.Vector3(19,16,32));camera.lookAt(this.bus.position.clone().add(new T.Vector3(0,-22,0)));}
 else{if(this.state==='spectating'&&this.spectatingBot?.alive){follow=this.spectatingBot.pos;this.yaw=this.spectatingBot.heading;}const dir=this.viewDirection(),air=['drop','glide'].includes(this.state),scope=this.aim&&WEAPONS[this.weaponType()].scope;camera.fov=lerp(camera.fov,scope?24:this.aim?55:72,Math.min(1,dt*12));const target=follow.clone().add(new T.Vector3(0,this.player.crouch?1.13:1.62,0));const right=new T.Vector3(Math.cos(this.yaw),0,-Math.sin(this.yaw));const dist=air?8:this.aim?2.0:3.8;const desired=target.clone().addScaledVector(dir,-dist).addScaledVector(right,air?.5:.64);if(!air){const v=desired.clone().sub(target),h=this.world.collision.ray(target,v.clone().normalize(),v.length());if(h)desired.copy(target).addScaledVector(v.normalize(),Math.max(.38,h.distance-.24));desired.y=Math.max(desired.y,this.world.height(desired.x,desired.z)+.32);}camera.position.copy(desired);camera.lookAt(target.clone().addScaledVector(dir,40));camera.rotateZ(this.recoil*.07);this.ui.show('scope',scope&&this.state==='playing');$('crosshair').style.display=scope||air||this.build.enabled?'none':'block';$('crosshair').style.setProperty('--spread',`${this.aim?4:8+this.moveSpeed*.7+this.recoil*120}px`);}
 camera.updateProjectionMatrix();const groundY=this.world.height(follow.x,follow.z);sun.position.set(follow.x-110,groundY+160,follow.z+80);sun.target.position.set(follow.x,groundY,follow.z);sun.target.updateMatrixWorld();}
 updateLocation(dt){let loc=null,d=Infinity;for(const l of LOCATIONS){const v=Math.hypot(this.p.x-l.x,this.p.z-l.z);if(v<l.r*1.1&&v<d){d=v;loc=l;}}if(loc&&loc!==this.location&&['playing','drop','glide'].includes(this.state)){this.location=loc;this.locTimer=4;$('location-banner').innerHTML=`<small>ENTERED</small>${loc.name.toUpperCase()}`;}this.locTimer-=dt;if(this.locTimer<=0)$('location-banner').textContent='';}
 updatePhase(dt){
  if(this.busFlight?.active){const flight=this.busFlight;flight.elapsed=Math.min(BUS_SECONDS,flight.elapsed+dt);this.bus.position.copy(busPosition(flight.elapsed));for(const b of this.bots){if(!b.alive||b.phase!=='bus')continue;b.pos.copy(this.bus.position);if(flight.elapsed>=b.dropPlan.jumpAt){b.pos.y-=4;b.pos.x+=b.dropPlan.exitOffset;b.phase='drop';b.hasDropped=true;b.velY=-11;b.exitTime=flight.elapsed;b.dropOrigin=b.pos.clone();}}if(flight.elapsed>=BUS_SECONDS){flight.active=false;if(this.state==='bus')this.jumpBus();this.bus.visible=false;}}
  const state=this.state;let message='';if(state==='prematch'){this.phaseTimer-=dt;message='WAITING FOR PLAYERS <small>Battle Bus launching in '+Math.ceil(this.phaseTimer)+'s</small>';if(this.phaseTimer<=0)this.launchBus();}
  else if(state==='bus'){this.phaseTimer=BUS_SECONDS-this.busFlight.elapsed;this.p.copy(this.bus.position);message='EVERYBODY OFF. LAST STOP IN '+Math.ceil(this.phaseTimer)+'s <small>Press <kbd>SPACE</kbd> to jump</small>';}
  else if(state==='drop')message='<small>Press <kbd>SPACE</kbd> to deploy glider</small>';else if(state==='glide')message='<small>Steer with <kbd>W A S D</kbd> · Find a rooftop or open ground</small>';$('phase-message').innerHTML=message;
 }

 frame(now){if(this.qaStopped)return;const raw=(now-this.last)/1000,dt=Math.min(.045,raw);this.last=now;this.fps=lerp(this.fps,1/Math.max(.001,raw),.025);this.time+=dt;if(!this.paused){this.cooldown-=dt;this.recoil*=Math.exp(-dt*12);this.damageGrace=Math.max(0,(this.damageGrace||0)-dt);this.updatePhase(dt);if(this.state==='prematch')this.updateWarmup(dt);if(['prematch','playing','drop','glide'].includes(this.state)){this.movePlayer(dt);this.build.update(dt,this.p,this.yaw,this.pitch,this.player.materials);if(this.mouseDown&&(this.settings.turbo||!this.build.enabled))this.fire();this.updateAction(dt);this.updateInteraction();this.updateLocation(dt);}if(['bus','playing','drop','glide','spectating'].includes(this.state)){this.matchTime+=dt;if(this.state!=='bus')this.updateStorm(dt);this.updateBots(dt);if(this.state==='spectating'){const alive=this.bots.filter(b=>b.alive);if(alive.length<=1){this.state='eliminated';this.ui.show('spectating',false);this.ui.results(false);this.ui.show('spectate',false);this.ui.notify(alive[0]?alive[0].name+' won the match.':'The match has ended.',9);}else if(!this.spectatingBot?.alive)this.nextSpectator();}}this.updateProjectiles(dt);this.updateEffects(dt);}
 this.updateCamera(dt);const focal=this.state==='spectating'&&this.spectatingBot?this.spectatingBot.pos:this.p;this.world.update(this.time,focal,['bus','drop','glide'].includes(this.state),this.settings.quality);this.ui.update(dt);this.render.draw();requestAnimationFrame(t=>this.frame(t));}
 installDiagnostics(){const output=document.createElement('output');output.id='game-diagnostics';output.hidden=true;document.body.appendChild(output);setInterval(()=>{output.textContent=JSON.stringify(this.snapshot());},1000);window.chapterOne=this;document.addEventListener('mousemove',e=>{if(this.fallbackMouse&&this.mouseActive&&this.isControllable()&&this.aim){this.yaw-=e.movementX*.0022*this.settings.sensitivity;this.pitch=clamp(this.pitch+e.movementY*.002*this.settings.sensitivity,-1.2,1.25);}});}
 snapshot(){return {state:this.state,mode:this.mode,paused:this.paused,position:this.p.toArray().map(v=>+v.toFixed(2)),location:this.location?.name,health:this.player.health,shield:this.player.shield,alive:this.aliveCount(),kills:this.player.kills,builds:this.build.pieces.filter(b=>!b.dead).length,inventory:this.player.inventory,materials:this.player.materials,interaction:this.interaction?.text||null,stats:this.world.stats,storm:{phase:this.storm.phase,radius:Math.round(this.storm.radius),closing:this.storm.closing},character:this.avatar.name,bots:{waiting:this.bots.filter(b=>b.phase==='waiting').length,onBus:this.bots.filter(b=>b.phase==='bus').length,dropping:this.bots.filter(b=>b.phase==='drop').length,gliding:this.bots.filter(b=>b.phase==='glide').length,landed:this.bots.filter(b=>b.phase==='grounded').length,total:this.bots.length,alive:this.bots.filter(b=>b.alive).length,armed:this.bots.filter(b=>b.alive&&b.weapon).length,looted:this.bots.reduce((n,b)=>n+b.lootCount,0)},fps:Math.round(this.fps),calls:this.render.renderer.info.render.calls};}
 registerAgentControls(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const register=(name,description,inputSchema,execute,readOnlyHint=false)=>{try{Promise.resolve(ctx.registerTool({name,description,inputSchema,execute,annotations:{readOnlyHint,untrustedContentHint:false}})).catch(console.warn);}catch(e){console.warn(e);}};
 register('read_game_state','Read the local match, player inventory, position, and performance.',{type:'object',properties:{},additionalProperties:false},()=>this.snapshot(),true);
 register('start_local_match','Start a new local Solo or Explore match. This replaces the current local match.',{type:'object',properties:{mode:{enum:['solo','explore']}},required:['mode'],additionalProperties:false},({mode})=>{if(!['solo','explore'].includes(mode))throw Error('Invalid mode');this.mode=mode;this.startMatch();return this.snapshot();});
 register('travel_in_explore','Travel to a named location in Explore mode. Unavailable in Solo.',{type:'object',properties:{location:{enum:LOCATIONS.map(l=>l.name)}},required:['location'],additionalProperties:false},({location})=>{if(this.mode!=='explore'||this.state==='lobby')throw Error('Start Explore mode first');const i=LOCATIONS.findIndex(l=>l.name===location);if(i<0)throw Error('Unknown location');this.ui.close(false);this.travel(i);return this.snapshot();});
 register('play_game_input','Operate the same movement, camera, equipment and actions as keyboard and mouse controls for up to four seconds.',{type:'object',properties:{seconds:{type:'number',minimum:.05,maximum:4},keys:{type:'array',items:{enum:['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ControlLeft']}},lookYaw:{type:'number',minimum:-360,maximum:360},lookPitch:{type:'number',minimum:-65,maximum:65},fire:{type:'boolean'},aim:{type:'boolean'},action:{enum:['none','jump','interact','reload','build','repair']},slot:{type:'integer',minimum:0,maximum:5}},required:['seconds'],additionalProperties:false},async({seconds,keys=[],lookYaw,lookPitch,fire=false,aim=false,action='none',slot})=>{if(!Number.isFinite(seconds)||seconds<.05||seconds>4)throw Error('seconds must be between 0.05 and 4');if(this.ui.overlay)this.ui.close(false);if(this.state==='lobby')throw Error('Start a match first');if(lookYaw!==undefined)this.yaw=lookYaw*Math.PI/180;if(lookPitch!==undefined)this.pitch=lookPitch*Math.PI/180;if(slot!==undefined)this.equip(slot);if(action==='jump'){if(this.state==='bus')this.jumpBus();else if(this.state==='drop'){this.state='glide';this.glider.visible=true;}else if(this.player.onGround){this.player.velY=7.3;this.player.onGround=false;}}if(action==='interact')this.interact();if(action==='reload')this.reload();if(action==='build')this.build.toggle(this.p);if(action==='repair')this.build.repair(this.p,this.player.materials);for(const k of keys){if(!['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ControlLeft'].includes(k))throw Error('Invalid movement key');this.input.add(k);}this.mouseDown=fire;this.aim=aim;await new Promise(r=>setTimeout(r,seconds*1000));this.input.clear();this.mouseDown=false;this.aim=false;return this.snapshot();});}
}
function fatal(e){if(window.chapterOneBoot){window.chapterOneBoot.fail(e);return;}console.error(e);$('fatal-text').textContent=e?.stack||String(e);$('fatal-error').classList.remove('hidden');$('loading').classList.add('hidden');}
try{const game=new Game();await game.init();window.chapterOneBoot?.ready();}catch(e){fatal(e);}
