import {createPost} from './post.js';
import * as T from '../vendor/three.module.js';
import {rng,clamp} from './math.js';
export {T};
export const geo={box:new T.BoxGeometry(1,1,1),cylinder:new T.CylinderGeometry(1,1,1,16),cone:new T.ConeGeometry(1,1,12),sphere:new T.IcosahedronGeometry(1,2),rock:new T.IcosahedronGeometry(1,1),leafLOD:new T.IcosahedronGeometry(1,1),leaf:new T.IcosahedronGeometry(1,3)};
for(let i=0;i<geo.leaf.attributes.position.count;i++){const p=geo.leaf.attributes.position,x=p.getX(i),y=p.getY(i),z=p.getZ(i),s=1+.045*Math.sin(x*19+y*21)*Math.cos(z*17);p.setXYZ(i,x*s,y*s,z*s);}geo.leaf.computeVertexNormals();
const texRandom=rng(117);
function texture(type){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle='#b8b4a7';x.fillRect(0,0,256,256);
 if(type==='brick'){x.fillStyle='#888478';x.fillRect(0,0,256,256);for(let row=0;row<8;row++)for(let col=-1;col<5;col++){const px=col*64+(row%2)*32,py=row*32;const v=191+texRandom()*28;x.fillStyle=`rgb(${v},${v*.94},${v*.86})`;x.beginPath();x.roundRect(px+1.5,py+1.5,61,29,3);x.fill();x.fillStyle='#ffffff2c';x.fillRect(px+4,py+3,55,2);x.fillStyle='#00000020';x.fillRect(px+4,py+27,55,2);}}
 else if(type==='wood'){x.fillStyle='#b5a286';x.fillRect(0,0,256,256);for(let i=0;i<8;i++){x.fillStyle=i%3?'#ffffff12':'#00000012';x.fillRect(i*32,0,30,256);x.fillStyle='#3b352aaa';x.fillRect(i*32,0,2,256);for(let j=0;j<25;j++){let px=i*32+texRandom()*30;x.strokeStyle=texRandom()>.5?'#00000017':'#ffffff19';x.beginPath();x.moveTo(px,0);x.bezierCurveTo(px+10,72,px-9,145,px,256);x.stroke();}for(let y=18;y<256;y+=118){x.fillStyle='#55504b';x.fillRect(i*32+7,y,3,3);}}}
 else if(type==='roof'){x.fillStyle='#73787c';x.fillRect(0,0,256,256);for(let y=0;y<8;y++)for(let i=-1;i<8;i++){const a=i*40+(y%2)*20;x.fillStyle=`hsl(215,8%,${40+texRandom()*18}%)`;x.fillRect(a,y*32+1,38,30);x.fillStyle='#171e3250';x.fillRect(a,y*32+28,38,4);}}
 else if(type==='metal'){x.fillStyle='#afb7b9';x.fillRect(0,0,256,256);for(let i=0;i<32;i++){x.fillStyle=i%2?'#0000001e':'#ffffff20';x.fillRect(i*8,0,4,256);}x.fillStyle='#414c55';x.fillRect(0,0,256,3);x.fillRect(0,127,256,3);for(let i=8;i<256;i+=32){x.fillStyle='#596775';x.beginPath();x.arc(i,7,2,0,7);x.fill();}}
 else if(type==='tile'){for(let y=0;y<8;y++)for(let i=0;i<8;i++){x.fillStyle=(i+y)%2?'#79848a':'#c9c6ae';x.fillRect(i*32,y*32,31,31);}}
 else if(type==='grass'){x.fillStyle='#c1c1b5';x.fillRect(0,0,256,256);for(let i=0;i<5200;i++){x.fillStyle=texRandom()>.5?'#eeeeee26':'#40403824';x.fillRect(texRandom()*256,texRandom()*256,2+texRandom()*8,1+texRandom()*6);}}
 else {x.fillStyle='#c0c0b5';x.fillRect(0,0,256,256);}
 if(type!=='tile')for(let i=0;i<7000;i++){x.fillStyle=texRandom()>.5?'#ffffff0b':'#0000000e';x.fillRect(texRandom()*256,texRandom()*256,texRandom()*3+1,texRandom()*3+1);}
 const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;return t;}
const textures={};
export function material(color,type,scale=1){const m=new T.MeshStandardMaterial({color,roughness:.94,metalness:type==='metal'?.15:0});if(type){m.map=textures[type]??=texture(type);m.onBeforeCompile=s=>{s.vertexShader='varying vec3 vWorldPoint; varying vec3 vWorldNormal;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\nvec4 wp=vec4(position,1.0); vec3 wn=normal;\n#ifdef USE_INSTANCING\nwp=instanceMatrix*wp; wn=mat3(instanceMatrix)*wn;\n#endif\nvWorldPoint=(modelMatrix*wp).xyz;vWorldNormal=normalize(mat3(modelMatrix)*wn);`);s.fragmentShader='varying vec3 vWorldPoint; varying vec3 vWorldNormal;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>',`vec3 nw=abs(normalize(vWorldNormal));vec2 tx=nw.y>0.65?vWorldPoint.xz:(nw.x>nw.z?vWorldPoint.zy:vWorldPoint.xy);diffuseColor*=texture2D(map,tx*${scale.toFixed(4)});`);};m.customProgramCacheKey=()=>type+scale;}return m;}
export const M={
 brick:material(0xb88169,'brick',.45),redbrick:material(0xb06547,'brick',.5),stone:material(0xd4cabc,'brick',.45),concrete:material(0xd6d2b8,'plaster',.5),trim:material(0xe9e4cd),darktrim:material(0x5a5146),
 blue:material(0x88b9c2,'wood',.36),white:material(0xddd7b6,'wood',.36),yellow:material(0xdac079,'wood',.36),pink:material(0xc29488,'wood',.36),green:material(0x84aa8e,'wood',.36),
 wood:material(0xb29568,'wood',.5),bark:material(0x6b5438,'wood',.25),floor:material(0xc0a377,'wood',.4),roof:material(0x667580,'roof',.7),redroof:material(0xbd6044,'roof',.65),
 metal:material(0xa6b3b9,'metal',.5),rust:material(0xb88061,'metal',.4),steel:material(0x52616a,'metal',.5),dark:material(0x283945),black:material(0x202830),glass:new T.MeshStandardMaterial({color:0x416a78,roughness:.22,metalness:.42}),tile:material(0xf5e9cd,'tile',.45),
 asphalt:material(0x54626a,'plaster',.3),sidewalk:material(0xd1c6ad,'brick',.25),roadline:material(0xe0ce91),dirt:material(0xaaa078,'plaster',.3),grass:material(0x739a43,'grass',.23),
 leaf:material(0x548541,'grass',.5),leaflight:material(0x78a148,'grass',.5),pine:material(0x3e7750,'grass',.4),bush:material(0x648842,'grass',.5),pinkleaf:material(0xe78da4,'grass',.6),rock:material(0xb9b4a0,'plaster',.22),
 carblue:new T.MeshStandardMaterial({color:0x5a8fa2,roughness:.35,metalness:.25}),carred:new T.MeshStandardMaterial({color:0xb94f3d,roughness:.36,metalness:.25}),caryellow:new T.MeshStandardMaterial({color:0xd9b252,roughness:.38,metalness:.2}),cargreen:new T.MeshStandardMaterial({color:0x4e897b,roughness:.36,metalness:.2}),carcream:new T.MeshStandardMaterial({color:0xc9c7a9,roughness:.36,metalness:.2}),red:material(0xc55242),cream:material(0xf1d79f),orange:material(0xdb943c),gold:material(0xf5b936),cloth:material(0x6b814d),skin:material(0xd6a878),pants:material(0x876f4f),boot:material(0x3f3930),vest:material(0x53624b),hair:material(0x7f633a),
 light:new T.MeshBasicMaterial({color:0xffe9ad}),water:new T.MeshStandardMaterial({color:0x34647e,roughness:.3,metalness:.2,transparent:true,opacity:.8})
};
M.roof.side=M.redroof.side=T.DoubleSide;
export async function loadWorldTextures(){const t=await new T.TextureLoader().loadAsync('assets/foliage.png');t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;for(const k of ['leaf','leaflight','bush','pine']){M[k].map=t;M[k].color.setHex(k==='pine'?0x86bb9d:k==='leaflight'?0xd3e4ab:0xa9c992);M[k].needsUpdate=true;}}
export class Batcher{
 constructor(scene){this.scene=scene;this.buckets=new Map();this.meshes=[];this.dummy=new T.Object3D();this.serial=0;this.ready=false;this.cells=new Map();}
 add(kind,mat,pos,scale,rot=0,owner=null,detail=0){const key=kind+':'+mat.uuid+':'+Math.floor(pos[0]/160)+':'+Math.floor(pos[2]/160)+':'+detail;let b=this.buckets.get(key);if(!b){b={kind,mat,entries:[],detail,x:Math.floor(pos[0]/160)*160+80,z:Math.floor(pos[2]/160)*160+80};this.buckets.set(key,b);}const d=this.dummy;d.position.set(...pos);d.scale.set(...scale);if(Array.isArray(rot))d.rotation.set(...rot);else d.rotation.set(0,rot,0);d.updateMatrix();const ref={b,index:b.entries.length,matrix:d.matrix.clone()};b.entries.push(ref);if(owner)(owner.refs??=[]).push(ref);return ref;}
 box(mat,x,y,z,w,h,d,rot=0,owner=null,detail=0){return this.add('box',mat,[x,y,z],[w,h,d],rot,owner,detail);}
 build(){for(const b of this.buckets.values()){const mesh=new T.InstancedMesh(geo[b.kind],b.mat,b.entries.length);for(const e of b.entries)mesh.setMatrixAt(e.index,e.matrix);mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);mesh.castShadow=true;mesh.receiveShadow=true;mesh.computeBoundingSphere();b.mesh=mesh;this.scene.add(mesh);this.meshes.push(b);}this.ready=true;}
 hide(owner){for(const r of owner.refs||[]){const a=new T.Matrix4().makeScale(0,0,0);if(r.b.mesh){r.b.mesh.setMatrixAt(r.index,a);r.b.mesh.instanceMatrix.needsUpdate=true;}else r.matrix=a;}}
 update(x,z,aerial=false,quality='high'){const max=aerial?4000:quality==='low'?470:quality==='medium'?720:1000;for(const b of this.meshes){const d=Math.hypot(x-b.x,z-b.z);b.mesh.visible=d<(b.detail?170:max)+130;b.mesh.castShadow=d<150;if(b.kind==='leaf')b.mesh.geometry=d<220?geo.leaf:geo.leafLOD;}}
}
export function mesh(kind,mat,parent,pos,scale,rot=0){const m=new T.Mesh(geo[kind],mat);m.position.set(...pos);m.scale.set(...scale);if(Array.isArray(rot))m.rotation.set(...rot);else m.rotation.y=rot;m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
export function beam(parent,mat,a,b,width=.1){const v1=new T.Vector3(...a),v2=new T.Vector3(...b),mid=v1.clone().add(v2).multiplyScalar(.5);const m=mesh('cylinder',mat,parent,mid.toArray(),[width,v1.distanceTo(v2),width]);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v2.sub(v1).normalize());return m;}
export function labelTexture(text,bg='#264c5b',fg='#fff4d4',width=512){const c=document.createElement('canvas');c.width=width;c.height=128;const x=c.getContext('2d');x.fillStyle=bg;x.fillRect(0,0,width,128);x.strokeStyle=fg;x.lineWidth=5;x.strokeRect(6,6,width-12,116);x.fillStyle=fg;x.font='italic 900 64px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,width/2,65,width-25);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
export function sign(parent,text,pos,width=6,height=1.3,rot=0,bg,fg){const m=new T.Mesh(new T.PlaneGeometry(width,height),new T.MeshStandardMaterial({map:labelTexture(text,bg,fg),roughness:.8,side:T.DoubleSide}));m.position.set(...pos);m.rotation.y=rot;parent.add(m);return m;}
export function makeRenderer(canvas){const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;const scene=new T.Scene();scene.background=new T.Color(0x91c9de);scene.fog=new T.FogExp2(0xa6c8cb,.00115);const camera=new T.PerspectiveCamera(72,innerWidth/innerHeight,.12,6500);scene.add(new T.HemisphereLight(0xcceeff,0x71806c,2.4));const sun=new T.DirectionalLight(0xffe5b5,3.1);sun.position.set(-150,260,130);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-85;sun.shadow.camera.right=85;sun.shadow.camera.top=85;sun.shadow.camera.bottom=-85;sun.shadow.camera.near=1;sun.shadow.camera.far=650;sun.shadow.bias=-.0006;sun.shadow.normalBias=.12;scene.add(sun,sun.target);const sky=new T.Mesh(new T.SphereGeometry(4900,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:'varying vec3 vPos;void main(){vPos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 vPos;void main(){float h=normalize(vPos).y;vec3 c=mix(vec3(.71,.83,.86),vec3(.14,.48,.76),smoothstep(-.07,.7,h));float band=sin(vPos.x*.001+vPos.z*.0014)*.02;gl_FragColor=vec4(pow(c+band,vec3(2.2)),1.);}' }));scene.add(sky);const ocean=new T.Mesh(new T.PlaneGeometry(14000,14000,1,1),new T.MeshStandardMaterial({color:0x388399,roughness:.35,metalness:.28}));ocean.rotation.x=-Math.PI/2;ocean.position.y=0;scene.add(ocean);
 const clouds=new T.Group();const random=rng(532);const cloudMat=new T.MeshBasicMaterial({color:0xe4f1ef,transparent:true,opacity:.8});for(let i=0;i<60;i++){const x=(random()-.5)*5000,z=(random()-.5)*5000,y=420+random()*190;for(let j=0;j<4;j++)mesh('sphere',cloudMat,clouds,[x+j*30,y+random()*9,z],[42+random()*33,10+random()*12,23+random()*25]);}scene.add(clouds);return {renderer,scene,camera,sun,sky,ocean,clouds,draw:createPost(renderer,scene,camera)};}
