import {T,M,makeRenderer} from './render.js';
import {makeWeapon} from './character.js';
import {LOCATIONS,SIZE,COAST,LAKE,ROADS,WEAPONS,RARITY} from './data.js';
import {clamp,inPolygon,noise} from './math.js';
export const $=id=>document.getElementById(id);
const escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const timeString=s=>`${Math.floor(Math.max(0,s)/60)}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
export class UI{
 constructor(game){this.g=game;this.overlay=null;this.notifyTimer=0;this.feed=[];this.icons={};this.invSelected=0;this.editTiles=new Set();this.lastHotbar='';this.mapTick=0;this.pointerLocked=false;this.bind();}
 bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{this.g.sound.play('click');const a=b.dataset.action;if(a==='settings'||a==='controls'||a==='mode'||a==='coverage')this.modal(a);else if(a==='close')this.close();else if(a==='fullscreen')document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>this.notify('Use your browser full screen command.'));else if(a==='map')this.openMap();});document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>b.dataset.panel==='lobby'?this.close():this.modal(b.dataset.panel));$('play').onclick=()=>this.g.startMatch();$('capture-mouse').onclick=()=>this.g.capture();$('modal-close').onclick=()=>this.close();$('play-again').onclick=()=>this.g.startMatch();$('return-lobby').onclick=()=>this.g.returnLobby();$('spectate').onclick=()=>this.g.spectate();$('spectator-return').onclick=()=>this.g.returnLobby();$('next-player').onclick=()=>this.g.nextSpectator();$('clear-marker').onclick=()=>{this.g.marker=null;this.drawMap();};$('travel-location').innerHTML=LOCATIONS.map((l,i)=>`<option value="${i}">${l.name}</option>`).join('');$('travel-button').onclick=()=>{this.g.travel(Number($('travel-location').value));this.close();};$('drop-item').onclick=()=>{this.g.dropSlot(this.invSelected);this.inventory();};
 $('map').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();this.g.marker={x:((e.clientX-r.left)/r.width-.5)*SIZE,z:((e.clientY-r.top)/r.height-.5)*SIZE};this.drawMap();this.g.sound.play('pickup');};document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{this.g.build.type=b.dataset.build;this.g.build.enabled=true;this.g.capture();});$('edit-reset').onclick=()=>{this.editTiles.clear();this.renderEdit();};$('edit-cancel').onclick=()=>{this.g.build.editing=null;this.close();};$('edit-confirm').onclick=()=>this.confirmEdit();}
 show(id,on=true){$(id).classList.toggle('hidden',!on);}
 close(capture=true){for(const id of ['map-overlay','inventory-overlay','modal','edit-overlay'])this.show(id,false);this.overlay=null;this.g.build.editing=null;this.g.paused=false;if(capture&&this.g.isControllable())this.g.capture();}
 openOverlay(id){this.close(false);this.overlay=id;this.show(id);document.exitPointerLock?.();this.g.input.clear();this.g.mouseDown=false;this.g.paused=this.g.state!=='lobby';this.show('capture-mouse',false);}
 openMap(){if(this.overlay==='map-overlay'){this.close();return;}this.openOverlay('map-overlay');this.show('travel-section',this.g.mode==='explore'&&this.g.state!=='lobby');this.drawMap();}
 inventory(){if(this.overlay!=='inventory-overlay')this.openOverlay('inventory-overlay');const g=this.g;$('inventory-slots').innerHTML=g.player.inventory.map((it,i)=>this.slot(it,i+1,i===this.invSelected,true)).join('');document.querySelectorAll('#inventory-slots .slot').forEach((el,i)=>{el.onclick=()=>{this.invSelected=i;this.inventory();};el.draggable=true;el.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const n=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(n)&&n>=0&&n<5){[g.player.inventory[i],g.player.inventory[n]]=[g.player.inventory[n],g.player.inventory[i]];g.equip(g.player.slot);this.inventory();}};});const it=g.player.inventory[this.invSelected],w=it&&WEAPONS[it.type];$('item-title').textContent=w?w.name.toUpperCase():'EMPTY SLOT';$('item-info').textContent=w?(w.damage?`Damage ${w.damage*(w.pellets||1)} · Magazine ${w.mag} · Reload ${w.reload}s · ${w.ammo} ammunition`:`Restores ${w.heal} ${w.health?'health':'shield'} · ${w.use} second use time`):'Pick up weapons and supplies. Drag items to rearrange.';$('inventory-resources').innerHTML=Object.entries(g.player.materials).map(([k,v])=>`<div><span>${k.toUpperCase()}</span><b>${v}</b></div>`).join('');$('inventory-ammo').innerHTML=Object.entries(g.player.ammo).map(([k,v])=>`<div><span>${k.toUpperCase()}</span><b>${v}</b></div>`).join('');}
 slot(it,key,selected,large=false){const w=it&&WEAPONS[it.type],color=w?RARITY[w.rarity]:'#718393';return `<button class="slot${selected?' selected':''}" aria-label="${key===0?'Pickaxe':`Slot ${key}: ${w?.name||'Empty'}`}" style="background:linear-gradient(145deg,${color}bb,${color}55)">${it&&this.icons[it.type]?`<img src="${this.icons[it.type]}" alt="${w.name}">`:it?`<span class="item-abbr">${w?.short||it.type}</span>`:''}<kbd>${key===0?'`':key}</kbd><small>${it&&key!==0?(it.count>1?it.count:w?.mag?it.rounds:''):''}</small></button>`;}
 hotbar(){const p=this.g.player;const key=JSON.stringify([p.inventory,p.slot,this.icons.ar!=null]);if(key===this.lastHotbar)return;this.lastHotbar=key;$('hotbar').innerHTML=this.slot({type:'pickaxe'},0,p.slot===0)+p.inventory.map((it,i)=>this.slot(it,i+1,p.slot===i+1)).join('');document.querySelectorAll('#hotbar .slot').forEach((b,i)=>b.onclick=()=>this.g.equip(i));const w=WEAPONS[this.g.weaponType()];$('weapon-name').textContent=w.short;}
 async makeIcons(){const r=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});r.setSize(128,128);r.setPixelRatio(1);r.outputColorSpace=T.SRGBColorSpace;r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.65;const s=new T.Scene(),cam=new T.PerspectiveCamera(32,1,.1,20);s.add(new T.HemisphereLight(0xffffff,0x666b7d,3));const light=new T.DirectionalLight(0xffedbc,5);light.position.set(-2,4,3);s.add(light);cam.position.set(1.3,1.2,2.4);cam.lookAt(0,0,0);for(const type of Object.keys(WEAPONS)){const model=makeWeapon(type);model.rotation.set(.1,-Math.PI/2,.4);if(type==='pickaxe'){model.scale.setScalar(.78);model.position.y=-.17;}else{model.scale.setScalar(1.3);model.position.x=-.06;}s.add(model);r.render(s,cam);this.icons[type]=r.domElement.toDataURL('image/png');s.remove(model);}r.dispose();}
 modal(type){this.openOverlay('modal');let h='';const g=this.g,s=g.settings;if(type==='settings'){h=`<h2>SETTINGS</h2><div class="settings-row"><label for="quality">Graphics quality</label><select id="quality"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div><div class="settings-row"><label for="sensitivity">Mouse sensitivity</label><input id="sensitivity" type="range" min="0.3" max="2.5" step="0.1" value="${s.sensitivity}"></div><div class="settings-row"><label for="volume">Sound volume</label><input id="volume" type="range" min="0" max="1" step="0.05" value="${s.volume}"></div><div class="settings-row"><label for="pace">Match length</label><select id="pace"><option value="standard">Standard · about 14 minutes</option><option value="quick">Quick · about 6 minutes</option></select></div><div class="settings-row"><label for="bots-setting">Local opponents</label><select id="bots-setting"><option value="99">99 bots</option><option value="49">49 bots</option><option value="19">19 bots</option></select></div><div class="settings-row"><label for="auto-material">Auto material change</label><input id="auto-material" type="checkbox" ${s.autoMaterial?'checked':''}></div><div class="settings-row"><label for="turbo">Turbo building</label><input id="turbo" type="checkbox" ${s.turbo?'checked':''}></div><div class="settings-row"><label for="fps-setting">Show FPS</label><input id="fps-setting" type="checkbox" ${s.fps?'checked':''}></div><div class="modal-actions"><button id="save-settings" class="yellow-button">APPLY</button><button id="settings-controls">CONTROLS</button></div>`;}
 else if(type==='controls'){const controls=[['Move','W A S D'],['Look','Mouse'],['Run','Shift'],['Jump / leave bus','Space'],['Crouch','Ctrl / C'],['Fire / harvest','Left mouse'],['Aim / build material','Right mouse'],['Interact / open chest','E'],['Reload / rotate piece','R'],['Pickaxe','` / 0'],['Equipment slots','1 – 5'],['Build mode','Q'],['Wall / floor / ramp / roof','F1 – F4'],['Edit structure','G'],['Repair structure','H'],['Island map','M'],['Inventory','Tab / I'],['Deploy glider','Space'],['Menu / release mouse','Esc'],['Camera without mouse lock','Arrow keys']];h=`<h2>CONTROLS</h2><p>Click the game to capture the mouse. Escape releases it. Mouse and keyboard are required.</p><div class="control-grid">${controls.map(([a,b])=>`<div><span>${a}</span><kbd>${b}</kbd></div>`).join('')}</div>`;}
 else if(type==='mode'){h=`<h2>SELECT MODE</h2><div class="mode-options"><button data-mode="solo" class="mode-option ${g.mode==='solo'?'active':''}"><b>SOLO</b><p>Drop from the Battle Bus. Loot, build, and fight local bots. Last survivor wins.</p></button><button data-mode="explore" class="mode-option ${g.mode==='explore'?'active':''}"><b>EXPLORE</b><p>Visit the island without opponents or storm. Start in Tilted with weapons and materials.</p></button></div><p>All opponents run locally in your browser. Online matchmaking is unavailable.</p>`;}
 else if(type==='coverage'){h=`<h2>FEATURE COVERAGE</h2><p>A playable local reconstruction using the original 2018 v3.1.0 reference. This build is not an exact reproduction of Epic's island or assets.</p><table class="coverage-table"><tr><td>Island</td><td>All 19 named locations, connecting terrain, roads, lake, river, and selected unnamed landmarks. Layouts and terrain are approximations.</td></tr><tr><td>Architecture</td><td>Enterable modular buildings, stairs, roof spaces, furniture, windows and doors. Floor plans and facade details differ.</td></tr><tr><td>Combat</td><td>Local bots, weapons, projectiles, ammunition, healing, shields, harvesting and loot.</td></tr><tr><td>Building</td><td>Four pieces, three materials, previews, edits, repairs and support checks. Edit and support rules are simplified.</td></tr><tr><td>Match</td><td>Lobby, waiting island, bus, drop, glide, storm, elimination, spectating, victory and replay.</td></tr><tr><td>Unavailable</td><td>Online services, Epic accounts, purchases, progression sync, complete historical loot pool and exact original animations.</td></tr></table><p><a href="FEATURE_COVERAGE.md" target="_blank">Read the full coverage report</a> · <a href="REFERENCES.md" target="_blank">Reference decisions</a></p>`;}
 else if(type==='profile'){const p=g.profile;h=`<h2>PROFILE</h2><p>Player · Device-local statistics</p><div class="profile-stats"><div>MATCHES<b>${p.matches}</b></div><div>VICTORIES<b>${p.wins}</b></div><div>ELIMINATIONS<b>${p.kills}</b></div></div><p>Progress is saved in this browser.</p>`;}
 else if(type==='locker'){h='<h2>LOCKER</h2><p>Choose one of three original characters.</p><div class="locker-grid"><button data-skin="0"><i>◆</i>RANGER</button><button data-skin="1"><i>◆</i>KESTREL</button><button data-skin="2"><i>◆</i>BREAKER</button></div><p>Ranger: field vest and swept hair. Kestrel: flight jacket and ponytail. Breaker: heavy workwear. Each has original geometry and custom movement and action animations.</p>';}
 else if(type==='challenges'){h=`<h2>CHALLENGES</h2><p>Complete these goals during local matches.</p><div class="settings-row">Play a match <b>${Math.min(g.profile.matches,1)} / 1</b></div><div class="settings-row">Search treasure chests <b>${Math.min(g.profile.chests,3)} / 3</b></div><div class="settings-row">Eliminate opponents <b>${Math.min(g.profile.kills,5)} / 5</b></div>`;}
 else if(type==='battlepass'){h='<h2>SEASON 3 BATTLE PASS</h2><p>The original season introduced a 100-tier Battle Pass. Epic account linking, paid rewards, and historical progression are unavailable in this local reconstruction.</p><p>Your matches, victories, and eliminations are recorded in Profile.</p><button id="view-profile">VIEW PROFILE</button>';}
 else if(type==='shop'){h='<h2>ITEM SHOP</h2><p>The Item Shop requires Epic online services and is unavailable in this local game. No purchases or account connections are offered.</p><button id="view-locker">OPEN LOCKER</button>';}
 else if(type==='pause'){h=`<h2>GAME MENU</h2><p>${g.mode==='solo'?'Solo match paused. All opponents are local bots.':'Explore mode paused.'}</p><div class="modal-actions"><button id="resume" class="yellow-button">RESUME</button><button id="pause-settings">SETTINGS</button><button id="pause-lobby">LEAVE MATCH</button></div>`;}
 $('modal-content').innerHTML=h;
 if(type==='settings'){$('quality').value=s.quality;$('pace').value=s.pace;$('bots-setting').value=s.bots;$('save-settings').onclick=()=>{Object.assign(s,{quality:$('quality').value,sensitivity:Number($('sensitivity').value),volume:Number($('volume').value),pace:$('pace').value,bots:Number($('bots-setting').value),autoMaterial:$('auto-material').checked,turbo:$('turbo').checked,fps:$('fps-setting').checked});g.saveSettings();this.close();};$('settings-controls').onclick=()=>this.modal('controls');}
 if(type==='mode')document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{g.mode=b.dataset.mode;$('mode-label').textContent=g.mode==='solo'?'SOLO':'EXPLORE';$('mode-description').textContent=g.mode==='solo'?`BATTLE ROYALE · ${g.settings.bots} LOCAL BOTS`:'THE ISLAND · NO STORM';this.close();});
 if(type==='locker')document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{g.setSkin(Number(b.dataset.skin));this.close();});
 if(type==='battlepass')$('view-profile').onclick=()=>this.modal('profile');if(type==='shop')$('view-locker').onclick=()=>this.modal('locker');if(type==='pause'){$('resume').onclick=()=>this.close();$('pause-settings').onclick=()=>this.modal('settings');$('pause-lobby').onclick=()=>g.returnLobby();}}
 notify(text,duration=2.5){$('notifications').textContent=text;this.notifyTimer=duration;}
 addFeed(text){this.feed.unshift({text,time:7});this.feed=this.feed.slice(0,5);}
 damageNumber(value,shield,x=50,y=45){const el=document.createElement('div');el.className='damage-num'+(shield?' shield':'');el.textContent=Math.round(value);el.style.left=`${x+Math.random()*2-1}%`;el.style.top=`${y}%`;$('damage-numbers').appendChild(el);setTimeout(()=>el.remove(),700);}
 edit(b){this.openOverlay('edit-overlay');this.g.build.editing=b;this.editTiles=new Set(b.removed);this.renderEdit();}
 renderEdit(){const type=this.g.build.editing?.type;if(!type)return;const n=type==='wall'?9:4;$('edit-grid').style.gridTemplateColumns=`repeat(${n===9?3:2},100px)`;$('edit-grid').innerHTML=Array.from({length:n},(_,i)=>`<button aria-label="Edit tile ${i+1}" data-tile="${i}" class="${this.editTiles.has(i)?'removed':''}"></button>`).join('');document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.tile);this.editTiles.has(i)?this.editTiles.delete(i):this.editTiles.add(i);this.renderEdit();});$('edit-error').textContent='';}
 confirmEdit(){if(this.g.build.applyEdit(this.editTiles))this.close();else $('edit-error').textContent='That edit pattern is not supported. Try a window, doorway, or half piece.';}
 prepareMap(){const n=384,c=document.createElement('canvas');c.width=c.height=n;const ctx=c.getContext('2d'),img=ctx.createImageData(n,n),world=this.g.world;for(let j=0;j<n;j++)for(let i=0;i<n;i++){const x=(i/n-.5)*SIZE,z=(j/n-.5)*SIZE,h=world.height(x,z),land=inPolygon(x,z,COAST),wet=world.wet(x,z);const p=(j*n+i)*4;let rgb;if(!land)rgb=[30,79,99];else if(wet)rgb=[47,94,103];else{const sh=clamp((world.height(x-5,z-5)-h)*1.6,-30,30),f=noise(x*.02,z*.02);rgb=[103+f*27+sh,135+f*26+sh,59+f*19+sh];if(h>75)rgb=[137+sh,145+sh,98+sh];if(Math.hypot(x-LOCATIONS[12].x,z-LOCATIONS[12].z)<130)rgb=[77+sh,99+sh,55+sh];}img.data.set([...rgb,255],p);}ctx.putImageData(img,0,0);const base=document.createElement('canvas');base.width=base.height=1000;const a=base.getContext('2d');a.drawImage(c,0,0,1000,1000);const px=x=>(x/SIZE+.5)*1000;for(const road of ROADS){a.strokeStyle='#bfc097';a.lineWidth=2.6;a.beginPath();road.forEach(([x,z],i)=>i?a.lineTo(px(x),px(z)):a.moveTo(px(x),px(z)));a.stroke();}for(const o of world.props){if(o.kind!=='tree'||!o.x)continue;a.fillStyle='#365f3e99';a.beginPath();a.arc(px(o.x),px(o.z),2.3,0,7);a.fill();}for(const b of world.buildings){a.fillStyle='#d1c7ad';a.fillRect(px(b.x-b.w/2),px(b.z-b.d/2),b.w/SIZE*1000,b.d/SIZE*1000);a.strokeStyle='#514f41';a.lineWidth=.6;a.strokeRect(px(b.x-b.w/2),px(b.z-b.d/2),b.w/SIZE*1000,b.d/SIZE*1000);}this.mapBase=base;}
 drawMap(){if(!this.mapBase)return;const c=$('map'),ctx=c.getContext('2d'),g=this.g;ctx.clearRect(0,0,1000,1000);ctx.drawImage(this.mapBase,0,0);ctx.strokeStyle='#deecff22';ctx.lineWidth=1;for(let i=1;i<10;i++){ctx.beginPath();ctx.moveTo(i*100,0);ctx.lineTo(i*100,1000);ctx.moveTo(0,i*100);ctx.lineTo(1000,i*100);ctx.stroke();}ctx.font='bold 13px Arial';ctx.fillStyle='#e1eaf1';for(let i=0;i<10;i++){ctx.fillText(String.fromCharCode(65+i),i*100+48,18);ctx.fillText(String(i+1),9,i*100+54);}if(g.mode==='solo'&&g.state!=='lobby'&&g.storm.active){const st=g.storm,x=(st.x/SIZE+.5)*1000,z=(st.z/SIZE+.5)*1000,r=st.radius/SIZE*1000;ctx.save();ctx.fillStyle='#8323bd75';ctx.beginPath();ctx.rect(0,0,1000,1000);ctx.arc(x,z,r,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc((st.nextX/SIZE+.5)*1000,(st.nextZ/SIZE+.5)*1000,st.nextRadius/SIZE*1000,0,7);ctx.stroke();ctx.restore();}if(['lobby','prematch','bus'].includes(g.state)){ctx.strokeStyle='#52e5ff';ctx.lineWidth=3;ctx.setLineDash([7,8]);ctx.beginPath();ctx.moveTo(110,680);ctx.lineTo(890,280);ctx.stroke();ctx.setLineDash([]);}ctx.textAlign='center';ctx.font='italic 900 15px Arial';ctx.lineWidth=3;ctx.strokeStyle='#17291e';ctx.fillStyle='#fffbe6';for(const l of LOCATIONS){const half=ctx.measureText(l.name.toUpperCase()).width/2+8,x=clamp(l.u*1000,half,1000-half),z=l.v*1000+14;ctx.strokeText(l.name.toUpperCase(),x,z);ctx.fillText(l.name.toUpperCase(),x,z);}const p=g.state==='bus'?g.bus.position:g.state==='spectating'&&g.spectatingBot?g.spectatingBot.pos:g.player.pos;this.mapArrow(ctx,(p.x/SIZE+.5)*1000,(p.z/SIZE+.5)*1000,g.yaw,10);if(g.marker){const x=(g.marker.x/SIZE+.5)*1000,z=(g.marker.z/SIZE+.5)*1000;ctx.fillStyle='#6ce7fa';ctx.font='25px Arial';ctx.fillText('◆',x,z);}$('map-status').textContent=g.state==='lobby'?'Choose a place to land.':`${g.aliveCount()} remaining · ${g.player.kills} eliminations`;$('map-meta').textContent=`CHAPTER 1 · SEASON 3 · ${g.mode==='solo'?'SOLO':'EXPLORE'}`;}
 mapArrow(ctx,x,z,yaw,size){ctx.save();ctx.translate(x,z);ctx.rotate(-yaw);ctx.fillStyle='#fff';ctx.strokeStyle='#193b4d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-size);ctx.lineTo(size*.65,size);ctx.lineTo(0,size*.5);ctx.lineTo(-size*.65,size);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
 mini(){if(!this.mapBase)return;const c=$('minimap'),a=c.getContext('2d'),g=this.g,p=g.state==='bus'?g.bus.position:g.state==='spectating'&&g.spectatingBot?g.spectatingBot.pos:g.player.pos;const x=(p.x/SIZE+.5)*1000,z=(p.z/SIZE+.5)*1000,size=g.state==='bus'?800:160;a.fillStyle='#254a5e';a.fillRect(0,0,230,230);a.drawImage(this.mapBase,x-size/2,z-size/2,size,size,0,0,230,230);if(g.mode==='solo'&&g.storm.active){const s=g.storm;a.strokeStyle='#f6f3ff';a.lineWidth=2;a.beginPath();a.arc(((s.nextX/SIZE+.5)*1000-x)/size*230+115,((s.nextZ/SIZE+.5)*1000-z)/size*230+115,s.nextRadius/SIZE*1000/size*230,0,7);a.stroke();}this.mapArrow(a,115,115,g.yaw,7);if(g.marker){const mx=((g.marker.x/SIZE+.5)*1000-x)/size*230+115,mz=((g.marker.z/SIZE+.5)*1000-z)/size*230+115;a.fillStyle='#73f0ff';a.beginPath();a.arc(clamp(mx,8,222),clamp(mz,8,222),5,0,7);a.fill();}}
 update(dt){const g=this.g,p=g.player;this.notifyTimer-=dt;if(this.notifyTimer<=0)$('notifications').textContent='';for(const f of this.feed)f.time-=dt;this.feed=this.feed.filter(f=>f.time>0);$('killfeed').innerHTML=this.feed.map(f=>`<div>${escapeText(f.text)}</div>`).join('');if(g.state==='lobby')return;this.hotbar();$('health-fill').style.width=p.health+'%';$('shield-fill').style.width=p.shield+'%';$('health-value').textContent=Math.ceil(p.health);$('shield-value').textContent=Math.ceil(p.shield);for(const k of ['wood','brick','metal'])$(k+'-count').textContent=Math.floor(p.materials[k]);$('alive').textContent=g.mode==='explore'?'1':g.aliveCount();$('kills').textContent=p.kills;const it=p.inventory[p.slot-1],w=WEAPONS[g.weaponType()];$('ammo-count').innerHTML=w.mag?`<b>${it?.rounds||0}</b><span> / ${p.ammo[w.ammo]}</span>`:'';$('storm-time').textContent=g.mode==='explore'?'∞':`◷ ${timeString(g.storm.timer)}`;$('location-mini').textContent=g.location?.name.toUpperCase()||'';
 let h='';const yaw=((g.yaw*180/Math.PI)%360+360)%360;for(let i=0;i<24;i++){const deg=i*15,d=((deg-yaw+540)%360)-180;if(Math.abs(d)<72){const names={0:'N',45:'NW',90:'W',135:'SW',180:'S',225:'SE',270:'E',315:'NE'};h+=`<span style="left:${50+d/144*100}%">${names[deg]||'·'}<small>${(360-deg)%360}</small></span>`;}}$('compass').innerHTML=h;this.show('build-help',g.build.enabled&&!this.overlay);if(g.build.enabled){$('build-help').querySelector('b').textContent=g.build.material.toUpperCase();$('build-help').querySelector('span').textContent=g.build.candidate?.valid?'10 MATERIALS':'CANNOT PLACE';}document.querySelectorAll('[data-build]').forEach(b=>b.classList.toggle('active',g.build.enabled&&b.dataset.build===g.build.type));$('action-progress').textContent=g.action?`${g.action.label} ${g.action.remaining.toFixed(1)}s`:'';$('storm-vignette').style.opacity=g.inStorm?'1':'0';$('fps').textContent=g.settings.fps?`${Math.round(g.fps)} FPS · ${g.render.renderer.info.render.calls} draws`:'';this.mapTick+=dt;if(this.mapTick>.14){this.mini();this.mapTick=0;if(this.overlay==='map-overlay')this.drawMap();}}
 profile(){const p=this.g.profile;$('level').textContent=1+Math.floor(p.xp/1000);$('xp-label').textContent=`${p.xp%1000} / 1,000`;$('xp').style.width=(p.xp%1000)/10+'%';$('challenge-match').textContent=`${Math.min(p.matches,1)} / 1`;$('challenge-chests').textContent=`${Math.min(p.chests,3)} / 3`;$('challenge-elims').textContent=`${Math.min(p.kills,5)} / 5`;}
 results(win){const g=this.g;this.close(false);document.exitPointerLock?.();this.show('results');$('victory-title').innerHTML=win?'<b>#1</b> VICTORY ROYALE':'';$('result-place').textContent=win?'VICTORY ROYALE':`YOU PLACED #${g.placement||g.aliveCount()+1}`;$('result-kills').textContent=g.player.kills;$('result-time').textContent=timeString(g.matchTime);$('result-chests').textContent=g.player.chests;this.show('spectate',!win&&g.bots.some(b=>b.alive));}
}
