import {T,M,geo,Batcher,material,mesh,sign,beam} from './render.js';
import {LOCATIONS,SIZE,COAST,LAKE,RIVER,SOUTH_RIVER,ROADS,HILLS,W} from './data.js';
import {rng,noise,fbm,clamp,lerp,smooth,inPolygon,pathDistance,SpatialHash} from './math.js';
import {makeWeapon} from './character.js';
import {installDetailGeometry,detailedCar,decorateHouse,streetFurniture} from './detail.js';
installDetailGeometry();
const ISOLATED_HOUSES=[[.384,.153],[.692,.177],[.623,.633],[.857,.587],[.611,.553],[.526,.528],[.873,.215],[.222,.145],[.291,.771],[.514,.727]];
export class World{
 constructor(scene){this.scene=scene;this.batch=new Batcher(scene);this.collision=new SpatialHash(20);this.random=rng(3102018);this.buildings=[];this.props=[];this.chests=[];this.loot=[];this.water=[];this.signs=[];this.sites=LOCATIONS;this.stats={};this.terrainCache=new Map();this.foundations=[];}
 height(x,z){let h=20+fbm(x*.004,z*.004)*20+noise(x*.015,z*.015)*3;const coastD=pathDistance(x,z,[...COAST,COAST[0]]),land=inPolygon(x,z,COAST);if(!land)return -8-Math.min(coastD*.05,40);h*=smooth(0,24,coastD);for(const hill of HILLS){const angle=Math.atan2(z-hill.z,x-hill.x),d=Math.hypot(x-hill.x,(z-hill.z)*1.12)/hill.r+Math.sin(angle*3+hill.x)*.055+(noise(x*.018,z*.018)-.5)*.075;h+=hill.h*(.43*(1-smooth(.25,1.06,d))+.57*(1-smooth(.58,.9,d)));}
 for(const l of LOCATIONS){if(l.type==='lake'||l.type==='swamp')continue;const d=Math.hypot(x-l.x,z-l.z);h=lerp(h,l.y,1-smooth(l.r*.7,l.r*1.25,d));}
 if(inPolygon(x,z,LAKE)){h=18.2;const center=W([.432,.36]);const d=Math.hypot(x-center[0],z-center[1]);h=lerp(h,27,1-smooth(18,31,d));for(const p of [[.405,.32],[.46,.389],[.413,.412]]){const q=W(p),d2=Math.hypot(x-q[0],z-q[1]);h=lerp(h,22,1-smooth(6,12,d2));}}
 const ld=pathDistance(x,z,[...LAKE,LAKE[0]]);if(ld<12&&!inPolygon(x,z,LAKE))h=lerp(h,19,smooth(12,1,ld));
 const rd=pathDistance(x,z,RIVER),sd=pathDistance(x,z,SOUTH_RIVER);if(rd<17)h=lerp(h,18.15,1-smooth(6,17,rd));if(sd<20){const rh=lerp(18,4,clamp((z-W([0,.43])[1])/(SIZE*.53),0,1));h=lerp(h,rh-.95,1-smooth(6,20,sd));}
 const sw=LOCATIONS.find(l=>l.type==='swamp');const ds=Math.hypot((x-sw.x)/1.12,z-sw.z);if(ds<170)h=lerp(h,8+noise(x*.027,z*.027)*4,1-smooth(105,175,ds));
 const mine=LOCATIONS.find(l=>l.type==='mine');if(Math.abs(x-mine.x)<37&&Math.abs(z-mine.z)<29)h=Math.min(h,26.5);if(Math.abs(x-mine.x-3)<4&&z>mine.z+27&&z<mine.z+47)h=Math.min(h,26.5+Math.max(0,z-mine.z-32)*.72);
 for(const pad of this.foundations){const edge=Math.max(Math.abs(x-pad.x)-pad.half,Math.abs(z-pad.z)-pad.half);h=lerp(h,pad.y,1-smooth(0,12,edge));}
 return h;}
 wet(x,z){if(inPolygon(x,z,LAKE)&&this.height(x,z)<19.1)return 19.15;if(pathDistance(x,z,RIVER)<8)return 19; if(pathDistance(x,z,SOUTH_RIVER)<8)return lerp(18,4,clamp((z-W([0,.43])[1])/(SIZE*.53),0,1));const s=LOCATIONS[12];if(Math.hypot(x-s.x,z-s.z)<125&&this.height(x,z)<10.1)return 10.2;return this.height(x,z)<0?.4:0;}
 terrain(){const n=440,g=new T.PlaneGeometry(SIZE*1.12,SIZE*1.12,n,n);g.rotateX(-Math.PI/2);const p=g.attributes.position,colors=[];const grass=new T.Color(),a=new T.Color(0x7d9f40),b=new T.Color(0x507943),rock=new T.Color(0xb8acaa),sand=new T.Color(0xbcb18a);for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),h=this.height(x,z);p.setY(i,h);const slope=Math.max(Math.abs(h-this.height(x+4,z)),Math.abs(h-this.height(x,z+4)))/4;grass.copy(a).lerp(b,fbm(x*.011,z*.011)*.9);if(x<-.2*SIZE)grass.lerp(b,.16);grass.lerp(rock,smooth(.22,.65,slope));if(h<6)grass.lerp(sand,.7);if(Math.hypot(x-LOCATIONS[12].x,z-LOCATIONS[12].z)<160)grass.setHex(0x697946);colors.push(grass.r,grass.g,grass.b);}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();const mat=material(0xffffff,'grass',.19);mat.vertexColors=true;const terrainCompile=mat.onBeforeCompile;mat.onBeforeCompile=s=>{terrainCompile(s);s.fragmentShader=s.fragmentShader.replace('#include <roughnessmap_fragment>',`diffuseColor.rgb*=mix(1.,.94+.075*sin(vWorldPoint.y*.63+sin(vWorldPoint.x*.14)),smoothstep(.15,.6,1.-abs(normalize(vWorldNormal).y)));
#include <roughnessmap_fragment>`);};this.land=new T.Mesh(g,mat);this.land.receiveShadow=true;this.scene.add(this.land);
 const shape=new T.Shape();LAKE.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));const water=new T.Mesh(new T.ShapeGeometry(shape),M.water);water.rotation.x=-Math.PI/2;water.position.y=19.1;this.scene.add(water);this.water.push(water);this.ribbon(RIVER,16,M.water,()=>19.05);this.ribbon(SOUTH_RIVER,17,M.water,(x,z)=>lerp(18,4,clamp((z-W([0,.43])[1])/(SIZE*.53),0,1)));
 const s=LOCATIONS[12];const swamp=new T.Mesh(new T.CircleGeometry(135,64),new T.MeshStandardMaterial({color:0x647951,roughness:.45,transparent:true,opacity:.82}));swamp.rotation.x=-Math.PI/2;swamp.position.set(s.x,10.25,s.z);this.scene.add(swamp);this.water.push(swamp);
 for(const road of ROADS)this.ribbon(road,5.5,M.dirt,(x,z)=>this.height(x,z)+.08);
 const mountains=new T.Group();for(let i=0;i<36;i++){const angle=i/36*Math.PI*2,rad=2400+this.random()*800;mesh('cone',material(0x548f9b),mountains,[Math.cos(angle)*rad,-25,Math.sin(angle)*rad],[180+this.random()*130,160+this.random()*180,170+this.random()*130]);}this.scene.add(mountains);}
 ribbon(points,width,mat,h){const curve=new T.CatmullRomCurve3(points.map(([x,z])=>new T.Vector3(x,0,z))),samples=curve.getPoints(points.length*14),pos=[],uv=[],indices=[];for(let i=0;i<samples.length;i++){const a=samples[i],b=samples[Math.min(i+1,samples.length-1)].clone().sub(samples[Math.max(i-1,0)]).normalize();for(const side of [-1,1]){const x=a.x+b.z*width*.5*side,z=a.z-b.x*width*.5*side;pos.push(x,h(x,z),z);uv.push(side*.5+.5,i*.2);}if(i){const j=i*2;indices.push(j-2,j,j-1,j-1,j,j+1);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();const m=new T.Mesh(g,mat);m.receiveShadow=true;this.scene.add(m);return m;}
 solid(mat,x,y,z,w,h,d,rot=0,kind='wall',hp=300,owner=null,detail=0){const o=owner||{kind,hp,maxHp:hp,resource:mat===M.wood||mat===M.bark?'wood':mat===M.metal||mat===M.steel?'metal':'brick',refs:[]};this.batch.box(mat,x,y,z,w,h,d,rot,o,detail);if(kind!=='decor'){const c=Math.abs(Math.cos(rot)),s=Math.abs(Math.sin(rot)),wx=w*c+d*s,dz=d*c+w*s;const b=this.collision.insert({min:{x:x-wx/2,y:y-h/2,z:z-dz/2},max:{x:x+wx/2,y:y+h/2,z:z+dz/2},owner:o,kind});(o.colliders??=[]).push(b);}return o;}
 tree(x,z,size=1,pine=false,pink=false){const y=this.height(x,z),o={kind:'tree',hp:180,maxHp:180,resource:'wood',refs:[],x,z};const a=this.batch;if(pine){a.add('cylinder',M.bark,[x,y+size*3,z],[size*.3,size*6,size*.3],0,o);for(let i=0;i<4;i++)a.add('cone',M.pine,[x,y+size*(3+i*1.65),z],[size*(2.9-i*.57),size*4.2,size*(2.9-i*.57)],(i*.85),o);}else{a.add('cylinder',M.bark,[x,y+size*2.7,z],[size*.43,size*5.4,size*.43],.15,o);for(let i=0;i<4;i++){const ang=i*2.1;a.add('cylinder',M.bark,[x+Math.cos(ang)*size*.72,y+size*4.4,z+Math.sin(ang)*size*.72],[size*.2,size*2.8,size*.2],[Math.sin(ang)*.7,0,-Math.cos(ang)*.7],o);}for(let i=0;i<8;i++){const angle=i*2.4;a.add('leaf',pink?M.pinkleaf:(i%3===0?M.leaflight:M.leaf),[x+Math.cos(angle)*size*1.65,y+size*(5.5+this.random()*1.1),z+Math.sin(angle)*size*1.65],[size*(1.6+this.random()*.5),size*(1.7+this.random()*.6),size*(1.7+this.random()*.6)],angle,o);}}
 this.collision.insert({min:{x:x-.44*size,y,z:z-.44*size},max:{x:x+.44*size,y:y+5*size,z:z+.44*size},owner:o,kind:'tree'});this.props.push(o);return o;}
 bush(x,z,size=1){const y=this.height(x,z);const o={kind:'bush',hp:50,maxHp:50,resource:'wood',refs:[]};for(let i=0;i<3;i++)this.batch.add('sphere',M.bush,[x+Math.cos(i*2.1)*size*.3,y+size*.58,z+Math.sin(i*2.1)*size*.3],[size*.8,size*.65,size*.85],0,o);this.collision.insert({min:{x:x-size,y,z:z-size},max:{x:x+size,y:y+size*1.3,z:z+size},owner:o,kind:'bush',sensor:true});this.props.push(o);}
 rock(x,z,size=1){const y=this.height(x,z);const o={kind:'rock',hp:220,maxHp:220,resource:'brick',refs:[]};this.batch.add('rock',M.rock,[x,y+size*.65,z],[size*1.5,size,size*1.2],[.2,this.random()*6,.1],o);this.collision.insert({min:{x:x-size,y,z:z-size},max:{x:x+size,y:y+size*1.5,z:z+size},owner:o,kind:'rock'});this.props.push(o);}
 chest(x,y,z,rot=0){const g=new T.Group();g.position.set(x,y,z);g.rotation.y=rot;mesh('box',M.wood,g,[0,.3,0],[.9,.52,.57]);const lid=mesh('cylinder',M.wood,g,[0,.55,0],[.29,.88,.29],[0,0,Math.PI/2]);for(let side of [-.31,.31]){mesh('box',M.gold,g,[side,.29,-.3],[.075,.53,.034]);mesh('box',M.gold,g,[side,.29,.3],[.075,.53,.034]);mesh('box',M.gold,g,[side,.76,0],[.085,.05,.5]);}mesh('box',M.gold,g,[0,.39,-.32],[.15,.2,.035]);const glow=new T.Mesh(new T.CircleGeometry(1.1,24),new T.MeshBasicMaterial({color:0xffbb41,transparent:true,opacity:.22,depthWrite:false}));glow.rotation.x=-Math.PI/2;glow.position.y=.02;g.add(glow);this.scene.add(g);const c={kind:'chest',x,y,z,mesh:g,lid,opened:false,hp:100,maxHp:100,resource:'wood'};c.collider=this.collision.insert({min:{x:x-.48,y,z:z-.32},max:{x:x+.48,y:y+.83,z:z+.32},kind:'chest',owner:c});this.chests.push(c);return c;}
 addLoot(type,x,y,z,count=1){const model=makeWeapon(type),g=new T.Group();g.position.set(x,y+.4,z);g.add(model);if(!['mini','shield','medkit','bandage','chug'].includes(type))model.rotation.z=Math.PI/2;const glow=new T.Mesh(new T.RingGeometry(.3,.52,24),new T.MeshBasicMaterial({color:['sniper','ar','shield'].includes(type)?0x459cf0:['scar','chug'].includes(type)?0xe9a547:0x5fce67,transparent:true,opacity:.65,side:T.DoubleSide}));glow.rotation.x=-Math.PI/2;glow.position.y=-.3;g.add(glow);this.scene.add(g);const l={type,x,y:y+.4,z,count,mesh:g,active:true,phase:this.random()*6};this.loot.push(l);return l;}
 car(x,z,rot=0,truck=false,color=0){detailedCar(this,x,z,rot,truck,color);}
 fence(x,z,length,rot=0,metal=false){const y=this.height(x,z);for(let i=0;i<=Math.floor(length/2.5);i++){const dx=i*2.5-length/2;this.batch.box(metal?M.steel:M.wood,x+Math.cos(rot)*dx,y+.75,z-Math.sin(rot)*dx,.12,1.5,.12,rot);}for(let dy of [.52,1.05])this.batch.box(metal?M.steel:M.white,x,y+dy,z,length,.1,.09,rot);}
 lamp(x,z){const y=this.height(x,z);this.batch.add('cylinder',M.steel,[x,y+2.3,z],[.09,4.6,.09]);this.batch.box(M.steel,x+.42,y+4.57,z,.95,.075,.085);this.batch.box(M.light,x+.8,y+4.47,z,.43,.12,.28);this.batch.add('cylinder',M.concrete,[x,y+.25,z],[.21,.5,.21]);}
 async create(progress=()=>{}){const [px,pz]=W([.767,.741]);this.foundations.push({x:px,z:pz,y:this.height(px,pz),half:29});for(const uv of ISOLATED_HOUSES){const [x,z]=W(uv);this.foundations.push({x,z,y:this.height(x,z),half:7.5});}progress(.05,'Sculpting the island');this.terrain();await new Promise(r=>setTimeout(r,0));progress(.2,'Building Tilted Towers');this.makeLocation(LOCATIONS[0]);await new Promise(r=>setTimeout(r,0));for(let i=1;i<LOCATIONS.length;i++){this.makeLocation(LOCATIONS[i]);progress(.22+i*.022,LOCATIONS[i].name);await new Promise(r=>setTimeout(r,0));}this.landmarks();progress(.73,'Planting forests and roadside detail');this.nature();await new Promise(r=>setTimeout(r,0));progress(.85,'Preparing collision and loot');this.batch.build();this.stats={locations:this.sites.length,buildings:this.buildings.length,colliders:this.collision.items.length,chests:this.chests.length,loot:this.loot.length,props:this.props.length,drawGroups:this.batch.meshes.length};progress(.99,'Ready to drop');}
 nature(){const rand=this.random;for(let i=0;i<18000;i++){const x=(rand()-.5)*SIZE,z=(rand()-.5)*SIZE,h=this.height(x,z);if(h<12||this.wet(x,z)||Math.abs(h-this.height(x+1,z))>.65||Math.abs(h-this.height(x,z+1))>.65)continue;if(LOCATIONS.some(l=>Math.hypot(x-l.x,z-l.z)<l.r*.69)||ROADS.some(p=>pathDistance(x,z,p)<6))continue;if(this.collision.query(x,z,1).some(c=>x>c.min.x-1&&x<c.max.x+1&&z>c.min.z-1&&z<c.max.z+1))continue;this.batch.add('tuft',M.blade,[x,h,z],[1.2,.8+rand()*.7,1.2],rand()*6,null,1);}for(let i=0;i<6100;i++){const x=(rand()-.5)*SIZE,z=(rand()-.5)*SIZE,h=this.height(x,z);if(h<8||this.wet(x,z)||!inPolygon(x,z,COAST))continue;const slope=Math.max(Math.abs(h-this.height(x+2,z)),Math.abs(h-this.height(x,z+2)))/2;if(slope>.8){if(i%9===0)this.rock(x,z,2.4);continue;}let near=false;for(const l of LOCATIONS){const d=Math.hypot(x-l.x,z-l.z);if(d<l.r*(l.type==='woods'?.26:l.type==='swamp'?.45:.81)){near=true;break;}}if(near)continue;if(ROADS.some(p=>pathDistance(x,z,p)<8))continue;if(this.collision.query(x,z,3).some(b=>x>b.min.x-3&&x<b.max.x+3&&z>b.min.z-3&&z<b.max.z+3))continue;const wailing=LOCATIONS[10],forest=Math.hypot(x-wailing.x,z-wailing.z)<180;const s=.8+rand()*.95;if(i%6===0)this.rock(x,z,s*1.8);else if(i%4===0)this.bush(x,z,s*1.25);else this.tree(x,z,s,forest||rand()<.31);}
 const forestCenter=LOCATIONS[10];for(let i=0;i<260;i++){const x=forestCenter.x+(rand()-.5)*340,z=forestCenter.z+(rand()-.5)*290,h=this.height(x,z);if(Math.hypot(x-forestCenter.x,z-forestCenter.z)<72||h<18||Math.abs(h-this.height(x+2,z))>1.6)continue;if(this.collision.query(x,z,2).some(c=>x>c.min.x-2&&x<c.max.x+2&&z>c.min.z-2&&z<c.max.z+2))continue;this.tree(x,z,1+rand()*.6,i%5!==0);}for(const l of LOCATIONS.filter(l=>!['woods','swamp','lake'].includes(l.type))){for(let i=0;i<12;i++){const a=i/12*Math.PI*2,r=l.r*(.78+this.random()*.15),x=l.x+Math.cos(a)*r,z=l.z+Math.sin(a)*r;if(!this.collision.query(x,z,4).some(b=>x>b.min.x-4&&x<b.max.x+4&&z>b.min.z-4&&z<b.max.z+4))this.tree(x,z,.9+this.random()*.3,i%3===0);}}
 }
 platform(x,z,w,d,y=this.height(x,z),mat=M.sidewalk){return this.solid(mat,x,y-.12,z,w,.25,d,0,'floor',999999);}
 street(x,z,w,d,y=this.height(x,z)){this.platform(x,z,w+4,d+4,y+.08);this.platform(x,z,w,d,y+.12,M.asphalt);const long=d>w;for(let t=-Math.max(w,d)/2+2;t<Math.max(w,d)/2;t+=7)this.batch.box(M.roadline,x+(long?0:t),y+.145,z+(long?t:0),long?.12:2.7,.02,long?2.7:.12);}
 makeLocation(l){const {x,z,y,type}=l;
 if(type==='city'){this.platform(x,z,171,168,y+.025,M.sidewalk);streetFurniture(this,x,z,y);this.street(x,z,13,145,y);this.street(x,z,155,11,y);this.street(x-45,z,9,125,y);this.street(x+43,z,9,125,y);this.street(x,z-48,130,8,y);this.street(x,z+46,120,9,y);
 const specs=[[-24,-27,3,3,5,M.stone,'flat'],[23,-29,4,3,4,M.brick,'flat'],[-72,-22,3,3,3,M.redbrick,'flat'],[70,-28,4,3,5,M.concrete,'flat'],[-23,24,3,3,3,M.brick,'flat'],[24,25,4,3,3,M.stone,'flat'],[70,24,3,3,4,M.redbrick,'flat'],[-70,24,3,3,2,M.yellow,'gable'],[-20,-70,4,2,4,M.concrete,'flat'],[34,-70,4,3,5,M.stone,'flat'],[21,69,3,2,3,M.brick,'flat'],[-27,67,3,2,2,M.green,'gable']];
 for(let i=0;i<specs.length;i++){const[a,b,w,d,f,m,r]=specs[i];this.house(x+a,z+b,{w:w*5.12,d:d*5.12,floors:f,mat:m,roof:r,commercial:true,sign:i===4?'NOMS':i===1?'PAWN':i===5?'APARTMENTS':null,y});}
 this.clockTower(x-70,z+67,y);for(let i=0;i<12;i++){this.lamp(x+(i%2?7.6:-7.6),z-62+i*11);if(i%2===0)this.car(x+(i%4?5:-5),z-49+i*9,0,false,i);}this.platform(x-68,z-62,26,20,y);this.fountain(x-68,z-62,y);this.signs.push(sign(this.scene,'TILTED TOWERS',[x,y+5,z+80],7,1.2));
 }else if(type==='park'){this.street(x,z,69,72,y);this.platform(x,z,49,57,y+.2,M.grass);this.pitch(x,z,y+.24,35,48);this.gazebo(x,z-34,y);const coords=[[-44,-43],[-14,-51],[20,-51],[47,-39],[-47,-10],[47,-6],[-46,25],[46,28],[-24,48],[13,50]];coords.forEach(([a,b],i)=>{this.house(x+a,z+b,{mat:[M.blue,M.white,M.yellow,M.brick,M.green][i%5],floors:i%3===0?1:2,rot:b<0?Math.PI:0,y});this.fence(x+a,z+b+11,18);});
 }else if(type==='depot'){for(let i=0;i<3;i++)this.warehouse(x,z+(i-1)*22,25,15,[M.red,M.metal,M.blue][i],y);this.platform(x,z,62,78,y-.04,M.dirt);this.car(x-21,z+15,Math.PI/2,true,2);for(let i=0;i<7;i++)this.crate(x+20,z-22+i*6,y);}
 else if(type==='lake'){const p=W([.432,.36]);this.house(p[0],p[1],{w:15.36,d:10.24,mat:M.white,floors:2,y:27});this.platform(p[0]+3,p[1]+20,3,18,19.6,M.wood);this.warehouse(x-94,z+35,26,15,M.brick,23);this.house(x-86,z-62,{floors:1,mat:M.yellow,y:24});for(const[a,b]of [[-62,68],[56,15],[11,-63]]){this.platform(x+a,z+b,3,14,19.6,M.wood);this.chest(x+a,19.8,z+b);}for(let i=0;i<3;i++)this.tree(p[0]-15+i*15,p[1]-12,1.1);}
 else if(type==='farm'){this.street(x,z,6,125,y);this.house(x-31,z-29,{mat:M.white,floors:2,w:15.36,y});this.barn(x+21,z-3,y);this.warehouse(x-33,z+31,15,13,M.wood,y);this.silo(x+39,z+17,y);this.silo(x+47,z+17,y);this.windmill(x+32,z-39,y);for(let fx of [-1,1]){const cx=x+fx*54,cz=z+32;this.platform(cx,cz,28,40,y+.1,M.dirt);for(let row=0;row<7;row++){this.batch.box(M.wood,cx-12+row*4,y+.16,cz,.4,.1,38);for(let col=0;col<15;col++){this.batch.add('cone',M.leaflight,[cx-12+row*4,y+.68,cz-18+col*2.5],[.38,1.1,.38]);}}this.fence(cx,cz+22,30);this.fence(cx,cz-22,30);}for(let i=0;i<8;i++){this.batch.add('cylinder',M.yellow,[x-53+i*3,y+.7,z-5],[.7,1.3,.7],[Math.PI/2,0,0]);}this.car(x+25,z+30,1.5,true,3);}
 else if(type==='retail'||type==='greasy'||type==='salty'){this.street(x,z,115,9,y);this.street(x-28,z,8,91,y);const coords=type==='salty'?[[-32,-22],[1,-22],[32,-20],[-37,22],[3,23]]:[[-43,-27],[-14,-26],[-46,24],[-13,24],[-45,55]];coords.forEach(([a,b],i)=>this.house(x+a,z+b,{mat:[M.blue,M.white,M.brick,M.yellow,M.green][i%5],floors:2,w:i%2?10.24:15.36,y}));if(type!=='salty'){this.house(x+31,z-27,{w:30.72,d:15.36,floors:1,roof:'flat',mat:M.brick,commercial:true,sign:type==='greasy'?'DURRR BURGER':'NOMS',y});this.house(x+31,z+24,{w:25.6,d:15.36,floors:type==='retail'?2:1,roof:'flat',mat:M.stone,commercial:true,sign:type==='retail'?'BIG SHOTS':'OUTDOOR',y});this.platform(x+31,z,42,21,y+.1,M.asphalt);if(type==='greasy')this.burger(x+31,z-27,y+8);}else this.gasStation(x+37,z+28,y);for(let i=0;i<6;i++)this.car(x-44+i*18,z+5,Math.PI/2,false,i);}
 else if(type==='tomato'){this.street(x,z+9,85,12,y);this.house(x-10,z-15,{w:20.48,d:15.36,floors:2,roof:'hip',mat:M.stone,commercial:true,sign:'PIZZA PIT',y});this.tomato(x-10,z-15,y+12);this.gasStation(x+28,z+31,y);this.house(x-37,z+32,{floors:1,mat:M.white,y});this.house(x+32,z-17,{floors:1,mat:M.wood,roof:'flat',w:15.36,y});for(let i=0;i<4;i++)this.car(x-29+i*13,z+8,Math.PI/2,false,i);this.tunnel(x,z+79);}
 else if(type==='woods'){for(let i=0;i<6;i++){const s=10+i*9,gap=3.2;for(const side of [-1,1]){if(i%2){for(const a of [-1,1])this.hedge(x+side*s,z+a*(s+gap)*.5,s-gap,0);this.hedge(x,z+side*s,s*2,Math.PI/2);}else{this.hedge(x+side*s,z,s*2,0);for(const a of [-1,1])this.hedge(x+a*(s+gap)*.5,z+side*s,s-gap,Math.PI/2);}}}this.house(x,z,{floors:1,w:10.24,d:10.24,mat:M.wood,y});this.chest(x+18,y+.3,z+19);this.chest(x-34,y+.3,z-30);}
 else if(type==='lodge'){this.house(x-10,z,{w:25.6,d:15.36,floors:2,mat:M.wood,y});this.lookout(x+30,z+28,y);for(let i=0;i<3;i++)this.house(x-29+i*26,z-40,{w:10.24,d:10.24,floors:1,mat:M.wood,y});this.campsite(x+25,z-29);}
 else if(type==='factory'){this.warehouse(x-15,z,30,24,M.metal,y);this.house(x+17,z+3,{w:15.36,d:20.48,floors:3,roof:'flat',mat:M.brick,commercial:true,sign:'FLUSH',y});this.silo(x-28,z-25,y,2);this.silo(x-10,z-27,y,1.7);for(let i=0;i<14;i++){this.batch.box(M.trim,x-36+(i%7)*6,y+.5,z+24+Math.floor(i/7)*5,.8,1,.7);this.batch.add('cylinder',M.trim,[x-36+(i%7)*6,y+.8,z+23.6+Math.floor(i/7)*5],[.4,.16,.4]);}this.fence(x,z+39,80,0,true);this.car(x+35,z-19,0,true,4);}
 else if(type==='mine'){this.mine(x,z,y);this.house(x-40,z-39,{mat:M.blue,floors:2,y:35});this.house(x-15,z-45,{mat:M.white,floors:1,y:35});}
 else if(type==='snobby'){this.street(x+4,z,6,140,y);for(let i=0;i<5;i++){const pz=z+(i-2)*29;this.house(x-16,pz,{w:i===4?20.48:15.36,d:15.36,floors:2,roof:i%2?'flat':'gable',mat:[M.white,M.brick,M.blue,M.stone,M.concrete][i],rot:Math.PI/2,y,modern:i%2===1});this.fence(x-23,pz+13,35);this.platform(x-39,pz,9,12,y+.13,M.concrete);this.batch.box(M.water,x-39,y+.17,pz,7,.08,10);this.car(x+10,pz,0,false,i);}}
 else if(type==='graveyard'){this.church(x,z,y);for(let i=0;i<28;i++){const px=x-24+(i%7)*7,pz=z+13+Math.floor(i/7)*7;this.batch.box(M.stone,px,y+.52,pz,1,.95,.22);this.batch.add('cylinder',M.stone,[px,y+1.02,pz],[.5,.2,.5],[Math.PI/2,0,0]);this.platform(px,pz+1,1.2,2.5,y+.05,M.dirt);}for(let i=0;i<3;i++)this.house(x+(i-1)*25,z-24,{w:5.12,d:5.12,floors:1,mat:M.stone,roof:'gable',y});this.fence(x,z+43,80,0,true);}
 else if(type==='junk'){this.warehouse(x-12,z-22,26,16,M.rust,y);this.house(x+23,z-22,{w:10.24,d:10.24,floors:2,mat:M.brick,roof:'flat',y});for(let row=0;row<6;row++)for(let i=0;i<6;i++){const px=x-29+i*11,pz=z+row*7;this.car(px,pz,Math.PI/2,false,i+row);if((i+row)%2)this.batch.box([M.red,M.blue,M.metal][i%3],px,y+2.4,pz,3.9,1.2,1.75);}this.fence(x,z+42,80,0,true);this.fence(x-43,z,80,Math.PI/2,true);}
 else if(type==='lucky'){this.street(x,z,8,93,y);this.street(x,z,85,8,y);const buildings=[[-22,-26,3], [22,-27,2],[-23,20,3],[22,23,2],[-1,-51,3],[-45,-3,2],[44,-2,2]];for(const[a,b,f]of buildings)this.house(x+a,z+b,{w:15.36,d:15.36,floors:f,mat:M.concrete,roof:'pagoda',asian:true,y});this.tree(x,z,2,false,true);this.platform(x,z,12,12,y+.1,M.stone);for(let i=0;i<8;i++){const a=i*Math.PI/4;const lx=x+Math.cos(a)*12,lz=z+Math.sin(a)*12;this.batch.add('sphere',M.red,[lx,y+3,lz],[.4,.58,.4]);this.batch.add('cylinder',M.gold,[lx,y+2.4,lz],[.06,.5,.06]);this.batch.add('cylinder',M.dark,[lx+.7,y+1.95,lz],[.055,3.9,.055]);this.batch.box(M.dark,lx+.35,y+3.9,lz,.8,.07,.07);this.batch.box(M.dark,lx,y+3.69,lz,.025,.36,.025);}this.car(x-5,z+31,0,false,3);}
 else if(type==='swamp'){for(let i=0;i<24;i++){const a=i*2.4,r=20+(i%5)*21;const px=x+Math.cos(a)*r,pz=z+Math.sin(a)*r;this.tree(px,pz,1.8+(i%3)*.4);if(i%7===0)this.chest(px+3,this.height(px+3,pz)+.1,pz);}this.house(x-29,z+42,{w:10.24,d:10.24,floors:1,mat:M.wood,y:13});this.platform(x-25,z+20,3,38,12.9,M.wood);}
 }
 house(x,z,opt={}){const w=opt.w||10.24,d=opt.d||10.24,F=opt.floors||2,y=opt.y??this.height(x,z),rot=opt.rot||0,mat=opt.mat||M.blue;const building={x,z,w,d,y,rot,parts:[],stairs:[],floors:F,type:opt.asian?'pagoda':opt.commercial?'commercial':'house'};this.buildings.push(building);const point=(a,c)=>[x+a*Math.cos(rot)+c*Math.sin(rot),z-a*Math.sin(rot)+c*Math.cos(rot)];const box=(m,a,b,c,ww,hh,dd,kind='wall',hp=300,owner=null,detail=0)=>{const [px,pz]=point(a,c);const o=this.solid(m,px,y+b,pz,ww,hh,dd,rot,kind,hp,owner,detail);if(kind!=='decor'&&!owner){o.building=building;building.parts.push(o);}return o;};
 const groundSlab=(mat,level,thickness)=>{const e=opt.entryStair;if(!e){box(mat,0,level,0,w,thickness,d,'floor');return;}const left=e.x-e.width/2,right=e.x+e.width/2;box(mat,(-w/2+left)/2,level,0,left+w/2,thickness,d,'floor');if(right<w/2)box(mat,(right+w/2)/2,level,0,w/2-right,thickness,d,'floor');const back=e.start+d/2,front=d/2-(e.start+e.run);if(back>0)box(mat,e.x,level,-d/2+back/2,e.width,thickness,back,'floor');if(front>0)box(mat,e.x,level,d/2-front/2,e.width,thickness,front,'floor');};
 groundSlab(M.concrete,-.2,.4);groundSlab(opt.commercial?M.tile:M.floor,.13,.18);
 const panel=(px,pz,len,vertical,f,door=false)=>{const owner={kind:door?'doorframe':'wall',hp:mat===M.wood||[M.blue,M.white,M.yellow,M.green].includes(mat)?200:350,maxHp:350,resource:[M.blue,M.white,M.yellow,M.green,M.wood].includes(mat)?'wood':'brick',refs:[],building};building.parts.push(owner);const h=3.84,b=f*h;
 const cb=(m,a,dy,c,ww,hh,dd,kind='wall')=>box(m,px+(vertical?c:a),b+dy,pz+(vertical?a:c),vertical?dd:ww,hh,vertical?ww:dd,kind,350,owner);
 const wide=door?1.55:opt.commercial&&f===0?len-1:1.65,sill=door?0:opt.commercial&&f===0?.2:1.06,top=door?2.7:opt.commercial&&f===0?3.22:2.68;
 cb(mat,-(len+wide)/4,h/2,0,(len-wide)/2,h,.25);cb(mat,(len+wide)/4,h/2,0,(len-wide)/2,h,.25);if(sill)cb(mat,0,sill/2,0,wide,sill,.25);cb(mat,0,(top+h)/2,0,wide,h-top,.25);
 if(!door){cb(M.trim,0,sill-.06,0,wide+.25,.14,.4,'decor');cb(M.trim,0,top+.03,0,wide+.24,.13,.38,'decor');for(const a of [-1,1])cb(opt.asian?M.red:M.trim,a*(wide/2+.035),(sill+top)/2,0,.1,top-sill,.34,'decor');cb(M.darktrim,0,(sill+top)/2,.025,.055,top-sill,.08,'decor');cb(M.darktrim,0,(sill+top)/2,.025,wide,.045,.08,'decor');if(f>0||!opt.commercial){cb(M.glass,0,(sill+top)/2,.055,wide,.015,.02,'decor');}}
 else{const[pdx,pdz]=point(px,pz);const doorRot=rot+(vertical?Math.PI/2:0);const o=this.solid(M.wood,pdx,y+1.32,pdz,1.43,2.64,.12,doorRot,'door',120);o.x=pdx;o.y=y;o.z=pdz;o.rot=doorRot;o.open=false;building.parts.push(o);}
 };
 const stairGap=Math.min(2.7,w*.52),stairX=w/2-stairGap/2,stairStart=-d/2+1.10,stairRun=Math.min(5.28,d-2.20),tread=stairRun/12;
 const slab=(level,mat=M.floor)=>{box(mat,-stairGap/2,level,0,w-stairGap,.18,d,'floor');const back=stairStart-.05+d/2,front=d/2-(stairStart+stairRun+.06);if(back>0)box(mat,stairX,level,-d/2+back/2,stairGap,.18,back,'floor');if(front>0)box(mat,stairX,level,d/2-front/2,stairGap,.18,front,'floor');};
 for(let f=0;f<F;f++){for(let side of [-1,1]){const nx=Math.round(w/5.12),nz=Math.round(d/5.12);for(let i=0;i<nx;i++)panel(-w/2+(i+.5)*w/nx,side*d/2,w/nx,false,f,f===0&&side===1&&i===Math.floor(nx/2));for(let j=0;j<nz;j++)panel(side*w/2,-d/2+(j+.5)*d/nz,d/nz,true,f,false);}
 if(f>0)slab(f*3.84);
 if(f<F-1||(opt.roof==='flat')){
  for(let i=0;i<12;i++)box(M.wood,stairX,f*3.84+(i+1)*.32-.085,stairStart+(i+.5)*tread,stairGap-.30,.17,tread+.018,'stairs');
  for(let i=0;i<4;i++){const yy=f*3.84+(i*3+1)*.32;box(M.darktrim,stairX-(stairGap-.30)/2,yy+.49,stairStart+(i*3+.5)*tread,.07,.95,.07,'decor');}
  building.stairs.push({floor:f,x:stairX,start:stairStart,run:stairRun,tread,bottom:y+f*3.84,top:y+(f+1)*3.84,width:stairGap-.30});
 }

 for(let side of [-1,1]){box(M.trim,0,f*3.84+.1,side*(d/2+.04),w+.4,.18,.28,'decor');box(M.trim,side*(w/2+.04),f*3.84+.1,0,.28,.18,d+.4,'decor');}
 this.furniture(x,z,y+f*3.84,w,d,rot,opt.commercial,f,box);
 }
 const top=F*3.84;const roof=opt.roof||'gable';if(roof==='flat'){slab(top,M.steel);for(let side of [-1,1]){box(mat,0,top+.55,side*d/2,w+.6,1.1,.3);box(mat,side*w/2,top+.55,0,.3,1.1,d);box(M.trim,0,top+1.15,side*d/2,w+.85,.17,.65,'decor');box(M.trim,side*w/2,top+1.15,0,.65,.17,d+.85,'decor');}box(M.metal,-w*.2,top+.6,-d*.23,2,1.2,1.5,'prop',150);for(let i=0;i<5;i++)box(M.dark,-w*.2+i*.32-.65,top+.7,-d*.23-.77,.15,.65,.04,'decor');}
 else if(roof==='pagoda'){for(let f=1;f<=F;f++){const [px,pz]=point(0,0);this.pagodaRoof(px,y+f*3.84,pz,w+2.6,d+2.6,rot,f===F,building);for(let side of [-1,1]){box(M.red,side*(w/2+.07),f*3.84-.15,0,.22,.2,d+.3,'decor');box(M.red,0,f*3.84-.05,side*(d/2+.05),w+.5,.24,.32,'decor');}}box(M.floor,0,top,0,w,.2,d,'floor');}
 else{const rise=roof==='hip'?2.2:2.7;this.gable(x,y+top,z,w+.95,d+.85,rise,rot,roof==='hip'?M.redroof:M.roof,building);box(M.floor,0,top,0,w-2.6,.16,d,'floor');box(M.brick,-w*.25,top+2,-d*.24,.9,3,.95);box(M.concrete,-w*.25,top+3.55,-d*.24,1.1,.2,1.15,'decor');}
 if(opt.asian)for(const side of [-1,1])for(const edge of [-1,1])box(M.red,side*(w/2+.08),top*.5,edge*(d/2+.08),.26,top,.26,'decor');
 const[cx,cz]=point(-w*.25,-d*.25);this.chest(cx,y+(F>1?3.84:0)+.2,cz,rot);const[fx,fz]=point(0,d*.17);this.addLoot(['ar','pump','mini','smg','shield','hunting','burst','pistol','bandage','medkit'][Math.floor(this.random()*10)],fx,y+.25,fz);if(F>2){const[p,q]=point(w<8?-w*.25:w*.1,-d*.3);this.chest(p,y+(F-1)*3.84+.2,q,rot);}
 if(opt.sign){const[px,pz]=point(0,d/2+.2);const s=sign(this.scene,opt.sign,[px,y+3.3,pz],Math.min(w-1,10),1.05,rot,opt.sign==='NOMS'?'#c67f32':'#416259');this.signs.push(s);}
 decorateHouse(this,building,opt,box,point);return building;}
 furniture(x,z,y,w,d,rot,commercial,f,box){const oy=f*3.84;if(commercial&&f===0){for(let i=0;i<Math.min(4,w/5);i++){const sx=-w/2+2+i*3;box(M.steel,sx,oy+.9,-d/2+2,1.9,1.8,.45,'decor',150,null,1);for(let j=0;j<3;j++){box(M.wood,sx,oy+.35+j*.55,-d/2+2,2,.08,.7,'decor',150,null,1);for(let k=0;k<5;k++)box([M.red,M.blue,M.yellow,M.white][k%4],sx-.8+k*.35,oy+.53+j*.55,-d/2+2,.22,.3,.25,'decor',150,null,1);}}box(M.wood,-w/2+2,oy+.55,d/2-2,2.9,1.1,.75,'decor',150,null,1);box(M.dark,-w/2+2,oy+1.2,d/2-2,.5,.23,.4,'decor',150,null,1);}
 else{box(M.floor,-w*.2,oy+.61,-d*.1,1.65,.13,.95,'decor',150,null,1);for(const a of [-1,1])for(const c of [-1,1])box(M.wood,-w*.2+a*.62,oy+.3,-d*.1+c*.34,.08,.6,.08,'decor',150,null,1);box(f?M.blue:M.red,-w*.21,oy+.48,-d/2+1.2,2.25,.43,.95,'decor',150,null,1);box(f?M.trim:M.red,-w*.21,oy+.84,-d/2+.8,2.25,.74,.24,'decor',150,null,1);box(M.wood,-w/2+.55,oy+.95,0,.65,1.9,1.2,'decor',150,null,1);for(let j=0;j<5;j++)box([M.red,M.blue,M.gold][j%3],-w/2+.93,oy+1.22,j*.19-.4,.1,.37,.12,'decor',150,null,1);box(M.concrete,-w/2+1.05,oy+.49,d/2-1.5,1.5,.98,.7,'decor',150,null,1);box(M.metal,-w/2+1.05,oy+1.01,d/2-1.5,1.5,.07,.72,'decor',150,null,1);}}
 gable(x,y,z,w,d,rise,rot,mat,building){const p=[-w/2,0,-d/2,w/2,0,-d/2,0,rise,-d/2,-w/2,0,d/2,w/2,0,d/2,0,rise,d/2],idx=[0,2,1,3,4,5,0,3,5,0,5,2,2,5,4,2,4,1];const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute([0,0,1,0,.5,1,0,0,1,0,.5,1],2));g.setIndex(idx);g.computeVertexNormals();const m=new T.Mesh(g,mat);m.position.set(x,y,z);m.rotation.y=rot;m.castShadow=m.receiveShadow=true;this.scene.add(m);const o={kind:'roof',hp:300,maxHp:300,resource:'wood',mesh:m,building};if(building)building.parts.push(o);this.collision.insert({min:{x:x-w/2,y:y-.1,z:z-d/2},max:{x:x+w/2,y:y+rise,z:z+d/2},kind:'slopeRoof',owner:o,slope:{x,z,w,d,y,rise,rot}});return m;}
 pagodaRoof(x,y,z,w,d,rot,full=false,building=null){const n=12,p=[],uv=[],idx=[];for(let j=0;j<=n;j++)for(let i=0;i<=n;i++){const u=i/n*2-1,v=j/n*2-1,h=2.1*(1-Math.max(Math.abs(u),Math.abs(v)))+.38*Math.pow(Math.min(Math.abs(u),Math.abs(v)),6);p.push(u*w/2,h,v*d/2);uv.push(i/n,j/n);}for(let j=0;j<n;j++)for(let i=0;i<n;i++){const u=((i+.5)/n*2-1),v=((j+.5)/n*2-1);if(!full&&Math.abs(u)<(w-2.6)/w&&Math.abs(v)<(d-2.6)/d)continue;const k=j*(n+1)+i;idx.push(k,k+n+1,k+1,k+1,k+n+1,k+n+2);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();const m=new T.Mesh(g,M.redroof);m.position.set(x,y,z);m.rotation.y=rot;m.castShadow=m.receiveShadow=true;this.scene.add(m);const o={kind:'roof',hp:250,maxHp:250,resource:'wood',mesh:m,building,refs:[],colliders:[]};if(building)building.parts.push(o);if(full){const c=this.collision.insert({min:{x:x-w/2,y:y-.08,z:z-d/2},max:{x:x+w/2,y:y+2.1,z:z+d/2},kind:'slopeRoof',owner:o,slope:{x,z,w,d,y,rise:2.1,rot,hip:true}});o.colliders.push(c);}for(const side of [-1,1]){this.batch.box(M.red,x+side*w/2*Math.cos(rot),y+.05,z-side*w/2*Math.sin(rot),.16,.18,d,rot,o);this.batch.box(M.red,x+side*d/2*Math.sin(rot),y+.05,z+side*d/2*Math.cos(rot),w,.18,.16,rot,o);}}

 warehouse(x,z,w,d,mat,y=this.height(x,z)){this.platform(x,z,w+5,d+5,y);const building={x,z,w,d,y,type:'warehouse',parts:[]};this.buildings.push(building);for(let side of [-1,1]){const o=this.solid(mat,x+side*w/2,y+3,z,.24,6,d,0,'wall',500);o.building=building;building.parts.push(o);this.solid(mat,x,y+3,z+side*d/2,w-7,6,.24,0,'wall',500);this.solid(mat,x+(w-7)/2+1.8,y+5.2,z+side*d/2,3.6,1.6,.24);for(let i=0;i<4;i++)this.batch.box(M.steel,x+side*(w/2-.2),y+3,z-d/2+1+i*d/4,.22,6,.22);}
 this.gable(x,y+6,z,w+1,d+1,2,0,M.roof,building);for(let i=0;i<5;i++)this.crate(x-w/2+2+i*3,z-d/2+3,y);this.chest(x-w/2+2,y+.05,z+d/2-2);this.addLoot('ar',x+2,y+.1,z);}
 barn(x,z,y){this.warehouse(x,z,20,26,M.red,y);for(const a of [-1,1]){this.batch.box(M.trim,x+a*9.9,y+3,z,.15,6,26);this.batch.box(M.trim,x,y+5.8,z+a*13.15,20,.2,.15);this.batch.box(M.trim,x,y+2.8,z+a*13.17,7,.15,.15,[0,0,.78]);}this.batch.box(M.wood,x-5,y+3.3,z-7,8,.2,10);this.chest(x-5,y+3.5,z-8);}
 silo(x,z,y,s=1){const o={kind:'silo',hp:400,maxHp:400,resource:'metal',refs:[]};this.batch.add('cylinder',M.metal,[x,y+4*s,z],[2*s,8*s,2*s],0,o);this.batch.add('cone',M.metal,[x,y+8.7*s,z],[2.1*s,1.6*s,2.1*s],0,o);this.collision.insert({min:{x:x-2*s,y,z:z-2*s},max:{x:x+2*s,y:y+9*s,z:z+2*s},owner:o,kind:'silo'});}
 windmill(x,z,y){for(let side of [-1,1])this.batch.box(M.metal,x+side,y+5,z,.18,10,.18,[0,0,side*.12]);for(let i=0;i<8;i++)this.batch.box(M.wood,x,y+i+1,z,2,.08,.08);for(let i=0;i<8;i++){const a=i*Math.PI/4;this.batch.box(M.metal,x+Math.sin(a)*1.6,y+10+Math.cos(a)*1.6,z,.7,2,.08,[0,0,-a]);}}
 crate(x,z,y=this.height(x,z)){const o=this.solid(M.wood,x,y+.65,z,1.3,1.3,1.3,0,'crate',100);for(let a of [-.48,.48])this.batch.box(M.darktrim,x+a,y+.65,z-.67,.08,1.35,.04,0,o);}
 clockTower(x,z,y){const building={x,z,y,w:6,d:6,parts:[],type:'clocktower'};this.buildings.push(building);for(let side of [-1,1]){this.solid(M.stone,x+side*2.8,y+10,z,.5,20,6);this.solid(M.stone,x,y+10,z+side*2.8,5.5,20,.5);}this.batch.box(M.trim,x,y+18.4,z,6.6,.7,6.6);this.batch.box(M.trim,x,y+21.1,z,6.6,.5,6.6);for(let i=0;i<4;i++)for(let j=0;j<2;j++)this.batch.box(M.stone,x+(j?2.8:-2.8),y+22.2,z-2.8+i*1.85,.55,1.8,.55);for(let side of [-1,1]){const cv=document.createElement('canvas');cv.width=cv.height=256;const c=cv.getContext('2d');c.fillStyle='#dccdaa';c.beginPath();c.arc(128,128,119,0,7);c.fill();c.strokeStyle='#433e35';c.lineWidth=10;c.stroke();for(let i=0;i<12;i++){c.save();c.translate(128,128);c.rotate(i*Math.PI/6);c.fillStyle='#534434';c.fillRect(-3,-104,6,17);c.restore();}c.lineWidth=9;c.beginPath();c.moveTo(128,128);c.lineTo(128,54);c.moveTo(128,128);c.lineTo(180,151);c.stroke();const tx=new T.CanvasTexture(cv);tx.colorSpace=T.SRGBColorSpace;const clock=new T.Mesh(new T.CircleGeometry(2.05,40),new T.MeshStandardMaterial({map:tx}));clock.position.set(x,y+16,z+side*3.03);clock.rotation.y=side===1?0:Math.PI;this.scene.add(clock);}this.chest(x,y+21.4,z);}
 fountain(x,z,y){this.batch.add('cylinder',M.stone,[x,y+.4,z],[3,.8,3]);this.batch.add('cylinder',M.water,[x,y+.83,z],[2.7,.06,2.7]);this.batch.add('cylinder',M.stone,[x,y+1.6,z],[.5,2,.5]);this.batch.add('cylinder',M.stone,[x,y+2.5,z],[1.3,.2,1.3]);}
 pitch(x,z,y,w,d){const line=(a,b,c,e)=>this.batch.box(M.trim,x+a,y+.01,z+b,c,.025,e);line(0,0,.12,d);for(const s of [-1,1]){line(s*w/2,0,.14,d);line(0,s*d/2,w,.14);line(0,s*(d/2-5),12,.14);line(-6,s*(d/2-2.5),.14,5);line(6,s*(d/2-2.5),.14,5);for(let a of [-3,3])this.batch.box(M.trim,x+a,y+1.5,z+s*d/2,.1,3,.1);this.batch.box(M.trim,x,y+3,z+s*d/2,6,.1,.1);}const ring=new T.Mesh(new T.RingGeometry(4.8,4.95,48),new T.MeshBasicMaterial({color:0xe8e5c9,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,y+.02,z);this.scene.add(ring);this.batch.add('sphere',M.trim,[x,y+.22,z],[.22,.22,.22]);}
 gazebo(x,z,y){this.platform(x,z,8,8,y+.3,M.wood);for(let a of [-3.5,3.5])for(let b of [-3.5,3.5])this.batch.box(M.trim,x+a,y+2,z+b,.2,3.5,.2);this.gable(x,y+3.8,z,9,9,2,0,M.roof);this.chest(x,y+.5,z);}
 gasStation(x,z,y){this.house(x,z-7,{floors:1,w:10.24,d:10.24,mat:M.white,roof:'flat',commercial:true,sign:'GAS',y});this.platform(x,z+6,21,15,y+.1);this.batch.box(M.yellow,x,y+4,z+6,19,.45,10);for(let a of [-7,7]){this.batch.box(M.red,x+a,y+2,z+6,.3,4,.3);this.solid(M.trim,x+a*.5,y+.8,z+7,1,1.6,.6,0,'pump',150);this.batch.box(M.black,x+a*.5,y+1.16,z+7.32,.68,.38,.04);}}
 tomato(x,z,y){this.batch.add('sphere',M.red,[x,y+1.5,z],[2.4,2.15,2.3]);for(const a of [-.85,.85]){this.batch.add('sphere',M.trim,[x+a,y+1.85,z+2.03],[.62,.7,.29]);this.batch.add('sphere',M.black,[x+a,y+1.9,z+2.28],[.19,.3,.08]);}this.batch.box(M.black,x,y+.69,z+2.1,2,.35,.2,[0,0,.12]);for(let i=0;i<5;i++)this.batch.add('cone',M.leaf,[x+Math.sin(i)*.5,y+3.7,z+Math.cos(i)*.5],[.5,1.1,.5],[Math.sin(i),0,Math.cos(i)]);this.batch.add('cylinder',M.steel,[x,y-1.2,z],[.16,3,.16]);}
 burger(x,z,y){this.batch.add('sphere',M.yellow,[x,y+1.3,z],[2,1.1,1.7]);this.batch.add('cylinder',M.wood,[x,y+.65,z],[1.9,.45,1.9]);this.batch.add('cylinder',M.leaf,[x,y+.88,z],[2.08,.17,2.08]);this.batch.add('cylinder',M.yellow,[x,y+.18,z],[1.9,.5,1.9]);for(let a of [-.7,.7]){this.batch.add('sphere',M.trim,[x+a,y+1.85,z+1.28],[.5,.6,.4]);this.batch.add('sphere',M.black,[x+a,y+1.8,z+1.64],[.19,.26,.08]);}this.batch.add('sphere',M.red,[x+.3,y+.2,z+1.7],[.4,.16,.67]);}
 hedge(x,z,len,rot){const y=this.height(x,z);this.solid(M.bush,x,y+1.5,z,1.7,3,len,rot,'hedge',100);}
 lookout(x,z,y){
 const tower={x,z,y,w:6,d:6,rot:0,type:'lookout',floors:4,parts:[],stairs:[]};this.buildings.push(tower);
 for(let a of [-2.5,2.5])for(let b of [-2.5,2.5])this.solid(M.wood,x+a,y+9,z+b,.3,18,.3);
 for(let f=0;f<4;f++){
  this.platform(x-1.1,z,3.8,6,y+f*4.3,M.wood);this.platform(x+1.9,z+2.65,2.2,.7,y+f*4.3,M.wood);
  for(let i=0;i<13;i++){const o=this.solid(M.wood,x+1.6,y+f*4.3+(i+1)*4.3/13-.075,z-2.2+(i+.5)*4.4/13,1.6,.15,4.4/13+.015,0,'stairs');o.building=tower;tower.parts.push(o);}
  tower.stairs.push({floor:f,x:1.6,start:-2.2,run:4.4,tread:4.4/13,bottom:y+f*4.3,top:y+(f+1)*4.3,width:1.6});
 }
 this.house(x,z,{w:5.12,d:5.12,floors:1,mat:M.wood,y:y+17.2,entryStair:{x:1.6,width:1.8,start:-2.3,run:4.6}});
 }
 church(x,z,y){this.house(x,z,{w:10.24,d:20.48,floors:1,mat:M.stone,roof:'gable',y});this.house(x,z-12,{w:5.12,d:5.12,floors:3,mat:M.stone,roof:'hip',y});this.batch.box(M.wood,x,y+16,z-12,.16,2,.2);this.batch.box(M.wood,x,y+16.5,z-12,1.1,.15,.2);}
 mine(x,z,y){const floor=26.7;for(let s of [-1,1]){this.solid(M.rock,x+s*35,(y+floor)/2,z,4,y-floor,64,0,'wall',500);this.platform(x+s*23,z,22,64,y,M.dirt);}for(let i=-3;i<=3;i++){this.batch.box(M.wood,x,y-1,z+i*8,25,.4,.4);for(let s of [-1,1])this.solid(M.wood,x+s*12,(y+floor)/2,z+i*8,.45,y-floor,.45,0,'beam',150);}this.platform(x,z,25,52,y-.7,M.wood);this.platform(x,z,23,63,floor,M.dirt);for(let s of [-1,1])this.batch.box(M.steel,x+s*.5,floor+.07,z,.08,.12,61);for(let i=-25;i<25;i+=2)this.batch.box(M.wood,x,floor+.05,z+i,1.8,.1,.25);for(let i=0;i<23;i++)this.solid(M.wood,x+3,floor+i*.36,z+32+i*.5,5,.35,.54,0,'stairs');this.chest(x-6,floor+.1,z-17);this.chest(x+7,floor+.1,z+13);this.crate(x-6,z+8,floor);}
 tunnel(x,z){const y=this.height(x,z)-5;for(let s of [-1,1])this.solid(M.stone,x+s*5,y+3,z,1,6,23);this.platform(x,z,11,24,y+6,M.rock);this.platform(x,z,9,26,y,M.asphalt);}
 campsite(x,z){const y=this.height(x,z);for(let i=0;i<3;i++){const a=i*2.1;this.gable(x+Math.cos(a)*5,y,z+Math.sin(a)*5,3,3,2,a,M.orange);}for(let i=0;i<9;i++){const a=i/9*6.28;this.batch.add('rock',M.rock,[x+Math.cos(a)*1.2,y+.2,z+Math.sin(a)*1.2],[.35,.25,.3]);}this.batch.box(M.wood,x,y+.2,z,1.4,.2,.24,.7);this.batch.box(M.wood,x,y+.23,z,1.4,.2,.24,-.7);this.chest(x+4,y+.1,z+2);}
 landmarks(){const at=(p)=>{const[x,z]=W(p);return{x,z,y:this.height(x,z)};};
 let p=at([.767,.741]);this.prison(p.x,p.z,p.y);
 p=at([.424,.819]);this.warehouse(p.x,p.z,30,20,M.metal,p.y);this.warehouse(p.x+37,p.z+12,22,17,M.brick,p.y);
 p=at([.215,.478]);this.warehouse(p.x,p.z,31,46,M.steel,p.y);this.pitch(p.x,p.z,p.y+.2,23,35);this.house(p.x+31,p.z,{mat:M.brick,floors:1,roof:'flat',y:p.y});
 for(const uv of ISOLATED_HOUSES){p=at(uv);this.house(p.x,p.z,{mat:[M.blue,M.white,M.wood][Math.floor(this.random()*3)],floors:2,y:p.y});}
 for(const uv of [[.531,.684],[.476,.435],[.685,.435],[.294,.35]]){p=at(uv);this.campsite(p.x,p.z);}
 for(const uv of [[.63,.218],[.417,.704],[.438,.485]]){p=at(uv);const y=this.wet(p.x,p.z)+3;this.platform(p.x,p.z,41,7,y,M.wood);for(const side of [-1,1]){this.batch.box(M.red,p.x,y+1.2,p.z+side*3.4,41,.2,.18);for(let j=-4;j<=4;j++)this.batch.box(M.red,p.x+j*5,y+.6,p.z+side*3.4,.18,1.3,.18);}}
 p=at([.798,.525]);for(let i=0;i<9;i++){this.car(p.x+(i%3)*7,p.z+Math.floor(i/3)*12,0,true,i);this.batch.box(M.white,p.x+(i%3)*7,p.y+2,p.z+Math.floor(i/3)*12,2.3,2.5,6);}
 p=at([.905,.586]);for(let i=0;i<3;i++){const points=[];for(let k=0;k<=80;k++){const a=k/80*Math.PI*2;points.push([p.x+Math.cos(a)*(30+i*10),p.z+Math.sin(a*3)*18+i*25]);}this.ribbon(points,4,M.dirt,(x,z)=>this.height(x,z)+.15);}
 // The small pre-match island is separate from the battle island.
 const sy=12,sx=-1260,sz=-1150;this.batch.add('cylinder',M.rock,[sx,0,sz],[80,23,70]);this.batch.add('cylinder',M.grass,[sx,11.7,sz],[77,.8,67]);this.platform(sx,sz,100,15,12.3,M.asphalt);this.warehouse(sx-20,sz-25,25,19,M.metal,12.3);this.spawnIsland={x:sx,y:12.5,z:sz};
 }
 prison(x,z,y){for(let a of [-1,1]){this.solid(M.stone,x+a*22,y+3,z,1,6,38.88,0,'wall',700);this.solid(M.stone,x,y+3,z+a*22,38.88,6,1,0,'wall',700);for(let b of [-1,1])this.house(x+a*22,z+b*22,{w:5.12,d:5.12,floors:3,roof:'flat',mat:M.stone,y});}this.house(x,z-8,{w:25.6,d:10.24,floors:2,roof:'flat',mat:M.stone,y});this.platform(x,z+10,28,14,y+.1,M.asphalt);}
 ground(x,z,feet,maxStep=.5){let h=this.height(x,z);const island=this.spawnIsland;if(island&&Math.hypot(x-island.x,z-island.z)<70)h=Math.max(h,12.3);for(const c of this.collision.query(x,z,.35)){if(c.sensor||c.kind==='tree'||c.kind==='bush'||!c.active||x<c.min.x-.02||x>c.max.x+.02||z<c.min.z-.02||z>c.max.z+.02)continue;let top=c.max.y;if(c.slope){const s=c.slope,dx=x-s.x,dz=z-s.z;const u=dx*Math.cos(s.rot)-dz*Math.sin(s.rot),v=dx*Math.sin(s.rot)+dz*Math.cos(s.rot);if(Math.abs(u)>s.w/2||Math.abs(v)>s.d/2)continue;top=s.y+s.rise*(1-(s.hip?Math.max(Math.abs(u)/(s.w/2),Math.abs(v)/(s.d/2)):Math.abs(u)/(s.w/2)));}if(top<=feet+maxStep)h=Math.max(h,top);}return h;}
 blocked(x,z,y,r=.32,height=1.72){for(const c of this.collision.query(x,z,r+.3)){if(!c.active||c.sensor||c.slope||c.max.y<y+.45||c.min.y>y+height)continue;const contactRadius=c.kind==='stairs'?Math.min(r,.12):r;if(x+contactRadius>c.min.x&&x-contactRadius<c.max.x&&z+contactRadius>c.min.z&&z-contactRadius<c.max.z)return true;}return this.height(x,z)>y+.65;}
 terrainHit(origin,dir,max){const step=max<10?.35:max<150?2:4;let last=0;for(let t=step;t<=max+step;t+=step){const at=Math.min(t,max);if(origin.y+dir.y*at<=this.height(origin.x+dir.x*at,origin.z+dir.z*at)){let lo=last,hi=at;for(let i=0;i<7;i++){const mid=(lo+hi)/2;if(origin.y+dir.y*mid<=this.height(origin.x+dir.x*mid,origin.z+dir.z*mid))hi=mid;else lo=mid;}return hi;}last=at;}return null;}
 destroy(o){if(o.dead)return;o.dead=true;if(o.refs)this.batch.hide(o);if(o.mesh)o.mesh.visible=false;for(const c of o.colliders||[])c.active=false;for(const c of this.collision.items)if(c.owner===o)c.active=false;if(o.kind==='chest'&&!o.opened)this.openChest(o);if(o.building){const supports=o.building.parts.filter(p=>p.kind==='wall'&&!p.dead&&p.colliders?.some(c=>c.min.y<o.building.y+1));if(supports.length===0)for(const p of o.building.parts){if(p===o||p.dead)continue;p.dead=true;this.batch.hide(p);if(p.mesh)p.mesh.visible=false;for(const c of p.colliders||[])c.active=false;for(const c of this.collision.items)if(c.owner===p)c.active=false;}}
 }
 openChest(c){if(c.opened)return [];c.opened=true;if(c.lid)c.lid.rotation.y=.9;if(c.mesh)c.mesh.children[0].material=M.darktrim;const weapon=['ar','pump','scar','sniper','hunting','smg','tactical','rocket','handcannon'][Math.floor(this.random()*9)];return[this.addLoot(weapon,c.x-1,c.y+.1,c.z+1),this.addLoot(['mini','shield','medkit','bandage','chug'][Math.floor(this.random()*5)],c.x+1,c.y+.1,c.z+1,2)];}
 toggleDoor(o){if(o.kind!=='door')return false;o.open=!o.open;for(const c of o.colliders||[])c.active=!o.open;for(const r of o.refs){const m=r.matrix.clone();if(o.open){const q=new T.Object3D();q.position.set(o.x+.62*Math.cos(o.rot),o.y+1.32,o.z-.62*Math.sin(o.rot));q.rotation.y=o.rot+Math.PI/2;q.scale.set(1.43,2.64,.12);q.updateMatrix();r.b.mesh.setMatrixAt(r.index,q.matrix);}else r.b.mesh.setMatrixAt(r.index,m);r.b.mesh.instanceMatrix.needsUpdate=true;}return true;}
 update(time,player,aerial,quality){this.batch.update(player.x,player.z,aerial,quality);for(const c of this.chests)c.mesh.visible=!c.dead&&Math.hypot(c.x-player.x,c.z-player.z)<180;for(const l of this.loot){l.mesh.visible=l.active&&Math.hypot(l.x-player.x,l.z-player.z)<120;if(l.mesh.visible){l.mesh.rotation.y=time*.6+l.phase;const floor=this.ground(l.x,l.z,l.y-.32,.05)+.44;if(floor<l.y-.15)l.y=Math.max(floor,l.y-.16);l.mesh.position.y=l.y+Math.sin(time*2+l.phase)*.08;}}for(const s of this.signs)s.visible=Math.hypot(s.position.x-player.x,s.position.z-player.z)<450;}
}
