import {REGIONS,BOSSES,ATTACKS} from './data.js';
import {freshSave,restState,maxHP,maxFP,maxStamina,weaponDamage,attackPhase,validateSave,canTravel,dist} from './core.js';
export function installDiagnostics(g){
 const box=document.createElement('div');box.id='diagnostics';box.style.cssText='position:absolute;right:14px;top:100px;background:#081b17ed;color:#d9e6cf;padding:12px;font:11px monospace;z-index:35;width:275px;border:1px solid #9caa78';
 box.innerHTML='<b>DEVELOPMENT TEST VIEW</b><div style="display:flex;gap:6px;margin:10px 0"><button id="qa-run">Run checks</button><button id="qa-view">Change view</button><button id="qa-hide">Hide</button></div><select id="qa-region" style="width:100%">'+Object.entries(REGIONS).map(([id,r])=>`<option value="${id}">${r.name}</option>`).join('')+'</select><pre id="qa-state" style="white-space:pre-wrap;max-height:240px;overflow:auto"></pre><pre id="qa-results" style="white-space:pre-wrap;max-height:230px;overflow:auto">No tests run.</pre>';
 document.body.appendChild(box);const state=box.querySelector('#qa-state'),results=box.querySelector('#qa-results');g.qaResults=[];
 const capture=document.createElement('button');capture.textContent='Save gameplay capture';capture.id='qa-capture';capture.style.cssText='padding:8px;border:1px solid #9aa779;margin-top:8px';box.appendChild(capture);capture.onclick=async()=>{g.renderer.render(g.scene,g.camera);const response=await fetch('/__capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:g.save.region+'-'+Math.round(g.player.z),data:g.canvas.toDataURL('image/png')})});g.ui.toast(response.ok?'Gameplay capture saved.':'Capture could not be saved.');};
 setInterval(()=>{const snap=g.snapshot();state.textContent=JSON.stringify({region:snap.region,position:snap.position,hp:snap.hp,action:snap.action,combat:snap.inCombat,...snap.performance},null,2);},700);
 box.querySelector('#qa-hide').onclick=()=>box.style.display='none';let view=0;
 const views=[{name:'First Step',region:'limgrave',x:0,z:116,yaw:-.08,pitch:.025},{name:'Church of Elleh',region:'limgrave',x:-34,z:62,yaw:.03,pitch:-.08},{name:'Church interior',region:'limgrave',x:-34,z:47,yaw:.05,pitch:-.02},{name:'Gatefront',region:'limgrave',x:44,z:-35,yaw:0,pitch:.04},{name:'Gatefront cellar',region:'limgrave',x:69,z:-77,yaw:0,pitch:.1}];
 box.querySelector('#qa-view').onclick=async()=>{const v=views[view++%views.length];g.playing=true;g.save.day=.35;g.ui.hideTitle();g.ui.close();if(g.save.region!==v.region)g.loadRegion(v.region,{x:v.x,z:v.z});Object.assign(g.player,{x:v.x,z:v.z,y:g.world.groundAt(v.x,v.z),vy:0});g.cameraYaw=v.yaw;g.cameraPitch=v.pitch;g.cameraInitialized=false;g.ui.toast(v.name,1000);};
 box.querySelector('#qa-region').onchange=async e=>{g.save.defeated=[];await g.transition(e.target.value);};
 box.querySelector('#qa-run').onclick=async()=>{
  box.querySelector('#qa-run').disabled=true;g.ui.close();g.playing=false;const original=JSON.parse(JSON.stringify(g.save));const report=[];const assert=(label,test,detail='')=>{report.push({label,passed:!!test,detail});results.textContent=report.map(x=>(x.passed?'PASS ':'FAIL ')+x.label+(x.detail?' — '+x.detail:'')).join('\n');};
  try{
   g.save=restState(freshSave());g.loadRegion('limgrave',{x:0,z:116});g.updateEquipment();g.stamina=maxStamina(g.save);
   const start={...g.player};g.keys.add('KeyW');for(let i=0;i<120;i++)g.updatePlayer(1/60);g.keys.clear();assert('Movement advances across terrain',dist(g.player,start)>5,dist(g.player,start).toFixed(1)+' metres');
   Object.assign(g.player,{x:0,z:116,y:g.world.groundAt(0,116),vy:0});g.player.velocity.set(0,0,0);let routeOK=true,stop='';
   for(const [x,z]of [[-25,82],[-34,65],[-35,58],[-35,46],[-35,64],[-15,64],[-12,24],[8,-12],[34,-28],[44,-46],[48,-64],[44,-96],[20,-100],[-25,-127],[-25,-153]]){
    let ticks=0;g.keys.add('KeyW');while(dist(g.player,{x,z})>1.1&&ticks++<1000){g.cameraYaw=Math.atan2(-(x-g.player.x),-(z-g.player.z));g.updatePlayer(1/30);}g.keys.clear();if(dist(g.player,{x,z})>1.5){routeOK=false;stop=x+','+z+' stopped at '+g.player.x.toFixed(1)+','+g.player.z.toFixed(1);break;}
   }assert('First Step, church, Gatefront, Stormgate route',routeOK,stop||'All 15 waypoints reached using movement physics. Enemies held inactive.');g.player.velocity.set(0,0,0);
   g.player.action=null;g.player.velocity.set(0,0,0);Object.assign(g.player,{x:-45,z:43,y:g.world.groundAt(-45,43)});g.cameraYaw=0;g.keys.add('KeyD');for(let i=0;i<120;i++)g.updatePlayer(1/60);g.keys.clear();assert('Church wall collision',g.player.x>-45&&g.player.x<-43.7,g.player.x.toFixed(2));
   g.player.action=null;Object.assign(g.player,{x:0,z:110,y:g.world.groundAt(0,110),yaw:0});g.stamina=120;g.playing=true;const target=g.world.enemies[0];Object.assign(target,{x:0,z:108,hp:300,maxHp:300,dead:false,stagger:0,stance:0,aggro:false});target.y=g.world.groundAt(0,108);target.mesh.visible=true;
   g.attack('light');const hp=target.hp;g.updatePlayer(.05);assert('Startup causes no instant damage',target.hp===hp);for(let i=0;i<18;i++)g.updatePlayer(1/60);assert('Active swing connects',target.hp<hp);const hitHP=target.hp;for(let i=0;i<8;i++)g.updatePlayer(1/60);assert('One hit per attack per target',target.hp===hitHP);
   g.player.action=null;g.stamina=120;g.dodge();g.player.action.time=.15;g.player.action.backstep=false;g.hurtGrace=0;const hp0=g.save.hp;g.hurtPlayer(100);assert('Dodge invulnerability window',g.save.hp===hp0);
   g.player.action=null;g.player.yaw=0;g.save.equipment.shield=true;g.save.equipment.twoHand=false;g.blocking=true;g.stamina=120;g.hurtGrace=0;g.hurtPlayer(40,{x:g.player.x,z:g.player.z-1});assert('Frontal physical block',g.save.hp===hp0&&g.stamina<120);g.blocking=false;
   g.player.action=null;g.stamina=120;g.parry();g.player.action.time=.15;g.hurtGrace=0;target.x=g.player.x;target.z=g.player.z-1;target.stagger=0;g.hurtPlayer(50,target);assert('Parry creates critical opening',target.stagger>3);
   g.player.action=null;g.save.hp=200;g.save.flaskHP=2;g.flaskType='hp';g.flask();for(let i=0;i<80;i++)g.updatePlayer(1/60);assert('Timed flask restores HP and spends charge',g.save.hp>200&&g.save.flaskHP===1);
   g.save.quests.torrent=true;g.player.action=null;g.mount();assert('Torrent summon',g.mounted);g.jump();const vy=g.player.vy;g.player.y+=1;g.jump();assert('Torrent double jump',g.player.jumps===2&&g.player.vy>0);g.mounted=false;g.horse.visible=false;
   const copy=validateSave(JSON.parse(JSON.stringify(g.save)));assert('Save round-trip preserves inventory',copy.equipment.weapon===g.save.equipment.weapon&&copy.hp===g.save.hp);
   const gate=g.world.objects.find(o=>o.id==='limgrave-map');g.collect(gate);assert('Map fragment persists',g.save.fragments.includes('limgrave')&&g.save.loot.includes('limgrave-map'));
   g.save.runes=1234;g.hurtGrace=0;g.player.action=null;g.resting=false;g.save.hp=1;g.hurtPlayer(100);assert('Death drops all carried runes',g.save.runes===0&&g.save.deathRunes?.amount===1234);g.respawn();assert('Respawn restores HP at checkpoint',g.save.hp===maxHP(g.save)&&dist(g.player,g.save.checkpoint)<.1);
   g.playing=false;let good=0,fail=[];
   for(const id of Object.keys(REGIONS)){try{g.loadRegion(id,{x:0,z:id==='roundtable'?18:90});g.updateCamera(.016);g.renderer.render(g.scene,g.camera);let bad=false;g.world.root.traverse(o=>{if(o.isMesh&&o.geometry?.attributes?.position){const a=o.geometry.attributes.position.array;for(let i=0;i<a.length;i++)if(!Number.isFinite(a[i])){bad=true;break;}}});if(bad)fail.push(id);else good++;}catch(e){fail.push(id+': '+e.message);}await new Promise(r=>setTimeout(r,0));}
   assert('All region scenes render finite geometry',fail.length===0,good+'/'+Object.keys(REGIONS).length+(fail.length?' '+fail.join(','):''));
   g.save.defeated.push('maliketh');g.save=validateSave(JSON.parse(JSON.stringify(g.save)));g.loadRegion('leyndell',{x:0,z:90});assert('Capital becomes ash after Destined Death, including after save reload',g.save.region==='ashen'&&g.world.id==='ashen');
  }catch(e){assert('Test runner',false,e.stack||e.message);}finally{g.qaResults=report;await fetch('/__report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:new Date().toISOString(),type:'isolated browser integration checks; not a normal-input complete playthrough',checks:report})});g.save=original;g.loadRegion(original.region,original.position);g.updateEquipment();g.refill();g.deadTime=0;document.getElementById('death').style.display='none';g.playing=true;g.ui.hideTitle();g.saveNow();box.querySelector('#qa-run').disabled=false;}
 };
}
