import {THREE,V,createMaterials,createSky,makeCharacter,animateCharacter,setCharacterWeapon,makeWeapon,makeHorse,pointTexture} from './graphics.js';
import {World} from './world.js';
import {UI} from './ui.js';
import {AudioEngine} from './audio.js';
import {REGIONS,WEAPONS,BOSSES,ATTACKS,ENDINGS} from './data.js';
import {freshSave,restState,SaveStore,validateSave,maxHP,maxFP,maxStamina,loadRatio,attackTimeline,attackPhase,dodgeIFrames,weaponDamage,dist,clamp,lerp,angleDelta,recordDeath,recoverRunes,canTravel,gateReason} from './core.js';
const $=id=>document.getElementById(id);
const waitFrame=()=>new Promise(r=>requestAnimationFrame(r));
const spellNames=['Glintstone Pebble','Glintstone Arc','Catch Flame'];
class Game{
 constructor(){
  this.canvas=$('world');this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(57,innerWidth/innerHeight,.1,2100);this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setSize(innerWidth,innerHeight);this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;
  this.clock=new THREE.Clock();this.time=0;this.accum=0;this.frameCount=0;this.fps=60;this.frameTimes=[];this.keys=new Set();this.pointer={down:false,moved:false,x:0,y:0};this.cameraYaw=-.08;this.cameraPitch=.025;this.cameraDistance=5.2;this.lookAt=V();this.cameraRay=new THREE.Raycaster();this.cameraInitialized=false;
  this.audio=new AudioEngine();let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Browser storage is disabled. Export your save.');}};}this.storage=storage;this.store=new SaveStore(storage);this.save=this.store.load();this.hasSave=!!this.save;if(!this.save)this.save=restState(freshSave());this.settings={quality:'high',volume:.35,sensitivity:.75};try{Object.assign(this.settings,JSON.parse(storage.getItem('lands-between-settings')||'{}'));}catch{}
  this.audio.volume(this.settings.volume);this.player={x:this.save.position.x,z:this.save.position.z,y:0,vy:0,yaw:0,velocity:V(),action:null,buffer:null,jumps:0};this.stamina=maxStamina(this.save);this.staminaDelay=0;this.blocking=false;this.crouch=false;this.mounted=false;this.torrentHP=250;this.flaskType='hp';this.locked=null;this.effects=[];this.projectiles=[];this.hazards=[];this.spirit=null;this.spiritUsed=false;this.statusBuild=0;this.poison=0;this.deadTime=0;this.shake=0;this.lastSave=0;this.lastStep=0;this.playing=false;this.resting=false;this.currentGrace=null;this.hurtGrace=0;this.guardCounter=0;this.heavyStart=0;this.damageLabels=[];
  this.ui=new UI(this);this.bind();
 }
 async init(){
  this.m=await createMaterials();$('load-text').textContent='Building the Lands Between…';await waitFrame();
  this.sky=createSky();this.scene.add(this.sky);this.ambient=new THREE.HemisphereLight(0xd8dec4,0x344533,2.1);this.scene.add(this.ambient);this.sun=new THREE.DirectionalLight(0xffe7ad,3.1);this.sun.position.set(90,130,-60);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.camera.left=-48;this.sun.shadow.camera.right=48;this.sun.shadow.camera.top=48;this.sun.shadow.camera.bottom=-48;this.sun.shadow.camera.near=1;this.sun.shadow.camera.far=350;this.sun.shadow.bias=-.0003;this.sun.shadow.normalBias=.07;this.scene.add(this.sun);this.scene.add(this.sun.target);
  this.rim=new THREE.DirectionalLight(0xa9bcd0,.8);this.rim.position.set(-80,20,60);this.scene.add(this.rim);
  this.world=new World(this.scene,this.m);this.char=makeCharacter(this.m,{color:this.save.appearance.cape,weapon:WEAPONS[this.save.equipment.weapon].kind});this.scene.add(this.char);this.horse=makeHorse(this.m);this.horse.visible=false;this.scene.add(this.horse);
  if(this.save.hp<=0){this.save.region=this.save.checkpoint.region;this.save.position={x:this.save.checkpoint.x,z:this.save.checkpoint.z};restState(this.save);}
  this.loadRegion(this.save.region,this.save.position);this.updateEquipment();this.drawIcons();this.setQuality(this.settings.quality,false);this.makeMotes();
  this.ui.showTitle();if(this.store.error)this.ui.toast(this.store.error,6000);$('loading').style.opacity='0';setTimeout(()=>$('loading').classList.add('hidden'),850);
  this.tick();window.addEventListener('resize',()=>this.resize());
  window.__gameDiagnostics=()=>this.snapshot();
  // Test access is opt-in and never exposed as an in-game control.
  if(new URLSearchParams(location.search).get('test')==='1'){window.__testGame=this;const {installDiagnostics}=await import('./diagnostics.js');installDiagnostics(this);}
 }
 bind(){
  addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(this.ui.page)this.ui.close();else if(this.playing)this.ui.open('equipment');return;}if(e.repeat){this.keys.add(e.code);return;}if(e.code==='KeyH'){this.ui.page?this.ui.close():this.ui.open('controls');return;}if(!this.playing||this.ui.page||this.deadTime)return;this.audio.init();this.keys.add(e.code);
   if(e.code==='KeyE')this.interact();if(e.code==='Space')this.dodge();if(e.code==='KeyC')this.jump();if(e.code==='KeyX')this.crouch=!this.crouch;if(e.code==='KeyJ')this.attack('light');if(e.code==='KeyK')this.heavyStart=this.time;if(e.code==='KeyQ')this.blocking=true;if(e.code==='KeyR')this.flask();if(e.code==='Digit3'){this.flaskType=this.flaskType==='hp'?'fp':'hp';this.ui.toast(this.flaskType==='hp'?'Flask of Crimson Tears':'Flask of Cerulean Tears',1000);this.drawIcons();}if(e.code==='Tab')this.lockTarget();if(e.code==='KeyZ')this.lockTarget(true);if(e.code==='KeyV')this.parry();if(e.code==='KeyB')this.attack('skill');if(e.code==='KeyF')this.cast();if(e.code==='KeyT')this.mount();if(e.code==='KeyY'){this.save.equipment.twoHand=!this.save.equipment.twoHand;this.updateEquipment();}if(e.code==='Digit1')this.cycleWeapon();if(e.code==='Digit2'){this.save.equipment.spell=(this.save.equipment.spell+1)%3;this.ui.toast(spellNames[this.save.equipment.spell]);}if(e.code==='KeyG')this.summon();if(e.code==='KeyI')this.ui.open('equipment');if(e.code==='KeyM'){if(this.inCombat())this.ui.toast('Cannot open the map while in combat.');else this.ui.open('map');}
  });
  addEventListener('keyup',e=>{this.keys.delete(e.code);if(e.code==='KeyQ')this.blocking=false;if(e.code==='KeyK'&&this.playing&&!this.ui.page)this.attack(this.guardCounter>0?'counter':this.time-this.heavyStart>.6?'charged':'heavy');});
  addEventListener('blur',()=>{this.keys.clear();this.pointer.down=false;this.blocking=false;});
  this.canvas.addEventListener('contextmenu',e=>e.preventDefault());
  this.canvas.addEventListener('pointerdown',e=>{if(!this.playing||this.ui.page)return;this.audio.init();this.pointer={down:true,moved:false,x:e.clientX,y:e.clientY,button:e.button};this.canvas.setPointerCapture(e.pointerId);if(e.button===2)this.blocking=true;});
  this.canvas.addEventListener('pointermove',e=>{if(!this.pointer.down||!this.playing||this.ui.page)return;const dx=e.clientX-this.pointer.x,dy=e.clientY-this.pointer.y;if(Math.abs(dx)+Math.abs(dy)>2)this.pointer.moved=true;this.cameraYaw-=dx*.005*this.settings.sensitivity;this.cameraPitch=clamp(this.cameraPitch+dy*.003*this.settings.sensitivity,-.25,1);this.pointer.x=e.clientX;this.pointer.y=e.clientY;});
  this.canvas.addEventListener('pointerup',e=>{if(this.pointer.down&&e.button===0&&!this.pointer.moved)this.attack(this.save.equipment.paired?'paired':'light');this.pointer.down=false;if(e.button===2)this.blocking=false;});
  this.canvas.addEventListener('wheel',e=>{if(this.playing&&!this.ui.page){this.cameraDistance=clamp(this.cameraDistance+e.deltaY*.007,3.5,10);e.preventDefault();}},{passive:false});
  addEventListener('beforeunload',()=>{if(this.playing)this.saveNow();});
 }
 start(){this.playing=true;this.ui.hideTitle();this.audio.init();this.clock.getDelta();this.ui.discovery(REGIONS[this.save.region].name);if(!this.hasSave)this.ui.toast('Follow the golden light. E rests at a Site of Grace.',6000);}
 newGame(c,name,appearance){this.save=restState(freshSave(c,name,appearance));this.stamina=maxStamina(this.save);this.deadTime=0;this.statusBuild=0;this.poison=0;this.loadRegion('limgrave',this.save.position);this.updateEquipment();this.ui.close();this.start();this.saveNow();}
 saveSettings(){try{this.storage.setItem('lands-between-settings',JSON.stringify(this.settings));}catch{}}
 setQuality(q,save=true){this.settings.quality=q;const levels={high:1.5,medium:1,low:.75};this.renderer.setPixelRatio(Math.min(devicePixelRatio,levels[q]||1));this.renderer.shadowMap.enabled=q!=='low';this.renderer.setSize(innerWidth,innerHeight);if(save)this.saveSettings();}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);}
 loadRegion(id,pos){
  if(id==='leyndell'&&this.save.defeated.includes('maliketh'))id='ashen';
  for(const e of this.effects)this.scene.remove(e.mesh);for(const e of this.projectiles)this.scene.remove(e.mesh);for(const e of this.hazards)this.scene.remove(e.mesh);this.effects=[];this.projectiles=[];this.hazards=[];if(this.spirit)this.scene.remove(this.spirit.mesh);this.spirit=null;this.spiritUsed=false;this.locked=null;this.player.action=null;this.player.buffer=null;this.mounted=false;this.horse.visible=false;this.cameraInitialized=false;
  $('enemy-labels').replaceChildren();this.damageLabels=[];
  const info=this.world.load(id,this.save);this.save.region=id;this.regionInfo=info;this.sky.material.uniforms.tint.value.setHex(info.tint);this.sky.visible=!info.underground;this.player.x=pos.x;this.player.z=pos.z;this.player.y=this.world.groundAt(pos.x,pos.z);this.player.vy=0;this.player.velocity.set(0,0,0);this.char.position.set(this.player.x,this.player.y,this.player.z);this.cameraYaw=-.08;this.cameraPitch=.025;this.graceProtection=1.2;this.updateDeathMarker();$('location-label').querySelector('span').textContent=REGIONS[id].name.toUpperCase();$('sub-location').textContent=REGIONS[id].grace;
  if(!this.save.discovered[id])this.save.discovered[id]=[];
 }
 async transition(id,pos={x:0,z:92}){if(this.deadTime)return;this.ui.close();this.playing=false;this.keys.clear();$('loading').classList.remove('hidden');$('loading').style.opacity='1';$('load-text').textContent='Travelling to '+REGIONS[id].name+'…';await waitFrame();await waitFrame();try{this.loadRegion(id,pos);this.save.position={...pos};this.playing=true;this.ui.hideTitle();this.ui.discovery(REGIONS[this.save.region].name);this.saveNow();}catch(e){this.ui.toast('Could not load this area: '+e.message,8000);console.error(e);}finally{$('loading').style.opacity='0';setTimeout(()=>$('loading').classList.add('hidden'),500);this.clock.getDelta();}}
 fastTravel(id){if(this.inCombat())return this.ui.toast('Cannot travel while in combat.');const known=this.save.discovered[id];if(!known?.length)return this.ui.toast('Discover a Site of Grace here first.');let pos=id==='limgrave'?{x:0,z:116}:id==='roundtable'?{x:0,z:18}:{x:0,z:90};if(id==='limgrave'){const coords={first:[0,116],elleh:[-36,45],gatefront:[20,-94],agheel:[75,-35]};const c=coords[known[0]]||coords.first;pos={x:c[0],z:c[1]};}this.transition(id,pos);}
 updateEquipment(){const s=this.save;if(!this.char)return;setCharacterWeapon(this.char,WEAPONS[s.equipment.weapon].kind,this.m);this.char.userData.shield.visible=s.equipment.shield&&!s.equipment.twoHand&&!s.equipment.paired;this.char.userData.cloth.color.set(s.appearance.cape);this.char.userData.cape.visible=s.equipment.armor!=='unarmored';if(this.pairedBlade)this.char.userData.arms[0].remove(this.pairedBlade);if(s.equipment.paired){this.pairedBlade=makeWeapon(WEAPONS[s.equipment.weapon].kind,this.m);this.pairedBlade.position.set(0,-.7,0);this.pairedBlade.rotation.set(-.15,0,.15);this.char.userData.arms[0].add(this.pairedBlade);}this.drawIcons();}
 cycleWeapon(){const a=this.save.inventory.weapons;this.save.equipment.weapon=a[(a.indexOf(this.save.equipment.weapon)+1)%a.length];this.updateEquipment();this.ui.toast(WEAPONS[this.save.equipment.weapon].name,1600);}
 inCombat(){return this.world?.enemies.some(e=>!e.dead&&e.aggro&&dist(e,this.player)<42)||false;}
 objective(){const s=this.save;if(!s.discovered.limgrave?.includes('elleh'))return'Find the Church of Elleh';if(!s.quests.torrent)return'Rest at Gatefront and speak with Melina';if(!s.fragments.includes('limgrave'))return'Find the map stele in Gatefront Ruins';if(!s.defeated.includes('godrick'))return'Follow Stormgate toward Stormveil Castle';if(s.defeated.filter(id=>BOSSES[id]?.rune).length<2)return'Seek another shardbearer';if(!s.defeated.includes('morgott'))return'Reach Leyndell, the Royal Capital';if(!s.defeated.includes('firegiant'))return'Seek the Forge of the Giants';if(!s.defeated.includes('maliketh'))return'Claim Destined Death in Farum Azula';if(!s.defeated.includes('beast'))return'Return to the Erdtree';return s.ending?'Journey complete. Explore what remains.':'Touch fractured Marika';}
 moveVector(){const x=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0),z=(this.keys.has('KeyW')?1:0)-(this.keys.has('KeyS')?1:0);const v=V(x*Math.cos(this.cameraYaw)-z*Math.sin(this.cameraYaw),0,-x*Math.sin(this.cameraYaw)-z*Math.cos(this.cameraYaw));if(v.lengthSq()>1)v.normalize();return v;}
 spend(n){if(this.stamina<n)return false;this.stamina-=n;this.staminaDelay=.8;return true;}
 attack(kind){if(!this.playing||this.ui.page||this.deadTime)return;const p=this.player,s=this.save;if(p.action){if(p.action.total-p.action.time<.25)p.buffer={kind,time:this.time};return;}if(p.y>this.world.groundAt(p.x,p.z)+.35)kind='jumping';else if(kind==='light'&&this.keys.has('ShiftLeft')&&this.moveVector().lengthSq()>.1)kind='running';else if(kind==='light'&&this.rollEnd&&this.time-this.rollEnd<.5)kind='rolling';if(kind==='light'&&this.world.enemies.some(e=>!e.dead&&e.stagger>0&&dist(e,p)<2.4))kind='critical';
  const a=attackTimeline(kind,s.equipment.weapon);if(a.fp&&s.fp<a.fp)return this.ui.toast('Not enough FP.',1000);if(!this.spend(a.cost))return;if(a.fp)s.fp-=a.fp;
  if(this.locked&&!this.locked.dead)p.yaw=Math.atan2(-(this.locked.x-p.x),-(this.locked.z-p.z));p.action={type:'attack',kind,time:0,...a,hit:new Set(),yaw:p.yaw};this.blocking=false;this.crouch=false;this.audio.swing();
 }
 dodge(){if(this.player.action||this.mounted||this.deadTime)return;const ratio=loadRatio(this.save);if(ratio>=1)return this.ui.toast('Overloaded. Reduce equipment weight.');if(!this.spend(14))return;let dir=this.moveVector(),backstep=dir.lengthSq()<.01;if(backstep)dir=V(Math.sin(this.player.yaw),0,Math.cos(this.player.yaw));else this.player.yaw=Math.atan2(-dir.x,-dir.z);this.player.action={type:'roll',time:0,total:backstep?.37:ratio>=.7?.93:.63,dir,backstep,ratio,speed:backstep?4.5:ratio<.3?9.5:ratio<.7?7.8:5.8};this.blocking=false;this.crouch=false;}
 jump(){if(this.deadTime||this.player.action)return;const p=this.player,onGround=p.y<=this.world.groundAt(p.x,p.z)+.12;if(onGround||this.mounted&&p.jumps<2){p.vy=this.mounted?7.1:6;p.jumps=onGround?1:2;this.audio.tone(80,.12,'sine',.06,150);}}
 parry(){if(this.player.action||!this.save.equipment.shield||this.save.equipment.twoHand||this.save.equipment.paired)return;if(!this.spend(16))return;this.player.action={type:'parry',time:0,total:.63};this.blocking=false;this.audio.swing();}
 cast(){if(this.player.action||this.deadTime)return;const s=this.save,spell=s.equipment.spell,fire=spell===2;if(fire?(!s.quests.seal||s.stats[6]<8):(WEAPONS[s.equipment.weapon].kind!=='staff'||s.stats[5]<10))return this.ui.toast(fire?'Equip a Finger Seal and meet its faith requirement.':'Equip a staff to cast sorcery.');const cost=fire?10:spell===1?14:7;if(s.fp<cost)return this.ui.toast('Not enough FP.');if(!this.spend(13))return;s.fp-=cost;this.player.action={type:'cast',time:0,total:.95,castAt:.5,spell,fired:false};this.audio.cast();}
 flask(){const s=this.save;if(this.player.action||this.deadTime)return;const hp=this.flaskType==='hp',key=hp?'flaskHP':'flaskFP';if(s[key]<=0)return this.ui.toast('No charges remaining.',1200);s[key]--;this.player.action={type:'heal',time:0,total:1.3,healAt:.65,done:false,hp};this.audio.tone(520,.7,'sine',.07,780);}
 mount(){if(this.player.action||this.deadTime)return;if(!this.save.quests.torrent)return this.ui.toast('Melina can grant the Spectral Steed Whistle.');if(this.regionInfo.indoor||['stormveil','haligtree','elphael','farum','ashen'].includes(this.save.region))return this.ui.toast('Torrent cannot be summoned here.');this.mounted=!this.mounted;this.horse.visible=this.mounted;this.spark(this.player.x,this.player.y+1,this.player.z,0x84dbe6,25);this.audio.cast();}
 summon(){if(this.spirit){this.scene.remove(this.spirit.mesh);this.spirit=null;return;}if(!this.save.quests.spirit)return this.ui.toast('Speak with Roderika at Roundtable Hold to receive the Spirit Calling Bell.');if(this.spiritUsed)return this.ui.toast('Rest at a Site of Grace before summoning again.');if(!this.inCombat())return this.ui.toast('Spirit Ashes require a nearby active encounter.');if(this.save.fp<35)return this.ui.toast('Not enough FP.');this.save.fp-=35;const mesh=makeCharacter(this.m,{beast:true,spectral:true,scale:.65});mesh.position.set(this.player.x+2,this.player.y,this.player.z);this.scene.add(mesh);this.spirit={mesh,x:this.player.x+2,z:this.player.z,hp:200,timer:1};this.spiritUsed=true;this.audio.cast();}
 nearestObject(){let best=null,d=3.1;for(const o of this.world.objects){if(o.type==='loot'&&this.save.loot.includes(o.id))continue;const n=dist(o,this.player);if(n<d){best=o;d=n;}}if(this.save.deathRunes?.region===this.save.region&&dist(this.save.deathRunes,this.player)<2.6)return{type:'runes',label:'Retrieve lost runes'};if(this.save.region==='ashen'&&this.save.defeated.includes('beast')&&dist(this.player,{x:0,z:-144})<6)return{type:'ending',label:'Touch fractured Marika'};return best;}
 interact(){const o=this.nearestObject();if(!o||this.player.action)return;if(o.type==='grace'){if(this.inCombat())return this.ui.toast('Cannot rest while enemies are nearby.');this.currentGrace=o;if(!this.save.discovered[this.save.region].includes(o.id)){this.save.discovered[this.save.region].push(o.id);this.ui.discovery('LOST GRACE DISCOVERED',2800);this.audio.chime();}this.save.checkpoint={region:this.save.region,id:o.id,x:o.x,z:o.z};this.rest();if(o.id==='gatefront'&&!this.save.quests.torrent){this.dialogueFor('melina');}else this.ui.open('grace');}
  else if(o.type==='loot'){this.collect(o);}
  else if(o.type==='runes'){const n=recoverRunes(this.save);this.updateDeathMarker();this.ui.toast(n.toLocaleString()+' runes retrieved');this.audio.chime();this.saveNow();}
  else if(o.type==='exit'){if(!canTravel(this.save,o.requires))return this.ui.toast(gateReason[o.requires]||'Defeat '+(BOSSES[o.requires]?.name||o.requires)+' to proceed.',5000);if(this.inCombat())return this.ui.toast('Lose pursuing enemies before leaving.');this.transition(o.to);}
  else if(o.type==='npc')this.dialogueFor(o.id);
  else if(o.type==='smith'){this.ui.open('smith');}
  else if(o.type==='ending')this.ui.open('ending');
 }
 collect(o){const s=this.save;s.loot.push(o.id);o.mesh.visible=false;if(o.kind==='fragment'){if(!s.fragments.includes(o.value))s.fragments.push(o.value);}else if(o.kind==='weapon'){if(!s.inventory.weapons.includes(o.value))s.inventory.weapons.push(o.value);}else if(o.kind==='quest')s.quests[o.value]=true;else if(o.kind==='ash'){s.quests.whetstone=true;}else if(o.kind==='runes')s.runes+=o.value;else s.inventory[o.kind]=(s.inventory[o.kind]||0)+o.value;this.ui.toast('Acquired: '+o.label);this.audio.chime();this.saveNow();}
 refill(){restState(this.save);this.stamina=maxStamina(this.save);this.statusBuild=0;this.poison=0;}
 rest(){this.refill();this.resting=true;this.player.action=null;this.player.buffer=null;this.currentGrace&&Object.assign(this.player,{x:this.currentGrace.x,z:this.currentGrace.z});this.player.y=this.world.groundAt(this.player.x,this.player.z);for(const e of this.world.enemies){if(e.bossId&&this.save.defeated.includes(e.bossId))continue;e.dead=false;e.hp=e.maxHp;e.x=e.home.x;e.z=e.home.z;e.y=this.world.groundAt(e.x,e.z);e.aggro=false;e.action=null;e.mesh.visible=true;e.stance=0;e.stagger=0;e.mesh.rotation.z=0;}for(const p of this.projectiles)this.scene.remove(p.mesh);this.projectiles=[];for(const h of this.hazards)this.scene.remove(h.mesh);this.hazards=[];if(this.spirit)this.scene.remove(this.spirit.mesh);this.spirit=null;this.spiritUsed=false;this.torrentHP=250;this.saveNow();}
 dialogueFor(id){const s=this.save;this.npcId=id;const data={
  varre:{name:'White Mask Varré',text:'The guidance of grace points north. Begin at the ruined church. Beyond the trees, the soldiers of Gatefront guard the road to Stormveil.',options:[]},
  melina:{name:'Melina',text:s.quests.torrent?'Torrent has chosen you. Rest at grace, and turn your runes into strength.':'I can offer you an accord. I will help turn your runes into strength, and give you a steed to cross this land.',options:s.quests.torrent?[]:[{id:'accord',label:'Accept the accord'}]},
  ranni:{name:'Ranni the Witch',text:s.quests.ranni?'The fallen star opens the way to Nokron. Claim what lies beyond its silver guardian, then follow my path beneath the lakes.':'My path leads beyond the Golden Order. Will you enter my service?',options:s.quests.ranni?[]:[{id:'ranni',label:'Enter Ranni’s service'}]},
  albus:{name:'Albus',text:'Take this half of the secret medallion. Its counterpart lies in Castle Sol, far beyond the capital.',options:s.quests.secretLeft?[]:[{id:'albus',label:'Receive the medallion'}]},
  roderika:{name:'Roderika',text:'The spirits may answer your call. Take this bell, and summon them where battle gathers.',options:s.quests.spirit?[]:[{id:'spirit',label:'Receive the Spirit Calling Bell'}]},
  fia:{name:'Fia',text:s.defeated.includes('fortissax')?'The dragon’s dream has ended. Take the rune that will give those who live in death a place in the coming age.':'A dragon waits in the dream beneath these roots. Release it, and return to me.',options:s.defeated.includes('fortissax')&&!s.quests.fiaDone?[{id:'fia',label:'Receive the Mending Rune'}]:[]},
  corhyn:{name:'Brother Corhyn',text:'Goldmask has reached the capital. Seek him there, and speak of the Order.',options:s.quests.corhyn?[]:[{id:'corhyn',label:'Learn about Goldmask'}]},
  goldmask:{name:'Goldmask',text:s.defeated.includes('morgott')&&s.quests.corhyn?'The question has found its answer. A rune rests beneath the golden mask.':'The silent scholar turns toward the Erdtree. Return after speaking with Corhyn and defeating Morgott.',options:s.defeated.includes('morgott')&&s.quests.corhyn&&!s.quests.goldmaskDone?[{id:'goldmask',label:'Receive the Mending Rune'}]:[]},
  dungeater:{name:'Dung Eater',text:s.defeated.includes('mohgomen')?'The curse will outlive the order. Take this rune and choose what comes next.':'The sewers below conceal an omen. Return when it has fallen.',options:s.defeated.includes('mohgomen')&&!s.quests.dungDone?[{id:'dung',label:'Receive the Mending Rune'}]:[]},
  threefingers:{name:'The Three Fingers',text:'The chamber burns with an unquiet yellow flame. Embracing it commits this journey to the Lord of Frenzied Flame ending.',options:s.defeated.includes('mohgomen')&&!s.quests.frenzy?[{id:'frenzy',label:'Embrace the Frenzied Flame',detail:'This choice overrides the other endings.'}]:[]},
  tanith:{name:'Tanith',text:'The lord of this manor awaits beyond the temple. Steel yourself for the serpent’s fire.',options:[]}
 };if(['kale','twinmaidens','garr'].includes(id)){this.npcName=id==='kale'?'Merchant Kalé':id==='garr'?'Brother Corhyn':'Twin Maiden Husks';this.ui.open('merchant');return;}if(id==='hewg'){this.npcName='Smithing Master Hewg';this.ui.open('smith');return;}
  const d=data[id]||data.varre;this.npcName=d.name;this.dialogue=d;this.ui.open('dialogue');
 }
 dialogueAction(id){const s=this.save;if(id==='accord'){s.quests.torrent=true;s.quests.melina=true;this.ui.toast('Spectral Steed Whistle acquired. T summons Torrent.');}else if(id==='albus')s.quests.secretLeft=true;else if(id==='fia')s.quests.fiaDone=true;else if(id==='goldmask')s.quests.goldmaskDone=true;else if(id==='dung')s.quests.dungDone=true;else s.quests[id]=true;this.audio.chime();this.saveNow();this.dialogueFor(this.npcId);}
 saveNow(){if(!this.save||!this.world)return;this.save.position={x:this.player.x,z:this.player.z};if(!this.store.save(this.save)){this.ui.toast('Save failed: '+this.store.error,6000);}else this.hasSave=true;}
 exportSave(){this.saveNow();const b=new Blob([JSON.stringify(this.save,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='lands-between-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
 async importSave(file){if(!file)return;try{const s=validateSave(JSON.parse(await file.text()));this.save=s;this.stamina=maxStamina(s);this.deadTime=0;await this.transition(s.region,s.position);this.updateEquipment();this.ui.toast('Save imported.');}catch(e){this.ui.toast('Import failed: '+e.message,6000);}}
 updateDeathMarker(){if(this.deathMarker)this.scene.remove(this.deathMarker);this.deathMarker=null;const r=this.save.deathRunes;if(r?.region===this.save.region){const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:pointTexture(),color:0xc5f185,depthWrite:false,blending:THREE.AdditiveBlending}));sprite.position.set(r.x,this.world.groundAt(r.x,r.z)+.9,r.z);sprite.scale.set(1.3,2.5,1);this.scene.add(sprite);this.deathMarker=sprite;}}
 lockTarget(next=false){if(this.locked&&!next){this.locked=null;return;}const targets=this.world.enemies.filter(e=>!e.dead&&e.mesh.visible&&dist(e,this.player)<35).sort((a,b)=>dist(a,this.player)-dist(b,this.player));if(!targets.length){this.locked=null;return;}this.locked=next?targets[(targets.indexOf(this.locked)+1)%targets.length]:targets[0];}
 spark(x,y,z,color=0xf4be67,count=12){const pts=[],vel=[];for(let i=0;i<count;i++){pts.push(0,0,0);vel.push(V((Math.random()-.5)*5,1+Math.random()*4,(Math.random()-.5)*5));}const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));const mesh=new THREE.Points(geom,new THREE.PointsMaterial({color,size:.07,transparent:true,opacity:1,depthWrite:false}));mesh.position.set(x,y,z);this.scene.add(mesh);this.effects.push({mesh,vel,time:0,total:.65});}
 damageText(e,amount){const el=document.createElement('div');el.className='damage-number';el.textContent=amount;$('enemy-labels').appendChild(el);this.damageLabels.push({el,x:e.x,y:e.y+(e.boss?.scale||1)*2.3,z:e.z,time:0});}
 hurtEnemy(e,damage,stance=12,critical=false){if(e.dead)return;e.hp=Math.max(0,e.hp-damage);e.stance+=stance;e.aggro=true;e.hitFlash=.12;this.damageText(e,damage);this.spark(e.x,e.y+(e.boss?.scale||1),e.z,0xcaa177);this.audio.hit();this.shake=Math.max(this.shake,critical?.15:.045);
  if(WEAPONS[this.save.equipment.weapon].bleed){e.bleed+=WEAPONS[this.save.equipment.weapon].bleed;if(e.bleed>=100){e.hp-=Math.round(e.maxHp*.13);e.bleed=0;this.spark(e.x,e.y+1,e.z,0xb93627,20);}}
  if(e.stance>=(e.boss?100:45)){e.stagger=3.2;e.action=null;e.stance=0;this.audio.block();this.ui.toast('Stance broken',1000);}else if(!e.boss){e.stagger=.3;e.action=null;}
  if(e.hp<=0){e.dead=true;e.action=null;e.aggro=false;this.save.runes+=e.reward;if(e.bossId){if(!this.save.defeated.includes(e.bossId))this.save.defeated.push(e.bossId);this.ui.discovery(e.boss.rune?'DEMIGOD FELLED':'GREAT ENEMY FELLED',4200);this.audio.chime();this.save.inventory.stones+=3;this.save.inventory.tears+=1;if(e.bossId==='astel'&&this.save.quests.ranni)this.save.quests.ranniDone=true;if(e.bossId==='mimic')this.save.quests.nokronTreasure=true;this.saveNow();}else{this.save.inventory.flowers++;if(Math.random()<.28)this.save.inventory.stones++;}if(this.locked===e)this.locked=null;}
 }
 hurtPlayer(amount,attacker=null,kind='physical'){if(this.deadTime||this.resting||this.hurtGrace>0)return false;const p=this.player,a=p.action;if(a?.type==='roll'&&dodgeIFrames(a.time,a.ratio,a.backstep))return false;
  if(a?.type==='parry'&&a.time>.08&&a.time<.26&&attacker&&kind==='physical'&&dist(p,attacker)<4){attacker.stagger=3.4;attacker.action=null;this.spark(p.x,p.y+1,p.z,0xffec9a,25);this.audio.block();this.ui.toast('Parried',900);return false;}
  const front=attacker?Math.cos(angleDelta(p.yaw,Math.atan2(-(attacker.x-p.x),-(attacker.z-p.z))))>-.1:true;
  if(this.blocking&&this.save.equipment.shield&&!this.save.equipment.twoHand&&!this.save.equipment.paired&&front&&!this.mounted){const cost=amount*.55;this.audio.block();this.spark(p.x,p.y+1,p.z,0xe6cd98,10);if(this.stamina>=cost){this.stamina-=cost;this.staminaDelay=1;this.guardCounter=.75;if(kind!=='physical')this.save.hp=Math.max(0,this.save.hp-amount*.25);this.hurtGrace=.15;if(this.save.hp<=0)this.die();return false;}this.stamina=0;p.action={type:'stun',time:0,total:1};this.ui.toast('Guard broken',1000);}
  const armor=this.save.equipment.armor==='knight'?.8:this.save.equipment.armor==='light'?.91:1;const taken=Math.round(amount*armor);this.save.hp=Math.max(0,this.save.hp-taken);this.shake=.18;this.hurtGrace=.28;this.audio.hit();this.spark(p.x,p.y+1,p.z,0x974b2e,12);
  if(this.mounted){this.torrentHP-=amount;if(this.torrentHP<=0){this.mounted=false;this.horse.visible=false;p.action={type:'stun',time:0,total:1.2};this.torrentHP=250;this.ui.toast('Torrent has fallen.');}}
  else if(!p.action||!['charged','heavy'].includes(p.action.kind))p.action={type:'stun',time:0,total:.36};
  if(this.save.hp<=0)this.die();return true;
 }
 die(){if(this.deadTime)return;recordDeath(this.save,this.player);this.deadTime=3.4;this.player.action=null;this.player.buffer=null;this.locked=null;this.audio.death();$('death').style.display='flex';this.ui.close();this.saveNow();}
 respawn(){const c=this.save.checkpoint;this.loadRegion(c.region,{x:c.x,z:c.z});this.refill();this.deadTime=0;$('death').style.display='none';this.saveNow();}
 projectile(x,y,z,target,{speed=14,damage=40,color=0x84cae4,owner='enemy',radius=.18,homing=false,life=5,kind='magic'}={}){const mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(radius,1),new THREE.MeshBasicMaterial({color}));mesh.position.set(x,y,z);const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:pointTexture(),color,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));glow.scale.setScalar(radius*6);mesh.add(glow);this.scene.add(mesh);const dir=V(target.x-x,(target.y||0)+1-y,target.z-z).normalize();this.projectiles.push({mesh,dir,speed,damage,owner,radius,homing,life,kind,target,age:0});}
 hazard(x,z,r,delay,damage,color=0xe9ab5a,kind='magic',owner=null){const mesh=new THREE.Mesh(new THREE.RingGeometry(r*.88,r,44),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.6,side:THREE.DoubleSide,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.position.set(x,this.world.groundAt(x,z)+.07,z);this.scene.add(mesh);this.hazards.push({mesh,x,z,r,delay,damage,color,kind,owner,time:0,hit:false});}
 lineClear(a,b){const n=Math.ceil(dist(a,b));for(let i=1;i<n;i++){const t=i/n,x=lerp(a.x,b.x,t),z=lerp(a.z,b.z,t),y=lerp(a.y||this.world.groundAt(a.x,a.z),b.y||this.world.groundAt(b.x,b.z),t)+.9;if(this.world.blocked(x,z,y,.04))return false;}return true;}
 updatePlayer(dt){
  const p=this.player,s=this.save;this.hurtGrace=Math.max(0,this.hurtGrace-dt);this.guardCounter=Math.max(0,this.guardCounter-dt);this.staminaDelay=Math.max(0,this.staminaDelay-dt);if(this.staminaDelay<=0)this.stamina=Math.min(maxStamina(s),this.stamina+dt*(this.blocking?10:37));
  let moving=this.ui.page?V():this.moveVector(),speed=this.mounted?11:this.crouch?2:4.8;const sprint=this.keys.has('ShiftLeft')&&moving.lengthSq()>.1&&!this.blocking&&this.stamina>2;if(sprint){speed*=1.52;if(this.inCombat()){this.stamina=Math.max(0,this.stamina-dt*12);this.staminaDelay=.5;}}if(loadRatio(s)>=.7&&!this.mounted)speed*=.85;if(loadRatio(s)>=1)speed*=.5;if(this.blocking)speed*=.47;
  const a=p.action;
  if(a){a.time+=dt;if(a.type==='attack'){
    moving.multiplyScalar(.15);const phase=attackPhase(a);if(phase==='active'){
     if(!a.swung){a.swung=true;this.spark(p.x-Math.sin(p.yaw)*1.1,p.y+1,p.z-Math.cos(p.yaw)*1.1,a.kind==='skill'?0xebd796:0xb4c8bd,7);}
     for(const e of this.world.enemies){if(e.dead||!e.mesh.visible||a.hit.has(e.id))continue;const range=WEAPONS[s.equipment.weapon].reach+(this.mounted?1:0)+e.radius*.4,dx=e.x-p.x,dz=e.z-p.z,angle=angleDelta(a.yaw,Math.atan2(-dx,-dz));if(dist(e,p)<range&&Math.abs(angle)<a.arc/2+.15&&Math.abs(e.y-p.y)<(e.boss?.scale||1)*2&&this.lineClear(p,e)){a.hit.add(e.id);let damage=weaponDamage(s,a.kind);if(s.equipment.affinity==='keen')damage+=Math.floor(s.stats[4]*.3);if(s.equipment.affinity==='heavy')damage+=Math.floor(s.stats[3]*.3);this.hurtEnemy(e,damage,a.stance,a.kind==='critical');}}
     if(a.kind==='skill'&&s.equipment.ash==='storm'&&!a.stomp){a.stomp=true;for(const e of this.world.enemies)if(!e.dead&&dist(e,p)<4.5&&!a.hit.has(e.id))this.hurtEnemy(e,65,40);this.spark(p.x,p.y+.1,p.z,0xbfcaba,35);}
    }
   }else if(a.type==='roll'){moving=a.dir.clone();speed=a.speed*(1-a.time/a.total*.45);}
   else if(a.type==='heal'){moving.multiplyScalar(.24);if(!a.done&&a.time>=a.healAt){a.done=true;if(a.hp)s.hp=Math.min(maxHP(s),s.hp+240+s.flasks.level*70);else s.fp=Math.min(maxFP(s),s.fp+65+s.flasks.level*25);this.spark(p.x,p.y+1,p.z,a.hp?0xf3b74d:0x619ad4,25);}}
   else if(a.type==='cast'){moving.multiplyScalar(.18);if(!a.fired&&a.time>=a.castAt){a.fired=true;const target=this.locked||{x:p.x-Math.sin(p.yaw)*25,z:p.z-Math.cos(p.yaw)*25,y:p.y};if(a.spell===2){for(const e of this.world.enemies)if(!e.dead&&dist(e,p)<3.4&&Math.abs(angleDelta(p.yaw,Math.atan2(-(e.x-p.x),-(e.z-p.z))))<1.1)this.hurtEnemy(e,70+s.stats[6]*3,20);this.spark(p.x-Math.sin(p.yaw)*2,p.y+1,p.z-Math.cos(p.yaw)*2,0xf2a74b,30);}else{for(let i=0;i<(a.spell===1?3:1);i++)this.projectile(p.x,p.y+1.4,p.z,{x:target.x+(i-1)*(a.spell===1?2:0),y:target.y,z:target.z},{speed:21,damage:40+s.stats[5]*3,color:0x8ee5ec,owner:'player',radius:a.spell===1?.22:.14});}}}
   else moving.multiplyScalar(.08);
   if(a.time>=a.total){if(a.type==='roll')this.rollEnd=this.time;p.action=null;if(p.buffer&&this.time-p.buffer.time<.6){const kind=p.buffer.kind;p.buffer=null;this.attack(kind);}}
  }
  const acceleration=1-Math.exp(-dt*(p.action?.type==='roll'?35:12));p.velocity.x=lerp(p.velocity.x,moving.x*speed,acceleration);p.velocity.z=lerp(p.velocity.z,moving.z*speed,acceleration);
  if(!a&&moving.lengthSq()>.05&&!this.locked)p.yaw=lerpAngle(p.yaw,Math.atan2(-moving.x,-moving.z),1-Math.exp(-dt*13));
  if(this.locked&&!this.locked.dead&&!a){p.yaw=lerpAngle(p.yaw,Math.atan2(-(this.locked.x-p.x),-(this.locked.z-p.z)),1-Math.exp(-dt*12));}
  const nextX=p.x+p.velocity.x*dt,nextZ=p.z+p.velocity.z*dt,b=this.world.bounds;
  if(nextX>-b.x&&nextX<b.x&&!this.world.blocked(nextX,p.z,p.y+.1,this.mounted?.65:.35)&&this.world.groundAt(nextX,p.z)<p.y+1.05)p.x=nextX;
  if(nextZ>b.minZ&&nextZ<b.maxZ&&!this.world.blocked(p.x,nextZ,p.y+.1,this.mounted?.65:.35)&&this.world.groundAt(p.x,nextZ)<p.y+1.05)p.z=nextZ;
  const ground=this.world.groundAt(p.x,p.z);if(p.y>ground+.02||p.vy>0){p.vy-=dt*17;p.y+=p.vy*dt;if(p.y<=ground){if(p.vy<-17)this.hurtPlayer((Math.abs(p.vy)-15)*35);p.y=ground;p.vy=0;p.jumps=0;}}else{p.y=ground;p.jumps=0;}
  if(this.time-this.lastStep>(sprint?.24:.36)&&moving.lengthSq()>.15&&p.jumps===0&&!a){this.audio.step();this.lastStep=this.time;}
  const nearGrace=this.world.graces.reduce((a,b)=>!a||dist(b,p)<dist(a,p)?b:a,null);if(nearGrace&&dist(nearGrace,p)<35)document.getElementById('sub-location').textContent=nearGrace.label;this.char.position.set(p.x,p.y+(this.mounted?1.22:0),p.z);this.char.rotation.y=p.yaw;animateCharacter(this.char,this.time,moving.lengthSq()>.05?1:0,p.action,this.blocking,this.crouch,this.mounted);
  if(this.mounted){this.horse.position.set(p.x,p.y,p.z);this.horse.rotation.y=p.yaw;this.horse.userData.legs.forEach((l,i)=>l.rotation.x=Math.sin(this.time*10+i%2*Math.PI)*moving.length()*.55);}
  if(this.save.region==='rot'&&Math.abs(p.x)>22){this.statusBuild+=dt*6;if(this.statusBuild>100){this.poison=45;this.statusBuild=0;}}else this.statusBuild=Math.max(0,this.statusBuild-dt*3);if(this.poison>0){this.poison-=dt;this.save.hp-=dt*3;if(this.save.hp<=0)this.die();}
  if(!this.ui.page){const o=this.nearestObject();$('prompt').style.display=o?'block':'none';if(o)$('prompt').innerHTML='<kbd>E</kbd>　'+({grace:'Rest at '+o.label,loot:'Pick up '+o.label,npc:'Talk to '+o.label}[o.type]||o.label);}
  else $('prompt').style.display='none';
 }
 enemyAction(e){
  const p=this.player;let pattern=e.boss?e.boss.patterns[e.attackIndex++%e.boss.patterns.length]:e.kind==='knight'?'thrust':e.attackIndex++%3===2?'combo':'sweep';
  if(e.boss&&e.phase===1&&['meteor','nihil','aeonia','holycombo'].includes(pattern))pattern=e.boss.patterns[0];
  const slow=['delay','hammer','gravity','meteor','waterfowl','eruption','nihil','avalanche','aeonia','fissure','deathstorm'].includes(pattern);
  e.action={type:'attack',pattern,time:0,total:slow?2.8:2,windup:slow?1.3:.7,active:.3,hit:false,fired:false,aim:{x:p.x,z:p.z,y:p.y},yaw:e.yaw};
  const ranged=['dagger','sorcery','stars','beam','moon','greatbow','arrow','fireorb','skulls','boulder','blackblade','blood','rain','holyflame','bloodflame','spiritflame','flame','blackflame'].includes(pattern);
  if(ranged){e.action.ranged=true;e.action.total=2.3;e.action.windup=1;}
  if(['stomp','hammer','gravity','meteor','lightning','frost','lava','avalanche','eruption','aeonia','fissure','deathstorm','nihil','rings'].includes(pattern)){
   e.action.area=true;const target=['lightning','meteor','aeonia','eruption','deathstorm','fissure'].includes(pattern)?p:e;const radius={stomp:5,hammer:4,gravity:7,meteor:6,lightning:3,frost:6,lava:7,avalanche:7,eruption:5,aeonia:7,fissure:4,deathstorm:5,nihil:10,rings:6}[pattern];this.hazard(target.x,target.z,radius,e.action.windup,(e.boss?95:40)+(e.phase-1)*25,['frost'].includes(pattern)?0x95dbe2:['gravity','meteor'].includes(pattern)?0xa688d3:['nihil','lava','aeonia'].includes(pattern)?0xe65c3b:0xeaca85,'magic',e);
   if(['lightning','eruption','deathstorm'].includes(pattern))for(let i=0;i<3;i++)this.hazard(p.x+(Math.random()-.5)*12,p.z+(Math.random()-.5)*12,2.4,e.action.windup+.25+i*.25,80,pattern==='deathstorm'?0xdd5748:0xffd982,'magic',e);
  }
  if(['rush','leap','roll','serpent','waterfowl','teleport','grab'].includes(pattern))e.action.dash=true;
  if(pattern==='waterfowl'){e.action.total=3.5;e.action.windup=1.2;e.action.active=1.5;}
  if(pattern==='teleport'){e.x=p.x+Math.sin(p.yaw)*4;e.z=p.z+Math.cos(p.yaw)*4;this.spark(e.x,e.y+1,e.z,0xf6dc8a,30);}
 }
 fireEnemyAttack(e,a){const p=this.player,pat=a.pattern,color=pat.includes('flame')||pat==='blood'||pat==='fireorb'?0xeb7546:pat==='blackblade'?0x9c3851:pat==='dagger'||pat==='rain'?0xfbe8a4:0x91dce5,damage=e.boss?65+(e.phase-1)*20:35;
  if(a.ranged){let count=['stars','rain','skulls'].includes(pat)?5:['sorcery','blackblade'].includes(pat)?3:1;for(let i=0;i<count;i++){const offset=(i-(count-1)/2)*.6;this.projectile(e.x+offset,e.y+(e.boss?.scale||1)*1.5+(pat==='rain'?4:0),e.z,a.aim,{speed:pat==='beam'||pat==='arrow'?30:pat==='moon'?5:13,damage:pat==='beam'?120:damage,color,radius:pat==='moon'?.9:pat==='boulder'?.55:.19,owner:'enemy',homing:pat==='stars',kind:'magic'});}this.audio.tone(180,.45,'sine',.05,510);}
  if(pat==='summon'){if(!this.world.enemies.some(n=>n.summoned&&!n.dead)){for(const s of [-1,1]){const n=this.world.enemy('summon-'+this.time+'-'+s,e.x+s*4,e.z+2,'soldier');n.hp=n.maxHp=110;n.aggro=true;n.summoned=true;}}}
 }
 updateEnemies(dt){
  const p=this.player;let bossActive=null;
  for(const e of this.world.enemies){
   if(e.requires&&!this.save.defeated.includes(e.requires)){e.mesh.visible=false;continue;}if(e.dead){e.mesh.rotation.z=lerp(e.mesh.rotation.z,Math.PI/2,dt*3);e.mesh.position.y=lerp(e.mesh.position.y,e.y-.3,dt);if(e.mesh.rotation.z>1.5)e.mesh.visible=false;continue;}e.mesh.visible=dist(e,p)<85;if(!e.mesh.visible&&!e.aggro)continue;
   const distance=dist(e,p);if(e.boss&&e.aggro)bossActive=e;
   if(this.resting)continue;
   e.hitFlash=Math.max(0,e.hitFlash-dt);if(e.stagger>0){e.stagger-=dt;e.mesh.rotation.x=Math.sin(Math.min(1,e.stagger)*Math.PI)*.18;animateCharacter(e.mesh,this.time,0,{type:'stun',time:0,total:1});continue;}e.mesh.rotation.x=0;
   const perception=this.crouch?5:e.boss?25:12;const face=Math.abs(angleDelta(e.yaw,Math.atan2(-(p.x-e.x),-(p.z-e.z))));
   if(!e.aggro&&distance<perception&&(face<1.6||distance<5||this.keys.has('ShiftLeft'))&&this.lineClear(e,p))e.aggro=true;
   if(e.aggro&&(dist(e,e.home)>75||distance>68)){e.aggro=false;e.action=null;e.hp=e.maxHp;e.phase=1;}
   if(e.boss&&e.phase===1&&e.boss.phase&&e.hp/e.maxHp<e.boss.phase){e.phase=2;e.action=null;e.timer=.8;this.spark(e.x,e.y+2,e.z,0xe9bc87,40);this.ui.toast(e.bossId==='malenia'?'Malenia, Goddess of Rot':e.bossId==='godfrey'?'Hoarah Loux, Warrior':e.bossId==='maliketh'?'Maliketh unleashes Destined Death':e.bossId==='godrick'?'Godrick unleashes dragonfire':'The battle intensifies',2400);}
   let moving=false;
   if(e.action){const a=e.action;a.time+=dt;if(a.time>=a.windup&&!a.fired){a.fired=true;this.fireEnemyAttack(e,a);}
    if(a.dash&&a.time>a.windup&&a.time<a.windup+(a.pattern==='waterfowl'?1.45:.45)){
     const dx=p.x-e.x,dz=p.z-e.z,len=Math.hypot(dx,dz)||1,speed=a.pattern==='waterfowl'?8:11;e.x+=dx/len*dt*speed;e.z+=dz/len*dt*speed;e.yaw=Math.atan2(-dx,-dz);moving=true;
    }
    if(!a.ranged&&!a.area&&a.time>a.windup&&a.time<a.windup+a.active&&!a.hit){const reach=e.boss?Math.max(3,e.boss.scale*1.8):e.kind==='knight'?3.5:2.5;const arc=a.pattern==='sweep'||a.pattern==='combo'||a.pattern==='axecombo'?2.2:1.3;const ang=Math.abs(angleDelta(e.yaw,Math.atan2(-(p.x-e.x),-(p.z-e.z))));if(distance<reach&&ang<arc&&this.lineClear(e,p)){a.hit=true;const landed=this.hurtPlayer(e.boss?75+e.phase*15:e.kind==='knight'?61:39,e);if(e.boss?.heal&&landed)e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.025);}}
    if(['combo','axecombo','holycombo','waterfowl'].includes(a.pattern)&&a.hit&&a.time>a.windup+.4){if(!a.second){a.second=true;a.hit=false;a.active+=.6;a.windup+=.45;}}
    if(a.time>=a.total){e.action=null;e.timer=e.boss?.heal?.5:e.boss?.phase?.8:1.1+Math.random()*.5;}
   }else if(e.aggro){e.yaw=lerpAngle(e.yaw,Math.atan2(-(p.x-e.x),-(p.z-e.z)),dt*6);e.timer-=dt;const want=e.boss&&e.boss.patterns.some(x=>['sorcery','beam','stars'].includes(x))?8:e.boss?3.5:2.1;
    if(distance>want){const dx=(p.x-e.x)/distance,dz=(p.z-e.z)/distance,speed=e.boss?2.5:2.15;const nx=e.x+dx*dt*speed,nz=e.z+dz*dt*speed;if(!this.world.blocked(nx,e.z,e.y+.2,e.radius*.7))e.x=nx;if(!this.world.blocked(e.x,nz,e.y+.2,e.radius*.7))e.z=nz;moving=true;}else if(e.timer<=0){this.enemyAction(e);}
   }else{e.timer-=dt;const tx=e.home.x+Math.sin(this.time*.13+e.home.z)*2.2,tz=e.home.z+Math.cos(this.time*.11+e.home.x)*2.2,d=Math.hypot(tx-e.x,tz-e.z);if(d>.4){const nx=e.x+(tx-e.x)/d*dt*.65,nz=e.z+(tz-e.z)/d*dt*.65;if(!this.world.blocked(nx,nz,e.y+.1,e.radius*.65)){e.x=nx;e.z=nz;e.yaw=Math.atan2(-(tx-e.x),-(tz-e.z));moving=true;}}}
   e.y=this.world.groundAt(e.x,e.z);e.mesh.position.set(e.x,e.y,e.z);e.mesh.rotation.y=e.yaw;animateCharacter(e.mesh,this.time,moving?1:0,e.action?{...e.action,type:'attack'}:null);
  }
  $('boss-hud').style.display=bossActive?'block':'none';if(bossActive){$('boss-name').textContent=bossActive.boss.name;$('boss-health').style.width=Math.max(0,bossActive.hp/bossActive.maxHp*100)+'%';}
  if(this.spirit){const s=this.spirit,enemy=this.world.enemies.filter(e=>e.aggro&&!e.dead).sort((a,b)=>dist(a,s)-dist(b,s))[0];if(enemy){const d=dist(s,enemy);if(d>2){s.x+=(enemy.x-s.x)/d*dt*6;s.z+=(enemy.z-s.z)/d*dt*6;}s.timer-=dt;if(s.timer<=0&&d<3){this.hurtEnemy(enemy,35,6);s.timer=1.7;s.hp-=12;}s.mesh.position.set(s.x,this.world.groundAt(s.x,s.z),s.z);s.mesh.rotation.y=Math.atan2(-(enemy.x-s.x),-(enemy.z-s.z));animateCharacter(s.mesh,this.time,1,null);}if(s.hp<=0){this.scene.remove(s.mesh);this.spirit=null;}}
 }
 updateEffects(dt){
  const p=this.player;
  for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.time+=dt;const pos=e.mesh.geometry.attributes.position;e.vel.forEach((v,j)=>{v.y-=dt*9;pos.setXYZ(j,pos.getX(j)+v.x*dt,pos.getY(j)+v.y*dt,pos.getZ(j)+v.z*dt);});pos.needsUpdate=true;e.mesh.material.opacity=Math.max(0,1-e.time/e.total);if(e.time>e.total){this.scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();this.effects.splice(i,1);}}
  for(let i=this.projectiles.length-1;i>=0;i--){const a=this.projectiles[i];a.age+=dt;a.life-=dt;if(a.homing&&a.owner==='enemy')a.dir.lerp(V(p.x-a.mesh.position.x,p.y+1-a.mesh.position.y,p.z-a.mesh.position.z).normalize(),dt*.7).normalize();const before=a.mesh.position.clone();a.mesh.position.addScaledVector(a.dir,a.speed*dt);const v=a.mesh.position;let hit=false;
   if(a.owner==='player'){for(const e of this.world.enemies){if(!e.dead&&e.mesh.visible&&Math.hypot(v.x-e.x,v.z-e.z)<e.radius+a.radius+.3&&Math.abs(v.y-e.y-1)<(e.boss?.scale||1)*1.5){this.hurtEnemy(e,a.damage,15);hit=true;break;}}}else if(Math.hypot(v.x-p.x,v.z-p.z)<.45+a.radius&&Math.abs(v.y-p.y-1)<1){this.hurtPlayer(a.damage,{x:before.x,z:before.z},a.kind);hit=true;}
   if(this.world.blocked(v.x,v.z,v.y,.08)||v.y<this.world.groundAt(v.x,v.z))hit=true;
   if(hit||a.life<=0){if(hit)this.spark(v.x,v.y,v.z,a.mesh.material.color,9);this.scene.remove(a.mesh);a.mesh.geometry.dispose();a.mesh.material.dispose();this.projectiles.splice(i,1);}
  }
  for(let i=this.hazards.length-1;i>=0;i--){const h=this.hazards[i];h.time+=dt;if(h.time<h.delay){h.mesh.material.opacity=.2+Math.sin(h.time*12)*.18;h.mesh.scale.setScalar(.9+.1*h.time/h.delay);}else if(!h.hit){h.hit=true;this.spark(h.x,this.world.groundAt(h.x,h.z)+.2,h.z,h.color,40);if(dist(h,p)<h.r&&p.y<this.world.groundAt(p.x,p.z)+(h.kind==='physical'?.55:3))this.hurtPlayer(h.damage,h.owner,h.kind);this.shake=.08;}else{h.mesh.material.opacity=Math.max(0,.7-(h.time-h.delay)*1.4);}if(h.time>h.delay+.7){this.scene.remove(h.mesh);h.mesh.geometry.dispose();h.mesh.material.dispose();this.hazards.splice(i,1);}}
 }
 updateCamera(dt){const p=this.player;if(!this.ui.page&&this.playing){if(this.keys.has('ArrowLeft'))this.cameraYaw+=dt*1.6;if(this.keys.has('ArrowRight'))this.cameraYaw-=dt*1.6;if(this.keys.has('ArrowUp'))this.cameraPitch=clamp(this.cameraPitch-dt*.8,-.25,1);if(this.keys.has('ArrowDown'))this.cameraPitch=clamp(this.cameraPitch+dt*.8,-.25,1);}
  if(this.locked){if(this.locked.dead||dist(this.locked,p)>42)this.locked=null;else if(!this.pointer.down)this.cameraYaw=lerpAngle(this.cameraYaw,Math.atan2(-(this.locked.x-p.x),-(this.locked.z-p.z)),dt*3.5);}
  const target=V(p.x,p.y+1.45+(this.mounted?.9:0),p.z),distance=this.cameraDistance;const offset=V(Math.sin(this.cameraYaw)*distance*Math.cos(this.cameraPitch),.05+Math.sin(this.cameraPitch)*distance,Math.cos(this.cameraYaw)*distance*Math.cos(this.cameraPitch));
  let desired=target.clone().add(offset);for(let t=.12;t<=1;t+=.07){const at=target.clone().lerp(desired,t);if(this.world.blocked(at.x,at.z,at.y,.16)){desired=target.clone().lerp(desired,Math.max(.15,t-.1));break;}}
  desired.y=Math.max(desired.y,this.world.groundAt(desired.x,desired.z)+.5);if(!this.cameraInitialized){this.camera.position.copy(desired);this.lookAt.copy(target);this.cameraInitialized=true;}else{this.camera.position.lerp(desired,1-Math.exp(-dt*10));this.lookAt.lerp(target,1-Math.exp(-dt*12));}
  this.shake=Math.max(0,this.shake-dt*.7);if(this.shake){this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.position.y+=(Math.random()-.5)*this.shake;}
  this.camera.lookAt(this.lookAt);this.sky.position.copy(this.camera.position);this.char.visible=this.camera.position.distanceTo(target)>1.4;
  this.sun.position.set(p.x+80,p.y+110,p.z-55);this.sun.target.position.set(p.x,p.y,p.z);this.sun.target.updateMatrixWorld();
 }
 makeMotes(){const pos=[];for(let i=0;i<200;i++)pos.push((Math.random()-.5)*80,Math.random()*20,(Math.random()-.5)*80);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));this.motes=new THREE.Points(g,new THREE.PointsMaterial({color:0xe1cc81,size:.065,transparent:true,opacity:.65,depthWrite:false}));this.scene.add(this.motes);}
 updateEnvironment(dt){const day=this.save.day,night=day>.7?Math.min(1,(day-.7)*5):day<.12?(1-day/.12)*.7:0;this.sky.material.uniforms.time.value=this.time;this.sky.material.uniforms.night.value=night;const indoor=this.regionInfo.indoor,underground=this.regionInfo.underground;
  this.ambient.intensity=indoor?1.1:underground?1.2:2.0-night*1.25;this.sun.intensity=indoor?.9:underground?.3:3.15-night*2.8;this.sun.color.set(indoor?0xf6c587:night>.3?0xa3c6dd:0xffe5b2);this.rim.intensity=underground?.6:.8;this.renderer.toneMappingExposure=indoor?1.1:1.05;
  if(this.playing&&!this.resting)this.save.day=(day+dt/1700)%1;
  if(this.motes){this.motes.position.set(this.player.x,this.player.y,this.player.z);this.motes.rotation.y=this.time*.012;const a=this.motes.geometry.attributes.position;for(let i=0;i<a.count;i++){let y=a.getY(i)-dt*.24;if(y<0)y=20;a.setY(i,y);}a.needsUpdate=true;this.motes.visible=!indoor;}
 }
 labels(dt){for(let i=this.damageLabels.length-1;i>=0;i--){const d=this.damageLabels[i];d.time+=dt;const v=V(d.x,d.y+d.time*.8,d.z).project(this.camera);d.el.style.left=(v.x*.5+.5)*innerWidth+'px';d.el.style.top=(-v.y*.5+.5)*innerHeight+'px';d.el.style.opacity=String(1-d.time/1.3);if(d.time>1.3){d.el.remove();this.damageLabels.splice(i,1);}}
  for(const e of this.world.enemies){if(!e.healthEl){e.healthEl=document.createElement('div');e.healthEl.className='enemy-health';e.healthEl.innerHTML='<i></i>';$('enemy-labels').appendChild(e.healthEl);}const visible=!e.dead&&!e.boss&&e.aggro&&e.mesh.visible&&dist(e,this.player)<25;e.healthEl.style.display=visible?'block':'none';if(visible){const v=V(e.x,e.y+2.4,e.z).project(this.camera);e.healthEl.style.display=v.z<1?'block':'none';e.healthEl.style.left=(v.x*.5+.5)*innerWidth+'px';e.healthEl.style.top=(-v.y*.5+.5)*innerHeight+'px';e.healthEl.firstChild.style.width=Math.max(0,e.hp/e.maxHp*100)+'%';}}
  $('lock-marker').style.display=this.locked?'block':'none';if(this.locked){const e=this.locked,v=V(e.x,e.y+(e.boss?.scale||1)*1.5,e.z).project(this.camera);$('lock-marker').style.left=(v.x*.5+.5)*innerWidth+'px';$('lock-marker').style.top=(-v.y*.5+.5)*innerHeight+'px';}
 }
 drawIcons(){if(!this.m)return;const draw=(id,kind)=>{const canvas=$(id),ctx=canvas.getContext('2d');ctx.clearRect(0,0,96,96);ctx.save();ctx.translate(48,48);ctx.shadowColor='#000';ctx.shadowBlur=5;const grad=ctx.createLinearGradient(-20,-30,24,34);grad.addColorStop(0,'#dde0d2');grad.addColorStop(.3,'#526561');grad.addColorStop(.55,'#b2b7a3');grad.addColorStop(1,'#2f4140');ctx.fillStyle=grad;ctx.strokeStyle='#b7ae8b';ctx.lineWidth=1.5;
  if(kind==='flask'){ctx.fillStyle=this.flaskType==='hp'?'#a95827':'#2d7490';ctx.beginPath();ctx.moveTo(-8,-25);ctx.lineTo(-8,-8);ctx.bezierCurveTo(-31,7,-24,33,0,35);ctx.bezierCurveTo(26,33,31,7,8,-8);ctx.lineTo(8,-25);ctx.closePath();ctx.fill();ctx.strokeStyle='#c9b474';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle='#bdaf79';ctx.fillRect(-11,-32,22,9);for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(0,12,14-i*2,18-i*2,.7,0,6.28);ctx.strokeStyle='#dfc57e';ctx.lineWidth=.7;ctx.stroke();}}
  else if(kind==='shield'){ctx.beginPath();ctx.moveTo(-26,-31);ctx.lineTo(26,-31);ctx.quadraticCurveTo(31,15,0,37);ctx.quadraticCurveTo(-31,15,-26,-31);ctx.fill();ctx.stroke();ctx.strokeStyle='#b59f67';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-25);ctx.lineTo(0,29);ctx.moveTo(-19,-10);ctx.lineTo(19,-10);ctx.stroke();}
  else if(kind==='spell'){ctx.shadowColor='#7fdae9';ctx.shadowBlur=15;ctx.fillStyle='#72c0cc';ctx.beginPath();ctx.moveTo(0,-28);ctx.lineTo(11,0);ctx.lineTo(0,30);ctx.lineTo(-12,0);ctx.closePath();ctx.fill();ctx.strokeStyle='#b3edf2';ctx.stroke();}
  else{ctx.rotate(.55);ctx.fillStyle='#6a4c2e';ctx.fillRect(-3,18,6,17);ctx.fillStyle=grad;ctx.fillRect(-17,13,34,5);ctx.beginPath();ctx.moveTo(-5,13);ctx.lineTo(-4,-25);ctx.lineTo(0,-39);ctx.lineTo(4,-25);ctx.lineTo(5,13);ctx.closePath();ctx.fill();ctx.stroke();}ctx.restore();};draw('flask-icon','flask');draw('shield-icon','shield');draw('weapon-icon','weapon');draw('spell-icon','spell');}
 snapshot(){return{ready:!!this.world,playing:this.playing,region:this.save.region,position:{x:this.player.x,y:this.player.y,z:this.player.z},hp:this.save.hp,maxHP:maxHP(this.save),fp:this.save.fp,stamina:this.stamina,runes:this.save.runes,action:this.player.action?{type:this.player.action.type,phase:attackPhase(this.player.action),time:this.player.action.time}:null,inCombat:this.inCombat(),panel:this.ui.page,defeated:[...this.save.defeated],checkpoint:{...this.save.checkpoint},deathRunes:this.save.deathRunes,fragments:[...this.save.fragments],enemies:this.world.enemies.map(e=>({id:e.id,x:e.x,z:e.z,hp:e.hp,dead:e.dead,aggro:e.aggro})),performance:{fps:this.fps,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures}};}
 tick(){requestAnimationFrame(()=>this.tick());const rawDelta=this.clock.getDelta(),dt=Math.min(rawDelta,.05);this.time+=dt;this.frameCount++;this.accum+=rawDelta;if(this.accum>.5){this.fps=Math.round(this.frameCount/this.accum);this.accum=0;this.frameCount=0;}
  if(this.playing){if(this.deadTime>0){this.deadTime-=dt;this.char.rotation.z=lerp(this.char.rotation.z,Math.PI/2,dt*2);if(this.deadTime<=0){this.char.rotation.z=0;this.respawn();}}else{if(!this.resting)this.updatePlayer(dt);this.updateEnemies(dt);if(!this.resting)this.updateEffects(dt);this.save.playtime+=dt;if(this.time-this.lastSave>8){this.lastSave=this.time;this.saveNow();}}this.ui.update();}
  this.world.update(this.time,dt);this.world.updateGroundCover?.(this.player.x,this.player.z);this.updateEnvironment(dt);this.updateCamera(dt);this.labels(dt);this.renderer.render(this.scene,this.camera);
 }
}
function lerpAngle(a,b,t){return a+angleDelta(b,a)*clamp(t,0,1);}
try{const game=new Game();game.init().catch(e=>{$('load-text').textContent='Could not start the game: '+e.message;console.error(e);});}catch(e){$('load-text').textContent='WebGL could not start. Enable hardware acceleration in your browser. '+e.message;console.error(e);}

