import {ATTRS,CLASSES,WEAPONS,REGIONS,BOSSES,CONTROLS,ENDINGS,REFERENCE} from './data.js';
import {maxHP,maxFP,maxStamina,equipLoad,loadRatio,levelCost,weaponDamage,levelUp,upgradeWeapon,seeded} from './core.js';
const $=id=>document.getElementById(id);
export const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,detail='',disabled=false)=>`<button data-action="${action}" ${disabled?'disabled':''}>${label}${detail?`<small>${detail}</small>`:''}</button>`;
const row=(label,value)=>`<div class="stat-row"><span>${label}</span><b>${value}</b></div>`;
export class UI{
 constructor(game){this.g=game;this.page=null;this.layer='surface';this.selectedClass='Vagabond';this.panel=$('panel');this.content=$('panel-content');this.toastTimer=null;this.inspectWeapon=null;
  $('menu-button').onclick=()=>this.open('equipment');$('help-button').onclick=()=>this.open('controls');$('close-panel').onclick=()=>this.close();$('continue').onclick=()=>game.start();$('new-game').onclick=()=>this.open('creation');$('title-controls').onclick=()=>this.open('controls');$('title-coverage').onclick=()=>this.open('coverage');
  this.panel.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)this.action(b.dataset.action);});
 }
 showTitle(){this.close();$('title').classList.remove('hidden');$('hud').style.opacity='0';$('continue').textContent=this.g.hasSave?'Continue':'Enter the Lands Between';}
 hideTitle(){$('title').classList.add('hidden');$('hud').style.opacity='1';}
 toast(text,ms=3500){clearTimeout(this.toastTimer);$('toast').textContent=text;$('toast').classList.add('show');this.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),ms);}
 discovery(text,ms=4500){$('discovery').querySelector('h2').textContent=text;$('discovery').classList.add('show');clearTimeout(this.discoverTimer);this.discoverTimer=setTimeout(()=>$('discovery').classList.remove('show'),ms);}
 close(){this.page=null;this.panel.classList.add('hidden');this.g.resting=false;this.g.keys.clear();}
 open(page){this.g.keys.clear();this.g.blocking=false;this.page=page;this.panel.classList.remove('hidden');this.render();}
 render(){
  const s=this.g.save,p=this.page;const titles={equipment:'Equipment',inventory:'Inventory',status:'Status',crafting:'Item crafting',map:'Map',journal:'Journey',settings:'System',controls:'Controls',coverage:'Build coverage',creation:'Create a Tarnished',grace:this.g.currentGrace?.label||'Site of Grace',merchant:this.g.npcName||'Merchant',smith:'Strengthen armament',dialogue:this.g.npcName||'Dialogue',ending:'Journey’s end',level:'Level up'};
  $('panel-title').textContent=titles[p]||p;$('panel-eyebrow').textContent=p==='creation'?'NEW JOURNEY':s.name.toUpperCase();
  const tabs=['equipment','inventory','status','crafting','map','journal','settings'];$('panel-tabs').innerHTML=tabs.includes(p)?tabs.map(x=>`<button data-action="page:${x}" class="${p===x?'active':''}">${titles[x]}</button>`).join(''):'';
  $('panel-footer').textContent=this.g.resting?'Resting at a Site of Grace. Your progress is saved.':p==='coverage'?'Reference target: App 1.10 / Regulation 1.10. See COVERAGE.md and REFERENCES.md.':'Menus do not pause combat. Rest at a Site of Grace to find safety.';
  if(p==='equipment'){
   const w=WEAPONS[s.equipment.weapon];this.content.innerHTML=`<div class="menu-grid"><div><h3>Armaments</h3><div class="item-grid">${s.inventory.weapons.map(id=>`<button class="item-card ${id===s.equipment.weapon?'selected':''}" data-action="equip:${id}"><span>${WEAPONS[id].name}${s.upgrades[id]?' +'+s.upgrades[id]:''}</span><small>${WEAPONS[id].kind} · ${WEAPONS[id].weight} weight</small></button>`).join('')}</div><div class="menu-list" style="margin-top:22px">${btn(s.equipment.shield?'Heater Shield equipped':'Left hand empty','shield')}${btn(s.equipment.twoHand?'Two-handed grip':'One-handed grip','twohand')}${btn(s.equipment.paired?'Paired blades equipped':'Equip paired blades','paired','Paired blades require a second sword in your inventory.')}${btn('Armor: '+s.equipment.armor,'armor')}</div></div><div><h3>${w.name}</h3><p>${w.desc}</p>${row('Physical attack',weaponDamage(s))}${row('Upgrade',`+${s.upgrades[s.equipment.weapon]||0}`)}${row('Required strength / dexterity',w.req.join(' / '))}${row('Weapon skill',s.equipment.ash==='storm'?'Storm Stomp':w.skill)}${row('Equip load',equipLoad(s).toFixed(1))}${row('Load category',loadRatio(s)<.3?'Light':loadRatio(s)<.7?'Medium':loadRatio(s)<1?'Heavy':'Overloaded')}<p class="muted">F casts sorcery while holding a staff. A sacred seal is available from Brother Corhyn.</p>${s.quests.whetstone?`<div class="menu-list">${btn('Ash of War: '+(s.equipment.ash==='storm'?'Storm Stomp':'Default skill'),'ash')}${btn('Affinity: '+s.equipment.affinity,'affinity')}</div>`:''}</div></div>`;
  }else if(p==='inventory'){
   this.content.innerHTML=`<div class="menu-grid"><div><h3>Materials and consumables</h3>${row('Runes',s.runes.toLocaleString())}${row('Smithing stones',s.inventory.stones)}${row('Rowa fruit',s.inventory.flowers)}${row('Golden seeds',s.inventory.seeds)}${row('Sacred tears',s.inventory.tears)}${row('Neutralizing boluses',s.inventory.boluses)}<div class="menu-list" style="margin-top:18px">${btn('Use a bolus','bolus','Removes poison and rot buildup.',!s.inventory.boluses)}</div></div><div><h3>Key items</h3>${Object.entries({key:'Academy Glintstone Key',dectusLeft:'Dectus Medallion, left',dectusRight:'Dectus Medallion, right',secretLeft:'Haligtree Secret Medallion, right',torrent:'Spectral Steed Whistle',whetstone:'Whetstone Knife',spirit:'Spirit Calling Bell',seal:'Finger Seal'}).map(([id,name])=>row(name,s.quests[id]?'Acquired':'Undiscovered')).join('')}${row('Great Runes',s.defeated.filter(x=>BOSSES[x]?.rune).length)}</div></div>`;
  }else if(p==='status'){
   this.content.innerHTML=`<div class="menu-grid"><div><h3>${escapeHTML(s.name)}</h3>${row('Origin',s.className)}${row('Level',s.level)}${ATTRS.map((a,i)=>row(a,s.stats[i])).join('')}</div><div><h3>Character</h3>${row('HP',`${Math.ceil(s.hp)} / ${maxHP(s)}`)}${row('FP',`${Math.ceil(s.fp)} / ${maxFP(s)}`)}${row('Stamina',maxStamina(s))}${row('Physical attack',weaponDamage(s))}${row('Equip load',equipLoad(s).toFixed(1))}${row('Bosses defeated',s.defeated.length)}${row('Journey time',Math.floor(s.playtime/60)+' minutes')}${row('Next level',levelCost(s).toLocaleString()+' runes')}</div></div>`;
  }else if(p==='crafting'){
   this.content.innerHTML=`<div class="menu-grid"><div><h3>Crafting kit</h3><p>Gather rowa fruit along the road, then prepare a remedy.</p><div class="menu-list">${btn('Craft Neutralizing Boluses','craft','3 rowa fruit → 1 bolus',!s.quests.crafting||s.inventory.flowers<3)}</div>${row('Rowa fruit',s.inventory.flowers)}</div><div><p>${s.quests.crafting?'Your crafting kit is ready.':'Purchase a crafting kit from Merchant Kalé at the Church of Elleh.'}</p><p class="muted">The available recipe and its ingredients are a simplified substitute.</p></div></div>`;
  }else if(p==='map'){this.mapView();
  }else if(p==='journal'){
   const q=[['Guidance of Grace',this.g.objective()],['Melina',s.quests.torrent?'Accord accepted. Torrent and leveling are available.':'Meet Melina at the Gatefront Site of Grace.'],['Ranni',s.quests.ranniDone?'The Age of the Stars is available.':s.quests.ranni?'Claim Nokron’s treasure, then follow the river to Astel.':'Seek Caria Manor in northwestern Liurnia.'],['Fia',s.quests.fiaDone?'The Mending Rune of the Death-Prince is yours.':'Seek Fia in Deeproot Depths.'],['Goldmask',s.quests.goldmaskDone?'The Mending Rune of Perfect Order is yours.':'Speak with Corhyn on Altus Plateau and Goldmask in Leyndell.'],['Dung Eater',s.quests.dungDone?'The Mending Rune of the Fell Curse is yours.':'Find the Dung Eater in Leyndell.'],['Frenzied Flame',s.quests.frenzy?'The flame marks you. This ending overrides the others.':'Deep below the capital, a sealed chamber waits.']];
   this.content.innerHTML=`<p class="muted">These quest chains are condensed for this build. Their original dialogue, steps, and failure conditions are not reproduced.</p>${q.map(([a,b])=>`<div class="quest-entry"><b>${a}</b><p>${b}</p></div>`).join('')}<h3 style="margin-top:25px">Defeated foes</h3><p>${s.defeated.map(id=>BOSSES[id].name).join(' · ')||'No major bosses defeated.'}</p>`;
  }else if(p==='settings'){
   this.content.innerHTML=`<div class="menu-grid"><div><h3>Display and sound</h3><div class="field"><label for="quality">Graphics quality</label><select id="quality"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div><div class="field"><label for="volume">Master volume</label><input id="volume" type="range" min="0" max="100" value="${this.g.settings.volume*100}"></div><div class="field"><label for="sensitivity">Camera sensitivity</label><input id="sensitivity" type="range" min="20" max="180" value="${this.g.settings.sensitivity*100}"></div><div class="menu-list">${btn('Toggle full screen','fullscreen')}${btn('Controls','page:controls')}</div></div><div><h3>Save data</h3><p>Progress is saved to this browser on this computer. Export a backup before changing browsers or clearing site data.</p><div class="menu-list">${btn('Save now','save')}${btn('Export save','export')}<label class="action-button">Import a save<input id="import-save" type="file" accept=".json" style="display:block;margin-top:10px;width:100%"></label>${btn('Return to title','title')}</div><p class="muted">Network: offline. Co-op, invasions, bloodstains, and player messages are unavailable.</p></div></div>`;
   $('quality').value=this.g.settings.quality;$('quality').onchange=e=>this.g.setQuality(e.target.value);$('volume').oninput=e=>{this.g.settings.volume=e.target.value/100;this.g.audio.volume(this.g.settings.volume);this.g.saveSettings();};$('sensitivity').oninput=e=>{this.g.settings.sensitivity=e.target.value/100;this.g.saveSettings();};$('import-save').onchange=e=>this.g.importSave(e.target.files[0]);
  }else if(p==='controls'){
   this.content.innerHTML=`<p>Move with WASD. Drag the world to look around, or use the arrow keys. Press J to attack while steering the camera. Lock-on keeps a nearby enemy in view.</p><div class="controls-grid">${CONTROLS.map(([a,b])=>`<div class="control-line"><span>${b}</span><kbd>${a}</kbd></div>`).join('')}</div><p>Watch stamina. Dodge during a swing, block from the front, then press K for a guard counter. A stance break opens an opportunity for a critical strike.</p>`;
  }else if(p==='coverage'){
   this.content.innerHTML=`<h3>A playable interpretation, with substantial limits</h3><p>This is not the complete Elden Ring. It contains a detailed opening Limgrave route and ${Object.keys(REGIONS).length} compressed location scenes, ${Object.keys(BOSSES).length} simplified named encounters, a connected campaign, and six condensed ending branches.</p><table class="coverage-table"><tr><th>Area</th><th>Coverage</th></tr><tr><td>Reference release</td><td>PC / Steam, App 1.10, Regulation 1.10. Official patch identity verified.</td></tr><tr><td>Limgrave</td><td>First Step, Church of Elleh, Gatefront, cellar, Stormgate. Approximate scale, layout, and placements.</td></tr><tr><td>Other locations</td><td>Region-specific condensed scenes. Original full layouts and traversal networks are missing.</td></tr><tr><td>Characters and equipment</td><td>Original procedural substitute meshes. No extracted game assets or original animations.</td></tr><tr><td>Combat</td><td>Timed attacks, active hit tests, recovery, stamina, dodge windows, blocking, parrying, stance, magic. Timings and formulas are unverified substitutes.</td></tr><tr><td>Progression</td><td>Leveling, upgrades, merchants, flask allocation, save data, rune recovery, travel gates, condensed quests and endings.</td></tr><tr><td>Missing</td><td>Most optional encounters, exact boss models and arenas, complete interiors, full inventory, full quest scripts, voice acting, original music, multiplayer, controller support.</td></tr><tr><td>Expansion</td><td>Shadow of the Erdtree and Nightreign excluded.</td></tr></table><p>Full details, references, asset licenses, and test results are included in the delivered files.</p>`;
  }else if(p==='creation'){
   this.content.innerHTML=`<div class="field"><label for="character-name">Name</label><input id="character-name" maxlength="24" value="Tarnished"></div><h3>Choose an origin</h3><div class="class-grid">${Object.keys(CLASSES).map(c=>`<button data-action="class:${c}" class="${c===this.selectedClass?'active':''}">${c}<small style="display:block;font-size:11px;color:#a8b09a">Level ${CLASSES[c].level}</small></button>`).join('')}</div><div class="menu-grid" style="margin-top:24px"><div><h3>${this.selectedClass}</h3><p>${CLASSES[this.selectedClass].desc}</p><div class="field"><label for="cape-color">Cloak color</label><input id="cape-color" type="color" value="#685144"></div></div><div>${ATTRS.map((a,i)=>row(a,CLASSES[this.selectedClass].stats[i])).join('')}</div></div><p class="muted">Appearance is limited to cloak color and armor presets. A new journey replaces the current browser save.</p><button class="action-button" data-action="begin">Begin journey</button>`;
  }else if(p==='grace'){
   this.content.innerHTML=`<div class="menu-grid"><div class="menu-list">${btn('Level up','page:level',s.quests.torrent?'Spend runes to increase an attribute.':'Meet Melina at Gatefront first.',!s.quests.torrent)}${btn('Flasks: '+s.flasks.crimson+' crimson / '+(s.flasks.total-s.flasks.crimson)+' cerulean','allocate','Move one charge from crimson to cerulean. Cycles back at zero.')}${btn('Add charge to flask','flaskcharge','Consume a Golden Seed.',s.inventory.seeds<1||s.flasks.total>=14)}${btn('Increase amount replenished','flaskupgrade','Consume a Sacred Tear.',s.inventory.tears<1)}${btn('Pass time','time','Cycle morning, afternoon, and night.')}${btn('Travel to Roundtable Hold','roundtable','Available after accepting Melina’s accord.',!s.quests.torrent)}${btn('Memorize spell','spell','Cycle the selected spell.')}${btn('Leave','close')}</div><div><h3>${this.g.currentGrace?.label||'Site of Grace'}</h3><p>HP, FP, and flasks are restored. Ordinary enemies return when you rest. Defeated bosses remain defeated.</p>${row('Runes held',s.runes.toLocaleString())}${row('Next level',levelCost(s).toLocaleString())}${row('Flask potency','+'+s.flasks.level)}${row('Time',s.day<.33?'Morning':s.day<.68?'Afternoon':'Night')}</div></div>`;
  }else if(p==='level'){
   this.content.innerHTML=`<div class="menu-grid"><div><h3>Level ${s.level}</h3><div class="menu-list">${ATTRS.map((a,i)=>btn(a+'　'+s.stats[i]+' → '+(s.stats[i]+1),'level:'+i,'',s.runes<levelCost(s)||s.stats[i]>=99)).join('')}</div></div><div>${row('Runes held',s.runes.toLocaleString())}${row('Runes required',levelCost(s).toLocaleString())}<p>Choose an attribute to spend the displayed number of runes.</p></div></div>`;
  }else if(p==='smith'){
   const lv=s.upgrades[s.equipment.weapon]||0;this.content.innerHTML=`<div class="menu-grid"><div><h3>${WEAPONS[s.equipment.weapon].name} +${lv}</h3><div class="menu-list">${btn('Strengthen to +'+(lv+1),'upgrade',`${350*(lv+1)} runes and ${1+Math.floor(lv/3)} smithing stones`,lv>=12||s.runes<350*(lv+1)||s.inventory.stones<1+Math.floor(lv/3))}${btn('Change equipped weapon','page:equipment')}</div></div><div>${row('Runes held',s.runes)}${row('Smithing stones held',s.inventory.stones)}<p class="muted">This build uses a simplified +12 upgrade track with one stone type.</p></div></div>`;
  }else if(p==='merchant'){
   this.content.innerHTML=`<div class="menu-grid"><div class="menu-list">${btn('Crafting Kit','buy:crafting','300 runes',s.quests.crafting||s.runes<300)}${btn('Smithing Stone','buy:stones','200 runes',s.runes<200)}${btn('Sacred Tear','buy:tears','900 runes',s.runes<900)}${btn('Golden Seed','buy:seeds','1,200 runes',s.runes<1200)}${btn('Finger Seal','buy:seal','600 runes',s.quests.seal||s.runes<600)}${btn('Uchigatana','buy:katana','1,600 runes',s.inventory.weapons.includes('katana')||s.runes<1600)}${btn('Leave','close')}</div><div><h3>${escapeHTML(this.g.npcName||'Merchant')}</h3>${row('Runes held',s.runes.toLocaleString())}<p>Choose an item to purchase.</p><p class="muted">Stock and prices are simplified for this build.</p></div></div>`;
  }else if(p==='dialogue'){
   const d=this.g.dialogue;this.content.innerHTML=`<div class="menu-grid"><div><h3>${escapeHTML(this.g.npcName)}</h3><p>${d.text}</p><div class="menu-list">${d.options.map(o=>btn(o.label,'dialogue:'+o.id,o.detail||'',o.disabled)).join('')}${btn('Leave','close')}</div></div><div><p class="muted">Dialogue is newly written and quest steps are condensed.</p></div></div>`;
  }else if(p==='ending'){
   const done=s.ending,available=ENDINGS.filter(e=>s.quests.frenzy?e.id==='frenzy':e.id!=='frenzy'&&(!e.requires||s.quests[e.requires]));
   this.content.innerHTML=done?`<div class="ending"><span class="tiny">JOURNEY COMPLETE</span><h3>${ENDINGS.find(e=>e.id===done)?.name}</h3><p style="margin:0 auto">${escapeHTML(s.name)}, your journey through this interpretation of the Lands Between has reached its end.</p><p style="margin:20px auto" class="muted">This ending is a text presentation. The original ending cinematics are not reproduced.</p><button class="action-button" data-action="close">Return to the Lands Between</button></div>`:`<div class="ending"><h3>Touch fractured Marika</h3><p style="margin:10px auto 30px">Choose the age that will follow.</p><div class="menu-list" style="margin:0 auto">${available.map(e=>btn(e.name,'ending:'+e.id)).join('')}</div></div>`;
  }
 }
 mapView(){
  const s=this.g.save;this.content.innerHTML=`<div class="map-tools">${btn('Surface','layer:surface')}${btn('Underground','layer:underground')}<span class="muted" style="margin-left:auto;font-size:12px">Compressed travel map · ${s.fragments.length} fragments</span></div><div class="map-layout"><canvas class="map-canvas" id="map-art" width="1200" height="850" aria-label="Map of discovered regions"></canvas><div class="map-list"><p style="margin:0 0 15px">${REGIONS[s.region].name}</p>${Object.entries(s.discovered).filter(([id])=>REGIONS[id].layer===this.layer).map(([id,graces])=>`<button data-action="travel:${id}" class="${id===s.region?'current':''}">${REGIONS[id].name}<small>${graces.length} discovered Sites of Grace</small></button>`).join('')}<p class="muted" style="font-size:12px;margin-top:24px">Select a discovered region to travel to its first Site of Grace. Combat blocks travel.</p></div></div>`;
  const canvas=$('map-art'),ctx=canvas.getContext('2d'),w=1200,h=850,rand=seeded(44);
  ctx.fillStyle='#7b806e';ctx.fillRect(0,0,w,h);
  // Cartographic parchment and contour strokes, intentionally a diagram of travel nodes.
  const land=[[460,810],[402,741],[454,652],[393,597],[326,550],[207,471],[183,389],[264,292],[275,179],[374,116],[514,160],[633,153],[650,86],[754,50],[851,122],[873,246],[763,320],[850,460],[938,570],[867,676],[698,704],[604,653],[570,759],[600,817]];
  ctx.beginPath();land.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle='#b7aa7d';ctx.fill();ctx.strokeStyle='#5f644d';ctx.lineWidth=3;ctx.stroke();
  for(let i=0;i<14000;i++){ctx.fillStyle=`rgba(${rand()<.5?'41,45,28':'234,218,166'},${rand()*.07})`;ctx.fillRect(rand()*w,rand()*h,2+rand()*3,1);}
  for(let i=0;i<100;i++){const x=220+rand()*700,y=100+rand()*610;ctx.strokeStyle='#625e4533';ctx.lineWidth=.5;ctx.beginPath();ctx.ellipse(x,y,15+rand()*36,5+rand()*13,rand()*3,0,6.28);ctx.stroke();}
  const sx=id=>REGIONS[id].map[0]*11+40,sy=id=>REGIONS[id].map[1]*8.1;
  for(const [id,r]of Object.entries(REGIONS)){if(r.layer!==this.layer)continue;for(const e of r.exits){if(REGIONS[e.to].layer!==this.layer||(!s.discovered[id]&&!s.discovered[e.to]))continue;ctx.strokeStyle='#7e693e90';ctx.setLineDash([5,5]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(sx(id),sy(id));ctx.lineTo(sx(e.to),sy(e.to));ctx.stroke();}}
  ctx.setLineDash([]);
  for(const [id,r]of Object.entries(REGIONS)){if(r.layer!==this.layer)continue;const x=sx(id),y=sy(id),known=!!s.discovered[id],fragment=s.fragments.includes(id);if(!known&&!fragment)continue;ctx.fillStyle=id===s.region?'#f5db91':'#ece0ab';ctx.strokeStyle='#6c5630';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,id===s.region?8:5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='17px Georgia';ctx.textAlign='center';ctx.fillStyle='#302e22';ctx.fillText(r.name,x,y+24);}
  ctx.font='26px Georgia';ctx.textAlign='left';ctx.fillStyle='#e0d4a5';ctx.fillText(this.layer==='surface'?'The Lands Between':'Beneath the Lands Between',35,47);ctx.font='16px Georgia';ctx.fillText('N',1110,80);ctx.beginPath();ctx.moveTo(1110,91);ctx.lineTo(1110,135);ctx.strokeStyle='#ddcb94';ctx.stroke();
  canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*w,y=(e.clientY-r.top)/r.height*h;const id=Object.keys(s.discovered).find(id=>REGIONS[id].layer===this.layer&&Math.hypot(sx(id)-x,sy(id)-y)<35);if(id)this.g.fastTravel(id);};
 }
 action(a){
  const [type,value]=a.split(':'),g=this.g,s=g.save;
  if(type==='page'){if(value==='map'&&g.inCombat())return this.toast('Cannot open the map while in combat.');this.open(value);return;}
  if(type==='close'){this.close();return;}
  if(type==='class'){const name=$('character-name')?.value;const color=$('cape-color')?.value;this.selectedClass=value;this.render();$('character-name').value=name;$('cape-color').value=color;return;}
  if(type==='begin'){g.newGame(this.selectedClass,$('character-name').value,{cape:$('cape-color').value});return;}
  if(type==='equip'){s.equipment.weapon=value;g.updateEquipment();}
  else if(type==='shield'){s.equipment.shield=!s.equipment.shield;s.equipment.twoHand=false;g.updateEquipment();}
  else if(type==='twohand'){s.equipment.twoHand=!s.equipment.twoHand;s.equipment.paired=false;g.updateEquipment();}
  else if(type==='paired'){if(s.inventory.weapons.filter(w=>['sword','katana'].includes(WEAPONS[w].kind)).length<2)return this.toast('Find a second compatible blade.');s.equipment.paired=!s.equipment.paired;s.equipment.twoHand=false;g.updateEquipment();}
  else if(type==='armor'){s.equipment.armor=s.equipment.armor==='knight'?'light':s.equipment.armor==='light'?'unarmored':'knight';g.updateEquipment();}
  else if(type==='ash'){s.equipment.ash=s.equipment.ash==='storm'?'default':'storm';}
  else if(type==='affinity'){s.equipment.affinity=s.equipment.affinity==='standard'?'keen':s.equipment.affinity==='keen'?'heavy':'standard';}
  else if(type==='layer'){this.layer=value;this.render();return;}
  else if(type==='travel'){g.fastTravel(value);return;}
  else if(type==='level'){if(levelUp(s,Number(value))){g.audio.chime();g.saveNow();}}
  else if(type==='allocate'){s.flasks.crimson=s.flasks.crimson===0?s.flasks.total:s.flasks.crimson-1;g.refill();}
  else if(type==='flaskcharge'){if(s.inventory.seeds>0&&s.flasks.total<14){s.inventory.seeds--;s.flasks.total++;s.flasks.crimson++;g.refill();}}
  else if(type==='flaskupgrade'){if(s.inventory.tears>0){s.inventory.tears--;s.flasks.level++;g.refill();}}
  else if(type==='time'){s.day=(Math.round(s.day*3)+1)%3/3+.05;}
  else if(type==='roundtable'){g.transition('roundtable',{x:0,z:25});return;}
  else if(type==='spell'){s.equipment.spell=(s.equipment.spell+1)%3;this.toast(['Glintstone Pebble','Glintstone Arc','Catch Flame'][s.equipment.spell]);}
  else if(type==='upgrade'){if(upgradeWeapon(s)){g.updateEquipment();g.audio.chime();}}
  else if(type==='craft'){if(s.quests.crafting&&s.inventory.flowers>=3){s.inventory.flowers-=3;s.inventory.boluses++;g.audio.chime();}}
  else if(type==='bolus'){if(s.inventory.boluses>0){s.inventory.boluses--;g.statusBuild=0;g.poison=0;}}
  else if(type==='buy'){const cost={crafting:300,stones:200,tears:900,seeds:1200,seal:600,katana:1600}[value];if(cost&&s.runes>=cost){s.runes-=cost;if(['crafting','seal'].includes(value))s.quests[value]=true;else if(value==='katana')s.inventory.weapons.push('katana');else s.inventory[value]++;g.audio.chime();}}
  else if(type==='dialogue'){g.dialogueAction(value);return;}
  else if(type==='ending'){const e=ENDINGS.find(e=>e.id===value);if(e&&s.defeated.includes('beast')&&(!e.requires||s.quests[e.requires])){s.ending=value;g.audio.chime();g.saveNow();}}
  else if(type==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>this.toast('Fullscreen is unavailable in this browser view.'));return;}
  else if(type==='save'){g.saveNow();this.toast('Journey saved.');return;}
  else if(type==='export'){g.exportSave();return;}
  else if(type==='title'){g.saveNow();g.playing=false;this.showTitle();return;}
  g.saveNow();this.render();
 }
 update(){const g=this.g,s=g.save;$('hp-bar').style.width=Math.max(0,s.hp/maxHP(s)*100)+'%';$('fp-bar').style.width=Math.max(0,s.fp/maxFP(s)*100)+'%';$('st-bar').style.width=Math.max(0,g.stamina/maxStamina(s)*100)+'%';$('rune-count').textContent=Math.floor(s.runes).toLocaleString();$('flask-count').textContent=g.flaskType==='hp'?s.flaskHP:s.flaskFP;$('quick-name').textContent=g.flaskType==='hp'?'Flask of Crimson Tears':'Flask of Cerulean Tears';$('skill-name').textContent=s.equipment.ash==='storm'?'Storm Stomp':WEAPONS[s.equipment.weapon].skill;$('objective-text').textContent=g.objective();$('status-icons').textContent=(g.mounted?'♞ ':'')+(s.equipment.twoHand?'Ⅱ ':'')+(g.poison?'Poison ':'')+(g.spirit?'Spirit ally':'');const angle=((g.cameraYaw*180/Math.PI)%360+360)%360;const dirs=['N','NW','W','SW','S','SE','E','NE'];$('compass-points').textContent='·　　 '+dirs[Math.round(angle/45)%8]+' 　　·';}
}
