import {BIO} from './data.js';
export class OceanAudio{
 constructor(settings){this.settings=settings;this.active=false;this.lastBreath=0;this.lastSwim=0;this.lastMusic=0;this.sources=[];this.warnUntil=0;}
 async start(){if(this.active){await this.ctx.resume();return;}const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();const c=this.ctx;this.master=c.createGain();const compressor=c.createDynamicsCompressor();compressor.threshold.value=-14;compressor.knee.value=20;compressor.ratio.value=5;compressor.attack.value=.005;compressor.release.value=.25;this.master.connect(compressor);compressor.connect(c.destination);this.channels={};for(const k of ['effects','ambience','music','voice']){const gain=c.createGain();gain.connect(this.master);this.channels[k]=gain;}
 this.noise=c.createBuffer(1,c.sampleRate*4,c.sampleRate);const arr=this.noise.getChannelData(0);let last=0;for(let i=0;i<arr.length;i++){const white=Math.random()*2-1;last=(last+.022*white)/1.022;arr[i]=last*3.5;}
 this.reverb=c.createConvolver();const impulse=c.createBuffer(2,c.sampleRate*2.4,c.sampleRate);for(let channel=0;channel<2;channel++){const a=impulse.getChannelData(channel);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,3.5)*.3;}this.reverb.buffer=impulse;this.reverbGain=c.createGain();this.reverbGain.gain.value=.16;this.reverb.connect(this.reverbGain);this.reverbGain.connect(this.channels.effects);
 this.amb=c.createBufferSource();this.amb.buffer=this.noise;this.amb.loop=true;this.ambFilter=c.createBiquadFilter();this.ambFilter.type='lowpass';this.ambFilter.frequency.value=500;this.ambGain=c.createGain();this.ambGain.gain.value=.23;this.amb.connect(this.ambFilter);this.ambFilter.connect(this.ambGain);this.ambGain.connect(this.channels.ambience);this.amb.start();
 this.engine=c.createOscillator();this.engine.type='sawtooth';this.engine.frequency.value=45;this.engineFilter=c.createBiquadFilter();this.engineFilter.frequency.value=130;this.engineGain=c.createGain();this.engineGain.gain.value=0;this.engine.connect(this.engineFilter);this.engineFilter.connect(this.engineGain);this.engineGain.connect(this.channels.effects);this.engine.start();
 this.deep=c.createOscillator();this.deep.frequency.value=35;this.deepGain=c.createGain();this.deepGain.gain.value=0;this.deep.connect(this.deepGain);this.deepGain.connect(this.channels.ambience);this.deep.start();this.active=true;this.apply();await c.resume();}
 apply(){if(!this.active)return;const c=this.ctx;this.master.gain.setTargetAtTime(this.settings.master??.75,c.currentTime,.1);for(const k of Object.keys(this.channels))this.channels[k].gain.setTargetAtTime(this.settings[k]??.65,c.currentTime,.1);}
 pause(paused){if(!this.active)return;if(paused)this.ctx.suspend();else this.ctx.resume();}
 route(source,volume=.2,pos=null,channel='effects',cutoff=2200,duration=1){const c=this.ctx,filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=cutoff;const gain=c.createGain();gain.gain.setValueAtTime(0,c.currentTime);gain.gain.linearRampToValueAtTime(volume,c.currentTime+.025);gain.gain.exponentialRampToValueAtTime(.0001,c.currentTime+duration);source.connect(filter);filter.connect(gain);if(pos){const p=c.createPanner();p.panningModel='HRTF';p.distanceModel='inverse';p.refDistance=8;p.maxDistance=650;p.rolloffFactor=.7;p.positionX.value=pos.x;p.positionY.value=pos.y;p.positionZ.value=pos.z;gain.connect(p);p.connect(this.channels[channel]);p.connect(this.reverb);this.sources.push({panner:p,position:pos,filter,stop:c.currentTime+duration});}else {gain.connect(this.channels[channel]);if(channel==='effects')gain.connect(this.reverb);}source.start();source.stop(c.currentTime+duration);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
 tone(freq,duration=.2,volume=.12,shape='sine',pos=null,end=freq,channel='effects'){if(!this.active)return;const o=this.ctx.createOscillator();o.type=shape;o.frequency.setValueAtTime(freq,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(10,end),this.ctx.currentTime+duration);this.route(o,volume,pos,channel,2400,duration);}
 effect(type,pos=null,volume=1){if(!this.active)return;const table={click:[850,.1,.08],collect:[650,.22,.13],scan:[1200,.38,.07],craft:[420,.7,.13],repair:[160,.22,.1],door:[100,.8,.2],impact:[65,.65,.4],splash:[240,.55,.28],swim:[160,.3,.035],breath:[280,1.3,.055],build:[110,.8,.2],cut:[380,.3,.15],emp:[40,1.6,.3],warning:[600,.5,.16]};const [freq,dur,vol]=table[type]||table.click;
 if(['impact','splash','swim','breath','cut','door','build'].includes(type)){const src=this.ctx.createBufferSource();src.buffer=this.noise;src.playbackRate.value=type==='breath'?1.8:1;this.route(src,vol*volume,pos,'effects',type==='breath'?1400:type==='splash'?3000:650,dur);}this.tone(freq,dur,vol*.45*volume,type==='impact'?'triangle':'sine',pos,type==='collect'?1100:freq*.65);
 }
 call(species,pos,cave=false){if(!this.active)return;const table={reaper:[80,380,3.2,.75],ghost:[200,720,4.6,.5],dragon:[45,160,4,.8],stalker:[240,110,1.2,.25],sandshark:[110,75,1.4,.25],reefback:[44,70,7,.35],crabsquid:[300,900,2.1,.32]};const [a,b,d,v]=table[species]||table.stalker;for(let i=1;i<=3;i++){const o=this.ctx.createOscillator();o.type=i===1?'sine':'sawtooth';o.frequency.setValueAtTime(a*i,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(b*i,this.ctx.currentTime+d*.35);o.frequency.exponentialRampToValueAtTime(a*.5*i,this.ctx.currentTime+d);this.route(o,v/i*.28,pos,'effects',cave?900:1500,d);}this.effect('swim',pos,2);}
 warning(text){if(!this.active)return;const c=this.ctx;if(c.currentTime<this.warnUntil)return;this.warnUntil=c.currentTime+3;this.tone(680,.5,.18,'sine',null,580,'voice');setTimeout(()=>this.tone(510,.4,.15,'sine',null,480,'voice'),400);if(this.settings.spoken&&'speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.93;u.volume=(this.settings.voice??.7)*(this.settings.master??.7);speechSynthesis.speak(u);}}
 update({pos,forward,up,biome,depth,inside,vehicle,moving,oxygen,time}){if(!this.active)return;const c=this.ctx,t=c.currentTime,l=c.listener;for(const [name,val]of [['positionX',pos.x],['positionY',pos.y],['positionZ',pos.z],['forwardX',forward.x],['forwardY',forward.y],['forwardZ',forward.z],['upX',up.x],['upY',up.y],['upZ',up.z]])if(l[name])l[name].setTargetAtTime(val,t,.04);
 const air=depth<1||inside;const deep=depth>300;const cutoff=air?inside?350:2600:biome==='kelp'?330:deep?180:800;this.ambFilter.frequency.setTargetAtTime(cutoff,t,1);this.ambGain.gain.setTargetAtTime(inside?.07:depth<1?.17:biome==='kelp'?.28:deep?.14:.21,t,1);this.deepGain.gain.setTargetAtTime(deep&&!inside?.045:0,t,2);this.deep.frequency.setTargetAtTime(['lava','lakes'].includes(biome)?42:31,t,2);this.reverbGain.gain.setTargetAtTime(inside?.26:depth>600?.3:.09,t,1);
 this.engineGain.gain.setTargetAtTime(vehicle&&vehicle.power>0?(vehicle.silent?.014:vehicle.demoBoost?.075:moving?.048:.025):inside?.011:0,t,.3);this.engine.frequency.setTargetAtTime(vehicle?.demoBoost?112:vehicle?.type==='cyclops'?35:vehicle?moving?75:50:55,t,.4);
 for(const s of this.sources){s.panner.positionX.setTargetAtTime(s.position.x,t,.08);s.panner.positionY.setTargetAtTime(s.position.y,t,.08);s.panner.positionZ.setTargetAtTime(s.position.z,t,.08);const dist=s.position.distanceTo(pos);s.filter.frequency.setTargetAtTime(Math.max(130,1800/(1+dist*.03))*(inside?.35:1),t,.3);}this.sources=this.sources.filter(s=>s.stop>t);for(const key of ['effects','ambience','music'])this.channels[key].gain.setTargetAtTime((this.settings[key]??.6)*(t<this.warnUntil?.45:1),t,.15);
 if(!air&&!vehicle&&time-this.lastBreath>(oxygen<25?2.1:4.2)){this.effect('breath',null,oxygen<25?1.8:1);this.lastBreath=time;}
 if(moving&&!vehicle&&!inside&&time-this.lastSwim>.9){this.effect(depth<1?'splash':'swim',null,depth<1?.3:1);this.lastSwim=time;}
 if(time-this.lastMusic>90&&['shallows','mushroom','grand'].includes(biome)&&!inside){this.lastMusic=time;for(let i=0;i<4;i++)setTimeout(()=>this.tone([196,293.66,392,440][i],9,.017,'sine',null,[196,293.66,392,440][i],'music'),i*1400);}
 }
}
