import * as T from '../vendor/three.module.js';
import {ITEMS,RECIPES,BUILDS,BIOMES,BIO,VEHICLES,LANDMARKS,STORY,FRAGMENT_COUNTS} from './data.js';
import {freshState,counts,pack,canPay,pay,craft,equip,addItem,makeItem,maxOxygen,scanFragment,createVehicle,depthLimit,hullIntegrity,serialize,deserialize,transfer,nextStory,storyAction,exchangeBattery,chargeBatteries} from './state.js';
import {World,biomeAt,surfaceHeight,moveWithCollision,caveNear} from './world.js';
import * as M from './models.js';
import {OceanAudio} from './audio.js';
import {UI,icon,escapeHTML} from './ui.js';
import {freshDemoState,DemoHunt,DEMO_HOME} from './demo.js';
const $=id=>document.getElementById(id),clamp=T.MathUtils.clamp;
const defaults={master:.75,effects:.8,ambience:.75,music:.45,voice:.9,spoken:false,subtitles:true,quality:'High',sensitivity:1,fov:76,invert:false,motion:true,keys:{forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD',up:'Space',down:'KeyC',sprint:'ShiftLeft',interact:'KeyE',pda:'Tab',build:'KeyB',reload:'KeyR',light:'KeyF',exit:'KeyQ',defense:'KeyX',silent:'KeyV',grapple:'KeyG'}};
class Game{
 constructor(){
  try{const saved=JSON.parse(localStorage.getItem('crater-settings')||'{}');this.settings={...defaults,...saved,keys:{...defaults.keys,...saved.keys}};}catch{this.settings=structuredClone(defaults);}
  this.keys=new Set();this.mouseDown=false;this.playing=false;this.paused=true;this.slot=1;this.s=freshState();this.player=new T.Vector3(0,-6,35);this.velocity=new T.Vector3();this.yaw=0;this.pitch=-.1;this.time=0;this.last=performance.now();this.frameCount=0;this.fps=60;this.frameTimes=[];this.flash=false;this.entities=[];this.vehicleMeshes=new Map();this.baseMeshes=new Map();this.deployMeshes=new Map();this.interiorEntities=[];this.rocketOrder=['neptunePlatform','neptuneGantry','neptuneBoosters','neptuneFuel','neptuneCockpit'];this.audio=new OceanAudio(this.settings);this.ui=new UI(this);this.setupRenderer();this.setupInput();this.buildWorld();this.applySettings();
  window.addEventListener('error',e=>{console.error(e.error||e.message);this.ui.toast('A runtime error occurred. Save if possible and reload.');});
  Object.defineProperty(window,'craterDiagnostics',{get:()=>({fps:Math.round(this.fps),drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,position:this.player.toArray(),yaw:this.yaw,pitch:this.pitch,oxygen:this.s.oxygen,health:this.s.health,inside:this.inside?.id||null,vehicle:this.vehicle?{type:this.vehicle.type,power:this.vehicle.power,hp:this.vehicle.hp,boost:this.vehicle.boost,modules:[...this.vehicle.modules]}:null,demo:this.demo?.diagnostics()||null,bases:this.s.bases.length,biome:this.biome?.name,mode:this.s.mode,playing:this.playing,paused:this.paused,inventory:this.s.inventory.map(i=>i.id),flags:{...this.s.flags},scans:[...this.s.scans],entities:this.world.entities.size,tiles:this.world.tiles.size,audio:this.audio.active?this.audio.ctx.state:'inactive'})});
  requestAnimationFrame(t=>this.frame(t));setTimeout(()=>{$('loading').classList.add('hidden');$('main-menu').classList.remove('hidden');},800);
 }
 setupRenderer(){
  this.renderer=new T.WebGLRenderer({canvas:$('ocean'),antialias:true,powerPreference:'high-performance'});this.renderer.setSize(innerWidth,innerHeight);this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;
  this.scene=new T.Scene();this.scene.background=new T.Color(BIO.shallows.color);this.scene.fog=new T.FogExp2(BIO.shallows.color,.012);this.camera=new T.PerspectiveCamera(this.settings.fov,innerWidth/innerHeight,.08,4200);this.camera.rotation.order='YXZ';this.scene.add(this.camera);
  this.sun=new T.DirectionalLight(0xdaf5e7,3.5);this.sun.position.set(90,140,-65);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-50,right:50,top:50,bottom:-50,near:1,far:350});this.sun.shadow.bias=-.001;this.scene.add(this.sun,this.sun.target);
  this.ambient=new T.HemisphereLight(0x8cced5,0x355348,2);this.scene.add(this.ambient);
  this.fill=new T.PointLight(0x75c6d3,3,27,1.3);this.camera.add(this.fill);
  this.spot=new T.SpotLight(0xd6f4dc,95,52,.33,.7,1.25);this.spot.position.set(.25,-.2,0);this.spot.target.position.set(0,0,-18);this.camera.add(this.spot,this.spot.target);this.spot.visible=false;
  const skyGeo=new T.SphereGeometry(3800,32,16);this.sky=M.mesh(skyGeo,new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{sun:{value:new T.Vector3(.45,.56,-.5).normalize()}},vertexShader:'varying vec3 vPos;void main(){vPos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 vPos;uniform vec3 sun;void main(){vec3 dir=normalize(vPos);float h=max(0.0,dir.y);vec3 color=mix(vec3(.70,.84,.84),vec3(.16,.42,.66),pow(h,.4));float s=pow(max(0.0,dot(dir,sun)),700.);float glow=pow(max(0.0,dot(dir,sun)),14.);color+=vec3(1.,.85,.53)*s*2.+vec3(.23,.15,.04)*glow;float clouds=sin(dir.x*39.+sin(dir.z*22.))*sin(dir.z*31.+dir.x*11.);color+=vec3(.08)*smoothstep(.3,.9,clouds)*pow(1.-h,3.);gl_FragColor=vec4(color,1.);}'}),this.scene);
  this.waterUniforms={time:M.clockUniform,under:{value:1},roomActive:{value:0},roomMin:{value:new T.Vector2()},roomMax:{value:new T.Vector2()},sunDir:{value:new T.Vector3(.45,.55,-.5).normalize()}};
  const waterMat=new T.ShaderMaterial({uniforms:this.waterUniforms,side:T.DoubleSide,transparent:true,depthWrite:false,vertexShader:'uniform float time;varying vec3 vWorld;void main(){vec3 p=position;p.z+=sin(p.x*.026+time*.55)*.35+cos(p.y*.03-time*.45)*.24;vec4 w=modelMatrix*vec4(p,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}',fragmentShader:`uniform float time;uniform float under;uniform float roomActive;uniform vec2 roomMin;uniform vec2 roomMax;uniform vec3 sunDir;varying vec3 vWorld;
  void main(){if(roomActive>.5&&vWorld.x>roomMin.x&&vWorld.x<roomMax.x&&vWorld.z>roomMin.y&&vWorld.z<roomMax.y)discard;vec3 view=normalize(cameraPosition-vWorld);float waves=sin(vWorld.x*.4+time)*cos(vWorld.z*.29+time*.5);vec3 n=normalize(vec3(sin(vWorld.x*.16+time)*.13,1.,cos(vWorld.z*.14-time)*.11));float fres=pow(1.-abs(dot(view,n)),4.);float spec=pow(max(0.,dot(reflect(-sunDir,n),view)),140.);vec3 c=mix(vec3(.025,.32,.41),vec3(.48,.69,.76),fres);c+=vec3(1.,.82,.51)*spec*2.;c+=waves*.012;if(under>.5){c=mix(vec3(.19,.64,.69),vec3(.48,.83,.81),fres*.6);float caust=pow(1.-abs(sin(vWorld.x*.3+sin(vWorld.z*.31+time*.2))*cos(vWorld.z*.29+sin(vWorld.x*.21-time*.2))),12.);c+=caust*.075;float distanceFade=exp(-length(cameraPosition-vWorld)*.014);c=mix(vec3(.026,.43,.54),c,distanceFade);}gl_FragColor=vec4(c,under>.5?exp(-length(cameraPosition-vWorld)*.008):1.);}`});
  this.water=M.mesh(new T.PlaneGeometry(8500,8500,90,90),waterMat,this.scene,[0,0,0]);this.water.rotation.x=-Math.PI/2;this.water.castShadow=false;
  this.shafts=new T.Group();this.scene.add(this.shafts);const shaftMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,uniforms:{time:M.clockUniform},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform float time;void main(){float a=pow(sin(vUv.x*3.14159),3.)*sin(vUv.y*3.14159)*.025*(.7+.3*sin(time*.2+vUv.y*12.));gl_FragColor=vec4(.42,.8,.68,a);}'});for(let i=0;i<7;i++){const shaft=M.mesh(new T.PlaneGeometry(7,75),shaftMat,this.shafts,[(i%3)*25-25,-30,Math.floor(i/3)*28-20]);shaft.rotation.z=.28;shaft.rotation.y=.4;shaft.castShadow=false;}
  this.toolRoot=new T.Group();this.camera.add(this.toolRoot);this.cockpit=new T.Group();this.camera.add(this.cockpit);this.setToolModel('hands');
  window.addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);});
 }
 buildWorld(){if(this.worldGroup){this.worldGroup.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){for(const mat of Array.isArray(o.material)?o.material:[o.material]){if(mat.map&&mat.map!==M.textures.sand&&mat.map!==M.textures.reef)mat.map.dispose();mat.dispose();}}if(o.isInstancedMesh)o.dispose();});this.scene.remove(this.worldGroup);}this.entities=[];this.rocketObject=null;this.worldGroup=new T.Group();this.scene.add(this.worldGroup);this.world=new World(this.worldGroup,this.s);this.vehicleMeshes.clear();this.baseMeshes.clear();this.deployMeshes.clear();this.inside=null;this.vehicle=null;this.syncPersistent();}
 applySettings(){const q=this.settings.quality;this.renderer.setPixelRatio(Math.min(devicePixelRatio,q==='High'?1.5:q==='Medium'?1:.7));this.renderer.shadowMap.enabled=q==='High';this.camera.fov=this.settings.fov;this.camera.updateProjectionMatrix();this.audio.apply();try{localStorage.setItem('crater-settings',JSON.stringify(this.settings));}catch{this.ui.toast('Browser storage is unavailable; export saves manually.');}}
 setupInput(){
  const canvas=$('ocean');canvas.addEventListener('click',()=>{if(this.playing&&!this.ui.modal){this.audio.start();if(document.pointerLockElement!==canvas)canvas.requestPointerLock?.().catch?.(()=>this.ui.toast('Drag to look, or use the arrow keys.'));}});
  document.addEventListener('pointerlockchange',()=>{$('reticle-tip').style.display=document.pointerLockElement?'none':this.playing?'block':'none';if(!document.pointerLockElement&&this.playing&&!this.ui.modal){this.keys.clear();this.mouseDown=false;}});
  document.addEventListener('mousemove',e=>{if(!this.playing||this.paused||this.ui.modal)return;if(document.pointerLockElement===canvas||this.dragLook){this.yaw-=e.movementX*.0022*this.settings.sensitivity;this.pitch-=e.movementY*.0022*this.settings.sensitivity*(this.settings.invert?-1:1);this.pitch=clamp(this.pitch,-1.52,1.52);}});
  canvas.addEventListener('mousedown',e=>{if(!this.playing||this.paused)return;if(e.button===0){this.mouseDown=true;this.dragLook=!document.pointerLockElement;if(this.buildPreview)this.placeBuild();else this.useTool(true);}if(e.button===2)this.cancelBuild();});
  document.addEventListener('mouseup',()=>{this.mouseDown=false;this.dragLook=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
  document.addEventListener('keydown',e=>{if(['Tab','Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','F1'].includes(e.code))e.preventDefault();if(this.remapping){e.preventDefault();if(e.code!=='Escape'){const existing=Object.entries(this.settings.keys).find(([id,key])=>key===e.code&&id!==this.remapping);if(existing)this.ui.toast('That key is already assigned. Choose another.');else{this.settings.keys[this.remapping]=e.code;this.remapping=null;this.applySettings();this.ui.controls();}}else{this.remapping=null;this.ui.controls();}return;}
   if(e.code==='Escape'){if(this.ui.modal&& !['death','ending'].includes(this.ui.modal))this.ui.close();else if(this.playing&&!this.ui.modal)this.ui.pause();return;}
   if(!this.playing)return;const k=this.settings.keys;if(e.code===k.pda){if(this.ui.modal==='pda')this.ui.close();else if(!this.ui.modal)this.ui.pda();return;}if(this.paused||this.ui.modal)return;this.keys.add(e.code);if(e.repeat)return;
   if(e.code===k.interact)this.interact();if(e.code===k.build)this.has('builder')?this.ui.construction():this.ui.toast('Craft a habitat builder first.');if(e.code===k.reload){if(this.buildPreview){this.buildYaw+=Math.PI/2;}else this.exchangePower();}if(e.code===k.light){if(this.has('light')||this.vehicle){if(this.vehicle)this.vehicle.lights=this.vehicle.lights===false;else this.flash=!this.flash;this.audio.effect('click');}else this.ui.toast('A flashlight is required.');}if(e.code===k.exit){if(this.vehicle)this.exitVehicle();else if(this.inside)this.leaveInterior();}if(e.code===k.defense)this.vehicleDefense();if(e.code===k.grapple)this.grapple();if(e.code===k.silent&&this.vehicle?.type==='cyclops'){this.vehicle.silent=!this.vehicle.silent;this.ui.notify(this.vehicle.silent?'Silent running engaged':'Standard running');}if(e.code==='KeyH')this.ui.controls();if(e.code==='F1')$('hud').style.opacity=$('hud').style.opacity==='0'?'1':'0';if(/^Digit[1-5]$/.test(e.code))this.selectSlot(Number(e.code.slice(-1))-1);
  });document.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>{this.keys.clear();this.mouseDown=false;if(this.playing&&!this.ui.modal)this.ui.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.playing&&!this.ui.modal)this.ui.pause();});
 }
 has(id){return this.s.inventory.some(i=>i.id===id)||Object.values(this.s.equipment).some(i=>i?.id===id)||this.s.mode==='creative';}
 startDemo(){this.startState(freshDemoState());this.ui.subtitle('Your submarine is ready. Look at the Seamoth and press E to board. Mouse to look; WASD to move.',9);this.ui.notify('SUBMARINE SURVIVAL');}
 startNew(mode){this.s=freshState(mode);for(let i=1;i<=3;i++)if(!localStorage.getItem('crater-save-'+i)){this.slot=i;break;}this.startState(this.s);this.ui.subtitle('PDA online. The lifepod fabricator can turn local resources into survival equipment. Start with oxygen and a scanner.',10);this.ui.notify('LIFE SIGNS STABLE');}
 startState(s){this.demo=null;this.launching=null;this.damageFlash=0;this.shake=0;this.s=s;document.body.classList.toggle('demo-mode',!!s.demo);document.body.classList.remove('piloting');$('demo-console').innerHTML='';$('demo-cracks').style.opacity=0;$('objective').querySelector('p').firstChild.textContent='PERSONAL LOG ';this.buildWorld();this.player.fromArray(s.position);this.yaw=s.yaw||0;this.pitch=s.pitch||0;this.velocity.set(0,0,0);this.playing=true;this.paused=false;this.dead=false;this.flash=false;this.time=s.time;this.ui.close();if(s.demo)this.demo=new DemoHunt(this);$('main-menu').classList.add('hidden');$('hud').classList.remove('hidden');this.audio.start();this.refreshHotbar();this.setToolModel(s.selected||'hands');if(s.activeVehicle){const v=s.vehicles.find(v=>v.uid===s.activeVehicle);if(v)this.enterVehicle(v);}else if(s.inside){const e=this.world.entities.get(s.inside)||this.entities.find(e=>e.id===s.inside);if(e)this.enterInterior(e);}
 }
 refreshHotbar(){this.slots=['hands',...this.s.inventory.filter(i=>ITEMS[i.id].kind==='tool').map(i=>i.id).filter((v,i,a)=>a.indexOf(v)===i)];if(this.s.selected&&!this.slots.includes(this.s.selected))this.s.selected='hands';let visible=this.slots.slice(0,5);if(this.s.selected&&!visible.includes(this.s.selected)){visible[4]=this.s.selected;}this.hotbar=visible;$('quickslots').innerHTML=Array.from({length:5},(_,i)=>{const id=visible[i];return `<div class="quickslot ${id===this.s.selected?'active':''} ${id?'':'empty'}"><small>${i+1}</small>${id?icon(id):''}<span class="slot-name">${id==='hands'?'Empty hands':ITEMS[id]?.name||''}</span><i id="slot-charge-${i}"></i></div>`;}).join('');}
 selectSlot(index){const id=this.hotbar[index];if(id){this.s.selected=id;this.setToolModel(id);this.refreshHotbar();this.audio.effect('click');}}
 setToolModel(id){this.toolRoot.clear();if(id==='hands')return;const tool=M.tool(id);this.toolRoot.add(tool);if(id==='seaglide'){tool.position.set(.02,-.49,-.95);tool.rotation.x=.25;tool.scale.setScalar(.65);}else{tool.position.set(.38,-.36,-.79);tool.rotation.set(.1,-.23,-.14);tool.scale.setScalar(.6);}this.toolRoot.visible=!this.vehicle;}
 selectedItem(){return this.s.inventory.find(i=>i.id===this.s.selected);}
 consumeTool(amount,id=this.s.selected){if(this.s.mode==='creative')return true;const item=this.s.inventory.find(i=>i.id===id);if(!item)return false;if(item.charge===undefined)return true;if(item.charge<=0){this.ui.notify('Battery depleted · R to exchange');return false;}item.charge=Math.max(0,item.charge-amount);return true;}
 useItem(uid){const item=this.s.inventory.find(i=>i.uid===uid);if(!item)return;const d=ITEMS[item.id];if(d.kind==='food'){for(const k of ['food','water','health'])if(d[k])this.s[k]=clamp(this.s[k]+d[k],0,100);this.s.inventory.splice(this.s.inventory.indexOf(item),1);this.audio.effect('collect');}else if(d.kind==='equipment'){if(!equip(this.s,uid))this.ui.toast('Not enough room to exchange equipment.');else{this.s.oxygen=Math.min(this.s.oxygen,maxOxygen(this.s));this.ui.toast(d.name+' equipped');}}else if(d.kind==='tool'){this.s.selected=item.id;this.setToolModel(item.id);this.refreshHotbar();this.ui.close();}else if(d.kind==='deploy'){this.deploy(item);}else if(d.kind==='module'){const v=this.nearVehicle();if(!v){this.ui.toast('Move within 15m of a vehicle.');return;}if(item.id.includes('Depth')&&!item.id.startsWith(v.type)||['drill','grapple'].includes(item.id)&&v.type!=='prawn'||item.id==='shield'&&v.type!=='cyclops'||item.id==='defense'&&v.type!=='seamoth'){this.ui.toast('This module is incompatible with the vehicle.');return;}const previous=v.modules.find(m=>item.id.includes('Depth')&&m.includes('Depth'));if(v.modules.includes(item.id)){this.ui.toast('That module is already installed.');return;}if(previous){v.modules.splice(v.modules.indexOf(previous),1);this.s.inventory.splice(this.s.inventory.indexOf(item),1);addItem(this.s,previous);}else this.s.inventory.splice(this.s.inventory.indexOf(item),1);v.modules.push(item.id);this.ui.toast(d.name+' installed');}else if(d.kind==='battery')this.exchangePower(item);this.refreshHotbar();}
 dropItem(uid){const index=this.s.inventory.findIndex(i=>i.uid===uid);if(index<0)return;const item=this.s.inventory.splice(index,1)[0],pos=this.player.clone().addScaledVector(this.forward(),2);const drop={uid:this.s.uid++,pos:pos.toArray(),items:[item]};this.s.drops.push(drop);this.syncPersistent();this.refreshHotbar();}
 transfer(uid,from,to){const v=this.s.vehicles.find(v=>v.storage===to);const item=from.find(i=>i.uid===uid);if(v&&item&&!pack([...to,item],v.type==='cyclops'?8:v.modules.includes('storageModule')?6:4,v.type==='cyclops'?8:v.modules.includes('storageModule')?8:4)){this.ui.toast('Vehicle storage full. A storage module expands the compartment.');return;}if(!transfer(this.s,uid,from,to))this.ui.toast('No room in the destination.');else this.audio.effect('collect');}
 deploy(item){if(item.id==='vehicleBay'&&this.player.y<-4){this.ui.toast('Deploy the mobile vehicle bay at the surface.');return;}const pos=this.player.clone().addScaledVector(this.forward(),4);if(item.id==='vehicleBay')pos.y=.35;this.s.inventory.splice(this.s.inventory.indexOf(item),1);this.s.beacons.push({uid:this.s.uid++,type:item.id,pos:pos.toArray(),name:item.id==='vehicleBay'?'Mobile vehicle bay':'Beacon '+(this.s.beacons.length+1)});this.syncPersistent();this.ui.close();this.audio.effect('build');this.ui.notify(ITEMS[item.id].name+' deployed');}
 craft(id,station){
  if(ITEMS[id].kind==='rocket'&&id!==this.rocketOrder[this.s.rocket]){this.ui.toast('Build the Neptune stages in order.');return;}
  if(this.inside?.base&&this.inside.base.power<5&&this.s.mode!=='creative'){this.ui.toast('The habitat has insufficient power.');return;}
  const result=craft(this.s,id,station);if(!result.ok){this.ui.toast(result.reason);return;}if(this.inside?.base&&this.s.mode!=='creative')this.inside.base.power=Math.max(0,this.inside.base.power-5);
  if(ITEMS[id].kind==='vehicle'){const p=this.player.clone().add(new T.Vector3(12,-5,12));p.y=Math.min(-3,p.y);p.y=Math.max(p.y,surfaceHeight(p.x,p.z)+6);createVehicle(this.s,id,p.toArray());this.ui.close();this.syncPersistent();this.ui.notify(ITEMS[id].name+' constructed');}
  else if(ITEMS[id].kind==='rocket'){this.s.rocket++;this.s.rocketPos=this.s.rocketPos||[this.player.x+15,0,this.player.z+15];this.syncPersistent();this.ui.notify('Neptune construction '+this.s.rocket+'/5');}
  else this.ui.toast('Fabricated '+ITEMS[id].name+(result.recipe.count>1?' × '+result.recipe.count:''));
  this.audio.effect('craft');this.refreshHotbar();
 }
 beginBuild(type){this.cancelBuild();if(!this.has('builder')){this.ui.toast('A habitat builder is required.');return;}this.buildType=BUILDS.find(b=>b.id===type);if(!canPay(this.s,this.buildType.cost)){this.ui.toast('Missing construction materials.');return;}this.buildPreview=M.habitat(type);this.buildPreview.traverse(o=>{if(o.isMesh){o.material=new T.MeshBasicMaterial({color:0x72efc5,wireframe:true,transparent:true,opacity:.6});}});this.scene.add(this.buildPreview);this.buildYaw=0;this.ui.notify('Position the habitat · Click to build · R rotate');}
 cancelBuild(){if(this.buildPreview)this.scene.remove(this.buildPreview);this.buildPreview=null;this.buildType=null;}
 updateBuild(){if(!this.buildPreview)return;const p=this.player.clone().addScaledVector(this.forward(),10),kind=this.buildType.kind;const c=p.y<surfaceHeight(p.x,p.z)-10?caveNear(p.toArray()):null;
 const floorAt=(x,z)=>c&&c.distance<c.radius?c.point.y-c.radius*.78:surfaceHeight(x,z);
 if(kind==='inside'){if(this.inside){p.y=this.inside.origin.y-.1;p.x=clamp(p.x,this.inside.origin.x-this.inside.size[0]+.8,this.inside.origin.x+this.inside.size[0]-.8);p.z=clamp(p.z,this.inside.origin.z-this.inside.size[2]+.8,this.inside.origin.z+this.inside.size[2]-.8);}else p.y=floorAt(p.x,p.z)+.5;}
 else if(kind==='room'){p.x=Math.round(p.x/8)*8;p.z=Math.round(p.z/8)*8;const r=this.buildType.id==='moonpool'?8:4.5;let ground=-Infinity;for(const x of [-r,0,r])for(const z of [-r,0,r])ground=Math.max(ground,floorAt(p.x+x,p.z+z));p.y=Math.ceil(Math.max(ground+.8,p.y-3)/4)*4;}
 else p.y=Math.max(floorAt(p.x,p.z)+.25,p.y-2);this.buildPreview.position.copy(p);this.buildPreview.rotation.y=this.buildYaw;
 }

 placeBuild(){if(!this.buildPreview)return;const b=this.buildType,p=this.buildPreview.position.clone(),near=this.s.bases.find(x=>['room','corridor','glassCorridor','moonpool','observatory'].includes(x.type)&&new T.Vector3(...x.pos).distanceTo(p)<17);if(['inside','attachment'].includes(b.kind)&&!near){this.ui.toast('Place this beside or inside a habitat compartment.');return;}if(b.kind==='inside'&&!this.inside){this.ui.toast('Enter a habitat to place interior equipment.');return;}if(b.kind==='room'&&this.s.bases.some(x=>['room','corridor','glassCorridor','moonpool','observatory'].includes(x.type)&&new T.Vector3(...x.pos).distanceTo(p)<6)){this.ui.toast('The construction footprint overlaps another compartment.');return;}if(!pay(this.s,b.cost)){this.ui.toast('Missing materials.');return;}const base={uid:this.s.uid++,type:b.id,pos:p.toArray(),yaw:this.buildYaw,power:0,hp:100,flood:0,store:[],parent:near?.uid,fuel:0,plants:[],created:this.s.time};this.s.bases.push(base);if(b.kind==='room')this.world.refreshBaseArea(base);this.consumeTool(.5,'builder');this.audio.effect('build',p);this.cancelBuild();this.syncPersistent();this.ui.notify(b.name+' constructed');if(this.inside)this.rebuildInteriorEntities();}
 deconstruct(base){const b=BUILDS.find(b=>b.id===base.type);if(base.store?.length||base.plants?.length){this.ui.toast('Empty this structure before deconstructing it.');return;}if(this.s.bases.some(x=>x.parent===base.uid)){this.ui.toast('Deconstruct attached equipment first.');return;}const trial=structuredClone(this.s);for(const[id,n]of Object.entries(b.cost))if(!addItem(trial,id,n)){this.ui.toast('Free inventory space for recovered materials.');return;}this.s.inventory=trial.inventory;this.s.uid=trial.uid;this.s.bases=this.s.bases.filter(x=>x.uid!==base.uid);if(b.kind==='room')this.world.refreshBaseArea(base);const obj=this.baseMeshes.get(base.uid);if(obj)this.worldGroup.remove(obj);this.baseMeshes.delete(base.uid);this.entities=this.entities.filter(e=>e.base?.uid!==base.uid);this.audio.effect('build');this.ui.toast('Materials recovered');}
 syncPersistent(){
  for(const v of this.s.vehicles){if(this.vehicleMeshes.has(v.uid))continue;const obj=M.vehicle(v.type);obj.position.fromArray(v.pos);obj.rotation.y=v.yaw;this.worldGroup.add(obj);this.vehicleMeshes.set(v.uid,obj);this.entities.push({id:'vehicle-'+v.uid,type:'vehicle',name:VEHICLES[v.type].name,pos:obj.position,vehicle:v,object:obj,reach:v.type==='cyclops'?12:5});}
  for(const b of this.s.bases){if(this.baseMeshes.has(b.uid))continue;const obj=M.habitat(b.type);obj.position.fromArray(b.pos);obj.rotation.y=b.yaw;this.worldGroup.add(obj);this.baseMeshes.set(b.uid,obj);this.entities.push({id:'base-'+b.uid,type:'base',name:BUILDS.find(x=>x.id===b.type)?.name||b.type,pos:obj.position,base:b,object:obj,reach:7});}
  for(const b of this.s.beacons){if(this.deployMeshes.has(b.uid))continue;const g=new T.Group();if(b.type==='vehicleBay'){M.box(g,M.MAT.white,[0,0,0],[3,.5,2.5]);for(const s of [-1,1])M.ellipsoid(g,M.MAT.orange,[s*1.5,-.05,0],[.3,.35,1.5]);M.box(g,M.MAT.dark,[0,.3,0],[1.5,.15,1.5]);M.label(g,'VEHICLE BAY',[0,1,.3],.45);}else{M.cylinder(g,M.MAT.orange,[0,0,0],.18,.18,1);M.ellipsoid(g,M.MAT.cyan,[0,.6,0],[.2,.2,.2]);}g.position.fromArray(b.pos);this.worldGroup.add(g);this.deployMeshes.set(b.uid,g);this.entities.push({id:'deploy-'+b.uid,type:b.type,name:b.name,pos:g.position,deploy:b,object:g,reach:5});}
  for(const d of this.s.drops){const key='drop-'+d.uid;if(this.entities.some(e=>e.id===key))continue;const obj=M.habitat('locker');obj.scale.set(.45,.45,.45);obj.position.fromArray(d.pos);this.worldGroup.add(obj);this.entities.push({id:key,type:'drop',name:'Recovery cache',pos:obj.position,drop:d,object:obj,reach:5});}
  if(this.s.rocket){if(this.rocketObject)this.worldGroup.remove(this.rocketObject);const g=new T.Group();M.box(g,M.MAT.dark,[0,-.5,0],[24,1,24]);for(const x of [-10,10])for(const z of [-10,10])M.ellipsoid(g,M.MAT.orange,[x,-.5,z],[2.2,1,2.2]);if(this.s.rocket>1){for(const x of [-5,5])M.box(g,M.MAT.steel,[x,18,1],[.9,36,.9]);for(let i=0;i<9;i++)M.box(g,M.MAT.orange,[0,i*4,1],[11,.3,.5]);}if(this.s.rocket>2){for(const x of [-3,3])M.cylinder(g,M.MAT.white,[x,8,0],1.5,2,15);M.cylinder(g,M.MAT.dark,[0,9,0],3,3,17);}if(this.s.rocket>3)M.cylinder(g,M.MAT.white,[0,22,0],2.7,3,12);if(this.s.rocket>4){M.mesh(new T.ConeGeometry(2.7,8,32),M.MAT.white,g,[0,32,0]);M.ellipsoid(g,M.MAT.glass,[0,30,-2.2],[1.7,1.5,.7]);}g.position.fromArray(this.s.rocketPos);this.worldGroup.add(g);this.rocketObject=g;this.entities=this.entities.filter(e=>e.id!=='neptune');this.entities.push({id:'neptune',type:'rocket',name:'Neptune launch platform',pos:g.position,object:g,reach:20});}
 }
 forward(){return new T.Vector3(0,0,-1).applyEuler(new T.Euler(this.pitch,this.yaw,0,'YXZ'));}
 nearVehicle(){return this.vehicle||this.s.vehicles.find(v=>new T.Vector3(...v.pos).distanceTo(this.player)<(v.type==='cyclops'?35:15));}
 enterVehicle(v){if(v.hp<=0)return;this.vehicle=v;this.s.activeVehicle=v.uid;this.s.inside=null;this.player.fromArray(v.pos);this.yaw=v.yaw;this.pitch=0;this.velocity.set(0,0,0);this.vehicleMeshes.get(v.uid).visible=false;this.cockpit.clear();this.toolRoot.visible=false;const g=this.cockpit;if(v.type==='seamoth'){for(const s of [-1,1]){const strut=M.pathTube(g,M.MAT.dark,[[s*.55,-.55,-.7],[s*.95,-.06,-1],[s*.75,.65,-1.2]],.055,14);M.box(g,M.MAT.white,[s*.56,-.5,-.7],[.45,.28,.45]);const screen=M.box(g,M.MAT.cyan,[s*.47,-.37,-.7],[.19,.045,.21]);screen.rotation.x=.2;}M.pathTube(g,M.MAT.dark,[[-.55,-.55,-.6],[0,-.48,-.72],[.55,-.55,-.6]],.08,16);M.box(g,M.MAT.orange,[0,-.51,-.63],[.33,.1,.13]);}else if(v.type==='prawn'){for(const s of [-1,1]){M.box(g,M.MAT.orange,[s*.65,-.1,-1],[.1,1.35,.15]);M.box(g,M.MAT.white,[s*.62,-.6,-.8],[.5,.55,.4]);M.box(g,M.MAT.cyan,[s*.6,-.32,-.85],[.24,.05,.18]);M.pathTube(g,M.MAT.steel,[[s*.7,-.65,-.6],[s*.76,-.6,-1.4],[s*.62,-.5,-1.8]],.09);}M.box(g,M.MAT.dark,[0,.65,-1],[1.5,.13,.1]);}else {for(const s of [-1,1]){M.box(g,M.MAT.white,[s*1.05,0,-1.5],[.17,2.3,.3]);M.box(g,M.MAT.dark,[s*.82,-.65,-1.2],[.9,.45,.4]);M.box(g,M.MAT.cyan,[s*.82,-.41,-1.2],[.6,.03,.27]);}M.box(g,M.MAT.dark,[0,-.85,-1.2],[2.5,.25,.35]);M.box(g,M.MAT.white,[0,.95,-1.5],[2.5,.1,.2]);}this.ui.notify(VEHICLES[v.type].name+' · Welcome aboard');this.audio.effect('door');if(v.power>0)this.s.oxygen=maxOxygen(this.s);}
 exitVehicle(){this.clearGrapple();const v=this.vehicle;if(!v)return;this.vehicleMeshes.get(v.uid).visible=true;v.pos=this.player.toArray();v.yaw=this.yaw;this.vehicleMeshes.get(v.uid).position.copy(this.player);this.vehicleMeshes.get(v.uid).rotation.y=this.yaw;this.player.add(new T.Vector3(v.type==='cyclops'?9:3,1,0).applyAxisAngle(new T.Vector3(0,1,0),this.yaw));this.vehicle=null;delete this.s.activeVehicle;this.cockpit.clear();this.toolRoot.visible=true;this.velocity.set(0,0,0);this.audio.effect('door');}
 grapple(){const v=this.vehicle;if(v?.type!=='prawn'||!v.modules.includes('grapple')){this.ui.toast('A Prawn grapple arm is required.');return;}if(this.grappleTarget){this.clearGrapple();return;}if(v.power<2&&this.s.mode!=='creative'){this.ui.toast('Insufficient power.');return;}const ray=new T.Raycaster(this.player,this.forward(),2,55);const hits=ray.intersectObject(this.worldGroup,true).filter(h=>h.object.isMesh&&!h.object.material?.transparent&&!h.object.isInstancedMesh);const hit=hits[0];if(!hit){this.ui.toast('No solid grapple anchor within 55m.');return;}this.grappleTarget=hit.point.clone();this.grappleUntil=this.time+4;v.power=Math.max(0,v.power-2);this.grappleLine=new T.Line(new T.BufferGeometry().setFromPoints([this.player,this.grappleTarget]),new T.LineBasicMaterial({color:0xb8c2b6}));this.worldGroup.add(this.grappleLine);this.audio.effect('impact',hit.point,.4);this.ui.notify('Grapple attached · G to release');}
 clearGrapple(){this.grappleTarget=null;if(this.grappleLine){this.worldGroup.remove(this.grappleLine);this.grappleLine.geometry.dispose();this.grappleLine.material.dispose();this.grappleLine=null;}}
 vehicleDefense(){if(this.demo){this.demo.repel();return;}const v=this.vehicle;if(!v||v.power<5){this.ui.toast('Defense system unavailable.');return;}if(!v.modules.some(m=>['defense','shield'].includes(m))){this.ui.toast('Install a perimeter defense or shield module first.');return;}v.power-=5;v.shieldUntil=this.time+8;this.audio.effect('emp',this.player,1);for(const c of this.world.creatures)if(c.pos.distanceTo(this.player)<70){c.state='retreat';c.timer=0;c.stunned=4;}this.ui.notify('Defense field discharged');}
 exchangePower(chosen){const v=this.nearVehicle();let kind=v?'cell':'battery',item=chosen;if(item&&((kind==='cell'&&!['cell','ionCell'].includes(item.id))||(kind==='battery'&&!['battery','ionBattery'].includes(item.id)))){this.ui.toast(v?'Use a power cell for a vehicle.':'Use a battery for handheld equipment.');return;}item=item||this.s.inventory.filter(i=>kind==='cell'?['cell','ionCell'].includes(i.id):['battery','ionBattery'].includes(i.id)).sort((a,b)=>(b.charge||0)-(a.charge||0))[0];if(!item){this.ui.toast(v?'No spare power cell.':'No spare battery.');return;}const target=v||this.selectedItem();if(!target||!v&&target.charge===undefined){this.ui.toast('Select a powered tool to exchange its battery.');return;}const charge=item.charge||0;exchangeBattery(target,item,!!v);this.audio.effect('door');this.ui.toast('Power exchanged · '+Math.round(charge)+' energy units');}
 enterInterior(ent){
  if(this.vehicle)this.exitVehicle();if(this.inside)this.leaveInterior();let b=ent.base;const isBase=ent.type==='base';if(isBase&&['room','corridor','glassCorridor','moonpool','observatory'].includes(b.type)){const hatch=this.s.bases.some(x=>x.type==='hatch'&&(x.parent===b.uid||new T.Vector3(...x.pos).distanceTo(new T.Vector3(...b.pos))<14));if(!hatch){this.ui.toast('Build a hatch beside this compartment.');return;}}
  const origin=ent.landmark?new T.Vector3(...ent.landmark.pos):ent.pos.clone();const type=ent.type==='pod'?'pod':ent.type==='aurora'?'aurora':ent.type==='alien'?'alien':ent.type==='vehicle'?'cyclops':ent.type==='degasi'?'degasi':ent.type==='wreck'?'wreck':'base';
  const size=type==='pod'?[2.5,2.7,2.5]:type==='cyclops'?[3.3,3.7,19]:['alien','aurora'].includes(type)?[10,7,11]:type==='wreck'?[5.5,5.7,11]:[3.65,3.3,3.65];
  this.inside={id:ent.id,type,origin,exit:this.player.toArray(),object:ent.object,base:b,entity:ent,size};this.s.inside=ent.id;this.insideGroup=new T.Group();this.insideGroup.position.copy(origin);this.worldGroup.add(this.insideGroup);if(ent.object)ent.object.visible=false;const g=this.insideGroup,[w,h,l]=size,alien=type==='alien',dark=['wreck','degasi','aurora'].includes(type),wall=alien?M.MAT.alien:dark?M.MAT.whiteDark:M.MAT.white;
  M.box(g,alien?M.MAT.alien:M.material(0x435257,.85,.2),[0,-.16,0],[w*2+.3,.32,l*2+.3]);M.box(g,wall,[0,h,0],[w*2,.35,l*2]);for(const s of [-1,1]){if(dark||alien)M.box(g,wall,[s*w,h*.5,0],[.3,h,l*2]);else{M.box(g,wall,[s*w,h*.18,0],[.3,h*.4,l*2]);M.box(g,wall,[s*w,h*.86,0],[.3,h*.3,l*2]);}for(let i=0;i<Math.floor(l);i++){M.box(g,alien?M.MAT.alienLight:M.MAT.steel,[s*(w-.15),h*.5,-l+1+i*2],[.12,h-.4,.06]);}if(!dark&&!alien){for(let i=-1;i<=1;i++){M.box(g,M.MAT.glass,[s*(w-.19),h*.56,i*l*.5],[.045,h*.35,l*.49]);}}}
  M.box(g,wall,[0,h*.5,l],[w*2,h,.3]);for(const s of [-1,1])M.box(g,wall,[s*(w*.65),h*.5,-l],[w*.7,h,.3]);M.box(g,wall,[0,h-.45,-l],[w*.6,.9,.35]);
  for(let z=-l+1;z<l;z+=2){M.box(g,alien?M.MAT.alienLight:M.MAT.whiteDark,[0,.02,z],[w*1.8,.015,.04]);for(const s of [-1,1])M.box(g,alien?M.MAT.alienLight:M.MAT.cyan,[s*(w-.4),.0,z],[.045,.04,1.4]);}
  // Interior frames, service panels, cable conduits and a visible pressure door.
  for(const side of [-1,1]){
   M.pathTube(g,dark?M.MAT.rust:M.MAT.steel,[[side*(w-.23),h-.55,-l+.6],[side*(w-.23),h-.55,0],[side*(w-.23),h-.55,l-.4]],.065,12);
   for(let z=-l+1.7;z<l-.7;z+=2.7){const panel=M.box(g,dark?M.MAT.rust:M.MAT.whiteDark,[side*(w-.19),.53,z],[.045,.65,1.5]);for(let j=0;j<4;j++)M.box(g,M.MAT.dark,[side*(w-.215),.33+j*.1,z],[.025,.03,1.1]);}
  }
  if(type==='pod'){for(const side of [-1,1]){M.box(g,M.MAT.orange,[side*2.1,1.03,-.5],[.12,.85,.7]);M.box(g,M.MAT.rubber,[side*1.88,.38,-.5],[.5,.15,.65]);}const roof=M.ring(g,M.MAT.orange,[0,h-.22,-.8],.8,.07,[Math.PI/2,0,0]);M.cylinder(g,M.MAT.dark,[0,h-.23,-.8],.72,.72,.08);}
  if(dark){for(let z=-l+3;z<l;z+=4){for(const side of [-1,1])M.box(g,M.MAT.steel,[side*(w-.3),h*.5,z],[.32,h,.26]);M.box(g,M.MAT.steel,[0,h-.25,z],[w*2,.3,.26]);M.box(g,M.MAT.orange,[0,.025,z],[w*1.6,.03,.08]);}for(let i=0;i<7;i++)M.pathTube(g,M.MAT.dark,[[-w+.3+i*.22,h-.2,-l+1],[-w+1+i*.15,h-.8,-l+5],[-w+.7+i*.2,h-.4,l-1]],.04,16);}
  const door=M.ring(g,alien?M.MAT.alienLight:M.MAT.orange,[0,1.18,-l+.18],.91,.08);door.scale.set(.85,1.22,1);M.box(g,M.MAT.dark,[0,.05,-l+.12],[1.6,.12,.45]);
  const light=new T.PointLight(alien?0x78e6b4:dark?0x83bacc:0xffe0a0,alien?60:dark?19:type==='pod'?8:22,50,1.5);light.position.set(0,h-.6,0);g.add(light);this.interiorLight=light;
  this.interiorEntities=[];this.addInside('exit','Exit '+(type==='pod'?'lifepod':type==='cyclops'?'Cyclops':'compartment'),[0,1,-l+.2]);
  const addStation=(id,name,x,z)=>{const obj=id==='fabricator'?M.fabricator():id==='radio'?M.radio():M.habitat(id==='locker'?'locker':'modification');obj.position.set(x,['fabricator','radio'].includes(id)?1.1:0,z);obj.rotation.y=0;g.add(obj);this.addInside(id,name,[x,1,z-.5]);};
  if(type==='pod'){addStation('fabricator','Fabricator',-1.35,1.6);addStation('radio','Radio',1.25,1.6);this.addInside('locker','Lifepod storage',[1.3,.4,-.4]);const locker=M.habitat('locker');locker.scale.set(.6,.5,.6);locker.position.set(1.5,0,0);g.add(locker);const ladder=M.habitat('ladder');ladder.position.set(-1.7,0,-1.9);g.add(ladder);this.addInside('ladder','Climb to the roof',[-1.7,1,-1.9]);}
  else if(type==='cyclops'){addStation('fabricator','Fabricator',-1.7,0);addStation('cyclopsFabricator','Cyclops fabricator',1.7,9);addStation('locker','Cyclops storage',-1.7,13);this.addInside('helm','Pilot Cyclops',[0,1,-l+3]);for(let z=-12;z<14;z+=8){M.box(g,M.MAT.white,[0,h-.25,z],[w*2,.4,.5]);}}
  else if(type==='base'){this.rebuildInteriorEntities();}
  else if(type==='alien'||type==='aurora'||type==='degasi'){addStation('terminal',type==='alien'?'Alien control terminal':type==='aurora'?'Captain’s terminal · code 2679':'Recovered Degasi PDA',0,l-2);if(type==='alien'&&ent.id==='containment'){addStation('incubator','Sea Emperor incubator',-5,2);addStation('enzyme','Enzyme 42',5,2);addStation('portal','Surface arch',5,-5);const eggs=M.resource('ion');eggs.scale.setScalar(3);eggs.position.set(-5,0,0);g.add(eggs);}if(type==='aurora'){addStation('driveCore','Drive core breach',-6,2);addStation('prawnScan','Prawn suit fragments',6,2);}if(type==='degasi')addStation('locker','Abandoned supply locker',2,0);}
  else if(type==='wreck'){addStation('wreckDoor','Sealed bulkhead',0,1);addStation('wreckData','Data box',0,l-2);for(let i=0;i<12;i++){const o=M.box(g,M.MAT.rust,[Math.sin(i*2)*3,0,i-l/2],[1.3,.25,.8]);o.rotation.set(.3,i,.15);}}
  this.player.copy(origin).add(new T.Vector3(0,1.15,-l+1.2));this.yaw=Math.PI;this.pitch=0;this.velocity.set(0,0,0);this.s.safeItems=this.s.inventory.map(i=>i.uid);this.audio.effect('door');this.ui.notify('Entered '+(ent.name||type));
 }
 addInside(action,name,local){const p=this.inside.origin.clone().add(new T.Vector3(...local));this.interiorEntities.push({id:'inside-'+action,action,type:'interior',name,pos:p,reach:4});}
 rebuildInteriorEntities(){if(!this.inside?.base)return;this.interiorEntities=this.interiorEntities.filter(e=>e.action==='exit');const base=this.inside.base;for(const b of this.s.bases.filter(x=>x.parent===base.uid)){const action={fabricator:'fabricator',locker:'locker',charger:'charger',cellCharger:'cellCharger',modification:'modification',upgrade:'upgrade',bioreactor:'bioreactor',bed:'bed',ladder:'ladder'}[b.type];if(action){this.interiorEntities.push({id:'inside-base-'+b.uid,action,type:'interior',name:BUILDS.find(d=>d.id===b.type).name,pos:new T.Vector3(...b.pos).add(new T.Vector3(0,1,0)),base:b,reach:4});}}}
 leaveInterior(){if(!this.inside)return;const i=this.inside;this.player.fromArray(i.exit);if(i.object)i.object.visible=true;this.worldGroup.remove(this.insideGroup);this.insideGroup=null;this.inside=null;delete this.s.inside;this.interiorEntities=[];this.velocity.set(0,0,0);this.audio.effect('door');}
 closest(){const dir=this.forward();const entities=this.inside?this.interiorEntities:this.entities;let best=this.inside?null:this.world.closest(this.player,dir);let score=best?best.pos.distanceTo(this.player):Infinity;for(const e of entities){if(e.object&&!e.object.visible)continue;const d=e.pos.distanceTo(this.player);if(d>(e.reach||5))continue;const dot=e.pos.clone().sub(this.player).normalize().dot(dir);if(dot<.7&&d>.65)continue;if(d<score){score=d;best=e;}}return best;}
 interact(){if(this.vehicle){if(this.vehicle.type==='cyclops'){const v=this.vehicle;this.exitVehicle();const ent=this.entities.find(e=>e.vehicle===v);this.enterInterior(ent);}else this.exitVehicle();return;}const e=this.target||this.closest();if(!e){this.ui.toast('Move closer and look at an object to interact.');return;}if(e.type==='resource')this.gather(e);else if(e.type==='creature'){if(['peeper','bladderfish'].includes(e.creature.species)){if(addItem(this.s,e.creature.species)){e.creature.caught=true;e.object.visible=false;this.world.entities.delete(e.id);this.s.harvested.push(e.id);this.audio.effect('collect');}else this.ui.toast('Inventory full.');}else this.ui.notify('Select the scanner to study this creature.');}
  else if(e.type==='fragment')this.ui.notify('Select scanner and hold the left mouse button.');
  else if(['pod','wreck','aurora','alien','degasi'].includes(e.type)){if(e.type==='aurora'&&!this.has('cutter'))this.ui.toast('The damaged entrance requires a laser cutter.');else this.enterInterior(e);}
  else if(e.type==='lostpod')this.lostPod(e);
  else if(e.type==='vehicle')this.enterVehicle(e.vehicle);
  else if(e.type==='vehicleBay')this.ui.crafting('Mobile vehicle bay');
  else if(e.type==='beacon'){this.ui.panel('Beacon signal','SIGNAL MANAGER',`<label class="setting-row"><span>Beacon name</span><input id="beacon-name" maxlength="40" value="${escapeHTML(e.deploy.name)}"></label><button id="save-beacon" class="wide-button primary">Set beacon name</button>`);$('save-beacon').onclick=()=>{e.deploy.name=$('beacon-name').value||'Beacon';e.name=e.deploy.name;this.ui.close();};}
  else if(e.type==='drop')this.ui.storage(e.drop.items,'Recovery cache');
  else if(e.type==='rocket')this.rocketMenu();
  else if(e.type==='base')this.baseInteract(e);
  else if(e.type==='interior')this.insideInteract(e);
 }
 gather(e){const needsKnife=['coral','tube','vine','eye','ghost','fungal','bulbSample','crown'].includes(e.item);if(needsKnife&&!this.has('knife')&&this.vehicle?.type!=='prawn'){this.ui.toast('A survival knife is required to take this sample.');return;}if(addItem(this.s,e.item)){this.world.collect(e);this.audio.effect('collect',e.pos);this.ui.toast('Collected '+ITEMS[e.item].name);this.refreshHotbar();}else this.ui.toast('Inventory full. Store materials or build equipment.');}
 lostPod(e){if(!this.s.opened.includes(e.id)){const loot={pod3:['water','battery'],pod17:['silver','silver','lead'],pod19:['ruby','gel','purple'],pod12:['diamond','diamond','lithium'],pod2:['nickel','nickel','ion']}[e.id]||['water'];this.s.containers[e.id]=loot.map(id=>makeItem(this.s,id));this.s.opened.push(e.id);if(e.id==='pod3'){storyAction(this.s,'pod3');this.ui.subtitle('The occupants are gone. The PDA has recovered a rendezvous signal near an island to the north.',8);}this.log(e.name,'A damaged escape pod. The occupants left supplies and fragment signatures. No survivors remain.');}this.ui.storage(this.s.containers[e.id],e.name);}
 insideInteract(e){const a=e.action;
 if(a==='exit'){this.leaveInterior();return;}if(a==='ladder'){const i=this.inside;if(i?.type==='pod'){this.leaveInterior();this.player.set(0,3.5,0);}else{this.ui.toast('Upper habitat decks are not implemented. This ladder is decorative.');}return;}
 if(['fabricator','modification','upgrade','cyclopsFabricator'].includes(a)){if(this.inside?.base&&(this.inside.base.power<5||this.inside.base.flood>.7)&&this.s.mode!=='creative'){this.ui.toast('Restore power and repair the flooded habitat.');return;}this.ui.crafting({fabricator:'Fabricator',modification:'Modification station',upgrade:'Vehicle upgrade console',cyclopsFabricator:'Cyclops fabricator'}[a]);return;}
 if(a==='locker'){let container;if(e.base)container=e.base.store;else if(this.inside.type==='cyclops')container=this.inside.entity.vehicle.storage;else {const id=this.inside.id;this.s.containers[id]||=[];container=this.s.containers[id];}this.ui.storage(container,e.name);return;}
 if(a==='radio'){const error=storyAction(this.s,'radio');if(error){this.ui.toast(error);return;}this.log('Radio restored','Lifepod 3 reported damaged equipment. Lifepod 17 sank near a red-grass plateau. Their signals are now available in the PDA.');this.ui.subtitle('Radio restored. Two distress signals have been downloaded to your PDA.',8);this.ui.notify('NEW SIGNALS RECEIVED');this.audio.effect('repair');return;}
 if(a==='helm'){const v=this.inside.entity.vehicle;this.leaveInterior();this.enterVehicle(v);return;}
 if(a==='charger'||a==='cellCharger'){const base=this.inside.base;const bat=this.s.inventory.filter(i=>(a==='charger'?['battery','ionBattery']:['cell','ionCell']).includes(i.id));const result=chargeBatteries(bat,base.power);base.power=result.power;const charged=result.charged;this.ui.toast(charged?'Charged '+Math.round(charged)+' units from habitat power.':'No stored power or depleted batteries.');return;}
 if(a==='bioreactor'){const item=this.s.inventory.find(i=>['peeper','bladderfish','acid','seed','melon','gel'].includes(i.id));if(item){this.s.inventory.splice(this.s.inventory.indexOf(item),1);e.base.fuel+=100;this.ui.toast('Bioreactor fueled.');}else this.ui.toast('Organic material required.');return;}
 if(a==='bed'){this.s.time+=300;this.time+=300;this.s.health=Math.min(100,this.s.health+10);this.ui.notify('Several hours pass.');return;}
 if(a==='driveCore'){if(!this.has('repair')){this.ui.toast('Repair tool required.');return;}this.s.flags.radiationRepaired=true;this.ui.notify('Drive core radiation leaks sealed');this.audio.effect('repair');return;}
 if(a==='prawnScan'){if(!this.has('scanner')){this.ui.toast('Scanner required.');return;}for(let i=0;i<4;i++)scanFragment(this.s,'prawn','aurora-prawn-'+i);this.ui.notify('Prawn suit blueprint acquired');return;}
 if(a==='terminal'){this.terminal();return;}
 if(a==='incubator'){this.runStory(this.s.flags.emperor?'hatch':'emperor');return;}if(a==='enzyme'){this.runStory('cure');return;}if(a==='portal'){if(!this.s.flags.emperor){this.ui.toast('Activate the incubator before using the arch.');return;}this.leaveInterior();this.player.set(370,10,-1140);this.yaw=0;this.ui.notify('Alien arch transit complete');this.audio.effect('emp');return;}
 if(a==='wreckDoor'){if(!this.has('cutter')){this.ui.toast('Laser cutter required.');return;}if(!this.consumeTool(2,'cutter'))return;this.s.flags[this.inside.id+'-cut']=true;this.audio.effect('cut');this.ui.notify('Sealed bulkhead cut open');return;}
 if(a==='wreckData'){if(!this.s.flags[this.inside.id+'-cut']){this.ui.toast('Cut the sealed bulkhead first.');return;}for(const bp of ['modification','reinforced'])if(!this.s.blueprints.includes(bp))this.s.blueprints.push(bp);this.ui.notify('Data box downloaded · Modification station / reinforced suit');}
 }
 terminal(){const id=this.inside.id;let name=this.inside.entity.name,action=id,text='';if(id==='qep'){action=this.s.flags.cured?'disable':'qep';text=this.s.flags.qep?'The platform enforces a planetary quarantine. The control terminal will reject infected individuals.':'Insert a purple tablet. This installation controls the weapon above the island.';}else if(id==='aurora')text='Repair the drive core and use the captain’s access code to download the Neptune escape rocket plans.';else if(id==='thermal')text='Insert a purple tablet to retrieve ion power schematics and a blue access tablet.';else if(id==='containment'){action='emperor';text='A living Sea Emperor remains below the facility. Insert a blue tablet and an ion cube to power the incubator.';}else if(id==='disease')text='The containment experiment failed. The Kharaa bacterium has spread beyond this research facility. Insert a purple tablet.';else if(id==='degasi1')text='The survivors left the island to build a deeper habitat. The recovered coordinates lead to Jellyshroom Cave.';else if(id==='degasi2')text='The survivors moved again, to a habitat five hundred metres below the surface in the Deep Grand Reef.';else if(id==='degasi3')text='A strange creature attacked the habitat. The survivors recorded a green brine river beneath the reef.';
 this.ui.panel(name,'RECOVERED TERMINAL',`<article class="log-card"><p>${text}</p></article>${id==='aurora'?'<label class="setting-row"><span>Captain’s access code</span><input id="captain-code" inputmode="numeric" maxlength="4" placeholder="4 digits"></label>':''}<button id="terminal-action" class="wide-button primary">${action==='disable'?'Disable quarantine platform':'Access terminal'}</button><p class="panel-note">This is condensed replacement text. Original PDA recordings are not included.</p>`,'terminal');$('terminal-action').onclick=()=>{if(id==='aurora'&&$('captain-code').value!=='2679'){this.ui.toast('Incorrect access code. The survival log contains the recovered code.');return;}if(this.runStory(action))this.ui.close();};
 }
 runStory(action){const before=!!this.s.flags[action],error=storyAction(this.s,action);if(error){this.ui.toast(error);return false;}const messages={qep:'Infection detected. The quarantine cannot be disabled. An Aurora data signature and Degasi rendezvous signal are available.',aurora:'Neptune blueprints recovered. The Aurora drive core has been stabilized.',degasi1:'Degasi habitat coordinates recovered: 250 metres.',degasi2:'Deeper habitat coordinates recovered: 500 metres. Modification and stasis blueprints restored.',degasi3:'A deep cave entrance has been marked. A green river runs beneath the crater.',disease:'Research data recovered. Thermal power signatures detected below one thousand metres.',thermal:'Ion power schematics downloaded. Blue tablet acquired.',emperor:'The incubator is active. Five plant samples are needed to synthesize hatching enzymes.',hatch:'The eggs are hatching. The young carry concentrated Enzyme 42.',cure:'Bacterial infection cleared. Return to the quarantine control terminal.',disable:'Quarantine enforcement disabled. The way home is open.'};this.ui.subtitle(messages[action]||'Data downloaded.',10);this.ui.notify(action==='cure'?'INFECTION CLEARED':'PDA UPDATED');this.audio.effect('scan');this.log(action==='cure'?'Cure confirmed':this.inside?.entity.name||'Discovery',messages[action]||'New data recovered.');this.refreshHotbar();return true;}
 log(title,text){if(!this.s.logs.some(l=>l.title===title&&l.text===text))this.s.logs.push({title,text,time:this.s.time});}
 baseInteract(e){const b=e.base;if(this.s.selected==='builder'){this.ui.panel(e.name,'HABITAT COMPONENT',`<p class="small-text">Hull ${Math.round(b.hp)}% · Power ${Math.round(b.power)} · Integrity ${hullIntegrity(this.s,b).toFixed(1)}</p><button id="enter-base" class="wide-button primary">Interact with component</button><button id="deconstruct" class="wide-button">Deconstruct and recover materials</button>`);$('enter-base').onclick=()=>{this.ui.close();this.s.selected='hands';this.setToolModel('hands');this.baseInteract(e);};$('deconstruct').onclick=()=>{this.deconstruct(b);this.ui.close();};return;}
 if(['room','corridor','glassCorridor','moonpool','observatory'].includes(b.type)){if(b.type==='moonpool'){const v=this.nearVehicle();if(v&&v.type!=='cyclops'){const transfer=Math.max(0,Math.min((v.capacity||100)-v.power,b.power));v.power+=transfer;b.power-=transfer;this.ui.toast('Moonpool charging transferred '+Math.round(transfer)+' power.');}}this.enterInterior(e);}else if(b.type==='hatch'){const room=this.entities.find(x=>x.base?.uid===b.parent);if(room)this.enterInterior(room);}else if(b.type==='growbed')this.growbed(b);else if(b.type==='locker')this.ui.storage(b.store,'Locker');else this.ui.toast(e.name+' · connected to nearby habitat.');}
 growbed(b){const s=this.s;const plants=['acid','seed','gel','eye','ghost','bulbSample','crown','deepMushroom','melon'];this.ui.panel('Growbed','CULTIVATION',`<p class="small-text">Plant a sample. Each planted sample yields two after five minutes of game time.</p><div class="storage-list">${s.inventory.filter(i=>plants.includes(i.id)).map(i=>`<button data-plant="${i.uid}">${icon(i.id)}Plant ${ITEMS[i.id].name}</button>`).join('')}</div>${b.plants.map((p,i)=>`<button class="wide-button" data-harvest="${i}">${ITEMS[p.id].name} · ${s.time-p.time>=300?'Harvest × 2':Math.ceil(300-(s.time-p.time))+'s remaining'}</button>`).join('')}`,'growbed');document.querySelectorAll('[data-plant]').forEach(el=>el.onclick=()=>{if(b.plants.length>=8){this.ui.toast('Growbed is full.');return;}const idx=s.inventory.findIndex(i=>i.uid===Number(el.dataset.plant)),i=s.inventory.splice(idx,1)[0];b.plants.push({id:i.id,time:s.time});this.growbed(b);});document.querySelectorAll('[data-harvest]').forEach(el=>el.onclick=()=>{const i=Number(el.dataset.harvest),p=b.plants[i];if(s.time-p.time<300)return;if(addItem(s,p.id,2)){b.plants.splice(i,1);this.growbed(b);}else this.ui.toast('Inventory full.');});}
 rocketMenu(){if(this.s.rocket<5){this.ui.crafting('Neptune platform');return;}this.ui.panel('Neptune ready','PRE-FLIGHT SYSTEMS',`<article class="log-card"><h3>${this.s.flags.disabled?'Quarantine disabled':'Quarantine active'}</h3><p>Power reserves charged. Life support ready. Launch sequence available when the alien enforcement platform is disabled.</p></article><button id="launch-rocket" class="wide-button primary" ${!this.s.flags.disabled?'disabled':''}>Launch Neptune</button>`,'rocket');$('launch-rocket').onclick=()=>{this.save();if(storyAction(this.s,'launch')===null){this.ui.close();this.launching=0;this.audio.effect('emp',null,1);}};}
 closeEnding(){this.launching=null;this.player.set(...(this.s.rocketPos||[0,0,0]));this.player.y=3;this.pitch=0;}
 useTool(pressed=false){if(this.ui.modal||!this.playing||this.paused)return;const id=this.s.selected,ent=this.target||this.closest();if(this.vehicle?.type==='prawn'&&ent?.type==='resource'&&pressed){if(!this.vehicle.modules.includes('drill'))this.gather(ent);return;}if(id==='hands'&&pressed){if(ent?.type==='resource'||ent?.type==='creature')this.interact();return;}if(id==='knife'&&pressed){if(ent?.type==='resource')this.gather(ent);else if(ent?.creature){const c=ent.creature;c.health-=20;c.state='retreat';c.timer=0;if(c.health<=0&&!['reaper','ghost','dragon','reefback'].includes(c.species)){c.object.visible=false;c.caught=true;this.world.entities.delete(c.id);}this.audio.effect('impact',c.pos,.3);}return;}if(id==='builder'&&pressed&&!this.buildPreview){this.ui.construction();return;}if(id==='airBladder'&&pressed){this.velocity.y=14;this.ui.notify('Emergency buoyancy');return;}if(id==='light'&&pressed){this.flash=!this.flash;return;}if(id==='stasis'&&pressed&&this.consumeTool(4)){for(const c of this.world.creatures)if(c.pos.distanceTo(this.player)<35&&c.pos.clone().sub(this.player).normalize().dot(this.forward())>.85)c.stunned=15;this.audio.effect('emp');this.ui.notify('Stasis field deployed');}if(id==='propulsion'&&pressed&&this.consumeTool(2)){if(ent?.type==='resource'){ent.pos.copy(this.player).addScaledVector(this.forward(),2);if(ent.object)ent.object.position.copy(ent.pos);if(ent.instances)for(const m of ent.instances){const matrix=new T.Matrix4();m.getMatrixAt(ent.instanceIndex,matrix);matrix.setPosition(ent.pos);m.setMatrixAt(ent.instanceIndex,matrix);m.instanceMatrix.needsUpdate=true;}}if(ent?.creature){ent.creature.pos.addScaledVector(this.forward(),8);ent.creature.state='retreat';}this.audio.effect('emp',null,.4);}}
 updateTool(dt){if(this.vehicle?.type==='prawn'&&this.vehicle.modules.includes('drill')&&this.mouseDown&&!this.ui.modal){const e=this.target||this.closest();if(e?.type==='resource'&&(this.vehicle.power>0||this.s.mode==='creative')){if(this.drillTarget!==e.id){this.drillTarget=e.id;this.drillTime=0;}this.drillTime=(this.drillTime||0)+dt;this.vehicle.power=Math.max(0,this.vehicle.power-dt*.35);if(Math.floor(this.time*5)!==this.drillTick){this.drillTick=Math.floor(this.time*5);this.audio.effect('repair',e.pos,.4);}if(this.drillTime>1.3){const before=this.s.inventory.length;this.gather(e);if(this.s.inventory.length>before&&['titanium','copper','quartz','silver','gold','lead','lithium','diamond','ruby','nickel','kyanite','magnetite'].includes(e.item))addItem(this.s,e.item);this.drillTime=0;}}return;}if(!this.mouseDown||this.paused||this.buildPreview){this.scanTime=0;$('scan-progress').classList.add('hidden');return;}const e=this.target,id=this.s.selected;if(id==='scanner'&&e&&['fragment','creature','resource'].includes(e.type)){
  const key=e.type==='creature'?'species:'+e.creature.species:e.type==='resource'?'plant:'+e.item:e.id;if(this.s.scans.includes(key)){this.ui.notify('Already scanned');return;}if(!this.consumeTool(dt*.35))return;if(this.scanTarget!==key){this.scanTarget=key;this.scanTime=0;}this.scanTime=(this.scanTime||0)+dt;const duration=e.type==='fragment'?3:4;const percent=Math.min(100,this.scanTime/duration*100);$('scan-progress').classList.remove('hidden');$('scan-progress').querySelector('i').style.width=percent+'%';$('scan-progress').querySelector('b').textContent=Math.floor(percent)+'%';if(Math.floor(this.scanTime*3)!==this.lastScanTick){this.lastScanTick=Math.floor(this.scanTime*3);this.audio.effect('scan',e.pos,.4);}if(this.scanTime>=duration){if(e.type==='fragment'){scanFragment(this.s,e.blueprint,e.id);this.ui.notify(this.s.blueprints.includes(e.blueprint)?'BLUEPRINT ACQUIRED · '+(ITEMS[e.blueprint]?.name||e.blueprint):'Fragment scanned · '+this.s.fragments[e.blueprint]+'/'+FRAGMENT_COUNTS[e.blueprint]);}else{this.s.scans.push(key);this.ui.notify('Databank entry recorded');}this.scanTime=0;$('scan-progress').classList.add('hidden');this.mouseDown=false;}
 }else if(id==='repair'&&e&&(e.vehicle||e.base)&&this.consumeTool(dt*.3)){const target=e.vehicle||e.base;target.hp=Math.min(e.vehicle?VEHICLES[target.type].hp:100,target.hp+dt*25);if(e.base&&hullIntegrity(this.s,target)>0)target.flood=Math.max(0,target.flood-dt*.12);if(Math.floor(this.time*5)!==this.repairTick){this.audio.effect('repair',e.pos,.5);this.repairTick=Math.floor(this.time*5);}}else if(id==='cutter'&&e?.action==='wreckDoor'){if(this.consumeTool(dt))this.s.flags[this.inside.id+'-cut']=true;}
 }
 updateMovement(dt){const k=this.settings.keys,pressed=key=>this.keys.has(k[key]);if(this.keys.has('ArrowLeft'))this.yaw+=dt*1.2;if(this.keys.has('ArrowRight'))this.yaw-=dt*1.2;if(this.keys.has('ArrowUp'))this.pitch=Math.min(1.5,this.pitch+dt);if(this.keys.has('ArrowDown'))this.pitch=Math.max(-1.5,this.pitch-dt);
 const f=this.forward(),right=new T.Vector3(Math.cos(this.yaw),0,-Math.sin(this.yaw)),move=new T.Vector3();const vertical=(pressed('up')?1:0)-(pressed('down')?1:0);move.addScaledVector(f,(pressed('forward')?1:0)-(pressed('back')?1:0));move.addScaledVector(right,(pressed('right')?1:0)-(pressed('left')?1:0));move.y+=vertical;
 let speed=4.7*(this.s.equipment.fins?1.15:1);if(this.s.selected==='seaglide'&&this.selectedItem()?.charge>0||this.s.mode==='creative'&&this.s.selected==='seaglide')speed=9.5;if(pressed('sprint'))speed*=1.32;if(this.inside){speed=3.4;move.y=0;}else if(this.player.y>1){speed=4;move.y=0;}
 if(this.vehicle){speed=VEHICLES[this.vehicle.type].speed*(this.vehicle.silent?.45:1);if(this.vehicle.power<=0&&this.s.mode!=='creative')speed=0;if(this.vehicle.type==='prawn'){move.y=vertical>0&&(this.vehicle.power>0||this.s.mode==='creative')?1.4:-.15;speed=this.vehicle.power>0||this.s.mode==='creative'?7:0;}}
 if(this.demo&&this.vehicle&&this.demo.boost(dt,pressed('sprint'),move.lengthSq()>.01))speed*=1.85;if(this.vehicle?.grabbedUntil>this.time)speed*=.1;this.moving=move.lengthSq()>.01;if(move.lengthSq()>1)move.normalize();const desired=move.multiplyScalar(speed);this.velocity.lerp(desired,1-Math.exp(-dt*(this.inside?10:3)));if(this.grappleTarget){if(!this.vehicle||this.time>this.grappleUntil||this.player.distanceTo(this.grappleTarget)<4)this.clearGrapple();else{this.velocity.addScaledVector(this.grappleTarget.clone().sub(this.player).normalize(),dt*28);this.grappleLine.geometry.setFromPoints([this.player.clone().add(new T.Vector3(-1,-1,0)),this.grappleTarget]);this.moving=true;}}
 const to=this.player.clone().addScaledVector(this.velocity,dt);if(this.inside){const {origin,size}=this.inside;to.x=clamp(to.x,origin.x-size[0]+.45,origin.x+size[0]-.45);to.z=clamp(to.z,origin.z-size[2]+.45,origin.z+size[2]-.45);to.y=origin.y+1.25;const sealed=this.inside.type==='wreck'&&!this.s.flags[this.inside.id+'-cut'];if(sealed)to.z=Math.min(to.z,origin.z-.1);}else{if(this.vehicle?.type==='prawn')to.y-=dt*2.5;moveWithCollision(this.player,to,this.vehicle?VEHICLES[this.vehicle.type].radius:.6);if(to.y>0&&surfaceHeight(to.x,to.z)<-1&&!this.keys.has(k.up)&&desired.y>=-.01)to.y=Math.max(.35,to.y-dt*5);if(to.y>1.5&&surfaceHeight(to.x,to.z)<0)to.y=Math.min(to.y,1.5);if(to.y>surfaceHeight(to.x,to.z)+1.3&&surfaceHeight(to.x,to.z)>0)to.y-=dt*7;}
 this.player.copy(to);if(this.vehicle){this.vehicle.pos=this.player.toArray();this.vehicle.yaw=this.yaw;const o=this.vehicleMeshes.get(this.vehicle.uid);o.position.copy(this.player);o.rotation.y=this.yaw;}
 if(this.moving&&this.s.selected==='seaglide'&&!this.vehicle&&!this.inside)this.consumeTool(dt*.14);
 }
 damage(amount,cause='environment'){if(this.s.mode==='creative'||this.dead||this.launching!==undefined&&this.launching!==null)return;const v=this.vehicle;if(v){if(cause==='reaper')v.grabbedUntil=this.time+2;if((v.shieldUntil||0)>this.time)amount*=.1;v.hp-=amount*3;if(v.hp<=0){v.hp=0;if(this.demo){this.demo.fail(cause);return;}this.exitVehicle();this.s.vehicles=this.s.vehicles.filter(x=>x.uid!==v.uid);const obj=this.vehicleMeshes.get(v.uid);this.worldGroup.remove(obj);this.entities=this.entities.filter(e=>e.vehicle?.uid!==v.uid);this.vehicleMeshes.delete(v.uid);this.ui.notify('VEHICLE LOST');this.audio.effect('impact',this.player,1);}}else this.s.health-=amount;this.damageFlash=Math.min(1,(this.damageFlash||0)+.5);this.shake=Math.min(.08,amount*.002);if(this.s.health<=0)this.die(cause);}
 updateSurvival(dt){const s=this.s,depth=Math.max(0,-this.player.y),creative=s.mode==='creative';const sheltered=this.inside&&this.inside.type!=='wreck'&&this.inside.type!=='degasi'&&(!this.inside.base||this.inside.base.power>0&&this.inside.base.flood<.7);const oxygenated=depth<1||sheltered||this.vehicle&&this.vehicle.power>0;
 if(!creative){if(oxygenated)s.oxygen=Math.min(maxOxygen(s),s.oxygen+dt*15);else{s.oxygen=Math.max(0,s.oxygen-dt*(depth>200&&!s.equipment.head?3:depth>100&&!s.equipment.head?2:1));if(s.oxygen<=0)this.damage(dt*15,'drowning');}if(['survival','hardcore'].includes(s.mode)){s.food=Math.max(0,s.food-dt/42);s.water=Math.max(0,s.water-dt/30);if(s.food<=0||s.water<=0)this.damage(dt*.45,'dehydration');}
  if(!s.flags.radiationRepaired&&this.player.distanceTo(new T.Vector3(1110,0,220))<310&&s.equipment.suit?.id!=='radiation'&&!this.inside&&(!this.vehicle||this.vehicle.type==='prawn')){this.damage(dt*1.2,'radiation');if(Math.floor(this.time)%12===0)this.ui.notify('RADIATION DETECTED');}
  if(depth>1050&&!this.vehicle&&!this.inside&&s.equipment.suit?.id!=='reinforced')this.damage(dt*2,'heat');
  if(this.vehicle){const v=this.vehicle;if(v.lights!==false)v.power=Math.max(0,v.power-dt*.006);if(this.moving)v.power=Math.max(0,v.power-dt*(v.type==='cyclops'?.035:v.type==='prawn'?.025:.045)*(v.silent?1.8:1));if(depth>depthLimit(v)){this.damage(dt*2,'crush depth');if(this.time-(this.lastCrushWarning||0)>7){this.lastCrushWarning=this.time;this.audio.warning('Warning. Maximum depth exceeded. Hull damage imminent.');this.ui.subtitle('Warning: maximum depth exceeded. Hull damage imminent.');}}}
  if(!oxygenated&&s.mode!=='hardcore'){const band=s.oxygen<10?9:s.oxygen<30?30:0;if(band&&this.lastOxygenWarning!==band){this.lastOxygenWarning=band;this.audio.warning(band===30?'Thirty seconds of oxygen remaining.':'Oxygen.');this.ui.subtitle(band===30?'PDA: 30 seconds of oxygen remaining.':'PDA: Oxygen.',4);}}else this.lastOxygenWarning=0;
 }else{s.oxygen=maxOxygen(s);s.health=100;s.food=100;s.water=100;}
 if(this.flash&&!this.vehicle&&this.has('light')){const item=s.inventory.find(i=>i.id==='light');if(item&&item.charge>0)this.consumeTool(dt*.10,'light');else if(!creative)this.flash=false;}
 for(const b of s.bases){if(!['room','corridor','glassCorridor','moonpool','observatory'].includes(b.type))continue;let generation=0;const parts=s.bases.filter(x=>Math.hypot(x.pos[0]-b.pos[0],x.pos[1]-b.pos[1],x.pos[2]-b.pos[2])<45);for(const part of parts){if(part.type==='solar')generation+=Math.max(0,Math.sin(this.time/1200*Math.PI*2+.7))*Math.max(0,1+part.pos[1]/200)*1.5;if(part.type==='thermal'&&part.pos[1]<-900)generation+=2;if(part.type==='bioreactor'&&part.fuel>0){generation+=1;part.fuel=Math.max(0,part.fuel-dt*.2);}}
 b.power=clamp(b.power+dt*(generation-.02),0,150+parts.filter(x=>['solar','thermal','bioreactor'].includes(x.type)).length*75);const integrity=hullIntegrity(s,b);if(integrity<0){b.hp=Math.max(0,b.hp-dt*.03*Math.abs(integrity));if(b.hp<95)b.flood=Math.min(1,b.flood+dt*.003);}else if(b.hp>95&&b.power>0)b.flood=Math.max(0,b.flood-dt*.015);
 }
 }
 die(cause){if(this.demo){this.demo.fail(cause);return;}if(this.dead)return;this.dead=true;this.s.deathCount++;this.audio.warning('Life signs lost.');if(this.s.mode==='hardcore'){localStorage.removeItem('crater-save-'+this.slot);localStorage.removeItem('crater-backup-'+this.slot);}else{const loose=this.s.inventory.filter(i=>!this.s.safeItems.includes(i.uid)&&ITEMS[i.id].kind!=='tool');this.s.inventory=this.s.inventory.filter(i=>!loose.includes(i));if(loose.length)this.s.drops.push({uid:this.s.uid++,pos:this.player.toArray(),items:loose});}this.ui.death(this.s.mode==='hardcore');}
 respawn(){if(this.vehicle)this.exitVehicle();if(this.inside)this.leaveInterior();this.player.set(0,-2,5);this.s.health=100;this.s.oxygen=maxOxygen(this.s);this.s.food=Math.max(40,this.s.food);this.s.water=Math.max(40,this.s.water);this.dead=false;this.ui.close();this.syncPersistent();this.enterInterior(this.world.entities.get('pod'));this.refreshHotbar();}
 getSignals(all=false){if(this.demo){const sigs=[{id:'service',name:'Service buoy · Repair & recharge',pos:new T.Vector3(...DEMO_HOME)}];for(const v of this.s.vehicles)if(v!==this.vehicle)sigs.push({id:'v-'+v.uid,name:'Seamoth',pos:new T.Vector3(...v.pos)});return sigs;}const s=this.s,ids=['pod'];if(s.flags.radio)ids.push('pod3','pod17');if(s.flags.pod3)ids.push('qep');if(s.flags.qep)ids.push('aurora','floating','degasi1');if(s.flags.degasi1)ids.push('degasi2');if(s.flags.degasi2)ids.push('degasi3');if(s.flags.degasi3)ids.push('disease');if(s.flags.disease)ids.push('thermal');if(s.flags.thermal)ids.push('containment');const sigs=[];for(const id of ids){const l=LANDMARKS.find(l=>l.id===id);if(!l||id==='floating')continue;if(!all&&s.flags['hide-'+id])continue;if(!all&&id!=='pod'&&s.flags[id]&&!(id==='qep'&&s.flags.cured&&!s.flags.disabled))continue;sigs.push({id,name:l.name,pos:new T.Vector3(...l.pos)});}
 if(s.flags.degasi1&&!s.flags.degasi2)sigs.push({id:'jelly-mouth',name:'Jellyshroom Cave entrance',pos:new T.Vector3(-360,-95,230)});if(s.flags.degasi2&&!s.flags.degasi3)sigs.push({id:'grand-mouth',name:'Deep Grand Reef entrance',pos:new T.Vector3(-530,-340,1020)});if(s.flags.degasi3&&!s.flags.disease)sigs.push({id:'river-mouth',name:'Blood Kelp Trench entrance',pos:new T.Vector3(-1030,-330,470)});
 if(s.flags.disease&&!s.flags.thermal)sigs.push({id:'lava-mouth',name:'Thermal passage',pos:new T.Vector3(210,-1040,-140)});if(s.flags.thermal&&!s.flags.emperor)sigs.push({id:'lakes-mouth',name:'Lava Lakes passage',pos:new T.Vector3(190,-1340,170)});
 for(const b of s.beacons)if(all||!s.flags['hide-deploy-'+b.uid])sigs.push({id:'deploy-'+b.uid,name:b.name,pos:new T.Vector3(...b.pos)});for(const v of s.vehicles)if(v!==this.vehicle)sigs.push({id:'v-'+v.uid,name:VEHICLES[v.type].name,pos:new T.Vector3(...v.pos)});for(const d of s.drops)if(d.items.length)sigs.push({id:'d-'+d.uid,name:'Recovery cache',pos:new T.Vector3(...d.pos)});if(s.rocket)sigs.push({id:'rocket',name:'Neptune',pos:new T.Vector3(...s.rocketPos)});return sigs;
 }
 updateHUD(){const s=this.s,depth=Math.max(0,Math.round(-this.player.y));$('depth-value').textContent=depth;$('depth-limit').textContent=this.vehicle?'/ '+depthLimit(this.vehicle):'';$('depth-value').style.color=this.vehicle&&depth>depthLimit(this.vehicle)?'#ff8f68':'';const heading=T.MathUtils.euclideanModulo(-this.yaw*180/Math.PI,360),comp=['N','NE','E','SE','S','SW','W','NW'][Math.round(heading/45)%8];$('compass').textContent=s.equipment.chip?.id==='compass'||this.vehicle||s.mode==='creative'?'·  '+comp+'  ·':'·';$('temperature').textContent=Math.round(depth>1000?49+(depth-1000)*.03:Math.max(8,26-depth*.025))+'°C';$('power-reading').textContent=this.vehicle?'POWER '+Math.round(this.vehicle.power)+'%':this.inside?'INTERIOR':'O₂ ENVIRONMENT';$('oxygen-value').textContent=Math.ceil(s.oxygen);$('oxygen-max').textContent='/ '+maxOxygen(s);$('oxygen-ring').style.strokeDashoffset=302*(1-s.oxygen/maxOxygen(s));$('oxygen-ring').style.stroke=s.oxygen<15?'#ff8e73':'#f3ce80';for(const k of ['health','food','water']){$(k+'-value').textContent=Math.max(0,Math.ceil(s[k]));$(k+'-bar').style.width=clamp(s[k],0,100)+'%';}$('biome-name').textContent=this.inside?this.inside.entity.name.toUpperCase():this.biome.name.toUpperCase();$('location-label').textContent=this.inside?'SHELTER':this.vehicle?'VEHICLE EXPLORATION':'BIOME';const minutes=Math.floor(this.time%1200/1200*1440),hours=Math.floor(minutes/60);$('day-readout').textContent='DAY '+String(1+Math.floor(this.time/1200)).padStart(2,'0')+' · '+String((hours+8)%24).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');const q=nextStory(s,STORY);$('objective-title').textContent=q.title;$('objective').querySelector('p span').textContent=String(STORY.indexOf(q)+1).padStart(2,'0');$('objective-hint').textContent=this.buildPreview?'Click to construct · R to rotate':'Tab · Survival log for guidance';
 const e=this.target;if(e){const name=e.type==='resource'?ITEMS[e.item].name:e.type==='fragment'?(ITEMS[e.blueprint]?.name||e.blueprint)+' fragment':e.type==='creature'?this.speciesName(e.creature.species):e.name;let hint=e.type==='fragment'?'Scanner · Hold left mouse button':e.type==='resource'?'Collect sample':e.type==='creature'?'Catch / scan':'Interact';$('interaction').innerHTML=`<kbd>${this.ui.keyName(this.settings.keys.interact)}</kbd>${escapeHTML(name)}<small>${hint}</small>`;}else $('interaction').innerHTML='';
 $('vehicle-status').classList.toggle('hidden',!this.vehicle);if(this.vehicle){const v=this.vehicle;$('vehicle-status').innerHTML=`<strong>${VEHICLES[v.type].name.toUpperCase()}</strong> HULL ${Math.round(v.hp/VEHICLES[v.type].hp*100)}% &nbsp; ⚡ ${Math.round(v.power/(v.capacity||100)*100)}%<small>${v.type==='cyclops'?'E · Walk inside &nbsp; V · Silent running &nbsp; ':''}${v.type==='prawn'?'G · Grapple &nbsp; ':''}Q · Exit &nbsp; R · Power cell &nbsp; X · Defense</small>`;}
 this.hotbar?.forEach((id,i)=>{const item=s.inventory.find(x=>x.id===id);const el=$('slot-charge-'+i);if(el)el.textContent=item?.charge!==undefined?Math.round(item.charge)+'%':'';});
 const signals=this.getSignals().filter(sig=>sig.pos.distanceTo(this.player)>8).sort((a,b)=>a.pos.distanceTo(this.player)-b.pos.distanceTo(this.player));let html='';for(const sig of signals.slice(0,8)){const v=sig.pos.clone().project(this.camera);if(v.z>1||Math.abs(v.x)>1.05||Math.abs(v.y)>1.05)continue;const x=(v.x*.5+.5)*innerWidth,y=(-v.y*.5+.5)*innerHeight;html+=`<div class="beacon" style="left:${x}px;top:${y}px"><i>◇</i><span>${escapeHTML(sig.name)}</span><small>${Math.round(sig.pos.distanceTo(this.player))}m</small></div>`;}$('beacons').innerHTML=html;if(this.demo)this.demo.hud();
 }
 updateEnvironment(dt){M.causticStrength.value=this.inside?0:1;const underwater=this.player.y<.15&&!this.inside;this.biome=biomeAt(this.player.x,this.player.y,this.player.z);if(!this.s.discovered.includes(this.biome.id)&&this.playing){this.s.discovered.push(this.biome.id);this.ui.notify(this.biome.name.toUpperCase());if(['river','lava','blood','trench','void'].includes(this.biome.id))this.ui.subtitle(this.biome.id==='void'?'PDA: Ecological dead zone. The crater shelf ends here.':'PDA: Entering '+this.biome.name+'. Monitor oxygen and vehicle depth.',6);}
 const bio=this.biome;const target=new T.Color(this.inside?0x15343f:underwater?bio.color:0x9fbfc7);this.scene.fog.color.lerp(target,Math.min(1,dt*1.5));this.scene.background.copy(this.scene.fog.color);const fogTarget=this.inside?.002:underwater?bio.fog:.00045;this.scene.fog.density=T.MathUtils.lerp(this.scene.fog.density,fogTarget,dt*1.5);this.sky.visible=this.player.y>.15;this.sky.position.copy(this.player);this.waterUniforms.under.value=underwater?1:0;this.water.visible=true;this.waterUniforms.roomActive.value=this.inside?1:0;if(this.inside){const i=this.inside;this.waterUniforms.roomMin.value.set(i.origin.x-i.size[0]-.2,i.origin.z-i.size[2]-.2);this.waterUniforms.roomMax.value.set(i.origin.x+i.size[0]+.2,i.origin.z+i.size[2]+.2);}this.shafts.visible=underwater&&this.player.y>-90;this.shafts.position.set(Math.floor(this.player.x/40)*40,0,Math.floor(this.player.z/40)*40);const day=.3+.7*Math.max(0,Math.sin(this.time/1200*Math.PI*2+.7));this.sun.intensity=T.MathUtils.lerp(this.sun.intensity,(this.inside?.1:bio.light)*day*3,dt);this.ambient.intensity=T.MathUtils.lerp(this.ambient.intensity,this.inside?.4:underwater?bio.light*1.4:1.5,dt);this.fill.intensity=this.inside?.05:this.player.y<-600?2:1.7;this.sun.position.copy(this.player).add(new T.Vector3(70,130,-70));this.sun.target.position.copy(this.player);this.spot.visible=this.vehicle?this.vehicle.lights!==false:this.flash&&this.has('light');this.spot.intensity=this.vehicle?120:95;this.spot.distance=this.vehicle?75:52;
 if(this.wasUnder!==undefined&&this.wasUnder!==underwater&&!this.inside){this.audio.effect('splash');$('surface-drops').style.opacity=underwater?0:1;setTimeout(()=>$('surface-drops').style.opacity=0,1600);}this.wasUnder=underwater;if(this.inside?.base){this.interiorLight.intensity=this.inside.base.power>0?18:1;if(!this.floodPlane){this.floodPlane=M.mesh(new T.PlaneGeometry(8,8),M.MAT.glass,this.insideGroup,[0,0,0]);this.floodPlane.rotation.x=-Math.PI/2;}this.floodPlane.position.y=-.2+this.inside.base.flood*3;this.floodPlane.visible=this.inside.base.flood>.02;}else this.floodPlane=null;
 }
 frame(now){const dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.frameCount++;this.frameTimes.push(Math.min(5,Math.max(.001,(now-(this.previousFrame||now-16.7))/1000)));this.previousFrame=now;if(this.frameTimes.length>60)this.frameTimes.shift();this.fps=1/(this.frameTimes.reduce((a,b)=>a+b,0)/this.frameTimes.length);M.clockUniform.value=now/1000;
  if(!this.playing){this.time+=dt;this.player.set(12+Math.sin(this.time*.04)*4,-6.5,39);this.yaw=.18+Math.sin(this.time*.027)*.045;this.pitch=-.29;}
  else if(!this.paused&&!this.dead){this.time+=dt;this.s.time=this.time;this.updateMovement(dt);this.updateSurvival(dt);if(this.demo&&!this.dead)this.demo.update(dt);this.updateBuild();this.target=this.closest();this.updateTool(dt);if(this.launching!==undefined&&this.launching!==null){this.launching+=dt;this.player.y+=this.launching*dt*14;this.pitch=.35;if(this.launching>12){this.launching=null;this.ui.ending();}}
  }
  this.camera.position.copy(this.player);this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');if(this.settings.motion&&this.moving&&!this.paused&&this.playing&&!this.vehicle){this.camera.position.y+=Math.sin(this.time*3)*.027;this.toolRoot.rotation.z=Math.sin(this.time*3)*.025;}if(this.shake>0){this.camera.rotation.z=(Math.random()-.5)*this.shake;this.shake=Math.max(0,this.shake-dt*.04);}this.updateEnvironment(dt);
  if(!this.playing||!this.paused){this.world.update(this.player,dt,this.time,this.audio,(n,c)=>this.damage(n,c),this.vehicle,!!this.inside||this.s.mode==='creative'||!!this.demo);}
  if(this.playing&&!this.paused){this.audio.update({pos:this.player,forward:this.forward(),up:new T.Vector3(0,1,0),biome:this.biome.id,depth:Math.max(0,-this.player.y),inside:!!this.inside,vehicle:this.vehicle,moving:this.moving,oxygen:this.s.oxygen,time:this.time});}
  this.toolRoot.visible=this.playing&&!this.vehicle&&!this.ui.modal&&this.s.selected!=='hands';this.cockpit.visible=!!this.vehicle&&this.playing;this.damageFlash=Math.max(0,(this.damageFlash||0)-dt*.5);$('damage').style.opacity=this.damageFlash;this.renderer.render(this.scene,this.camera);if(this.playing&&this.frameCount%5===0)this.updateHUD();requestAnimationFrame(t=>this.frame(t));
 }
 snapshot(){this.s.position=this.player.toArray();this.s.yaw=this.yaw;this.s.pitch=this.pitch;this.s.time=this.time;this.s.activeVehicle=this.vehicle?.uid||null;this.s.inside=this.inside?.id||null;return serialize(this.s);}
 save(){if(this.demo){try{localStorage.setItem('crater-demo-save',this.snapshot());this.ui.toast('Submarine demo saved.');}catch(error){this.ui.toast('Save failed: '+error.message);}return;}if(this.dead&&this.s.mode==='hardcore')return;try{const raw=this.snapshot();deserialize(raw);const key='crater-save-'+this.slot,previous=localStorage.getItem(key);if(previous)localStorage.setItem('crater-backup-'+this.slot,previous);localStorage.setItem(key,raw);this.ui.toast('Expedition saved · slot '+this.slot);this.audio.effect('click');}catch(error){this.ui.toast('Save failed: '+error.message+' Export a save file from the save menu.');}}
 load(slot){try{const key='crater-save-'+slot;let raw=localStorage.getItem(key);if(!raw){this.ui.toast('This save slot is empty.');return;}let s;try{s=deserialize(raw);}catch(error){const backup=localStorage.getItem('crater-backup-'+slot);if(!backup)throw error;s=deserialize(backup);this.ui.toast('Recovered the preceding valid save.');}this.slot=slot;this.entities=[];this.startState(s);this.ui.notify('EXPEDITION RESTORED');}catch(error){this.ui.toast('Could not load: '+error.message);}}
 saveInfo(slot){try{const raw=localStorage.getItem('crater-save-'+slot);if(!raw)return null;const obj=JSON.parse(raw);return obj.state.mode+' · Day '+(1+Math.floor(obj.state.time/1200))+' · '+new Date(obj.savedAt).toLocaleString();}catch{return 'Damaged save · recovery will be attempted';}}
 exportSave(slot){let raw=localStorage.getItem('crater-save-'+slot);if(!raw&&this.playing)raw=this.snapshot();if(!raw)return;const blob=new Blob([raw],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='subnautica-crater-slot-'+slot+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
 importSave(raw){try{const s=deserialize(raw);this.entities=[];this.startState(s);this.ui.toast('Imported save loaded. Save to a slot to keep it in this browser.');}catch(error){this.ui.toast('Import rejected: '+error.message);}}
 returnToMenu(save=true){document.body.classList.remove('demo-mode','piloting');if(save&&this.playing&&!this.dead)this.save();if(this.vehicle)this.exitVehicle();if(this.inside)this.leaveInterior();this.playing=false;this.paused=true;this.ui.modal=null;$('modal-layer').classList.add('hidden');$('hud').classList.add('hidden');$('main-menu').classList.remove('hidden');document.exitPointerLock?.();this.keys.clear();}
 audioTest(){this.audio.start().then(()=>{this.ui.toast('Audio test: left, right, behind, then warning.');const left=this.player.clone().add(new T.Vector3(-10,0,0).applyAxisAngle(new T.Vector3(0,1,0),this.yaw)),right=this.player.clone().add(new T.Vector3(10,0,0).applyAxisAngle(new T.Vector3(0,1,0),this.yaw)),back=this.player.clone().addScaledVector(this.forward(),-12);this.audio.update({pos:this.player,forward:this.forward(),up:new T.Vector3(0,1,0),biome:'shallows',depth:5,inside:false,vehicle:null,moving:false,oxygen:45,time:this.time});this.audio.tone(450,1,.4,'sine',left);setTimeout(()=>this.audio.tone(550,1,.4,'sine',right),1400);setTimeout(()=>this.audio.call('reefback',back),3000);setTimeout(()=>this.audio.warning('Thirty seconds of oxygen remaining.'),4800);});}
 speciesName(id){return {peeper:'Peeper',bladderfish:'Bladderfish',stalker:'Stalker',sandshark:'Sand Shark',reefback:'Reefback Leviathan',crabsquid:'Crabsquid',reaper:'Reaper Leviathan',ghost:'Ghost Leviathan',dragon:'Sea Dragon Leviathan',emperor:'Sea Emperor Leviathan',treader:'Sea Treader'}[id]||id;}
 speciesDescription(id){return {peeper:'A small, fast fish with a prominent eye and yellow fins. Edible after cooking.',bladderfish:'A translucent organism that can be processed into filtered water.',stalker:'A territorial kelp-forest predator. Keep distance and retreat through vegetation.',sandshark:'An ambush predator close to the sandy floor of the plateaus.',reefback:'A slow, peaceful leviathan carrying an ecosystem on its back. Its low-frequency calls travel far.',reaper:'A large predator with four grasping mandibles. Found near the Aurora, Dunes and Mountains. Its call indicates a nearby animal.',ghost:'A long, bioluminescent territorial leviathan. Give it room. Vehicle noise attracts attention.',dragon:'A vast predator inhabiting the lava caverns. Its home is too hot for an unprotected diver.',crabsquid:'A many-limbed predator of the deep reef. Stay clear of its reach.',treader:'A large benthic herbivore found on the Sea Treader’s Path.'}[id]||'An organism adapted to the crater ecosystem.';}
}
try{new Game();}catch(error){console.error(error);$('load-message').textContent='Unable to start WebGL: '+error.message;}
