import {ITEMS,RECIPES,BUILDS,STORY,LANDMARKS,FRAGMENT_COUNTS} from './data.js';
import {pack,counts,canPay,maxOxygen,nextStory,serialize} from './state.js';
const $=id=>document.getElementById(id);
export const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={
 scanner:'<path d="M22 42l-4 16 11 4 6-19M13 22q17-10 39 0v18H13z" fill="#dce9e3"/><path d="M23 18V8h24v14" fill="#152d3d"/><path d="M27 12h16v5H27z" fill="#75e9d8"/><path d="M48 26h10v9H48" fill="#e9b962"/>',
 repair:'<path d="M25 36l-4 25 11 2 8-25" fill="#25444b"/><path d="M9 21h37l11 10-7 9H12z" fill="#e2e9df"/><path d="M12 21h21v7H12z" fill="#e7b257"/><circle cx="51" cy="31" r="6" fill="#53d7df"/>',
 cutter:'<path d="M25 36l-4 25 11 2 8-25" fill="#25444b"/><path d="M9 21h35l11 10-7 9H12z" fill="#e2e9df"/><path d="M12 21h21v7H12z" fill="#e7b257"/><path d="M48 31h15" stroke="#71e9f5" stroke-width="4"/>',
 light:'<path d="M16 20l30 6v22l-30 6z" fill="#c9dce0"/><path d="M11 22h10v30H11z" fill="#355966"/><ellipse cx="47" cy="37" rx="9" ry="13" fill="#b2ece9"/><path d="M47 27v20" stroke="#e6fbf1" stroke-width="5"/>',
 knife:'<path d="M22 44L45 5q12 17-14 43" fill="#d2e9e8"/><path d="M14 59l9-18 10 6-9 16z" fill="#dfb65c"/><path d="M19 42l17 9" stroke="#22464d" stroke-width="5"/>',
 seaglide:'<ellipse cx="32" cy="32" rx="24" ry="16" fill="#cce0dc"/><ellipse cx="32" cy="39" rx="18" ry="10" fill="#36505a"/><path d="M11 29L4 45l13 7m36-23 7 16-13 7" fill="none" stroke="#cce0dc" stroke-width="4"/><path d="M25 24h15v11H25z" fill="#67dfe2"/>',
 builder:'<path d="M25 35l-4 25 11 2 8-25" fill="#25444b"/><path d="M10 16h36l9 13-8 13H11z" fill="#e2e9df"/><path d="M18 16h22v8H18z" fill="#e7b257"/><path d="M48 24h14v10H48" fill="#5dddc8"/>',
 tank:'<rect x="19" y="14" width="27" height="45" rx="12" fill="#d9e8e0"/><path d="M24 4h16v14H24z" fill="#254751"/><path d="M19 30h27v11H19z" fill="#e4b95d"/><path d="M18 26h28m-28 20h28" stroke="#244f60" stroke-width="4"/>',
 battery:'<rect x="23" y="13" width="20" height="43" rx="3" fill="#364854"/><path d="M23 13h20v12H23z" fill="#ecc66c"/><path d="M27 8h12v5H27z" fill="#dbe8e4"/><path d="M29 31h8m-4-4v8" stroke="#c6d6d3" stroke-width="2"/>',
 water:'<path d="M25 8h16v10l5 9v30q-13 5-26 0V27l5-9z" fill="#aedfe7"/><path d="M21 35h24v15H21z" fill="#2d8ba7"/><path d="M25 7h16v9H25z" fill="#e7d7a7"/>',
 medkit:'<rect x="12" y="14" width="42" height="37" rx="5" fill="#dce8de"/><path d="M28 21h10v23H28zM21 28h24v9H21z" fill="#db6c5e"/>',
 fish:'<path d="M10 31q22-31 37 0-15 30-37 0M45 31l14-15v30z" fill="#54b4be"/><circle cx="24" cy="28" r="9" fill="#e9c967"/><circle cx="24" cy="28" r="5" fill="#174253"/>',
 suit:'<path d="M21 10L8 28l10 9 7-7-5 30h11l3-17 3 17h11l-5-30 7 7 10-9-13-18-13 7z" fill="#deba66"/><path d="M27 17h13v24H27z" fill="#2a4956"/>',
 module:'<rect x="14" y="14" width="38" height="38" rx="5" fill="#273f4e"/><path d="M17 18h32v9H17z" fill="#dbe5d9"/><circle cx="32" cy="39" r="8" fill="#62c9d8"/><path d="M10 22h5m-5 10h5m-5 10h5m37-20h5m-5 10h5m-5 10h5" stroke="#e2ba61" stroke-width="3"/>',
 vehicle:'<ellipse cx="32" cy="31" rx="21" ry="19" fill="#dce4db"/><ellipse cx="32" cy="33" rx="15" ry="14" fill="#286370"/><path d="M10 23q-13 13 0 25m44-25q13 13 0 25" fill="none" stroke="#e7bf64" stroke-width="8"/><path d="M23 15h18" stroke="#f3c862" stroke-width="5"/><path d="M29 24l-6 9" stroke="#98e3e3" stroke-width="3"/>',
 room:'<path d="M7 24l10-11h31l10 11v26H7z" fill="#d5e2dc"/><path d="M7 28h51v6H7z" fill="#365b65"/><path d="M24 34h18v17H24z" fill="#285a6f"/><path d="M11 51v9m42-9v9" stroke="#dfc077" stroke-width="4"/>',
 plant:'<path d="M32 60V11M32 44Q8 48 11 29q17-4 21 15M32 29Q52 32 54 11 34 10 32 29" fill="#8fb682" stroke="#71c2b1" stroke-width="2"/>',
 hands:'<path d="M21 48l-9-13q-4-8 4-8l7 7-3-19q0-7 6-5l4 19-1-24q3-7 7 0l1 23 4-20q6-4 6 3l-3 24 8-14q6-3 7 3L47 49q-12 16-26-1" fill="#d4d5ba"/>'
};
export function icon(id){const d=ITEMS[id]||{},kind=d.kind;let path=paths[id]||paths[id?.includes('Tank')?'tank':''];if(!path){if(id==='highTank'||id==='ultraTank')path=paths.tank;else if(kind==='vehicle'||id==='vehicleBay')path=paths.vehicle;else if(kind==='module'||['chip','wire','advancedWire','copperWire'].includes(id))path=paths.module;else if(kind==='battery')path=paths.battery;else if(kind==='equipment')path=paths.suit;else if(['peeper','bladderfish','cooked'].includes(id))path=paths.fish;else if(['acid','seed','vine','gel','eye','ghost','crown','fungal','bulbSample','deepMushroom'].includes(id))path=paths.plant;else if(BUILDS.some(b=>b.id===id))path=paths.room;else {const colors={titanium:'#9aafb5',copper:'#c5976a',gold:'#e3c575',silver:'#d5dee2',ruby:'#de7190',kyanite:'#73bded',ion:'#89e9ac',quartz:'#c5e4e1',diamond:'#a8e3e8',lithium:'#bda5d0',sulfur:'#e4c378',purple:'#b4a2ee',blue:'#6dc8ec'};path=`<path d="M13 20L35 7l19 16-4 27-26 8L9 38z" fill="${colors[id]||'#9dbaba'}"/><path d="M13 20l20 8 21-5M33 28l-9 30M33 28L35 7" fill="none" stroke="#eff9ed" opacity=".4" stroke-width="2"/><path d="M33 28l17 22-26 8z" fill="#143b4d" opacity=".25"/>`;}}
 return `<svg viewBox="0 0 64 64" aria-hidden="true">${path}</svg>`;
}
export class UI{
 constructor(game){this.g=game;this.modal=null;this.selectedItem=null;this.recipeId=null;this.recipeCategory='All';this.tab='inventory';this.bindMenu();}
 bindMenu(){$('play-demo').onclick=()=>this.g.startDemo();$('resume-demo').onclick=()=>{try{const raw=localStorage.getItem('crater-demo-save');if(raw)this.g.importSave(raw);else this.toast('No demo saved yet. Escape → Save demo during play.');}catch(error){this.toast('Could not load demo: '+error.message);}};$('new-game').onclick=()=>this.newGame();$('continue-game').onclick=()=>this.saves();$('menu-settings').onclick=()=>this.settings();$('menu-coverage').onclick=()=>this.coverage();$('import-file').onchange=async e=>{const file=e.target.files[0];if(file)this.g.importSave(await file.text());e.target.value='';};}
 panel(title,subtitle,body,kind='panel'){this.modal=kind;this.g.paused=true;this.g.keys.clear();document.exitPointerLock?.();$('modal-layer').classList.remove('hidden');$('panel').innerHTML=`<header class="panel-head"><div><small>${subtitle}</small><h2>${title}</h2></div><button class="close-button" aria-label="Close">×</button></header>${body}`;$('panel').querySelector('.close-button').onclick=()=>this.close();this.g.audio.effect('click');}
 close(){this.modal=null;$('modal-layer').classList.add('hidden');if(this.g.playing){this.g.paused=false;this.g.audio.pause(false);$('reticle-tip').style.display='block';}this.g.keys.clear();}
 toast(text){const div=document.createElement('div');div.className='toast';div.textContent=text;$('toast-stack').append(div);setTimeout(()=>div.remove(),4500);}
 subtitle(text,duration=7){if(!this.g.settings.subtitles)return;$('subtitle').textContent=text;$('subtitle').classList.add('visible');clearTimeout(this.subtitleTimer);this.subtitleTimer=setTimeout(()=>$('subtitle').classList.remove('visible'),duration*1000);}
 notify(text){$('notification').textContent=text;$('notification').style.opacity=1;clearTimeout(this.notifyTimer);this.notifyTimer=setTimeout(()=>$('notification').style.opacity=0,3500);}
 newGame(){this.panel('Descend into the unknown','NEW GAME',`<div class="mode-grid">${[['survival','Survival','Manage health, hunger, thirst and oxygen. Build your way from the shallows to escape.','◈'],['freedom','Freedom','Survival without hunger or thirst. Health, oxygen, energy and depth still matter.','◇'],['hardcore','Hardcore','One life. Survival rules, no oxygen warnings. A fatal mistake ends this save.','△'],['creative','Creative','Build and explore freely. No damage, oxygen limits or material costs.','∞']].map(([id,name,text,symbol])=>`<button class="mode" data-mode="${id}"><span>${symbol}</span><h3>${name}</h3><p>${text}</p></button>`).join('')}</div><p class="panel-note">Keyboard and mouse · WebGL 2 · Click the ocean to capture the mouse.<br>This build has a condensed, playable story and replacement environments. Read the coverage notes for fidelity limits.</p>`,'new');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>this.g.startNew(b.dataset.mode));}
 pause(){if(this.g.demo){this.panel('Take a breath','SUBMARINE DEMO · PAUSED',`<div style="max-width:400px;margin:auto"><button id="resume" class="wide-button primary">Return to the ocean</button><button id="restart-demo" class="wide-button">Restart demo</button><button id="save-demo" class="wide-button">Save demo</button><button id="options" class="wide-button">Options & controls</button><button id="to-menu" class="wide-button">Save & return to main menu</button></div>`,'pause');$('resume').onclick=()=>this.close();$('restart-demo').onclick=()=>this.g.startDemo();$('save-demo').onclick=()=>this.g.save();$('options').onclick=()=>this.settings();$('to-menu').onclick=()=>this.g.returnToMenu();return;}this.panel('Take a breath','PAUSED',`<div style="max-width:400px;margin:auto"><button id="resume" class="wide-button primary">Return to the ocean</button><button id="save-now" class="wide-button">Save game</button><button id="load-now" class="wide-button">Load / export saves</button><button id="options" class="wide-button">Options & controls</button><button id="to-menu" class="wide-button">Save & return to main menu</button></div>`,'pause');$('resume').onclick=()=>this.close();$('save-now').onclick=()=>this.g.save();$('load-now').onclick=()=>this.saves();$('options').onclick=()=>this.settings();$('to-menu').onclick=()=>this.g.returnToMenu();}
 pda(tab=this.tab){this.tab=tab;const s=this.g.s;this.panel('Personal data assistant','ALTERRA SYSTEMS · PDA',`<nav class="tabs">${[['inventory','Inventory'],['blueprints','Blueprints'],['databank','Databank'],['signals','Signals'],['log','Survival log']].map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</nav><div id="pda-content"></div>`,'pda');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>this.pda(b.dataset.tab));if(tab==='inventory')this.inventory();else if(tab==='blueprints')this.blueprints();else if(tab==='signals')this.signals();else if(tab==='log')$('pda-content').innerHTML=STORY.map((q,i)=>`<article class="log-card ${s.flags[q.flag]?'done':q===nextStory(s,STORY)?'current':''}"><h3>${s.flags[q.flag]?'✓':String(i+1).padStart(2,'0')} · ${q.title}</h3><p>${q.text}</p></article>`).join('');else $('pda-content').innerHTML=`<article class="log-card"><h3>Environmental assessment</h3><p>Planet 4546B. Oxygen is replenished at the surface, in Lifepod 5, in powered habitats, and aboard powered vehicles. Scan technology fragments to recover blueprints. Follow signals, mark return routes and take spare batteries.</p></article>${s.scans.filter(id=>id.startsWith('species:')).map(id=>`<article class="log-card"><h3>${this.g.speciesName(id.slice(8))}</h3><p>${this.g.speciesDescription(id.slice(8))}</p></article>`).join('')}${s.scans.filter(id=>id.startsWith('plant:')).map(key=>{const id=key.slice(6),uses=RECIPES.filter(r=>r.cost[id]).map(r=>ITEMS[r.id].name);return `<article class="log-card"><h3>${escapeHTML(ITEMS[id]?.name||id)}</h3><p>Sample analyzed. ${uses.length?'Used to fabricate: '+uses.map(escapeHTML).join(', ')+'.':'This sample can be kept for study.'}</p></article>`;}).join('')}${s.logs.slice().reverse().map(log=>`<article class="log-card"><h3>${escapeHTML(log.title)}</h3><p>${escapeHTML(log.text)}</p></article>`).join('')}<p class="small-text">Databank and voice lines in this build are condensed replacement writing.</p>`;}
 inventory(){const s=this.g.s,layout=pack(s.inventory)||[],selected=s.inventory.find(i=>i.uid===this.selectedItem),d=ITEMS[selected?.id];$('pda-content').innerHTML=`<div class="inventory-layout"><div class="inventory-grid-wrap"><div class="inventory-summary"><span>INVENTORY</span><span>${s.inventory.reduce((a,i)=>a+ITEMS[i.id].w*ITEMS[i.id].h,0)} / 48 cells</span></div><div class="inventory-grid">${layout.map(({item,x,y,w,h})=>`<button class="inventory-item ${item.uid===this.selectedItem?'selected':''}" data-item="${item.uid}" title="${ITEMS[item.id].name}" style="grid-column:${x+1}/span ${w};grid-row:${y+1}/span ${h}">${icon(item.id)}<small>${ITEMS[item.id].name}</small>${item.charge!==undefined?`<i>${Math.round(item.charge)}%</i>`:''}</button>`).join('')}</div></div><div><div class="inventory-summary">EQUIPPED</div>${['tank','head','suit','fins','chip'].map(slot=>`<div class="equipped">${s.equipment[slot]?icon(s.equipment[slot].id):'<span>◇</span>'}<div>${slot.toUpperCase()}<br><span>${s.equipment[slot]?ITEMS[s.equipment[slot].id].name:'Empty'}</span></div></div>`).join('')}<p class="small-text">${maxOxygen(s)} seconds of oxygen<br>Infection: ${s.flags.cured?'cured':s.flags.infected?'detected':'unknown'}</p></div><div class="recipe-detail">${selected?`${icon(selected.id)}<h3>${d.name}</h3><p>${d.w} × ${d.h} inventory cells${selected.charge!==undefined?` · ${Math.round(selected.charge)}% charge`:''}</p>${d.kind==='food'?`<p>${Object.entries({Food:d.food,Water:d.water,Health:d.health}).filter(([,v])=>v).map(([k,v])=>`${k} ${v>0?'+':''}${v}`).join(' · ')}</p>`:''}${['food','equipment','tool','deploy','module','battery'].includes(d.kind)?`<button id="use-item" class="wide-button primary">${d.kind==='food'?'Consume':d.kind==='equipment'?'Equip':d.kind==='module'?'Install in nearby vehicle':d.kind==='battery'?'Exchange / recharge':d.kind==='deploy'?'Deploy':'Select tool'}</button>`:''}<button id="drop-item" class="wide-button">Drop item</button>`:'<h3>Your equipment</h3><p>Select an item to use, equip or drop it. Tools can be assigned to the quick slots by selecting them here.</p><p>Craft an oxygen tank before making longer dives.</p>'}</div></div>`;document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{this.selectedItem=Number(b.dataset.item);this.inventory();});if(selected){$('use-item')&&($('use-item').onclick=()=>{this.g.useItem(selected.uid);if(this.modal)this.inventory();});$('drop-item').onclick=()=>{this.g.dropItem(selected.uid);this.inventory();};}}
 blueprints(){const s=this.g.s;$('pda-content').innerHTML=`<div class="recipe-grid" style="grid-template-columns:repeat(5,1fr)">${RECIPES.map(r=>`<div class="recipe-card ${r.blueprint&&!s.blueprints.includes(r.blueprint)?'locked':''}">${icon(r.id)}<span>${ITEMS[r.id].name}</span><p class="small-text">${r.blueprint&&!s.blueprints.includes(r.blueprint)?`${s.fragments[r.blueprint]||0} / ${FRAGMENT_COUNTS[r.blueprint]||1} fragments`:r.station}</p></div>`).join('')}</div>`;}
 signals(){const s=this.g.s;const signals=this.g.getSignals(true);$('pda-content').innerHTML=signals.map(sig=>`<div class="signal-row"><div>${escapeHTML(sig.name)}<small>${Math.round(this.g.player.distanceTo(sig.pos))}m · ${Math.round(Math.max(0,-sig.pos.y))}m depth</small></div><button data-signal="${sig.id}">${s.flags['hide-'+sig.id]?'Show signal':'Hide signal'}</button></div>`).join('')+'<p class="panel-note">Signals indicate locations in three-dimensional space. No world map is added.</p>';document.querySelectorAll('[data-signal]').forEach(b=>b.onclick=()=>{s.flags['hide-'+b.dataset.signal]=!s.flags['hide-'+b.dataset.signal];this.signals();});}
 category(id){const d=ITEMS[id];if(d.kind==='food')return 'Sustenance';if(d.kind==='tool')return 'Tools';if(d.kind==='equipment')return 'Equipment';if(d.kind==='vehicle')return 'Vehicles';if(d.kind==='module')return 'Modules';if(d.kind==='deploy')return 'Deployables';if(d.kind==='rocket')return 'Neptune';return 'Resources';}
 crafting(station='Fabricator'){this.station=station;const s=this.g.s;const all=RECIPES.filter(r=>r.station===station);const cats=['All',...new Set(all.map(r=>this.category(r.id)))];if(!cats.includes(this.recipeCategory))this.recipeCategory='All';let list=all.filter(r=>this.recipeCategory==='All'||this.category(r.id)===this.recipeCategory);if(station==='Neptune platform')list=list.filter(r=>this.g.rocketOrder[s.rocket]===r.id);if(!list.some(r=>r.id===this.recipeId))this.recipeId=list.find(r=>canPay(s,r.cost))?.id||list[0]?.id;const selected=list.find(r=>r.id===this.recipeId);this.panel(station,'MANUFACTURING SYSTEM',`<div class="recipe-layout"><nav class="categories">${cats.map(c=>`<button data-category="${c}" class="${c===this.recipeCategory?'active':''}">${c}</button>`).join('')}</nav><div class="recipe-grid">${list.map(r=>`<button data-recipe="${r.id}" class="recipe-card ${r.id===this.recipeId?'selected':''} ${canPay(s,r.cost)?'affordable':''} ${r.blueprint&&!s.blueprints.includes(r.blueprint)&&s.mode!=='creative'?'locked':''}">${icon(r.id)}<span>${ITEMS[r.id].name}</span></button>`).join('')}</div><div id="recipe-detail" class="recipe-detail"></div></div><p class="panel-note">${station==='Fabricator'?'Crafted equipment goes into your inventory. Equip it in the PDA. Powered fabricators use five energy per craft.':'Vehicle modules must be installed from the inventory while close to the vehicle.'}</p>`,'craft');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{this.recipeCategory=b.dataset.category;this.crafting(station);});document.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>{this.recipeId=b.dataset.recipe;this.crafting(station);});if(selected){const unlocked=!selected.blueprint||s.blueprints.includes(selected.blueprint)||s.mode==='creative';$('recipe-detail').innerHTML=`${icon(selected.id)}<h3>${ITEMS[selected.id].name}</h3><p>${unlocked?'Blueprint available':`Blueprint required · ${s.fragments[selected.blueprint]||0} / ${FRAGMENT_COUNTS[selected.blueprint]||1} fragments`}</p>${this.ingredients(selected.cost)}<button id="fabricate" class="wide-button primary" ${!unlocked||!canPay(s,selected.cost)?'disabled':''}>${ITEMS[selected.id].kind==='vehicle'?'Construct vehicle':ITEMS[selected.id].kind==='rocket'?'Construct':'Fabricate'}${selected.count>1?' × '+selected.count:''}</button>`;$('fabricate').onclick=()=>{this.g.craft(selected.id,station);if(this.modal==='craft')this.crafting(station);};}}
 ingredients(cost){const count=counts(this.g.s);return `<ul class="ingredients">${Object.entries(cost).map(([id,n])=>`<li class="${(count[id]||0)>=n||this.g.s.mode==='creative'?'enough':'missing'}"><span>${ITEMS[id].name}</span><span>${count[id]||0} / ${n}</span></li>`).join('')}</ul>`;}
 construction(){this.panel('Habitat builder','CONSTRUCTION',`<div class="build-grid">${BUILDS.map(b=>`<button data-build="${b.id}" class="recipe-card ${canPay(this.g.s,b.cost)?'affordable':''}">${icon(b.id)}<span>${b.name}</span><p class="small-text">${Object.entries(b.cost).map(([id,n])=>`${n} ${ITEMS[id].name}`).join(' · ')}</p></button>`).join('')}</div><p class="panel-note">Select a component, then place the preview with the left mouse button. R rotates it. Right click cancels. Build a hatch beside a room to enter; solar panels power oxygen in shallow water. Negative hull integrity causes flooding.</p>`,'build');document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{this.close();this.g.beginBuild(b.dataset.build);});}
 storage(container,name){const s=this.g.s;this.panel(name,'STORAGE · SELECT AN ITEM TO TRANSFER',`<div class="storage-columns"><div><h3>Inventory</h3><div class="storage-list">${s.inventory.map(i=>`<button data-store="${i.uid}">${icon(i.id)}${ITEMS[i.id].name}</button>`).join('')}</div></div><div><h3>${escapeHTML(name)}</h3><div class="storage-list">${container.map(i=>`<button data-take="${i.uid}">${icon(i.id)}${ITEMS[i.id].name}</button>`).join('')||'<p class="small-text">Empty</p>'}</div></div></div>`,'storage');document.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>{this.g.transfer(Number(b.dataset.store),s.inventory,container);this.storage(container,name);});document.querySelectorAll('[data-take]').forEach(b=>b.onclick=()=>{this.g.transfer(Number(b.dataset.take),container,s.inventory);this.storage(container,name);});}
 settings(){const s=this.g.settings;this.panel('Options','PERSONAL PREFERENCES',`<div class="settings-columns"><div><h3>Audio</h3>${['master','effects','ambience','music','voice'].map(k=>`<label class="setting-row"><span>${k[0].toUpperCase()+k.slice(1)}</span><input type="range" data-setting="${k}" min="0" max="1" step=".01" value="${s[k]}"></label>`).join('')}<label class="setting-row"><span>Spoken warnings · device voice</span><input class="toggle" type="checkbox" data-setting="spoken" ${s.spoken?'checked':''}></label><label class="setting-row"><span>Subtitles</span><input class="toggle" type="checkbox" data-setting="subtitles" ${s.subtitles?'checked':''}></label><button id="audio-test" class="wide-button">Play directional audio test</button></div><div><h3>Display & input</h3><label class="setting-row"><span>Graphics quality</span><select data-setting="quality">${['Low','Medium','High'].map(q=>`<option ${s.quality===q?'selected':''}>${q}</option>`).join('')}</select></label><label class="setting-row"><span>Mouse sensitivity</span><input type="range" data-setting="sensitivity" min=".2" max="3" step=".1" value="${s.sensitivity}"></label><label class="setting-row"><span>Field of view</span><input type="range" data-setting="fov" min="60" max="95" step="1" value="${s.fov}"></label><label class="setting-row"><span>Invert vertical look</span><input class="toggle" type="checkbox" data-setting="invert" ${s.invert?'checked':''}></label><label class="setting-row"><span>Camera motion</span><input class="toggle" type="checkbox" data-setting="motion" ${s.motion?'checked':''}></label><button id="controls" class="wide-button">Controls & remapping</button><button id="fullscreen" class="wide-button">Toggle full screen</button><p class="small-text">Headphones use HRTF positional sound. This is a generated soundscape, with no original recordings. Settings persist on this browser.</p></div></div>`,'settings');document.querySelectorAll('[data-setting]').forEach(el=>el.oninput=()=>{s[el.dataset.setting]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;this.g.applySettings();});$('controls').onclick=()=>this.controls();$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen().catch(()=>this.toast('Full screen is unavailable in this browser panel.'));$('audio-test').onclick=()=>this.g.audioTest();}
 controls(){const names={forward:'Swim / walk forward',back:'Move backward',left:'Strafe left',right:'Strafe right',up:'Ascend / jump / Prawn thrusters',down:'Descend',sprint:'Swim faster / demo submarine boost',interact:'Interact / enter',pda:'PDA',build:'Habitat builder',reload:'Battery / rotate preview',light:'Toggle flashlight',exit:'Exit shelter / vehicle',defense:'Vehicle defense',silent:'Cyclops silent running',grapple:'Prawn grapple arm'};this.panel('Controls','KEYBOARD & MOUSE',`<div class="control-grid">${Object.entries(names).map(([id,name])=>`<div class="control-item"><span>${name}</span><button data-key="${id}">${this.keyName(this.g.settings.keys[id])}</button></div>`).join('')}</div><p class="panel-note">Click an assignment, then press a key. Mouse to look · Left button uses the selected tool · Hold left button to scan or repair · Right button cancels a construction preview · 1–5 selects quick slots · F1 hides HUD · Escape pauses. Arrow keys also turn the camera when pointer capture is unavailable.</p>`,'controls');document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{b.textContent='Press key…';this.g.remapping=b.dataset.key;});}
 keyName(code){return code?.replace('Key','').replace('Digit','').replace('Left','')||'—';}
 saves(){let rows='';for(let i=1;i<=3;i++){const info=this.g.saveInfo(i);rows+=`<div class="save-row"><div>Save slot ${i}<small>${info?escapeHTML(info):'Empty'}</small></div><div class="row-actions">${this.g.playing?`<button data-save="${i}">Save here</button>`:''}<button data-load="${i}" ${!info?'disabled':''}>Load</button>${info?`<button data-export="${i}">Export</button><button data-delete="${i}">Delete</button>`:''}</div></div>`;}this.panel('Saved expeditions','LOCAL BROWSER STORAGE',`${rows}<button id="import-save" class="wide-button">Import a save file</button><p class="panel-note">Three local save slots. Saves belong to this browser and this host address. Export a copy before clearing browser data. Manual saves also retain the preceding save as a recovery copy.</p>`,'saves');document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{this.g.slot=Number(b.dataset.save);this.g.save();this.saves();});document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>this.g.load(Number(b.dataset.load)));document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>this.g.exportSave(Number(b.dataset.export)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(b.dataset.confirm!=='yes'){b.dataset.confirm='yes';b.textContent='Confirm delete';return;}localStorage.removeItem('crater-save-'+b.dataset.delete);localStorage.removeItem('crater-backup-'+b.dataset.delete);this.saves();this.toast('Save deleted.');});$('import-save').onclick=()=>$('import-file').click();}
 async coverage(){this.panel('Build & reference notes','SCOPE AND FIDELITY','<pre id="coverage-text" class="report">Loading coverage notes…</pre>','coverage');try{$('coverage-text').textContent=await(await fetch('COVERAGE.md')).text();}catch{$('coverage-text').textContent='Open COVERAGE.md alongside index.html to read the coverage report.';}}
 death(hardcore){this.panel(hardcore?'Expedition lost':'You have died',hardcore?'HARDCORE · LIFE SIGNS LOST':'EMERGENCY RESPONSE',`<div class="credits"><p>${hardcore?'This expedition has ended. Your hardcore save slot has been removed.':'Emergency recovery returns you to Lifepod 5. Items gathered since your last shelter visit remain in a recoverable cache at the death location.'}</p><button id="respawn" class="wide-button primary">${hardcore?'Return to main menu':'Wake in Lifepod 5'}</button></div>`,'death');$('panel').querySelector('.close-button').style.display='none';$('respawn').onclick=()=>hardcore?this.g.returnToMenu(false):this.g.respawn();}
 ending(){this.panel('Into the stars','NEPTUNE · ESCAPE VELOCITY',`<div class="credits"><p class="eyebrow">PLANET 4546B · DEPARTURE CONFIRMED</p><h2>The ocean stays with you.</h2><p>The quarantine is over. The young Sea Emperors carry the cure beyond the crater.<br>You leave an ocean full of life behind.</p><div class="progress-pills">${Array.from({length:5},()=>'<span class="done"></span>').join('')}</div><p>Original world, characters and game design<br><strong>Unknown Worlds Entertainment</strong></p><p>Browser adaptation, replacement geometry and synthesized audio<br>Created in this workspace with Three.js</p><small>Replacement ending. The original cinematic and music are not included.</small><button id="continue-exploring" class="wide-button primary">Return to the pre-launch save</button><button id="ending-menu" class="wide-button">Main menu</button></div>`,'ending');$('panel').querySelector('.close-button').style.display='none';$('continue-exploring').onclick=()=>{this.g.launching=null;this.g.load(this.g.slot);};$('ending-menu').onclick=()=>{this.g.launching=null;this.g.returnToMenu(false);};}
}
