import * as T from '../vendor/three.module.js';
import {BIO,REGIONS,CAVE_PATHS,LANDMARKS} from './data.js';
import * as M from './models.js';
export const TILE=120;
const clamp=T.MathUtils.clamp;
export function regionAt(x,z){let best=1e10,out=BIO.shallows;for(const [id,cx,cz,r]of REGIONS){const score=((x-cx)**2+(z-cz)**2)/(r*r);if(score<best){best=score;out=BIO[id];}}return Math.hypot(x,z)>1850?BIO.void:out;}
export function surfaceHeight(x,z){
 if(Math.hypot(x,z)>1900)return -1900-Math.min(500,Math.hypot(x,z)-1900);
 let total=0,height=0;for(const [id,cx,cz,r]of REGIONS){const d=((x-cx)**2+(z-cz)**2)/(r*r),w=Math.exp(-d*3);height+=BIO[id].depth*w;total+=w;}
 let y=-(total>1e-9?height/total:regionAt(x,z).depth);
 const b=regionAt(x,z);const amp=b.id==='shallows'?5:b.id==='crag'||b.id==='mountains'?48:18;
 y+=Math.sin(x*.022+Math.cos(z*.024))*amp+Math.sin(z*.029+x*.009)*amp*.5+M.noise(x*.11,z*.11)*.7;
 if(b.id==='grassy')y+=Math.pow(Math.max(0,Math.sin(x*.018)*Math.cos(z*.020)),10)*35;
 for(const l of LANDMARKS){if(['lostpod','wreck'].includes(l.type)){const d=Math.hypot(x-l.pos[0],z-l.pos[2]);if(d<32)y=T.MathUtils.lerp(l.pos[1]-2,y,clamp((d-10)/22,0,1));}}
 for(const [ix,iz,r,h] of [[-640,1030,155,72],[350,-1250,165,115]]){const d=Math.hypot((x-ix)*.9,z-iz);if(d<r*1.45){const island=Math.max(-70,h*(1-d/r)+Math.sin(x*.055)*6+Math.cos(z*.048)*5);y=Math.max(y,island);} }
 for(const l of LANDMARKS.filter(l=>['qep','degasi1'].includes(l.id))){const d=Math.hypot(x-l.pos[0],z-l.pos[2]);if(d<25)y=T.MathUtils.lerp(l.pos[1]-3,y,clamp((d-12)/13,0,1));}
 return y;
}
const caveSegments=[];
for(const path of CAVE_PATHS){const curve=new T.CatmullRomCurve3(path.points.map(p=>new T.Vector3(...p)));const points=curve.getPoints(path.points.length*15);for(let i=1;i<points.length;i++)caveSegments.push({a:points[i-1],b:points[i],radius:path.radius,id:path.id});path.curve=curve;}
export function caveNear(pos){let best=null,min=Infinity;const p=new T.Vector3(...pos);for(const seg of caveSegments){const ab=seg.b.clone().sub(seg.a),t=clamp(p.clone().sub(seg.a).dot(ab)/ab.lengthSq(),0,1);const q=seg.a.clone().addScaledVector(ab,t);const d=q.distanceTo(p);if(d<min){min=d;best={...seg,point:q,distance:d};}}return best;}
export function biomeAt(x,y,z){if(y<surfaceHeight(x,z)-8){if(y<-1320)return BIO.lakes;if(y<-1030)return BIO.lava;if(y<-620)return BIO.river;const c=caveNear([x,y,z]);if(c?.distance<c.radius*1.5){if(c.id==='jelly')return BIO.jelly;if(c.id==='deepgrand')return BIO.deepgrand;if(c.id==='trench')return BIO.trench;if(c.id==='blood')return BIO.blood;}}return regionAt(x,z);}
export function moveWithCollision(from,to,radius=.6){
 const h=surfaceHeight(to.x,to.z),c=(to.y<h+100)?caveNear(to.toArray()):null;
 if(c&&c.distance<c.radius*.90&&to.y<h+10)return to;
 const oldH=surfaceHeight(from.x,from.z);
 if(from.y<oldH-10){const oldC=caveNear(from.toArray());if(oldC&&oldC.distance<oldC.radius*1.05){if(c){const v=to.clone().sub(c.point);if(v.length()>c.radius-radius-2)to.copy(c.point).add(v.normalize().multiplyScalar(c.radius-radius-2));}return to;}}
 if(to.y<h+radius){if(h-from.y>3&&from.y<0){to.x=from.x;to.z=from.z;to.y=Math.max(to.y,surfaceHeight(to.x,to.z)+radius);}else to.y=h+radius;}
 return to;
}
function mergeParts(template){template.updateMatrixWorld(true);const byMat=new Map();template.traverse(o=>{if(!o.isMesh)return;let geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geo.applyMatrix4(o.matrixWorld);let list=byMat.get(o.material);if(!list)byMat.set(o.material,list=[]);list.push(geo);});const out=[];for(const [mat,list]of byMat){const positions=[],normals=[],uv=[];for(const geo of list){positions.push(...geo.attributes.position.array);normals.push(...geo.attributes.normal.array);if(geo.attributes.uv)uv.push(...geo.attributes.uv.array);else uv.push(...Array(geo.attributes.position.count*2).fill(0));geo.dispose();}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('normal',new T.Float32BufferAttribute(normals,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));out.push({geometry:g,material:mat});}return out;}
const cached=new Map();
function batch(group,key,template,transforms){if(!transforms.length)return [];if(!cached.has(key))cached.set(key,mergeParts(template()));const out=[];for(const {geometry,material}of cached.get(key)){const mesh=new T.InstancedMesh(geometry,material,transforms.length);mesh.castShadow=false;mesh.receiveShadow=true;transforms.forEach((t,i)=>mesh.setMatrixAt(i,t));mesh.instanceMatrix.needsUpdate=true;mesh.computeBoundingSphere();group.add(mesh);out.push(mesh);}return out;}
const dummy=new T.Object3D();
function transform(x,y,z,s=1,ry=0,sx=s,sz=s){dummy.position.set(x,y,z);dummy.rotation.set(0,ry,0);dummy.scale.set(sx,s,sz);dummy.updateMatrix();return dummy.matrix.clone();}
const terrainM=M.material(0xffffff,.95,.015,0,{vertexColors:true,map:M.textures.sand,bumpMap:M.textures.sand,bumpScale:.12});
const resourcePools={shallows:['titanium','copper','quartz','acid','salt','coral','sulfur','tube'],kelp:['titanium','copper','silver','gold','seed','vine','tooth'],grassy:['titanium','silver','gold','lead','quartz'],mushroom:['lithium','diamond','titanium','fungal'],bulb:['bulbSample','lithium','silver','magnetite','salt'],grand:['gel','ruby','quartz','eye','uraninite'],sparse:['ruby','gel','lithium','quartz'],trench:['bloodOil','deepMushroom','ruby','diamond'],blood:['bloodOil','deepMushroom','ruby','uraninite'],crag:['quartz','lead','titanium','silver'],dunes:['lithium','quartz','diamond','titanium'],mountains:['diamond','lithium','gold','titanium'],treader:['diamond','gold','lithium'],islands:['quartz','silver','titanium','lithium'],crash:['titanium','lead','quartz']};
export class World{
 constructor(scene,state){this.scene=scene;this.state=state;this.tiles=new Map();this.entities=new Map();this.creatures=[];this.sway=[];this.landmarks=[];this.fixed=new T.Group();scene.add(this.fixed);this.buildLandmarks();this.buildCaves();this.makeParticles();this.createFauna();const tx=Math.floor(state.position[0]/TILE),tz=Math.floor(state.position[2]/TILE);for(let dx=-4;dx<=4;dx++)for(let dz=-4;dz<=4;dz++)this.makeTile(tx+dx,tz+dz,Math.abs(dx)<=1&&Math.abs(dz)<=1);}
 entity(id,type,pos,data={},object=null){const ent={id,type,pos:new T.Vector3(...pos),...data,object};this.entities.set(id,ent);return ent;}
 buildLandmarks(){
 // A persistent coarse exterior prevents distant islands/structures floating over unloaded terrain.
 const horizon=new T.PlaneGeometry(4400,4400,110,110);horizon.rotateX(-Math.PI/2);const hp=horizon.attributes.position,hc=[];
 for(let i=0;i<hp.count;i++){const x=hp.getX(i),z=hp.getZ(i),y=surfaceHeight(x,z);hp.setY(i,y);const c=new T.Color(y>0?0x67724e:regionAt(x,z).ground);hc.push(c.r,c.g,c.b);}
 horizon.setAttribute('color',new T.Float32BufferAttribute(hc,3));horizon.computeVertexNormals();
 const hm=M.material(0xffffff,.95,.01,0,{vertexColors:true,map:M.textures.reef});const baseCompile=hm.onBeforeCompile;
 hm.onBeforeCompile=shader=>{baseCompile(shader);shader.fragmentShader=shader.fragmentShader.replace('#include <dithering_fragment>','if(length((cameraPosition-vOceanWorld).xz)<440.0)discard;\n#include <dithering_fragment>');};const far=M.mesh(horizon,hm,this.fixed);far.castShadow=false;
 for(const l of LANDMARKS){let obj;if(l.type==='pod'||l.type==='lostpod')obj=M.lifepod(l.type==='lostpod');else if(l.type==='wreck')obj=M.wreck();else if(l.type==='aurora')obj=M.aurora();else if(l.type==='alien')obj=M.alienBuilding(l.id);else if(l.type==='degasi')obj=M.habitat('room');else continue;
 obj.position.set(...l.pos);this.fixed.add(obj);this.landmarks.push({data:l,object:obj});let pos=[...l.pos];if(l.type==='pod')pos[1]=-1.8;if(l.type==='aurora')pos=[l.pos[0]-60,10,l.pos[2]-170];else if(l.type==='alien')pos[2]-=l.id==='containment'?25:19;else if(l.type==='wreck')pos[2]-=13;this.entity(l.id,l.type,pos,{name:l.name,landmark:l,reach:l.type==='aurora'?18:l.type==='alien'?10:7},obj);
 }
 const specials=[['purple','island-tablet',370,8,-1133],['purple','floating-tablet',-629,14,1013],['purple','spare-tablet',-220,-266,390],['ion','qep-ion',392,8,-1147],['ion','river-ion',-455,-805,-72],['crown','crown-seed',345,-1460,308]];
 for(const[id,key,x,y,z]of specials)this.fixedResource(key,id,[x,y,z]);
 let n=0;const frag=(bp,p)=>{const id='fragment-'+n++;const obj=new T.Group();const shell=M.box(obj,M.MAT.white,[0,.25,0],[1.6,.6,1]);shell.rotation.z=.18;M.box(obj,M.MAT.dark,[0,.5,0],[1.1,.1,.8]);M.box(obj,M.MAT.cyan,[.3,.6,-.1],[.3,.025,.25]);obj.position.set(...p);this.fixed.add(obj);this.entity(id,'fragment',p,{blueprint:bp,name:bp,reach:5},obj);};
 for(const [bp,x,z,num]of [['seaglide',-77,-240,2],['vehicleBay',-62,-220,3],['seamoth',-476,237,3],['cutter',-449,315,3],['propulsion',-440,348,2],['modification',-640,-561,3],['cyclops',-650,-546,6],['cyclops',-145,-1000,3],['stasis',-230,365,2],['prawn',1070,80,4]]){for(let i=0;i<num;i++){let px=x+(i%3)*4,pz=z+Math.floor(i/3)*4;const y=bp==='stasis'?-266:surfaceHeight(px,pz)+.6;frag(bp,[px,y,pz]);}}
 for(let i=0;i<18;i++){const a=i*2.399,r=8+i*.7,x=Math.sin(a)*r,z=25+Math.cos(a)*r;this.fixedResource('starter-'+i,['titanium','copper','acid','quartz','sulfur','coral'][i%6],[x,surfaceHeight(x,z)+.7,z]);}
 const heroTube=M.coralTube(3.5);heroTube.position.set(20,surfaceHeight(20,4)+2.5,4);heroTube.rotation.x=Math.PI/2;heroTube.rotation.z=.22;this.fixed.add(heroTube);
 for(let i=0;i<20;i++){const plant=i%3===0?M.coralFan(0xc46580):i%3===1?M.acidMushroom():M.tableCoral();const x=17+Math.sin(i*2.4)*7,z=5+Math.cos(i*2.4)*6;plant.position.set(x,surfaceHeight(x,z)+.35,z);plant.scale.setScalar(.6+i%4*.24);this.fixed.add(plant);}
 for(let i=0;i<10;i++)this.fixedResource('island-food-'+i,'melon',[-637+Math.sin(i*2.4)*9,14,1032+Math.cos(i*2.4)*9]);
 this.fixedResource('starter-tube','tube',[11,surfaceHeight(11,24)+1,24]);
 }
 fixedResource(key,id,pos){if(this.state.harvested.includes(key))return;const obj=M.resource(id);obj.position.set(...pos);this.fixed.add(obj);this.entity(key,'resource',pos,{item:id,name:id,reach:4.3},obj);}
 buildCaves(){
 this.caves=new T.Group();this.scene.add(this.caves);
 const caveMaterial=M.material(0xffffff,.92,.02,0,{vertexColors:true,map:M.textures.reef,bumpMap:M.textures.reef,bumpScale:.55,side:T.DoubleSide});
 fetch('assets/cave-terrain.bin').then(r=>{if(!r.ok)throw Error('Missing cave terrain');return r.arrayBuffer();}).then(buffer=>{const count=new DataView(buffer).getUint32(0,true),data=new T.InterleavedBuffer(new Float32Array(buffer,4),11),geo=new T.BufferGeometry();for(const [name,size,offset]of [['position',3,0],['normal',3,3],['uv',2,6],['color',3,8]])geo.setAttribute(name,new T.InterleavedBufferAttribute(data,size,offset));geo.computeBoundingSphere();M.mesh(geo,caveMaterial,this.caves);this.caveReady=count>0;}).catch(error=>console.error(error));
 const formations=[];
 const lavaMaterial=M.material(0xff4214,.72,.1,0xff3300);lavaMaterial.onBeforeCompile=shader=>{shader.uniforms.time=M.clockUniform;shader.vertexShader='varying vec3 lavaWorld;\n'+shader.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nlavaWorld=(modelMatrix*vec4(transformed,1.)).xyz;');shader.fragmentShader='varying vec3 lavaWorld;uniform float time;\n'+shader.fragmentShader.replace('#include <dithering_fragment>','#include <dithering_fragment>\nfloat seam=abs(sin(lavaWorld.x*.26+sin(lavaWorld.z*.13)*2.+time*.05)+cos(lavaWorld.z*.24+sin(lavaWorld.x*.17)));float glow=pow(max(0.,1.-seam),7.);gl_FragColor.rgb=mix(vec3(.04,.025,.02),vec3(1.,.32,.04),glow);');};
 for(const path of CAVE_PATHS){
 const points=path.curve.getPoints(path.points.length*10);for(let i=2;i<points.length-1;i+=3){const p=points[i],id=biomeAt(p.x,p.y,p.z).id;const floor=p.y-path.radius*.88;for(let j=0;j<7;j++){const side=j%2?1:-1,x=p.x+side*path.radius*(.35+(j%3)*.15),z=p.z+Math.sin(i+j*2)*17;formations.push(transform(x,floor-5,z,5+(j%3)*3,i+j,8+(j%4)*4,6+(j%2)*3));}let plant;if(id==='jelly'){plant=M.bulbPlant();plant.scale.set(3,2.4,3);}else if(id==='river'){plant=M.coralFan(0x5aab9a);plant.scale.setScalar(5);}else if(id==='lava'||id==='lakes'){plant=new T.Group();const vent=M.mesh(M.rockGeo,M.MAT.rust,plant,[0,3,0],[4,8,4]);for(let j=0;j<3;j++)M.pathTube(plant,M.MAT.orange,[[j-1,0,-1],[0,3,j-1],[1,6,0]],.12);}else plant=M.kelp(18,true);plant.position.set(p.x+path.radius*.45,floor,p.z);this.caves.add(plant);
 if(id==='river'){const brine=M.mesh(new T.CircleGeometry(path.radius*.8,32),M.material(0x4b9e69,.18,.2,0x12391e,{transparent:true,opacity:.8,side:T.DoubleSide}),this.caves,[p.x,floor-3,p.z]);brine.rotation.x=-Math.PI/2;}
 if(id==='lava'||id==='lakes'){const lava=M.mesh(new T.CircleGeometry(path.radius*.7,32),lavaMaterial,this.caves,[p.x,floor-3,p.z]);lava.rotation.x=-Math.PI/2;if(i%9===2){const light=new T.PointLight(0xff591c,90,130,1.3);light.position.set(p.x,floor+8,p.z);this.caves.add(light);}}
 const resources=id==='jelly'?['magnetite','lithium','diamond']:id==='river'?['nickel','crystallineSulfur','ghost','ion']:id==='lava'||id==='lakes'?['kyanite','crystallineSulfur','nickel','ion']:['ruby','gel','deepMushroom','bloodOil'];for(let j=0;j<4;j++){const rid=resources[(i+j)%resources.length];this.fixedResource('cave-'+path.id+'-'+i+'-'+j,rid,[p.x+(j-1.5)*6,floor+3,p.z+(j%2)*4]);}
 }}
 batch(this.caves,'cave-formations',()=>{const g=new T.Group();M.mesh(M.rockGeometry(3),M.material(0x657269,.98,.01,0,{map:M.textures.reef,bumpMap:M.textures.reef,bumpScale:.2}),g);return g;},formations);
 const skeleton=M.skeleton();skeleton.position.set(-350,-860,-45);skeleton.rotation.y=1.1;this.caves.add(skeleton);
 const emperor=M.creature('emperor');emperor.position.set(357,-1440,350);emperor.rotation.y=.5;this.caves.add(emperor);this.emperor=emperor;
 }
 makeTile(tx,tz,props){const key=tx+','+tz,group=new T.Group();const steps=props?64:24,size=TILE;const geo=new T.PlaneGeometry(size,size,steps,steps);geo.rotateX(-Math.PI/2);geo.translate(tx*size+size/2,0,tz*size+size/2);const p=geo.attributes.position,colors=[];for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),y=surfaceHeight(x,z);p.setY(i,y);const bio=regionAt(x,z),c=new T.Color(bio.ground);const n=M.noise(x*.21,z*.17)*.08+M.noise(x*.57,z*.43)*.035;c.multiplyScalar(.82+n);if(y>0)c.lerp(new T.Color(0x6a7550),.35);colors.push(c.r,c.g,c.b);}const inds=geo.index.array,filtered=[];for(let i=0;i<inds.length;i+=3){const a=inds[i],b=inds[i+1],c=inds[i+2],x=(p.getX(a)+p.getX(b)+p.getX(c))/3,z=(p.getZ(a)+p.getZ(b)+p.getZ(c))/3;let hole=false;for(const path of CAVE_PATHS.slice(0,5)){const start=path.points[0];if(Math.hypot(x-start[0],z-start[2])<path.radius*.72){hole=true;break;}}if(!hole)filtered.push(a,b,c);}geo.setIndex(filtered);geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const ground=M.mesh(geo,terrainM,group);ground.castShadow=false;const entry={key,group,geo,props,entities:[],cx:tx*TILE+TILE/2,cz:tz*TILE+TILE/2};this.scene.add(group);this.tiles.set(key,entry);if(props)this.decorateTile(entry,tx,tz);return entry;}
 decorateTile(entry,tx,tz){M.randomSeed((tx*73856093)^(tz*19349663)^43589);const group=entry.group,cx=tx*TILE,cz=tz*TILE,bio=regionAt(cx+60,cz+60),rocks=[],tubes=[],mushrooms=[],fans=[],tables=[],kelps=[],trees=[],bulbs=[],brains=[],grass=[];const density=bio.id==='shallows'?1.6:bio.id==='sparse'||bio.id==='dunes'? .25:1;
 for(let i=0;i<30;i++){const x=cx+M.rand()*TILE,z=cz+M.rand()*TILE,y=surfaceHeight(x,z);if(y>0)continue;const scale=1.5+M.rand()*5;rocks.push(transform(x,y-scale*.3,z,scale,M.rand()*6,scale*(1+M.rand()),scale));}
 for(let i=0;i<Math.floor(65*density);i++){const x=cx+M.rand()*TILE,z=cz+M.rand()*TILE,y=surfaceHeight(x,z),r=M.rand(),s=.6+M.rand()*1.3;if(y>0)continue;const t=transform(x,y,z,s,M.rand()*6);if(bio.id==='shallows'){if(r<.3)tubes.push(t);else if(r<.58)mushrooms.push(t);else if(r<.75)fans.push(t);else if(r<.94)tables.push(t);else brains.push(t);}else if(bio.id==='kelp'){if(i<45)kelps.push(transform(x,y,z,.85+M.rand()*.55,M.rand()*6));}else if(bio.id==='mushroom'){if(i<14)trees.push(transform(x,y,z,.7+M.rand()*.7));}else if(bio.id==='blood'||bio.id==='trench'){if(i<24)kelps.push(t);}else if(bio.id==='grand'){if(i<18)bulbs.push(t);}else if(bio.id==='bulb'){if(i<24)bulbs.push(t);}else if(r<.3)fans.push(t);}
 for(let i=0;i<Math.floor(11000*density);i++){const x=cx+M.rand()*TILE,z=cz+M.rand()*TILE,y=surfaceHeight(x,z);if(y>0||bio.id==='dunes'||M.noise(x*.09,z*.09)<-.05)continue;grass.push(transform(x,y+.04,z,.55+M.rand()*.85,M.rand()*6,.5+M.rand()*.6,.5));}
 for(const [arr,r,h]of [[rocks,1.5,2],[tubes,1,3],[mushrooms,1,1],[fans,2,3],[tables,1,1],[kelps,4,22],[trees,12,28],[bulbs,5,9],[brains,2,3],[grass,.3,2]])for(let i=arr.length-1;i>=0;i--){const e=arr[i].elements,scale=Math.hypot(e[0],e[1],e[2]);if(this.state.bases.some(b=>['room','corridor','glassCorridor','moonpool','observatory'].includes(b.type)&&Math.hypot(e[12]-b.pos[0],e[14]-b.pos[2])<(b.type==='moonpool'?10:6)+r*scale&&e[13]<b.pos[1]+6&&e[13]+h*scale>b.pos[1]-1))arr.splice(i,1);}
 batch(group,'rocks-'+bio.id,()=>{const g=new T.Group();M.mesh(M.rockGeo,M.material(bio.ground,.88,.02,0,{map:M.textures.reef,bumpMap:M.textures.reef,bumpScale:.18}),g);return g;},rocks);
 batch(group,'tubes',()=>M.coralTube(),tubes);batch(group,'acid',()=>M.acidMushroom(),mushrooms);batch(group,'fan'+bio.id,()=>M.coralFan(bio.id==='grassy'?0xcf6565:0xc16b98),fans);batch(group,'table',()=>M.tableCoral(),tables);batch(group,'brain',()=>M.brainCoral(),brains);const blood=bio.id==='blood'||bio.id==='trench';batch(group,blood?'bloodkelp':'kelp',()=>M.kelp(18,blood),kelps);batch(group,'trees',()=>M.mushroomTree(),trees);batch(group,'bulbs'+bio.id,()=>M.bulbPlant(bio.id==='grand'),bulbs);
 batch(group,'grass'+bio.id,()=>{const g=new T.Group(),mat=M.material(bio.grass,.85,.01,0,{side:T.DoubleSide});for(let i=0;i<3;i++){const m=M.mesh(M.grassBladeGeometry,mat,g);m.rotation.y=i*Math.PI/3;m.rotation.z=.2*Math.sin(i);m.scale.set(1,1,1);}return g;},grass);
 M.randomSeed(((tx*73856093)^(tz*19349663)^43589)+91837);const pool=resourcePools[bio.id]||['titanium','quartz'];const resources=new Map();for(let i=0;i<30;i++){const x=cx+M.rand()*TILE,z=cz+M.rand()*TILE,y=surfaceHeight(x,z)+.5;const id='res-'+entry.key+'-'+i,item=pool[Math.floor(M.rand()*pool.length)];if(y>0||this.state.harvested.includes(id))continue;const p=[x,y,z];if(!resources.has(item))resources.set(item,[]);const list=resources.get(item),index=list.length;list.push({id,p,matrix:transform(...p,1,M.rand()*6)});const e=this.entity(id,'resource',p,{item,reach:4.5,instanceIndex:index});entry.entities.push(id);}
 for(const [item,list]of resources){const meshes=batch(group,'resmodel-'+item,()=>M.resource(item),list.map(x=>x.matrix));for(const item of list)this.entities.get(item.id).instances=meshes;}
 if(bio.id==='islands'){const rock=M.mesh(M.rockGeo,M.material(0x656d66),group,[cx+60,-190,cz+60],[25,13,28]);const plant=M.coralTube(3);plant.position.set(cx+60,-178,cz+60);group.add(plant);}
 }
 collect(ent){this.state.harvested.push(ent.id);if(ent.object)ent.object.visible=false;if(ent.instances){dummy.scale.set(0,0,0);dummy.updateMatrix();for(const m of ent.instances){m.setMatrixAt(ent.instanceIndex,dummy.matrix);m.instanceMatrix.needsUpdate=true;}}this.entities.delete(ent.id);}
 makeParticles(){const num=900,pos=[],sizes=[];for(let i=0;i<num;i++){pos.push((Math.random()-.5)*100,(Math.random()-.5)*70,(Math.random()-.5)*100);sizes.push(Math.random());}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(pos,3));const c=document.createElement('canvas');c.width=c.height=32;const ctx=c.getContext('2d'),gr=ctx.createRadialGradient(16,16,0,16,16,16);gr.addColorStop(0,'#c5f5de');gr.addColorStop(.15,'#b4dace');gr.addColorStop(1,'#ffffff00');ctx.fillStyle=gr;ctx.fillRect(0,0,32,32);const mat=new T.PointsMaterial({color:0xb6dfe1,map:new T.CanvasTexture(c),size:.20,transparent:true,opacity:.33,depthWrite:false,blending:T.AdditiveBlending});this.particles=new T.Points(geo,mat);this.scene.add(this.particles);}
 createFauna(){M.randomSeed(23191);const add=(species,pos,range)=>{const obj=M.creature(species);if(['peeper','bladderfish'].includes(species))obj.scale.setScalar(.65);obj.position.set(...pos);this.scene.add(obj);const c={id:'fauna-'+this.creatures.length,species,object:obj,origin:new T.Vector3(...pos),pos:obj.position,phase:M.rand()*6,range,state:'wander',timer:0,call:5+M.rand()*20,attack:0,stunned:0,health:species==='peeper'?5:100};this.creatures.push(c);if(this.state.harvested.includes(c.id)){c.caught=true;obj.visible=false;}else this.entity(c.id,'creature',pos,{creature:c,name:species,reach:species==='peeper'||species==='bladderfish'?4:8},obj);};
 for(let i=0;i<30;i++){const a=i*2.4,r=10+i*3;const x=Math.sin(a)*r,z=28+Math.cos(a)*r;add(i%4===0?'bladderfish':'peeper',[x,Math.max(surfaceHeight(x,z)+3,-12),z],10);}
 add('stalker',[-240,-38,20],65);add('stalker',[180,-48,-140],50);add('sandshark',[-440,-102,250],70);add('reefback',[-430,-42,420],90);add('reefback',[350,-58,-380],90);add('reaper',[1250,-80,5],180);add('reaper',[-1280,-180,-100],180);add('reaper',[750,-150,-1220],180);add('ghost',[-380,-800,-20],110);add('ghost',[-350,-245,1160],110);add('crabsquid',[-510,-510,845],50);add('treader',[-1270,-295,1110],65);add('dragon',[30,-1170,35],75);
 this.addFauna=add;
 }
 update(player,dt,time,audio,damage,vehicle,quiet=false){
 const tx=Math.floor(player.x/TILE),tz=Math.floor(player.z/TILE),deep=player.y<surfaceHeight(player.x,player.z)-50;let built=0;const radius=deep?2:4;
 for(let ring=0;ring<=radius;ring++)for(let dx=-ring;dx<=ring;dx++)for(let dz=-ring;dz<=ring;dz++){if(Math.max(Math.abs(dx),Math.abs(dz))!==ring)continue;const x=tx+dx,z=tz+dz,key=x+','+z,wantProps=Math.abs(dx)<=2&&Math.abs(dz)<=2&&!deep;if(!this.tiles.has(key)&&built<3){this.makeTile(x,z,wantProps);built++;}else {const tile=this.tiles.get(key);if(tile&&wantProps&&!tile.props&&built<2){this.removeTile(tile);this.makeTile(x,z,true);built++;}}}
 for(const tile of [...this.tiles.values()])if(Math.abs(tile.cx-player.x)>TILE*(radius+2)||Math.abs(tile.cz-player.z)>TILE*(radius+2))this.removeTile(tile);
 this.particles.position.copy(player);this.particles.position.y-=Math.sin(time*.13)*2;this.particles.rotation.y=time*.005;this.particles.visible=player.y<0;
 if(Math.hypot(player.x,player.z)>1820&&!this.voidSpawned){this.addFauna('ghost',[player.x+160,player.y-30,player.z-100],120);this.voidSpawned=true;}
 for(const c of this.creatures){if(!c.object.visible&&c.caught)continue;const dist=c.pos.distanceTo(player),big=['reaper','ghost','dragon'].includes(c.species),pred=big||['stalker','sandshark','crabsquid'].includes(c.species);c.object.visible=dist<(big?650:300);if(!c.object.visible)continue;const dir=new T.Vector3();c.stunned=Math.max(0,c.stunned-dt);c.attack=Math.max(0,c.attack-dt);c.timer+=dt;
 const fearRange=c.species==='ghost'?100:c.species==='reaper'?(vehicle?.silent?65:125):c.species==='dragon'?90:c.species==='crabsquid'?65:c.species==='sandshark'?18:24;
 if(c.species==='crabsquid'&&vehicle?.lights!==false&&vehicle&&dist<42&&!c.attack&&!quiet){vehicle.power=Math.max(0,vehicle.power-12);audio?.effect('emp',c.pos,.8);c.attack=14;}if(pred&&!quiet&&!c.stunned&&dist<fearRange&&c.state!=='retreat'){c.state='pursue';c.timer=0;}if(c.state==='pursue'&&(dist>fearRange*1.7||quiet||c.species==='ghost'&&c.pos.distanceTo(c.origin)>165||c.species==='stalker'&&c.pos.distanceTo(c.origin)>95)){c.state='retreat';c.timer=0;}
 if(c.state==='retreat'&&c.timer>15)c.state='wander';
 let speed=big?10:c.species==='reefback'?2:pred?4:1.8;let target;
 if(c.stunned){speed=0;target=c.pos.clone().add(new T.Vector3(0,0,-1));}
 else if(c.state==='pursue'){target=player;speed*=1.5;if(dist<(big?12:3)&&!c.attack){damage(big?27:10,c.species);audio?.effect('impact',c.pos,1);c.attack=9;c.state='retreat';c.timer=0;}}
 else {const a=time*(c.species==='reefback'?.011:.035)+c.phase+(c.state==='retreat'?2:0);target=c.origin.clone().add(new T.Vector3(Math.sin(a)*c.range,Math.sin(a*.7)*Math.min(8,c.range*.12),Math.cos(a)*c.range));}
 dir.subVectors(target,c.pos);if(dir.length()>.5){dir.normalize();const next=c.pos.clone().addScaledVector(dir,speed*dt);moveWithCollision(c.pos,next,big?3:1);c.pos.copy(next);const yaw=Math.atan2(-dir.x,-dir.z);c.object.rotation.y+=T.MathUtils.euclideanModulo(yaw-c.object.rotation.y+Math.PI,Math.PI*2)-Math.PI;c.object.rotation.x=T.MathUtils.lerp(c.object.rotation.x,Math.asin(clamp(dir.y,-.7,.7))*.6,dt*2);}
 for(let i=0;i<c.object.userData.fins.length;i++){const f=c.object.userData.fins[i];if(f.parent===c.object.userData.body){f.position.x=Math.sin(time*(big?1.2:3.3)-i*.38)*i*(big?.22:.022);f.rotation.y=Math.cos(time*(big?1.2:3.3)-i*.38)*(big?.045:.04);}else if(!f.userData.initial){f.userData.initial=f.rotation.clone();}else f.rotation.z=f.userData.initial.z+Math.sin(time*3+i)*.1;}
 c.call-=dt;if(c.call<0){c.call=(big?16:c.species==='reefback'?30:20)+Math.random()*25;if(pred||c.species==='reefback'){audio?.call(c.species,c.pos,deep);}}
 const ent=this.entities.get(c.id);if(ent)ent.pos.copy(c.pos);
 }
 }
 refreshBaseArea(base){for(const tile of [...this.tiles.values()])if(tile.props&&Math.abs(tile.cx-base.pos[0])<TILE/2+30&&Math.abs(tile.cz-base.pos[2])<TILE/2+30){const [tx,tz]=tile.key.split(',').map(Number);this.removeTile(tile);this.makeTile(tx,tz,true);}}
 removeTile(tile){this.scene.remove(tile.group);tile.geo.dispose();for(const id of tile.entities)this.entities.delete(id);tile.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});this.tiles.delete(tile.key);}
 closest(player,direction,max=8){let best=null,score=Infinity;for(const ent of this.entities.values()){if(ent.object&&!ent.object.visible)continue;if(ent.type==='resource'&&this.state.harvested.includes(ent.id))continue;const d=ent.pos.distanceTo(player);const reach=ent.reach||max;if(d>reach)continue;const to=ent.pos.clone().sub(player).normalize(),dot=to.dot(direction);if(dot<.79&&d>2)continue;const s=d*(1+(1-dot)*8);if(s<score){score=s;best=ent;}}return best;}
}
